### ISSUE TITLE
Warning: a promise was created in a handler but not returned from it

### ISSUE THREAD

**Issue by svileng** [knex/knex#1388]
I'm trying out knex and migrations for the first time, and I'm getting a few of those after I run `migrate:latest`:

```
Warning: a promise was created in a handler but was not returned from it
    at Runner.ensureConnection (/Users/Svilen/Development/testapp/node_modules/knex/lib/runner.js:156:26)
    at Runner.run (/Users/Svilen/Development/testapp/node_modules/knex/lib/runner.js:29:31)
    at QueryBuilder.Target.then (/Users/Svilen/Development/testapp/node_modules/knex/lib/interface.js:26:43)
    at Migrator._isLocked (/Users/Svilen/Development/testapp/node_modules/knex/lib/migrate/index.js:201:76)
    at /Users/Svilen/Development/testapp/node_modules/knex/lib/migrate/index.js:217:23
    at /Users/Svilen/Development/testapp/node_modules/knex/lib/transaction.js:42:18
From previous event:
    at /Users/Svilen/Development/testapp/node_modules/knex/lib/transaction.js:36:8
From previous event:
    at new Transaction (/Users/Svilen/Development/testapp/node_modules/knex/lib/transaction.js:29:27)
    at Client.transaction (/Users/Svilen/Development/testapp/node_modules/knex/lib/client.js:118:12)
    at Function.transaction (/Users/Svilen/Development/testapp/node_modules/knex/lib/util/make-knex.js:60:21)
    at Migrator._getLock (/Users/Svilen/Development/testapp/node_modules/knex/lib/migrate/index.js:216:24)
    at Migrator._runBatch (/Users/Svilen/Development/testapp/node_modules/knex/lib/migrate/index.js:241:19)
    at /Users/Svilen/Development/testapp/node_modules/knex/lib/migrate/index.js:74:25
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at /Users/Svilen/Development/testapp/node_modules/knex/lib/migrate/index.js:73:12
From previous event:
    at Migrator.rollback (/Users/Svilen/Development/testapp/node_modules/knex/lib/migrate/index.js:69:28)
    at Command.<anonymous> (/Users/Svilen/Development/testapp/node_modules/knex/lib/bin/cli.js:114:37)
    at Command.listener (/Users/Svilen/Development/testapp/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:100:13)
    at Command.emit (events.js:185:7)
    at Command.parseArgs (/Users/Svilen/Development/testapp/node_modules/commander/index.js:615:12)
    at Command.parse (/Users/Svilen/Development/testapp/node_modules/commander/index.js:458:21)
    at Liftoff.invoke (/Users/Svilen/Development/testapp/node_modules/knex/lib/bin/cli.js:145:13)
    at Liftoff.<anonymous> (/Users/Svilen/Development/testapp/node_modules/liftoff/index.js:193:16)
    at module.exports (/Users/Svilen/Development/testapp/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/Users/Svilen/Development/testapp/node_modules/liftoff/index.js:185:9)
    at /Users/Svilen/Development/testapp/node_modules/liftoff/index.js:159:9
    at /Users/Svilen/Development/testapp/node_modules/v8flags/index.js:108:14
    at /Users/Svilen/Development/testapp/node_modules/v8flags/index.js:36:12
    at /Users/Svilen/Development/testapp/node_modules/v8flags/index.js:47:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:146:18)
    at node.js:404:3
```

Here's my package.json:

``` json
{
  "name": "testapp",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node app.js",
    "dev": "DEBUG=testapp:* nodemon app.js",
    "migrate:make": "knex migrate:make",
    "migrate:latest": "knex migrate:latest",
    "migrate:rollback": "knex migrate:rollback"
  },
  "dependencies": {
    "bcryptjs": "^2.3.0",
    "body-parser": "^1.15.1",
    "connect-flash": "^0.1.1",
    "connect-session-knex": "^1.0.22",
    "conveyor-belt": "^1.0.0",
    "cookie-parser": "^1.4.1",
    "csurf": "^1.8.3",
    "debug": "^2.2.0",
    "express": "^4.13.4",
    "express-handlebars": "^3.0.0",
    "express-session": "^1.13.0",
    "knex": "^0.11.1",
    "morgan": "^1.7.0",
    "pg": "^4.5.5",
    "serve-favicon": "^2.3.0"
  },
  "devDependencies": {
    "debug": "^2.2.0",
    "nodemon": "^1.9.1"
  }
}
```

And the migration I've created:

``` js
exports.up = function(knex, Promise) {
  return Promise.all([
    knex.schema.createTable('users', function (table) {
      table.increments()
      table.string('name')
      table.timestamps()
    })
  ])
};

exports.down = function(knex, Promise) {
  return Promise.all([
    knex.schema.dropTable('users')
  ])
}
```

I also tried returning a Promise from `knex.schema` directly after I call `createTable` but that didn't make a difference. Any ideas what might be the problem? Thanks!

Note: could be related to petkaantonov/bluebird/issues/482

**Comment by svileng** [comment]
Could be related to petkaantonov/bluebird/issues/482.

**Comment by svileng** [comment]
Reverting back to knex@0.10.0 removes the warnings, so it's probably related to the Bluebird upgrade done for knex@0.11.0.

**Comment by rhys-vdw** [comment]
@svileng Hm. Sounds like the fix @bendrucker applied is not appropriate for the newer version of Bluebird.

What do you think @wubzz?

**Comment by gaastonsr** [comment]
Using last version and receiving warnings but still working.

![image](https://cloud.githubusercontent.com/assets/2997285/15334859/86ea9d58-1c35-11e6-9f5e-66cae3c2738a.png)

**Comment by ezmiller** [comment]
I'm experiencing the same bug, and fixed it temporarily by switching to v0.10.0 also.

**Comment by gordysc** [comment]
I believe this can be closed out when the next release occurs (currently 0.12.5)

**Comment by mercmobily** [comment]
Thanks for reporting this issue! This was indeed a real problem that affected Knex versions 0.11.0 through 0.11.10.

This warning was triggered by Bluebird's promise tracking mechanism when a promise was created inside a handler but wasn't properly returned. The issue manifested specifically in the migration system's transaction handling code, as shown in your stack trace pointing to `_isLocked` and `_getLock` methods.


The issue was addressed in two commits:
- Commit `26e720f1` (May 30, 2016) - Initial fix for the promise warning
- Commit `bc5b4f05` (June 13, 2016) - Fixed the warning in additional places

These fixes were included in Knex 0.12.0, released in October 2016. As @gordysc correctly noted in the comments, the issue was resolved with the 0.12.x release series.

This issue is completely resolved in modern Knex versions. In fact, Knex no longer uses Bluebird at all - the dependency was gradually removed starting in 2020 (v0.21.x) and Knex now uses native JavaScript Promises. The migration system has also been significantly refactored since then.
