### ISSUE TITLE
When connection is lost to Postgres Knex crashes app

### ISSUE THREAD

**Issue by vjpr** [knex/knex#178]
_UPDATE: Need to remove connection from pool on failure._

When I drop and re-create a database (for example when using a migration command such as `rake db:migrate:reset` from the `standalone_migrations` gem) the following error crashes the app if Knex has a connection:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
error: terminating connection due to administrator command
  at [object Object].Connection.parseE (/xxx/node_modules/pg/lib/connection.js:561:11)
  at [object Object].Connection.parseMessage (/xxx/node_modules/pg/lib/connection.js:390:17)
  at [object Object].<anonymous> (/xxx/node_modules/pg/lib/connection.js:92:20)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)
```

The fix is to add error handlers on the connection for each client created in the Postgres driver. A global `pg.on('error', -> ...` doesn't seem to work. Just having an empty handler fixes the issue actually.

```
clients/server/postgres.js#44

  getRawConnection: function(callback) {
    var connection = new pg.Client(this.connectionSettings);
    connection.on('error', function(){ this.poolInstance.destroy(connection) })
```

Things to consider:
- What other errors might be thrown here?
- Should connection errors bubble up to the api user in Knex and Bookshelf?
- Anything else that needs to be done apart from `this.poolInstance.destroy(connection)`?

More details see: https://github.com/brianc/node-postgres/issues/465

**Comment by vonnieda** [comment]
This seems like it's still happening with knex 0.73 and and pg 4.2.0:

index.js
```
var knex = require('knex')({
    client: 'postgres',
    connection: 'postgresql://hrs@localhost/hrs'
});
```

```
> node index &
[1] 34326
[jason@Geode:~/Desktop/knex-disconnect-test]
> psql -U hrs hrs -c ' select pg_terminate_backend(pid) from pg_stat_activity where pid <> pg_backend_pid();'
 pg_terminate_backend 
----------------------
 t
 t
 t
(3 rows)


events.js:72
[jason@Geode:~/Desktop/knex-disconnect-test]
>         throw er; // Unhandled 'error' event
              ^
error: terminating connection due to administrator command
    at Connection.parseE (/Users/jason/Desktop/knex-disconnect-test/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/jason/Desktop/knex-disconnect-test/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/jason/Desktop/knex-disconnect-test/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)

[1]+  Exit 8                  node index
[jason@Geode:~/Desktop/knex-disconnect-test]
> 
```


Doing a Postgres restart will cause the same issue:

```
[jason@Geode:~/Desktop/knex-disconnect-test]
> node index &
[1] 34844
[jason@Geode:~/Desktop/knex-disconnect-test]
> pg_ctl restart -D /usr/local/var/postgres
waiting for server to shut down....LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
...........................LOG:  shutting down
LOG:  database system is shut down
FATAL:  the database system is shutting down
FATAL:  the database system is shutting down
 done
server stopped
server starting
[1]+  Done                    node index
[jason@Geode:~/Desktop/knex-disconnect-test]
> LOG:  database system was shut down at 2015-02-03 17:45:45 PST
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started

[jason@Geode:~/Desktop/knex-disconnect-test]
> 
```

**Comment by kayoub5** [comment]
this is fixed on `master` branch, but still broken for the `0.7` branch.
@tgriesser Any plans to fix this on the `0.7` branch as well? or planned for `0.8.*` ?

**Comment by mfrost66** [comment]
I'm evaluating using knex with postgres and I ran into this on day 1 of testing.  I see it's been 9 months since this was "fixed" and it's still broken on 0.7.6 & pg4.3.0.  Is this not fixed due to general lack of interested in postgres/knex, or just knex in general?

**Comment by tgriesser** [comment]
I'll work on getting an 0.8 release out by the end of the week.

**Comment by rarkins** [comment]
@tgriesser any update to share?

**Comment by rarkins** [comment]
@tgriesser is 0.8 still planned and will it be the first release to contain this knex/pg crash fix?

**Comment by tgriesser** [comment]
Yes, see #768 - it's a big one, with a lot of great new features like savepoints and named bindings in raw queries - just working on polishing things up in the next day or two. Though you can work off master and get the benefits of this fix.

In the future I'm going to keep a closer eye on PR's not getting all merged into master so it's easier to cut new releases.

**Comment by tgriesser** [comment]
Err, meant #786
