### ISSUE TITLE
Sqlite prints out rejection error during test run, but test is not failing

### ISSUE THREAD

**Issue by elhigu** [knex/knex#2921]
# Environment

Knex version: 0.16-next..
Database + version: sqlite3
OS: osx / linux at least

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Should not spam messages that actually looks like errors or if those really are errors, tests should fail or to be disabled if sqlite doesn't support the tested feature.

2. Error message

https://travis-ci.org/tgriesser/knex/jobs/457686812#L3025

Unhandled rejection AssertionError: Constraint "pk-test" not correctly created.: expected [ Array(1) ] to have the same members as [ Array(1) ]
    at /home/travis/build/tgriesser/knex/test/integration/schema/index.js:1343:51
From previous event:
    at Builder.Target.then (/home/travis/build/tgriesser/knex/lib/interface.js:3:172)
    at /home/travis/build/tgriesser/knex/test/integration/schema/index.js:1342:18
From previous event:
    at /home/travis/build/tgriesser/knex/test/integration/schema/index.js:1333:12
    at init.then.then.transactor (/home/travis/build/tgriesser/knex/lib/transaction.js:8:69)
From previous event:
    at Transaction._promise._bluebird.default.using.connection (/home/travis/build/tgriesser/knex/lib/transaction.js:5:1201)
From previous event:
    at new Transaction (/home/travis/build/tgriesser/knex/lib/transaction.js:5:730)
    at Client_SQLite3.transaction (/home/travis/build/tgriesser/knex/lib/client.js:6:3141)
    at Function.transaction (/home/travis/build/tgriesser/knex/lib/util/make-knex.js:4:99)
    at Context.<anonymous> (/home/travis/build/tgriesser/knex/test/integration/schema/index.js:1324:19)
    at callFn (/home/travis/build/tgriesser/knex/node_modules/mocha/lib/runnable.js:372:21)
    at Test.Runnable.run (/home/travis/build/tgriesser/knex/node_modules/mocha/lib/runnable.js:364:7)
    at Runner.runTest (/home/travis/build/tgriesser/knex/node_modules/mocha/lib/runner.js:455:10)
    at /home/travis/build/tgriesser/knex/node_modules/mocha/lib/runner.js:573:12
    at next (/home/travis/build/tgriesser/knex/node_modules/mocha/lib/runner.js:369:14)
    at /home/travis/build/tgriesser/knex/node_modules/mocha/lib/runner.js:379:7
    at next (/home/travis/build/tgriesser/knex/node_modules/mocha/lib/runner.js:303:14)
    at Immediate._onImmediate (/home/travis/build/tgriesser/knex/node_modules/mocha/lib/runner.js:347:5)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

```
npm run test
```

**Comment by kibertoad** [comment]
I think this is related to how transaction rollback was handled previously, this is no longer the case and I can't reproduce it anymore
