### ISSUE TITLE
Using .raw with an escaped question mark ('\\?') produce a syntax error

### ISSUE THREAD

**Issue by jajm** [knex/knex#3112]
# Environment

Knex version: 0.16.3
Database + version: mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper
OS: Debian buster

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Using .raw with an escaped question mark (`'\\?'`) and other methods (limit, where, ...), database server returns a syntax error

2. Error message

```
Unhandled rejection Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1
    at Query.Sequence._packetToError (/home/urungi/urungi/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/urungi/urungi/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/urungi/urungi/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/home/urungi/urungi/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/urungi/urungi/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/urungi/urungi/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/home/urungi/urungi/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
    --------------------
    at Protocol._enqueue (/home/urungi/urungi/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/urungi/urungi/node_modules/mysql/lib/Connection.js:200:25)
    at /home/urungi/urungi/node_modules/knex/lib/dialects/mysql/index.js:144:18
    at Promise._execute (/home/urungi/urungi/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/home/urungi/urungi/node_modules/knex/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/urungi/urungi/node_modules/knex/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/home/urungi/urungi/node_modules/knex/lib/dialects/mysql/index.js:135:12)
    at Client_MySQL.query (/home/urungi/urungi/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/home/urungi/urungi/node_modules/knex/lib/runner.js:138:36)
    at Runner.tryCatcher (/home/urungi/urungi/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/home/urungi/urungi/node_modules/knex/node_modules/bluebird/js/release/method.js:15:34)
    at /home/urungi/urungi/node_modules/knex/lib/runner.js:47:21
    at tryCatcher (/home/urungi/urungi/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at /home/urungi/urungi/node_modules/knex/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/home/urungi/urungi/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/urungi/urungi/node_modules/knex/node_modules/bluebird/js/release/promise.js:512:31)
```

3. Reduced test code

```js
const knex = require('knex')({
    client: 'mysql',
    connection: {
        host: '127.0.0.1',
        user: 'user',
        password: 'user',
        database: 'koha'
    }
});

const qb = knex('borrowers')
    .select(knex.raw('CONCAT(??, "\\?")', 'borrowernumber'))
    .limit(1);

console.log(qb.toString());
// select CONCAT(`borrowernumber`, "?") from `borrowers` limit 1
// This query, if executed manually in mysql client, is valid and returns results

qb.then(result => {
    console.log(result);  // This is never executed
});
```

**Comment by wubzz** [comment]
Shouldn't it be `'\\?'` rather than `"\\?"` ? Not too keen on mysql syntax.. But using Postgres the example above works just fine _(after replacing " with ' ofc)_

**Comment by elhigu** [comment]
Knex seems to be doing there what it is supposed to be doing: https://runkit.com/embed/fn2wqp4ylahy (note that toString() doesn't give very truthful image what query is actually been run by knex).

However... since mysql uses `?` marks natively as paramater bindings , maybe they require some special escaping for mysql driver?

**Comment by jajm** [comment]
> Shouldn't it be `'\\?'` rather than `"\\?"` ? Not too keen on mysql syntax.. But using Postgres the example above works just fine _(after replacing " with ' ofc)_

I tried with simple quotes but it doesn't work (same error message)



> Knex seems to be doing there what it is supposed to be doing: https://runkit.com/embed/fn2wqp4ylahy (note that toString() doesn't give very truthful image what query is actually been run by knex).
> 
> However... since mysql uses `?` marks natively as paramater bindings , maybe they require some special escaping for mysql driver?

The only way I found to escape '?' for mysql client is by using `mysql.raw`.
The following snippet works:
```js
const mysql = require('mysql');
const qb = knex('borrowers')
      .select(knex.raw('CONCAT(??, "?")', ['borrowernumber', mysql.raw('?')]))
      .limit(1);
```
while the following doesn't work
```js
const qb = knex('borrowers')
      .select(knex.raw('CONCAT(??, "?")', ['borrowernumber', knex.raw('?')]))
      .limit(1);
```
Note that if I remove the `.limit(1)`, then the query works as expected:
```js
const qb = knex('borrowers')
    .select(knex.raw('CONCAT(??, "\\?")', 'borrowernumber'));
```

**Comment by elhigu** [comment]
Thanks for the info.

It is not unexpected that second one doesn't work and the last one works kind of by accident, because there are no value bindings at all in the query. 

I would accept PR which converts escaped ? automatically to mysql.raw value replacements in mysql dialect. I consider this actually as bug, since toSQL().toNative() should produce query and bindings that are runnable through mysql driver.

**Comment by tbenita** [comment]
wahoo ! tricky ! Thanks for the tip

**Comment by tbenita** [comment]
'?' still has a side effect : 
I have a request that renders a string that contains '?'. When I am in the report editor AND if there is a row limit (which is by default) then the limit value takes place of the first '?' caracter (the request is something like : 
"""
SELECT concat ('http://myurl?', some_field), ***
FROM***
LIMIT ?
"""
Gives with a 10 row limit : 
"""
SELECT concat ('http://myurl10', some_field), ***
FROM***
LIMIT ?
"""

**Comment by elhigu** [comment]
@tbenita sounds like you are not using knex raw parameter bindings correctly (thus using knex in a wrong way), please ask help from stackoverflow and add also some code, how are you generating those strings.

**Comment by wholebuzz** [comment]
`knex.raw()` seems to be replacing question marks within strings.  e.g. `knex.raw(INSERT INTO foo (bar) VALUES ('hello ?')` gets inserted with `hello $25`.  I was trying to use `knex-migrate-sql-file` to do some bulk INSERTs from a pg_dump file and everything blew up with corrupted data.

**Comment by wholebuzz** [comment]
I created PR https://github.com/ozum/knex-migrate-sql-file/pull/4 to escape question marks in SQL file.  Any suggestions appreciated.  Works better than it did for me, but I worry there's more edge cases to trip over in the future.

**Comment by Martindelataille** [comment]
I tried with \\? and it's working by now.

Ticket can be close.

**Comment by stefanorumi7** [comment]
This problem persists with knex v1.0.4 and Postgres v12+
`q.whereRaw('i.foo @\\? \'$.*.bar \\? (@ == "?")\'', bar)`
Yields the error: `Error: Expected 1 bindings, saw 3`

**Comment by iyuiasd7** [comment]
This issue occurred in knex v2.0.0 and Oracle 12.1c
<code>db.whereRaw(&#96;REGEXP_LIKE("column1", '^[+-]\\\\?\\\\d*\\.\\\\?\\\\d+([eE][+-]\\\\?\\\\d+)\\\\?$')&#96;)</code>
the original regex is `^[+-]?\d*\.?\d+([eE][+-]?\d+)?$`  
I checked the v$sql in oracle, even though I escaped `?` as `\\?`, knex translates all question marks into parameter binding
any advise would be appreciated

**Comment by OlivierCavadenti** [comment]
Same that https://github.com/knex/knex/issues/5189

**Comment by julianwagle** [comment]
This issue is still persisting. Attempting to use raw transactions to update URL's in a MySQL database. Any updates on this big?

**Comment by 675076143** [comment]
`\\u003F` solved my problems : )

**Comment by sadiqueWiseboxs** [comment]
@675076143 how does this \\u003F solved the issue any example please

**Comment by mmarkell** [comment]
@sadiqueWiseboxs , basically if you're trying to escape characters that go into the `knex.raw` value, you can use `badString.replace(
        /\?/g,
        "\\u003F"
    );`.

**Comment by erikverheij** [comment]
I was able to work around it by injecting the question marks as a param:

```
const params = {
  questionMark: '?',
};

knex.raw(
  `SELECT CONCAT('https://example.com', :questionMark, 'id=', entities.id) AS url from entities`,
  params
);
```
