### ISSUE TITLE
Flaky test on pg/Node 8

### ISSUE THREAD

**Issue by kibertoad** [knex/knex#3321]
Don't think I've seen it failing before:

```
  1) postgresql | pg
       Additional
         .timeout(ms, {cancel: true}) should release connections after failing if connection cancellation throws an error:
      AssertionError: expected { Object (name, message) } to deeply equal { Object (timeout, name, ...) }
      + expected - actual
       {
      -  "message": "expected { Object (name, message) } to deeply equal { Object (timeout, name, ...) }"
      -  "name": "AssertionError"
      +  "message": "Defined query timeout of 11ms exceeded when running query."
      +  "name": "TimeoutError"
      +  "timeout": 11
       }
      
      at /home/travis/build/tgriesser/knex/test/integration/builder/additional.js:933:71
  From previous event:
      at Context.<anonymous> (test/integration/builder/additional.js:932:15)
```

Maybe we need to slightly increase timeouts.

**Comment by elhigu** [comment]
If there is some millisecond specific waiting or something like that, usually its good to wait at least 5ms extra...

**Comment by kibertoad** [comment]
Haven't seen it in a while, closing.
