### ISSUE TITLE
Add --seeds-directory option

### ISSUE THREAD

**Issue by vladshcherbin** [knex/knex#3356]
# Environment

Knex version: 0.17.5
Database + version: PG 10.5
OS: Mac OS 10.13.4

# Feature discussion / request

It would be nice to have a `--seeds-directory` option, similar to `--migrations-directory` one. It's useful when you don't/can't use knexfile but still want to generate seeds in specific directory.

```
yarn knex --seeds-directory src/server/seeds seed:make users
```

**Comment by candyapplecorn** [comment]
I've just finished opening a pull request which may support this sort of functionality, albeit in a slightly different way: https://github.com/tgriesser/knex/pull/3357

It'd look like this:

`yarn knex seed:make --subdirectory src/server/seeds users`

If you can spare a minute, please give my pull request a quick review!

**Comment by vladshcherbin** [comment]
@candyapplecorn hey, the api looks exactly what I need.

I've tried your branch, but it gives an error for me. I tried both variants from your message and the error is:

```terminal
$ /Users/shcherbin/Sites/tests/knex-seeds/node_modules/.bin/knex seed:make --subdirectory src/server/seeds users
Failed to find configuration at default location of /Users/shcherbin/Sites/tests/knex-seeds/knexfile.js
Using environment: development
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:1037:7)
    at Seeder.<anonymous> (/Users/shcherbin/Sites/tests/knex-seeds/node_modules/knex/lib/seed/Seeder.js:177:12)
    at Seeder.tryCatcher (/Users/shcherbin/Sites/tests/knex-seeds/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/shcherbin/Sites/tests/knex-seeds/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/shcherbin/Sites/tests/knex-seeds/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/shcherbin/Sites/tests/knex-seeds/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/shcherbin/Sites/tests/knex-seeds/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/Users/shcherbin/Sites/tests/knex-seeds/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/Users/shcherbin/Sites/tests/knex-seeds/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/Users/shcherbin/Sites/tests/knex-seeds/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/Users/shcherbin/Sites/tests/knex-seeds/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/shcherbin/Sites/tests/knex-seeds/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/shcherbin/Sites/tests/knex-seeds/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/Users/shcherbin/Sites/tests/knex-seeds/node_modules/bluebird/js/release/promise.js:643:18)
    at /Users/shcherbin/Sites/tests/knex-seeds/node_modules/bluebird/js/release/nodeback.js:42:21
error Command failed with exit code 1.
```

**Comment by candyapplecorn** [comment]
Thought I fixed that earlier today. Can you pull down the changes and try one more time for me please @vladshcherbin ?

**Comment by flaviosilveira** [comment]
I know this is an old one, but in the last versions we have --directory option.

[Seeds CLI options](https://knexjs.org/#Seeds-CLI)

Looks like (at least for me, version ^0.20) override that config via command line is not working, I will try a PR in order to fix that

**Comment by EmmanDizon** [comment]
is this already solved?

**Comment by PinoFlores** [comment]
This is the way that worked for me:

My seeds directory => `<projectname/>database/seeds`


**How I call it**
```cmd
    shell.exec(`knex seed:make ../database/seeds/dev/${modelName}`);
```

As the `seed:make` by default try to create a `seed` dir, i call `../` for leave that and place the seed file in the dir I want.

**Comment by leanhvu21042001** [comment]
.

**Comment by mercmobily** [comment]
Here is a short summary: The CLI exposes `--migrations-directory` but there is no analogous `--seeds-directory` flag. Relevant command options are in bin/cli.js:83–119 for global options and bin/cli.js:320–370 for `seed:make`/`seed:run`. At present, the seed directory is resolved from the knexfile (`config.seeds.directory`) and there is no CLI override for it. Adding `--seeds-directory` would mirror `--migrations-directory` and thread through to the seeder configuration merger.

In the code: bin/cli.js:98–119 exposes `--migrations-directory` but nothing for seeds. `seed:make`/`seed:run` rely on resolved config (bin/cli.js:344–370), not a CLI directory override.

This feature is reasonable and consistent with migrations. Implementing it would involve:
- Adding a Commander option `--seeds-directory`.
- Parsing it into `opts` and merging into `config.seeds.directory` (similar to how migrations are handled).
- Ensuring the seeder configuration merger respects the override.

Until then, set the directory in your knexfile under `seeds.directory`.

I added this to the migrations metaissue, #6293 
.
