### ISSUE TITLE
Serialization error on transaction commit is not thrown

### ISSUE THREAD

**Issue by schuma7** [knex/knex#3370]
# Environment

Knex version: 0.19.1
Database + version: Postgres 11.2
OS: Mac OS 10.14.2

# Bug

1./2.

I’m trying to run two transactions with serializable isolation level concurrently using the code snippet in point 3.

As you can see I’m trying to update two separate rows on the same table. In my test scenario this table just has 3 rows. Executing this snippet on the “postgres:11.2” docker image yields the following output:

```
======> tx2 failed { error: could not serialize access due to read/write dependencies among transactions
    at Connection.parseE (/Users/user/pg-test/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/Users/user/pg-test/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/Users/user/pg-test/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)
From previous event:
    at Client_PG._query (/Users/user/pg-test/node_modules/knex/lib/dialects/postgres/index.js:245:12)
    at Client_PG.query (/Users/user/pg-test/node_modules/knex/lib/client.js:192:17)
    at /Users/user/pg-test/node_modules/knex/lib/transaction.js:232:21
From previous event:
    at Client_PG.trxClient.query (/Users/user/pg-test/node_modules/knex/lib/transaction.js:229:33)
    at Transaction.query (/Users/user/pg-test/node_modules/knex/lib/transaction.js:114:30)
    at Transaction.commit (/Users/user/pg-test/node_modules/knex/lib/transaction.js:94:17)
    at Function.transactor.commit.value [as commit] (/Users/user/pg-test/node_modules/knex/lib/transaction.js:194:38)
    at knex.table.where.update.transacting.then (/Users/user/pg-test/tmp/test.ts:59:31)
  name: 'error',
  length: 282,
  severity: 'ERROR',
  code: '40001',
  detail:
   'Reason code: Canceled on identification as a pivot, during commit attempt.',
  hint: 'The transaction might succeed if retried.',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'predicate.c',
  line: '4685',
  routine: 'PreCommit_CheckForSerializationFailure' }
======> tx2 committed
======> tx1 committed
======> updates succeeded
```

So it logs both transactions as committed instead of one ‘committed’ for the first one and one ‘rolled back’ for the second failed transaction. The library is not throwing on trx.commit() which according to the postgres logs is the statement that triggers the serialization error.

Please note that Knex behaves as expected when I replace ```await trx.commit();``` with ```await trx.raw('COMMIT')```. In which case it produces the following output:

```
======> tx1 committed
======> tx2 failed Error: Transaction rejected with non-error: undefined
    at q.trxClient.query.catch.tap (/Users/user/pg-test/node_modules/knex/lib/transaction.js:126:19)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Transaction._promise._bluebird.default.using.connection (/Users/user/pg-test/node_modules/knex/lib/transaction.js:63:14)
    at runCallback (timers.js:696:18)
From previous event:
    at new Transaction (/Users/user/pg-test/node_modules/knex/lib/transaction.js:36:39)
    at Client_PG.transaction (/Users/user/pg-test/node_modules/knex/lib/client.js:141:12)
    at Function.transaction (/Users/user/pg-test/node_modules/knex/lib/util/make-knex.js:58:31)
    at Promise (/Users/user/pg-test/tmp/test.ts:51:14)
    at new Promise (<anonymous>)
    at run (/Users/user/pg-test/tmp/test.ts:50:17)
    at Object.<anonymous> (/Users/user/pg-test/tmp/test.ts:81:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module.m._compile (/private/var/folders/qw/rq62bnpd4c9glv8gy2_1f0pw0000gn/T/ts-node-dev-hook-9593958921628161.js:55:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at require.extensions.(anonymous function) (/private/var/folders/qw/rq62bnpd4c9glv8gy2_1f0pw0000gn/T/ts-node-dev-hook-9593958921628161.js:57:14)
    at Object.nodeDevHook [as .ts] (/Users/user/pg-test/node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
======> tx2 rolled back { error: could not serialize access due to read/write dependencies among transactions
    at Connection.parseE (/Users/user/pg-test/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/Users/user/pg-test/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/Users/user/pg-test/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)
From previous event:
    at Client_PG._query (/Users/user/pg-test/node_modules/knex/lib/dialects/postgres/index.js:245:12)
    at Client_PG.query (/Users/user/pg-test/node_modules/knex/lib/client.js:192:17)
    at /Users/user/pg-test/node_modules/knex/lib/transaction.js:232:21
From previous event:
    at Client_PG.trxClient.query (/Users/user/pg-test/node_modules/knex/lib/transaction.js:229:33)
    at Runner.<anonymous> (/Users/user/pg-test/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /Users/user/pg-test/node_modules/knex/lib/runner.js:47:21
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
From previous event:
    at Runner.run (/Users/user/pg-test/node_modules/knex/lib/runner.js:33:30)
    at Raw.Target.then (/Users/user/pg-test/node_modules/knex/lib/interface.js:23:43)
  name: 'error',
  length: 282,
  severity: 'ERROR',
  code: '40001',
  detail:
   'Reason code: Canceled on identification as a pivot, during commit attempt.',
  hint: 'The transaction might succeed if retried.',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'predicate.c',
  line: '4685',
  routine: 'PreCommit_CheckForSerializationFailure' }
======> updates failed
```

3. 
```
import Knex from 'knex';

const knex = Knex({
  client: 'pg',
  version: '11.2',
});

const sleep = (timeoutMs: number): Promise<void> =>
  new Promise((resolve) => setTimeout(resolve, timeoutMs));

async function run() {
  const tx1 = new Promise((resolve, reject) => {
    knex.transaction(function(trx) {
      trx.raw('set transaction isolation level serializable;').then(() => {
        knex.table('test_table')
          .where({id: 1})
          .update({ value: 'update 1'})
          .transacting(trx)
          .then(async () => {
            await sleep(3000)
            await trx.commit();
            console.log('======> tx1 committed');
            resolve();
          })
          .catch(async (err) => {
            await trx.rollback();
            console.log('======> tx1 rolled back', err);
            reject(err);
          });
      });
    }).catch((err) => {
      console.error('======> tx1 failed', err);
    });
  });

  const tx2 = new Promise((resolve, reject) => {
    knex.transaction(function(trx) {
      trx.raw('set transaction isolation level serializable;').then(() => {
        knex.table('test_table')
          .where({id: 2})
          .update({ value: 'update 2'})
          .transacting(trx)
          .then(async () => {
            await sleep(3000)
            await trx.commit();
            console.log('======> tx2 committed');
            resolve();
          })
          .catch(async (err) => {
            await trx.rollback();
            console.log('======> tx2 rolled back', err);
            reject(err);
          });
      });
    }).catch((err) => {
      console.error('======> tx2 failed', err);
    });
  });

  try {
    await Promise.all([tx1, tx2]);
    console.error('======> updates succeeded');
  } catch (err) {
    console.error('======> updates failed');
  }
}

run();
```

**Comment by elhigu** [comment]
Could you run your code with `DEBUG` environment variable set? According to this there could be some logs explaining why that happens https://github.com/tgriesser/knex/blob/master/lib/transaction.js#L178

```
DEBUG=knex:* 
```

Sounds like a bug though.

**Comment by schuma7** [comment]
It seems like that line is indeed logged out:

```
knex:tx trx1: Starting top level transaction +0ms
  knex:tx trx2: Starting top level transaction +9ms
  knex:client acquired connection from pool: __knexUid3 +0ms
  knex:query BEGIN; trx1 +0ms
  knex:bindings undefined trx1 +0ms
  knex:client acquired connection from pool: __knexUid4 +3ms
  knex:query BEGIN; trx2 +3ms
  knex:bindings undefined trx2 +3ms
  knex:query set transaction isolation level serializable; trx1 +3ms
  knex:bindings [] trx1 +3ms
  knex:query set transaction isolation level serializable; trx2 +2ms
  knex:bindings [] trx2 +2ms
  knex:query update "registry"."tx_processor_data" set "value" = ? where "id" = ? trx1 +5ms
  knex:bindings [ 'update 1', 2 ] trx1 +5ms
  knex:query update "registry"."tx_processor_data" set "value" = ? where "id" = ? trx2 +3ms
  knex:bindings [ 'update 2', 3 ] trx2 +3ms
  knex:query COMMIT; trx1 +3s
  knex:bindings undefined trx1 +3s
  knex:query COMMIT; trx2 +3ms
  knex:bindings undefined trx2 +3ms
  knex:tx trx2 error running transaction query +3s
  knex:tx trx2: releasing connection +0ms
  knex:client releasing connection to pool: __knexUid4 +3s
======> tx2 failed { error: could not serialize access due to read/write dependencies among transactions
    at Connection.parseE (/Users/user/pg-test/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/Users/user/pg-test/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/Users/user/pg-test/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)
From previous event:
    at Client_PG._query (/Users/user/pg-test/node_modules/knex/lib/dialects/postgres/index.js:234:12)
    at Client_PG.query (/Users/user/pg-test/node_modules/knex/lib/client.js:158:17)
    at /Users/user/pg-test/node_modules/knex/lib/transaction.js:307:24
From previous event:
    at Client_PG.trxClient.query (/Users/user/pg-test/node_modules/knex/lib/transaction.js:302:12)
    at Transaction.query (/Users/user/pg-test/node_modules/knex/lib/transaction.js:173:8)
    at Transaction.commit (/Users/user/pg-test/node_modules/knex/lib/transaction.js:148:17)
    at Function.transactor.commit (/Users/user/pg-test/node_modules/knex/lib/transaction.js:263:40)
    at knex.table.where.update.transacting.then (/Users/user/pg-test/tmp/test.ts:66:31)
  name: 'error',
  length: 282,
  severity: 'ERROR',
  code: '40001',
  detail:
   'Reason code: Canceled on identification as a pivot, during commit attempt.',
  hint: 'The transaction might succeed if retried.',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'predicate.c',
  line: '4685',
  routine: 'PreCommit_CheckForSerializationFailure' }
======> tx2 committed
  knex:tx trx1: releasing connection +3ms
  knex:client releasing connection to pool: __knexUid3 +3ms
======> tx1 committed
======> updates succeeded
```

**Comment by schuma7** [comment]
Was wondering if there might be an update on this issue, since it's causing issues that are rather difficult to debug in applications that make use of serializable transactions. Would be great to know how this is currently prioritized?

Thanks

**Comment by elhigu** [comment]
AFAIK no one is working on this. PRs are welcome.

**Comment by javiertury** [comment]
I have explored related issues, and in #3246 I found out what I in my opinion is the real issue. In that discussion they quote @elhigu 
> There actually is kind of a good reason for forcing to have handler for rejects... transaction may be implicitly rejected from database side (actually even postgres does that by default if any of the queries done in transaction fails) and we should always have some kind of handler to catch those implicit rejects. That is actually something which for we should tests and documentation.
> so basically one should always get result of transaction through that result promise that is given when transaction is created... i don't know... that stuff is pretty ugly 😒
> we should try to come up some good syntax which handles explicit and implicit rejects nicely...

Transaction controlling queries('BEGIN', 'COMMIT', 'ROLLBACK', etc.) are treated different than regular queries. They are treated as non-failable, or made to appear non-failable. Any failure is silently transfered to the underlying `trx.executionPromise`.

According to this logic, error handlings should be applied to executionPromise. We as users are expected to use:
```
await t.commit();
await t.executionPromise;
```

An alternative, is to surface the errors related to transaction controlling queries. I've worked on this in [javiertury/knex#fix_commit_throw](https://github.com/javiertury/knex/tree/fix_commit_throw), maintaining the existing behavior of `executionPromise` intact.

```
  // lib/transaction.js
  query(conn, sql, status, value) {
    let isQueryError = false;

    const q = this.trxClient
      .query(conn, sql)
      .catch((err) => {
        status = 2;
        isQueryError = true;
        value = err;
        this._completed = true;
      })
      .then((res) => {
        const isNotRejectableRollback =
          this.doNotRejectOnRollback && /^ROLLBACK\b/i.test(sql);

        if (status === 1) {
          this._resolver(value);
        }
        if (status === 2) {
        } else if (status === 2) {
          if (value === undefined) {
            if (isNotRejectableRollback) {
              this._resolver();
              return;
            }
          }
          this._rejecter(value);
        }

        // Here! The promise is rejected 
        if (isQueryError && !isNotRejectableRollback) {
          throw value;
        }
        return res;
```

Advantages:
- Transparency regarding the result of underlying statements

Disadvantages:
- Users may think they don't need to check `t.executionPromise`

Hot topics:
- Deferred constraints, which are checked on 'COMMIT' and 'RELEASE SAVEPOINT'.
- Serialization failures, which are happen at 'COMMIT' and 'RELEASE SAVEPOINT'.
- Failure to execute 'ROLLBACK'.

Finally I want to emphasize the argument given by @elhigu about handling implicit rejections from the database side. I think it's **very** important. Regardless of the alternative, we should document and encourage users to handle errors using `t.executionPromise`.

**Comment by mercmobily** [comment]
Knex needs a change in transaction error propagation. Today `trx.commit()` issues `COMMIT;` via `Transaction.query`, and if the underlying driver rejects, we mark the transaction completed and resolve/reject through the internal execution promise. However, the promise returned by `trx.commit()` itself doesn’t surface the error in all cases, so you can see “committed” logs even when the database raised `40001` at commit.

Evidence: lib/execution/transaction.js:114–173, 180–214. The `query` helper catches and stores the error, then calls `_rejecter` to reject the execution promise, but does not rethrow to the caller of `trx.commit()` unless you were using `trx.raw('COMMIT')` (which goes through the normal query path and throws).

To fix it,  when a control statement fails (commit/savepoint release), rethrow the error from `Transaction.query` after signalling the execution promise, except for tolerated rollbacks (`doNotRejectOnRollback`). @javiertury’s suggested patch in the discussion is a good starting point. We should add tests for serialisation failures and deferred constraints to cover this path.

Workaround for now: after `trx.commit()`, also `await trx.executionPromise` to surface any commit‑time errors reliably.
