### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'raw' of undefined

### ISSUE THREAD

**Issue by brandonros** [knex/knex#3378]
# Environment

Knex version: 0.19.0
Database + version: Postgres latest (Docker)
OS: Mac OS X host, Linux Docker container

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

This code worked fine in v0.15.4

2. Error message

```
Unhandled rejection TypeError: Cannot read property 'raw' of undefined
    at raw (/Users/bros/repos/node-database/node_modules/knex/lib/util/make-knex.js:29:26)
    at Object.<anonymous> (/Users/bros/repos/node-database/test/e2e/database.spec.ts:66:13)
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

```
export class DatabaseConnection {
  db: Knex

  constructor (db: Knex) {
    this.db = db
  }

  async query (sql: string, parameters: Array<any>): Promise<QueryResult> {
    const { rowCount, rows } = await this.db.raw(sql, parameters)
    return { rowCount, rows }
  }

  async migrate (): Promise<void> {
    await this.db.migrate.latest()
  }

  /*
    Get a Knex transaction object, then expose the transaction object .raw property to a callback.
  */

  async transaction (cb: (executeQuery: Function) => Promise<any>): Promise<any> {
    return new Promise((resolve, reject) => {
      this.db.transaction(async (trx: any) => {
        try {
          const results = await cb(trx.raw)
          await trx.commit()
          resolve(results)
        } catch (err) {
          await trx.rollback(err)
          reject(err)
        }
      })
    })
  }
}

export const performTransaction = (cb: (executeQuery: Function) => Promise<any>, retryOptions: retry.OperationOptions = defaultRetryOptions): Promise<any> => {
  return new Promise((resolve, reject) => {
    let operation = retry.operation(retryOptions)
    operation.attempt((currentAttempt: number) => {
      getDatabaseConnection()
      .then((db: DatabaseConnection) => db.transaction(cb))
      .then(resolve)
      .catch((err: Error) => {
        if (shouldRetryError(err) && operation.retry(err)) {
          return
        }
        reject(err)
      })
    })
  })
}

it('should execute queries in a transaction', async () => {
    const { rowCount, rows } = await performTransaction(async (executeQuery: any) => {
      const row = {foo: 'bar'}
      const tableName = 'test'
      const fieldNames = ['foo']
      const { sql: insertSql, bindings: insertBindings } = getQueryBuilder().insert(row)
        .table(tableName)
        .toSQL()
      await executeQuery(insertSql, insertBindings)
      const { sql: selectSql, bindings: selectBindings } = getQueryBuilder().select(fieldNames)
        .table(tableName)
        .toSQL()
      return executeQuery(selectSql, selectBindings)
    })
    expect(rows.length).toEqual(1)
    /* Clean up */
    await deleteRows('test', {foo: 'bar'})
  })
```

**Comment by brandonros** [comment]
0.17.0 + 0.16.0 yield

```
 TypeError: Cannot read property 'client' of undefined
    at raw (/Users/bros/repos/node-database/node_modules/knex/lib/util/make-knex.js:48:19)
```

**Comment by ricardograca** [comment]
What line exactly in the above code example is throwing this error?

**Comment by elhigu** [comment]
@brandonros you check that you are passing db config correctly to knex. Error says that you are not doing it properly. I suppose your getDatabaseConnection function returns something invalid. Also when adding reproduction code, please add complete code that can be ran.

**Comment by brandonros** [comment]
@ricardograca https://github.com/tgriesser/knex/blob/master/lib/util/make-knex.js#L28

why would `this.client` be undefined there? again, same code worked in `0.15.2` but is broken in `0.16.x` on.

**Comment by brandonros** [comment]
For anybody else, I fixed it by wrapping `trx.raw` in a function instead of passing `trx.raw` directly to my callback.

**Comment by ricardograca** [comment]
I wasn't asking what line of code inside Knex was throwing the error. That is a bit meaningless. I wanted to know what line in your code was throwing the error.

**Comment by brandonros** [comment]
```
it('should execute queries in a transaction', async () => {
    const { rowCount, rows } = await performTransaction(async (executeQuery: any) => {
      const row = {foo: 'bar'}
      const tableName = 'test'
      const fieldNames = ['foo']
      const { sql: insertSql, bindings: insertBindings } = getQueryBuilder().insert(row)
        .table(tableName)
        .toSQL()
      await executeQuery(insertSql, insertBindings)
      const { sql: selectSql, bindings: selectBindings } = getQueryBuilder().select(fieldNames)
        .table(tableName)
        .toSQL()
      return executeQuery(selectSql, selectBindings)
    })
    expect(rows.length).toEqual(1)
    /* Clean up */
    await deleteRows('test', {foo: 'bar'})
  })
```

`executeQuery` is really `trx.raw`, so the first `await executeQuery(insertSql, insertBindings)` freaks out because `this` isn't applied to itself or something weird along those lines.

before, broken:

```
async transaction (cb: (executeQuery: Function) => Promise<any>): Promise<any> {
    return new Promise((resolve, reject) => {
      this.db.transaction(async (trx: any) => {
        try {
          const results = await cb(trx.raw)
          await trx.commit()
          resolve(results)
        } catch (err) {
          await trx.rollback(err)
          reject(err)
        }
      })
    })
  }
```

after, working:

```
async transaction (cb: (executeQuery: Function) => Promise<any>): Promise<any> {
    return new Promise((resolve, reject) => {
      this.db.transaction(async (trx: any) => {
        try {
          const executeQuery = (sql: string, bindings: any) => {
            return trx.raw(sql, bindings)
          }
          const results = await cb(executeQuery)
          await trx.commit()
          resolve(results)
        } catch (err) {
          await trx.rollback(err)
          reject(err)
        }
      })
    })
  }
```

**Comment by kibertoad** [comment]
Looks interesting, I'll look into it.

**Comment by brandonros** [comment]
```
const Knex = require('knex')

const getDatabaseConnection = () => {
  const config = {}
  return Knex(config)
}

const transactionWrapper = (db, cb) => {
  return new Promise((resolve, reject) => {
    db.transaction(async (trx) => {
      try {
        const results = await cb(trx.raw)
        await trx.commit()
        resolve(results)
      } catch (err) {
        await trx.rollback(err)
        reject(err)
      }
    })
  })
}

const performTransaction = (cb) => {
  const db = getDatabaseConnection()
  return transactionWrapper(db, cb)
}

const run = async () => {
  const result = await performTransaction((executeQuery) => {
    await executeQuery('SELECT 1', [])
  })
  console.log(result)
}

run()
```

let me know if this minified sample is enough. if you tell me what to put for `config` for mock database, I might be able to help.

**Comment by maximelkin** [comment]
@brandonros isn't this just loosing of context then calling trx.raw?
try to bind trx.raw to trx

**Comment by brandonros** [comment]
correct!
