### ISSUE TITLE
table charset and collate doesnt exist

### ISSUE THREAD

**Issue by Meldiron** [knex/knex#3478]
# Environment

Knex version: 0.19.5
Database + version: mysql  Ver 8.0.17 for osx10.13 on x86_64 (Homebrew)
OS: macOS 10.13.4 (17E199)

# Bug

1. I have created migration which works perfectly, but uses wrong collation. When I try to set collation using methods I found on wiki, typescript says they doesnt exist.

2. Error message:
```
migrations/20191009105856_create_channels_table.ts:6:11 - error TS2339: Property 'collate' does not exist on type 'CreateTableBuilder'.

6     table.collate('utf8_general_ci');
            ~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:240:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:244:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:360:34)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:393:11)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at FsMigrations.getMigration (/Users/meldiron/Desktop/CraftUpdateLog/Server/node_modules/knex/lib/migrate/sources/fs-migrations.js:84:12)
    at /Users/meldiron/Desktop/CraftUpdateLog/Server/node_modules/knex/lib/migrate/Migrator.js:82:69
    at arrayFilter (/Users/meldiron/Desktop/CraftUpdateLog/Server/node_modules/knex/node_modules/lodash/lodash.js:582:11)
    at filter (/Users/meldiron/Desktop/CraftUpdateLog/Server/node_modules/knex/node_modules/lodash/lodash.js:9173:14)
    at /Users/meldiron/Desktop/CraftUpdateLog/Server/node_modules/knex/lib/migrate/Migrator.js:81:13
```

3. Migration:
```
import * as Knex from 'knex';

export async function up(knex: Knex): Promise<any> {
  return knex.schema.createTable('channels', table => {
    table.charset('utf8');
    table.collate('utf8_general_ci');

    table.increments();

    table.string('name', 128).notNullable();
    table.string('tag', 128).notNullable();
    table
      .integer('priority')
      .notNullable()
      .defaultTo(0);
    table
      .boolean('published')
      .notNullable()
      .defaultTo(0);

    table
      .string('img_url', 128)
      .notNullable()
      .defaultTo(
        'https://craftmania-static.s3.eu-central-1.amazonaws.com/logo/new/logo_animated_bg.gif'
      );

    table
      .string('color', 128)
      .notNullable()
      .defaultTo('ffffff');

    table
      .timestamp('created_at')
      .notNullable()
      .defaultTo(knex.fn.now());
  });
}

export async function down(knex: Knex): Promise<any> {
  knex.schema.dropTable('channels');
}
```

Reduced migration:
```
import * as Knex from 'knex';

export async function up(knex: Knex): Promise<any> {
  return knex.schema.createTable('channels', table => {
    table.charset('utf8');
    table.collate('utf8_general_ci');

    table.increments();
    table.string('name', 128).notNullable();
  });
}

export async function down(knex: Knex): Promise<any> {
  knex.schema.dropTable('channels');
}

```

Comment:
Problem is pretty simple to understeand. In my opinion knex removed this method but its still on wiki, maybe it got replaced. How do I set collation of the table when creating it using Knex?

**Comment by lorefnon** [comment]
Those methods still exist but are only available for MySQL client. 

Currently the only way to tell typescript to allow MySQL specific APIs is by casting `table` to `Knex.MySqlTableBuilder`.

**Comment by kibertoad** [comment]
@lorefnon Wouldn't it be better to expose them always, but throw NotImplemented error on other dialects?

**Comment by lorefnon** [comment]
That is actually the [current  behavior](https://github.com/knex/knex/blob/9aa7085b052938dc5252d10b2b418a475637eda5/lib/schema/tablebuilder.js#L80-L82). I'll just update the typings to remove the need for explicit cast.

**Comment by corysimmons** [comment]
Tried turning my `Knex.TableBuilder` typings to `Knex.MySqlTableBuilder`

>`Knex' has no exported member 'MySqlTableBuilder'`

**Comment by kibertoad** [comment]
@corysimmons Would you consider sending PR for this?

**Comment by corysimmons** [comment]
`MySqlTableBuilder` doesn't seem like it even exists in the repo.

**Comment by mercmobily** [comment]
I am a little confused by this issue.

Functionally and in typings this is resolved by #3532. The confusion in 2021 for @corysimmons came I THINK from the older advice to use MySqlTableBuilder, which no longer exists by design.

The current docs already list table.charset/table.collate and  note "only within createTable" and "only for MySQL" , and the types expose these on CreateTableBuilder.

I am closing this, feel free to reopen to let me know what I missed.
