### ISSUE TITLE
Unsupported option opt.refreshIdle thrown from Knex/Tarn

### ISSUE THREAD

**Issue by dmaksimovic** [knex/knex#3492]
# Environment

Knex version: 0.19.5
Database + version: Mysql 5.7.26 (MySQL Community Server (GPL))
OS: MacOS, 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

# Bug

1. I am upgrading from 0.15.0 to 0.19.5 and getting an exception thrown during creation of Knex object with below config:
```
const Knex = knex({
  client: 'mysql',
  connection: { ...mysql },
  pool: {
    min: 10,
    max: 50,
    refreshIdle: false,
  },
};
```

2. Error message
```
Error: Tarn: unsupported option opt.refreshIdle
    at new Pool (/Users/darko/PROJECT/node_modules/tarn/lib/Pool.js:63:23)
    at Client_MySQL.initializePool (/Users/darko/PROJECT/node_modules/knex/lib/client.js:299:17)
    at Client_MySQL.Client (/Users/darko/PROJECT/node_modules/knex/lib/client.js:61:12)
    at new Client_MySQL (/Users/darko/PROJECT/node_modules/knex/lib/dialects/mysql/index.js:20:10)
    at Knex (/Users/darko/PROJECT/node_modules/knex/lib/knex.js:52:28)
    at knex.js (imports/api/connectors/knex.js:7:14)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/darko/.meteor/packages/modules/.0.13.0.1py1wwo.b2cxi++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (imports/api/connectors/index.js:1:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/darko/.meteor/packages/modules/.0.13.0.1py1wwo.b2cxi++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at jobs_cache.js (imports/startup/server/fixtures/jobs_cache.js:1:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/darko/.meteor/packages/modules/.0.13.0.1py1wwo.b2cxi++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (imports/startup/server/fixtures/index.js:1:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/darko/.meteor/packages/modules/.0.13.0.1py1wwo.b2cxi++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (imports/startup/server/index.js:1:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/darko/.meteor/packages/modules/.0.13.0.1py1wwo.b2cxi++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at main.js (server/main.js:1:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
```

3. I cannot replicate on test code in https://npm.runkit.com/knex because I don't know which version of tarn is run on it, probably pre-2.0.0

It looks like the problem has been introduced in tarn@2.0.0, which added this check:

   ```
     const allowedKeys = {
            create: true,
            validate: true,
            destroy: true,
            log: true,
            min: true,
            max: true,
            acquireTimeoutMillis: true,
            createTimeoutMillis: true,
            destroyTimeoutMillis: true,
            idleTimeoutMillis: true,
            reapIntervalMillis: true,
            createRetryIntervalMillis: true,
            propagateCreateError: true
        };
        for (let key of Object.keys(opt)) {
            if (!allowedKeys[key]) {
                throw new Error(`Tarn: unsupported option opt.${key}`);
            }
        }
```

As you can see, there is no mention of `refreshIdle` in it, so it throws an exception, because in Knex tarn is used for instantiating the pool (see stack above).

**Comment by lorefnon** [comment]
You can remove the refreshIdle option. refreshIdle was an option used by the [generic-pool](https://www.npmjs.com/package/generic-pool) package which knex stopped using around Feb 2018. 

I don't think tarn ever supported the refreshIdle option so it would have been no-op anyways.

**Comment by dmaksimovic** [comment]
Ok thank you! Closing the issue in this case.
