### ISSUE TITLE
seed --specific not working

### ISSUE THREAD

**Issue by NguyenTheSon** [knex/knex#3506]
I ran the command 'knex seed: run --specific = filename.js'
command line error: error: unknown option `--specific'

**Comment by lorefnon** [comment]
what is the version of knex you have installed (both global and local) ?

**Comment by kibertoad** [comment]
@NguyenTheSon Could you provide more info?

**Comment by strarsis** [comment]
+1, same issue.
When specifying more than one seed file using `--specific` (as [stated in the documentation](http://knexjs.org/#:~:text=To%20run%20specific%20seed%20files%2C%20execute%3A)), the command fails with no seed files under those names being found:
````
knex seed:run --specific=default_categories.ts --specific=default_items.ts
````
````
Invalid argument provided: the specific seed "default_categories.ts,default_items.ts" does not exist.
Error: Invalid argument provided: the specific seed "default_categories.ts,default_items.ts" does not exist.
    at FsSeeds.getSeeds ([...]/node_modules/knex/lib/migrations/seed/sources/fs-seeds.js:47:15)
    at Seeder.run ([...]/node_modules/knex/lib/migrations/seed/Seeder.js:22:19)
````
It works when only one seed file is specified using `--specific`. Using more than one seed with `--specific` appears to cause KnexJS to use the joined string (`,`) of those seed file names/paths as a whole.

**Comment by VladyslavYermolenko** [comment]
Perhaps your problem is that you do not have the path to the seed folder in the "knexfile" file. Example:
`import { DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_DATABASE } from './src/config';


module.exports = {

  client: '...',
  connection: {
    charset: 'utf8',
    timezone: 'UTC',
    host: DB_HOST,
    port: DB_PORT,
    user: DB_USER,
    password: DB_PASSWORD,
    database: DB_DATABASE,
  },
  },
  **seeds: {
    directory: 'src/databases/example-seeds-folder',**
  },
};
`
And on this path "src/databases/example-seeds-folder" you need to place the file with the seed.

**Comment by mercmobily** [comment]
Thank you for reporting this issue! This is a duplicate of #3678, which is the canonical issue tracking support for multiple specific seed files.

The initial report describes an error about an "unknown option `--specific`", which suggests a version mismatch between the global and local Knex installations. As @lorefnon correctly identified, this happens when the global Knex CLI is more recent than the local version. The `--specific` option was added in later versions, so if your global Knex knows about it but your local installation doesn't, you'll see this error. The solution is to update your local Knex installation or use `npx knex` or `yarn run knex` instead of the global CLI.

However, the discussion from @strarsis reveals the more significant problem: whilst a single `--specific` argument works fine, using multiple `--specific` arguments fails with an error like `Invalid argument provided: the specific seed "default_categories.ts,default_items.ts" does not exist.` This is the same issue described in #3678.

The root cause is in the argument parsing and filtering logic. When you run `knex seed:run --specific=file1.js --specific=file2.js`, the `getopts` library (used at bin/cli.js:10) correctly parses this as an array `['file1.js', 'file2.js']`. However, the code in lib/migrations/seed/sources/fs-seeds.js:44-50 only handles a string value, not an array:

```javascript
if (specific) {
  files = files.filter((file) => path.basename(file) === specific);
  if (files.length === 0) {
    throw new Error(
      `Invalid argument provided: the specific seed "${specific}" does not exist.`
    );
  }
}
```

When `specific` is an array, the comparison `path.basename(file) === specific` always fails (you can't use `===` to compare a string with an array), so no files match, and the error is thrown with the array being converted to a string with commas, hence `"default_categories.ts,default_items.ts"`.

Pull request #4374 by @bentesha implements support for multiple specific seed files and fixes this issue. The PR targets #3678 and has been waiting since 2020 for review and merge. The feature is particularly useful for users who want to run multiple seed files in a specific order without having to make separate CLI calls, which is expensive due to the process spawning and module loading overhead.

The current workaround, as suggested by @svrostislav, is to programmatically loop through the files:

```javascript
const files = ['test1.js', 'test2.js'];

const seed = async (files) => {
  for (const file of files) {
    await knex.seed.run({
      specific: file,
    });
  }
};

seed(files).then(() => console.log('Success'));
```

Even though the documentation at one point suggested that multiple `--specific` arguments should work, the current implementation does not support this functionality. This will be fixed when PR #4374 is merged.

**Recommendation**: Close this issue as a duplicate of #3678.

Exact duplicates:
- #3678 - Feature request for multiple specific seed files (open, canonical issue with PR #4374)
- #5988 - Cannot run multiple seeds at the same time (open, duplicate)
- #4588 - Parameter `specify` of seeds.run() fails to accept array (open, duplicate)

Related issues:
- #3369 - --specific runs all seed files (open, version mismatch issue)
- #4005 - Knex seed should notify when specific seed is not found (closed, fixed in PR #4011)
