### ISSUE TITLE
Redshift: column "knex_migrations.id" has unsupported type "serial"

### ISSUE THREAD

**Issue by alecdotico** [knex/knex#3546]
# Environment 

Knex version: 0.20.2
Database + version: Redshift, cluster version 1.0.11262
OS: Node 12 docker image (Debian)

# Bug
Knex migrations don't work with Redshift, but the documentation doesn't mention that it is not supported.
1. Migration schema [attempts to create](https://github.com/knex/knex/blob/9aa7085b052938dc5252d10b2b418a475637eda5/lib/migrate/table-creator.js#L39) an `id` column of `serial` type. Serial type is not supported by Redshift, so it crashes

2. Error message
```javascript
$ ./node_modules/.bin/knex migrate:latest
error: Column "knex_migrations.id" has unsupported type "serial".
    at Connection.parseE (/var/app/current/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/var/app/current/node_modules/pg/lib/connection.js:401:19)
    at TLSSocket.<anonymous> (/var/app/current/node_modules/pg/lib/connection.js:121:22)
    at TLSSocket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23)
error Command failed with exit code 1.
```

3. Test code
**knexfile.js**
```javascript
module.exports = {
  client: 'postgresql',
  connection: REDSHIFT_CONNECTION_STRING,
  searchPath: ['public'],
  migrations: {
    directory: './migrations',
    tableName: 'knex_migrations',
  },
  seeds: {
    directory: './seeds',
    tableName: 'knex_seeds',
  },
};
```

**Comment by elhigu** [comment]
ping, @acofer who is taking care of redshift dialect

**Comment by acofer** [comment]
I’ll take a look tomorrow.

**Comment by acofer** [comment]
Oh! I see the problem. In your `knexfile.js`, you have `client: 'postgresql',`. That's why it's trying to create a `serial primary key` column for `id` when the schema builder calls `t.increments()`.

Change it to `client: 'redshift',` and it will instead use `integer identity(1,1) primary key not null` for that column.

Let me know if that doesn't work.

**Comment by alecdotico** [comment]
Indeed, that worked like a charm! Thanks a lot, Adam. 

I couldn't find that option on the documentation, nor dig that much into the source code. Is there any specification of the `knexfile.js` config?

**Comment by ian-ragnarok** [comment]
I am having the exact same issue, even after changing my client to `'redshift'`.

`knexfile.js`:
```javascript

module.exports = {
  client: 'redshift',
  connection: {
    database: process.env.PGDATABASE,
    user: process.env.PGUSER,
    password: process.env.PGPASSWORD,
  },
  pool: {
    min: 2,
    max: 10,
  },
  migrations: {
    tableName: 'knex_migrations',
  },
};
```

Error message from AWS Lambda:
```json
{
  "errorType": "error",
  "errorMessage": "create table \"knex_migrations\" (\"id\" serial primary key, \"name\" varchar(255), \"batch\" integer, \"migration_time\" timestamptz) - Column \"knex_migrations.id\" has unsupported type \"serial\".",
  "trace": [
    "error: create table \"knex_migrations\" (\"id\" serial primary key, \"name\" varchar(255), \"batch\" integer, \"migration_time\" timestamptz) - Column \"knex_migrations.id\" has unsupported type \"serial\".",
    "    at Parser.parseErrorMessage (/var/task/node_modules/pg-protocol/dist/parser.js:278:15)",
    "    at Parser.handlePacket (/var/task/node_modules/pg-protocol/dist/parser.js:126:29)",
    "    at Parser.parse (/var/task/node_modules/pg-protocol/dist/parser.js:39:38)",
    "    at Socket.<anonymous> (/var/task/node_modules/pg-protocol/dist/index.js:8:42)",
    "    at Socket.emit (events.js:315:20)",
    "    at Socket.EventEmitter.emit (domain.js:482:12)",
    "    at addChunk (_stream_readable.js:295:12)",
    "    at readableAddChunk (_stream_readable.js:271:9)",
    "    at Socket.Readable.push (_stream_readable.js:212:10)",
    "    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)"
  ]
}
```

Any idea what I might be doing wrong?

**Comment by acofer** [comment]
Oh boy, this one got lost in pandemic brain, until I just got pinged that someone had the same issue. In general (for those who have searched their way to this issue), an example `knexfile.js` can be created with `knex init`, and supports all of the options mentioned in http://knexjs.org/#Installation-client. The only option that is different from the example code for connecting to PostgreSQL in the documentation is that `client: 'pg',` should be `client: 'redshift',`.

(Note that there are a few other differences when using Redshift in practice, such as the lack of support for creating a table index using the schema builder. These are mentioned elsewhere in the documentation.)

I think the confusion is because there is not a specific example of setting `client: 'redshift'` in the docs.  Let me see if I can get an appropriate pull request against the docs filed tomorrow to make sure others don't run into the same error when trying to create a migration table in Redshift.

**Comment by ian-ragnarok** [comment]
Hi @acofer — I was the one who was having this same issue. I then realized that it was due to error on my part, so I deleted my comment. Thanks for the explanation and your effort in updating the docs; much appreciated!

**Comment by mercmobily** [comment]
So... Redshift requires using the `redshift` client so the dialect maps `increments()` to `integer identity(1,1)` instead of `serial`. The maintainer’s comment in the thread covers it: set `client: 'redshift'` in your knexfile or instance and migrations will create the right type.

Closing it!
