### ISSUE TITLE
Error when running knex migrate:make

### ISSUE THREAD

**Issue by garrettg123** [knex/knex#358]
```
~/S/p/s/scripts> knex --debug migrate:make my_migration

/usr/local/share/npm/lib/node_modules/knex/lib/bin/cli.js:89
      var ext = (argv.x || env.configPath.split('.').pop()).toLowerCase();
                                          ^
TypeError: Cannot call method 'split' of null
    at Command.<anonymous> (/usr/local/share/npm/lib/node_modules/knex/lib/bin/cli.js:89:43)
    at Command.<anonymous> (/usr/local/share/npm/lib/node_modules/knex/node_modules/commander/index.js:249:8)
    at Command.emit (events.js:98:17)
    at Command.parseArgs (/usr/local/share/npm/lib/node_modules/knex/node_modules/commander/index.js:478:12)
    at Command.parse (/usr/local/share/npm/lib/node_modules/knex/node_modules/commander/index.js:370:21)
    at Liftoff.invoke (/usr/local/share/npm/lib/node_modules/knex/lib/bin/cli.js:128:13)
    at Liftoff.launch (/usr/local/share/npm/lib/node_modules/knex/node_modules/liftoff/index.js:140:6)
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/knex/lib/bin/cli.js:27:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by blaskovicz** [comment]
This was my issue as well.

Would it be possible to make a pre-run check and more helpful error message?
