### ISSUE TITLE
Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query

### ISSUE THREAD

**Issue by SephReed** [knex/knex#3591]
I get this bug all the time.  It's a nightmare to debug.

It'd be really helpful if wherever this error is coming from, some information on what table/column/etc was being modified, and what the bad data is.

```
Error: Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query.
             at QueryCompiler_PG._prepUpdate (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/query/compiler.js:814:13)
             at QueryCompiler_PG.update (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/dialects/postgres/query/compiler.js:39:29)
             at QueryCompiler_PG.toSQL (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/query/compiler.js:64:29)
             at Builder.toSQL (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/query/builder.js:76:44)
             at /Users/seph/Code/RSLTS/api/node_modules/knex/lib/runner.js:30:36
         From previous event:
             at Runner.run (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/runner.js:25:16)
             at Builder.Target.then (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/interface.js:14:43)
             at _findOrGet.then.results (/Users/seph/Code/RSLTS/api/node_modules/feathers-knex/lib/index.js:275:29)
             at processImmediate (timers.js:638:19)
         From previous event:
             at Object._patch (/Users/seph/Code/RSLTS/api/node_modules/feathers-knex/lib/index.js:265:9)
             at callMethod (/Users/seph/Code/RSLTS/api/node_modules/@feathersjs/adapter-commons/src/service.ts:10:20)
             at Object.patch (/Users/seph/Code/RSLTS/api/node_modules/@feathersjs/adapter-commons/src/service.ts:120:12)
             at processHooks.call.then.hookObject (/Users/seph/Code/RSLTS/api/node_modules/@feathersjs/feathers/lib/hooks/index.js:56:27) },
```

**Comment by elhigu** [comment]
Your application is sending empty object to update() query. You might be able to trigger that error earlier if you add debug code near to you .update() queries which will call query.toSQL() before actually awaiting the query builder. Closing as this is not a knex bug, but user error / usage question.

**Comment by SephReed** [comment]
This is a user error, but I'm putting in a feature request for better error messaging.

Obviously I did something wrong, but if the error message I get doesn't help me understand, you've also done something wrong.

**Comment by kibertoad** [comment]
I agree.

**Comment by kibertoad** [comment]
Released in 0.20.5

**Comment by pdkovacs** [comment]
I am getting this same error for the following update:

```
		const updateData = {
			display_name: user.display_name,
			active: user.active,
			information: JSON.stringify(user.information)
		};
		console.log("update11", updateData);
		await trxHandle(usersTableName)
			.where({ user_id })
			.update(updateData);
```
, even though `updateData` is definitely not an empty object:
```
[2020-05-14T16:38:05.193Z] info [console]: update11 { display_name: undefined, active: undefined, information: undefined }
```

Any thoughts?

**Comment by pdkovacs** [comment]
The following work-around avoids the error in my specific case:
```
		const updateData = {
			display_name: user.display_name || null,
			active: user.active || null,
			information: JSON.stringify(user.information) || null
		};
```
Note the `null` fall-back values in the property assignments.

**Comment by martinblostein** [comment]
Your workaround will insert nulls into the database if those fields are not populated. I'm not sure if that was the intention of your original query.
