### ISSUE TITLE
Error on project start

### ISSUE THREAD

**Issue by makavalon** [knex/knex#3610]
# Environment

Knex version: 0.19.4
Database + version: Psql 11.4
OS: Windows 10

@lorefnon.

# Bug

1. On npm start project should successfuly compile and started

2. E:\ntts\node_modules\knex\lib\client.js:258
        return this.acquireRawConnection().then(async (connection) => {
                                                                               ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\ntts\node_modules\knex\lib\knex.js:2:16)
[nodemon] app crashed - waiting for file changes before starting...

Error throws on Windows, the same project on Ububntu works fine.

**Comment by kibertoad** [comment]
Which Node version are you using? Sounds like it's older than Node 8, which is not supported.
