### ISSUE TITLE
Error when using batchInsert

### ISSUE THREAD

**Issue by igoventura** [knex/knex#3793]
# Environment

Knex version: 0.20.13
Database + version: MySQL 5.0
OS: Windows OS: Windows 10

# Bug

When I try to make a batchInsert I'm getting the error message below:
```bash
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received 1
    at setTimeout (timers.js:118:11)
    at fallback (D:\DUMMY_FOLDER\node_modules\async-listener\index.js:621:15)
    at D:\DUMMY_FOLDER\node_modules\async-listener\index.js:651:53
    at internal/util.js:286:30
    at new WrappedPromise (D:\DUMMY_FOLDER\node_modules\async-listener\es6-wrapped-promise.js:13:18)
    at internal/util.js:285:12
    at D:\DUMMY_FOLDER\node_modules\knex\lib\util\batchInsert.js:35:13
    at propagateAslWrapper (D:\DUMMY_FOLDER\node_modules\async-listener\index.js:504:23)
    at D:\DUMMY_FOLDER\node_modules\async-listener\glue.js:188:31
    at D:\DUMMY_FOLDER\node_modules\async-listener\index.js:541:70
    at D:\DUMMY_FOLDER\node_modules\async-listener\glue.js:188:31
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

After doing some research on knex code I've found that the ode of `./utils/batchInsert.js` has a call to a method called `delay` passing 1 as argument and this is what is throwing the error.

**Comment by maximelkin** [comment]
Probably you running your code in browser environment?

**Comment by igoventura** [comment]
Nope. It's a NodeJS application (back-end).

**Comment by maximelkin** [comment]
Try latest version, we replaced this function with more portable variant
