### ISSUE TITLE
migration error

### ISSUE THREAD

**Issue by yoannes** [knex/knex#3817]
Hi,

After last updates I got some errors when running migrations. The exact same commands was working few days ago.

I'm running inside a `node:13-buster` container

`knex migrate:make test`
```
calling knex without a tableName is deprecated. Use knex.queryBuilder() instead.
(node:272) UnhandledPromiseRejectionWarning: Error: select * - No tables used
    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:712:17)
    at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:28:26)
    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:417:32)
    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
(node:272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

`knex migrate:latest`
```
calling knex without a tableName is deprecated. Use knex.queryBuilder() instead.
Error: select * - No tables used
    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:712:17)
    at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:28:26)
    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:417:32)
    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
```

Thankyou

**Comment by kibertoad** [comment]
@yoannes Please share the migration file that is causing the problem.
`calling knex without a tableName is deprecated` looks very suspicious.

I really looks like https://github.com/knex/knex/issues/3815

**Comment by yoannes** [comment]
@kibertoad You were right. I totally messed the exports. I was exporting Knex() instead of the config.
Thankyou very much for your support.
