### ISSUE TITLE
javascript knexfile can't run typescript migrations

### ISSUE THREAD

**Issue by prk3** [knex/knex#3849]
# Environment

Knex version: 0.21.1
Database + version: postgres 12
OS: Linux

# Bug

1. Description

When the knexfile has `js` extension, typescript migrations and seeds can't be run. The error thrown suggests these files are not loaded with typescript loader. Changing knexfile extension to `ts` fixes the problem.

This is rather unexpected, as the documentation suggests that knex can run migrations of different types, no matter what the knexfile extension is.
```
loadExtensions: array of file extensions which knex will treat as migrations.
```

2. Error message
```
import Knex from 'knex';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at FsMigrations.getMigration (/home/przemek/DEV/sundae/sundae-collab-demo-api/node_modules/knex/lib/migrate/sources/fs-migrations.js:82:12)
    at /home/przemek/DEV/sundae/sundae-collab-demo-api/node_modules/knex/lib/migrate/Migrator.js:76:67
    at Array.some (<anonymous>)
```

3. Knexfile content
```javascript
require('dotenv').config();

const defaultSettings = {
  // client
  // connection
};

module.exports.development = {
  ...defaultSettings,
  migrations: {
    loadExtensions: ['.ts'],
    extension: 'ts',
  },
  seeds: {
    loadExtensions: ['.ts'],
  },
};

module.exports.test = {
  ...defaultSettings,
  migrations: {
    loadExtensions: ['.ts'],
    extension: 'ts',
  },
  seeds: {
    loadExtensions: ['.ts'],
  },
};

module.exports.production = {
  ...defaultSettings,
  migrations: {
    directory: 'build/migrations',
  },
  seeds: {
    directory: 'build/seeds',
  },
};
```

# Feature discussion / request

1. Explain what is your use case

I want to run Typescript migrations and seeds in development environment. In production, where Typescript and ts-node might not be present, compiled migrations and seeds should be used instead. Ideally, one `js` knexfile would handle both cases.

2. Explain what kind of feature would support this

Knexfile extension should not influence migration and seed loading. When `loadExtensions` includes `.ts`, typescript migrations and seeds should be loaded and run.

**Comment by love8587** [comment]
You could try with ```npx knex migrate:latest```

**Comment by prk3** [comment]
@love8587 
That's how I run migrations. Here is the exact console output. Notice that ts-node/register is used only when knexfile has `.ts` extension.

```
$ npx knex migrate:latest
/home/przemek/DEV/sundae/sundae-collab-demo-api/migrations/20200414144724_recipes.ts:1
import Knex from 'knex';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at FsMigrations.getMigration (/home/przemek/DEV/sundae/sundae-collab-demo-api/node_modules/knex/lib/migrate/sources/fs-migrations.js:82:12)
    at /home/przemek/DEV/sundae/sundae-collab-demo-api/node_modules/knex/lib/migrate/Migrator.js:76:67
    at Array.some (<anonymous>)
$ mv knexfile.js knexfile.ts
$ npx knex migrate:latest
Requiring external module ts-node/register
Batch 1 run: 2 migrations
$
```

**Comment by Heverson** [comment]
Hello @prk3 
I have the same problem, when run knex migrate in heroku cli  
```
Running knex --knexfile knexfile.ts migrate:latest on ⬢ backend-ecolab... up, run.5056 (Free)
Failed to load external module ts-node/register
Failed to load external module typescript-node/register
Failed to load external module typescript-register
Failed to load external module typescript-require
Failed to load external module sucrase/register/ts
Failed to load external module @babel/register
Error: Cannot find module 'ts-node/register'
Require stack:
- /app/knexfile.ts
- /app/node_modules/knex/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/knexfile.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
```

**Comment by abcd-ca** [comment]
Why do we get "SyntaxError: Cannot use import statement outside a module" when we run ts files with the CLI? Is there a setting we can change to fix that? 

@heverson I believe I fixed the "Failed to load external module ts-node/register" error by `npm install --save-dev ts-node` but then I got the `import` syntax error above. 

Still battling even trying to get it to work with require but it would be much better if I could use typescript. I'd like to know if it can work or if it's just broken and needs a fix.

**Comment by love8587** [comment]
@lorefnon that's  right. I found out it from document and resolved it.

**Comment by abcd-ca** [comment]
I can't get it to run a knexfile.ts that has typescript syntax such as,

```
import dotenv from 'dotenv'

dotenv.config();
```

without the error,

```
import dotenv from 'dotenv';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

I have tried running it like, 

`knex --knexfile ./knexfile.ts migrate:make create_users_table -x ts` (tried with and without the --knexfile option and with and without the -x ts option)

If I remove the import from knexfile.ts it just hides the problem because the rest of the file is the same as javascript – it creates the migration file with a .ts extension but any imports or requires of typescript code give the same error so I think we need to focus on why it's not interpreting knexfile.ts as typescript. Further, to get rid of the "Failed to load external module ts-node/register" message I did `yarn add --dev ts-node` which results in the line, "Requiring external module ts-node/register" being displayed before it throws the SyntaxError about `import`.

I don't know if TS is broken for the knex CLI or if I'm just missing something

**Comment by abcd-ca** [comment]
I just noticed that 0.21.1 in the [changelog has a bug fix](https://github.com/knex/knex/blob/master/CHANGELOG.md#bug-fixes) that looks related which I suspect might be causing this side effect issue.

**Comment by abcd-ca** [comment]
Is there a way to have a separate tsconfig.json file just for the knex CLI as a workaround?

**Comment by love8587** [comment]
@abcd-ca I resolved it below code.


`
const extension =
  process.env.NODE_CONFIG_ENV === 'production' || process.env.NODE_CONFIG_ENV === 'staging'
    ? 'js'
    : 'ts';

console.log('extension ============> ', extension);
`

`  migrations: {
    tableName: 'knex_migrations',
    extension: extension,
    directory: path.join(BASE_PATH, 'migrations'),
    disableMigrationsListValidation: true,
    loadExtensions: [`.${extension}`],
  },
  seeds: {
    extension: extension,
    directory: path.join(BASE_PATH, 'seeds'),
  },`

**Comment by abcd-ca** [comment]
@love8587 Yeah that's a good solution to your problem, thanks for sharing! In my case I realized it was a bit of a different problem than yours. In my case I couldn't get knex CLI to work with typescript files at all. In my case it was because my tsconfig.json didn't have `module` set to `commonjs` as it requires. Conversely, my UI framework Next.js requires `module` to be `esnext`. For now I'm switching back and forth when doing knex CLI activity vs running the server.

**Comment by lorefnon** [comment]
@abcd-ca You can use: 

```
TS_NODE_COMPILER_OPTIONS='{ "module": "commonjs" }' node_modules/.bin/knex migrate:latest
```

knex uses ts-node's require hook for `.ts` extension and that can accept TS compiler options through `TS_NODE_COMPILER_OPTIONS` env variable. These options will be merged into what you have in your tsconfig.json.

**Comment by abcd-ca** [comment]
thanks!

**Comment by abcd-ca** [comment]
@lorefnon That gave me this alternative idea:

created a tsconfig.knexcli.json containing an override for module,

```
{
  "extends": "./tsconfig",
  "compilerOptions": {
    "module": "commonjs"
  }
}
```

Then when running my commands, 

TS_NODE_PROJECT=tsconfig.knexcli.json knex migrate:latest

Just slightly cleaner because the JSON when in an npm script needs to escape the quotes and gets a bit busy looking. Thanks!

**Comment by lorefnon** [comment]
@abcd-ca Yes, that certainly looks like a cleaner approach.

**Comment by mrsufgi** [comment]
Thanks for your solution @abcd-ca.
Seems like this thread is a mix of two issues. 
1) knexfile.js doesn't transpile .ts migration files by default.
2) knex cli doesn't support 'esnext' code, even with node14.4 

the workaround for 1 was changing to knexfile.ts, it should be enough for most people (as I've seen it, "commonjs" is the most common module resolution). but the workaround for 2 only indicates that we have issues with esm :) 

for ts/node maybe we need to run it with 
```
node --loader ts-node/esm.mjs
```
somewhere down the pipeline?

**Comment by Adverbly** [comment]
For those seeing 

```
Failed to load external module ts-node/register
Failed to load external module typescript-node/register
Failed to load external module typescript-register
Failed to load external module typescript-require
Failed to load external module sucrase/register/ts
Failed to load external module @babel/register
Error: Cannot find module 'ts-node/register'
```

and unable to use things such as `import`, For me the fix was that I was missing ts-node from my package.json. A simple
``
npm install -D ts-node
```
was all I needed.

**Comment by Isaac-alencar** [comment]
> I can't get it to run a knexfile.ts that has typescript syntax such as,
> 
> ```
> import dotenv from 'dotenv'
> 
> dotenv.config();
> ```
> 
> without the error,
> 
> ```
> import dotenv from 'dotenv';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
> ```
> 
> I have tried running it like,
> 
> `knex --knexfile ./knexfile.ts migrate:make create_users_table -x ts` (tried with and without the --knexfile option and with and without the -x ts option)
> 
> If I remove the import from knexfile.ts it just hides the problem because the rest of the file is the same as javascript – it creates the migration file with a .ts extension but any imports or requires of typescript code give the same error so I think we need to focus on why it's not interpreting knexfile.ts as typescript. Further, to get rid of the "Failed to load external module ts-node/register" message I did `yarn add --dev ts-node` which results in the line, "Requiring external module ts-node/register" being displayed before it throws the SyntaxError about `import`.
> 
> I don't know if TS is broken for the knex CLI or if I'm just missing something

I have the same issue, and your suggest to add ts-node works to me

**Comment by cbaron** [comment]
@abcd-ca's method of

```
    "module": "commonjs",
```

in tsconfig.json worked for me as well

**Comment by jeanbispo** [comment]
I resolve with: 

`yarn add ts-node -D `

and add in package.json scripts: 

```json
{
  "scripts": {
     ...,
     "knex": "TS_NODE_COMPILER_OPTIONS='{ \"module\": \"commonjs\" }' npx knex"
  }
}
```

now use `yarn knex <your command>`

**Comment by hahayusuf** [comment]
Still having issues with this.

**Comment by opatajoshua** [comment]
I got it to work by generating a TS knexfile instead `knex init -x ts` and moving my js config into it

**Comment by BrainCrumbz** [comment]
For those using tsx, [this comment](https://github.com/knex/knex/issues/2998#issuecomment-1937821298) from another issue worked great. It relies on knex JS CLI file:

> The following is copied from original, credits to author

For those using tsx runtime i used

```
scripts: {
    ...
    "knex": "tsx ./node_modules/knex/bin/cli.js"
}
```

and used it like

```
npm run knex -- migrate:latest
```

**Comment by beenotung** [comment]
The solution of using tsx to wrap the knex cli works a esm project.

Would it be nice to wrap knex cli with tsx out of the box (by doing some update on knex side)?

**Comment by mercmobily** [comment]
This issue where JavaScript knexfiles can't run TypeScript migrations is another manifestation of the core problem we're solving in   #5800. The issue occurs because Knex's module loader (rechoir) only registers the TypeScript compiler when it sees a .ts extension in the knexfile itself, not when loading migration files.

The various workarounds discussed here (changing module to "commonjs", using TS_NODE_PROJECT, adding ts-node to dependencies) are  all band-aids for the same underlying problem: Knex's current tooling wasn't designed to handle the complex matrix of CommonJS/ESM + JavaScript/TypeScript combinations that modern projects use.

Issue #5800 will solve this permanently by migrating Knex from the current ts-node/rechoir setup to tsx, which handles all these  combinations gracefully. Once that's implemented, you'll be able to use any combination of JS/TS knexfiles with JS/TS migrations, regardless of your module system.

Until then, the most reliable workaround is to either use a .ts knexfile or set NODE_OPTIONS='--import tsx/esm' when running Knex  commands with TypeScript migrations.
