### ISSUE TITLE
knex CLI commands do not respect NODE_PATH environment variable.

### ISSUE THREAD

**Issue by DominicRoyStang** [knex/knex#3866]
# Environment

Knex version: 0.21.1 (also tested on 0.20.8)
Database + version: postgresql:12.2
OS: linux (docker container `node:12.16.3-stretch`)

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
I tend to organize my code by having the following structure:
```
├── package.json
├── package-lock.json
└── src/
    ├── folder1/
    |   └── file1.js
    └── folder2/
        └── file2.js
```

To make my code cleaner, I set `NODE_PATH=src` so that I can treat my codebase as a module and `require` using _absolute paths_.

so in the example above, if `file2.js` needs to require `file1.js`, it can have the following code:
```javascript
const file1 = require('folder1/file1');
```
 instead of 
```javascript
const file1 = require('../folder1/file1');
```

2. Error message

<details>
    <summary>
        Click to show error message
    </summary>
    ```
    > npx knex seed:run --knexfile=src/knexfile.js

    Using environment: development
    Error: Cannot find module 'examplefile'
    Require stack:
    - /example/src/db/seeds/001_users_seed.js
    - /example/node_modules/knex/lib/seed/Seeder.js
    - /example/node_modules/knex/lib/util/make-knex.js
    - /example/node_modules/knex/lib/transaction.js
    - /example/node_modules/knex/lib/client.js
    - /example/node_modules/knex/lib/knex.js
    - /example/node_modules/knex/lib/index.js
    - /example/node_modules/knex/knex.js
    - /example/node_modules/knex/bin/cli.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
        at Function.Module._load (internal/modules/cjs/loader.js:840:27)
        at Module.require (internal/modules/cjs/loader.js:1019:19)
        at require (internal/modules/cjs/helpers.js:77:18)
        at Object.<anonymous> (/example/src/db/seeds/001_users_seed.js:4:25)
        at Module._compile (internal/modules/cjs/loader.js:1133:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
        at Module.load (internal/modules/cjs/loader.js:977:32)
        at Function.Module._load (internal/modules/cjs/loader.js:877:14)
        at Module.require (internal/modules/cjs/loader.js:1019:19)
        at require (internal/modules/cjs/helpers.js:77:18)
        at Seeder._validateSeedStructure (/example/node_modules/knex/lib/seed/Seeder.js:72:18)
        at /example/node_modules/knex/lib/seed/Seeder.js:66:34
        at Array.forEach (<anonymous>)
        at Seeder._runSeeds (/example/node_modules/knex/lib/seed/Seeder.js:66:11)
        at Seeder.run (/example/node_modules/knex/lib/seed/Seeder.js:28:17)
    ```
</details>

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

This requires multiple files to test, but I created this repo (all containerized so it's easy to get running) to reproduce the issue: https://github.com/DominicRoyStang/knex-node-path-issue

The README is pretty descriptive about what part of the code creates the issue, how to run the code, and how to reproduce it.

It may help to look at it [commit-by-commit](https://github.com/DominicRoyStang/knex-node-path-issue/commits/master) (look at the commits written by me) to see the relevant changes.

# Feature discussion / request

1. Explain what is your use case
I use `NODE_PATH=src` to be able to treat my codebase as a module, and have absolute imports in my codebase.

2. Explain what kind of feature would support this
I would expect `knex` commands to be run with the same environment as regular code.

3. Give some API proposal, how the feature should work
I should be able to set `NODE_PATH` and have `knex` cli commands respect that environment variable.

**Comment by DominicRoyStang** [comment]
More discussion:

The call fails on `const seed = require(path.join(this._absoluteConfigDir(), name));` in [Seeder.js](https://github.com/knex/knex/blob/master/lib/seed/Seeder.js). `path.join(this._absoluteConfigDir(), name)` does give a string with the correct location. The issue is with files imported by that file.

I googled a bit and found that the Jest library had a similar [issue](https://github.com/facebook/jest/issues/102). Here is their [fix](https://github.com/facebook/jest/pull/246) and the [full file](https://github.com/carrbs/jest/blob/5f2b9155100a8fdff5a0180aaa0d724b1a88f85e/src/HasteModuleLoader/HasteModuleLoader.js) if it helps.

**Comment by DominicRoyStang** [comment]
Going to close this issue, as I've started using ECMAScript Modules (which don't support `NODE_ENV` either)
