### ISSUE TITLE
Migration directory error when using Custom Migration Source

### ISSUE THREAD

**Issue by laggingreflex** [knex/knex#3867]
# Environment

Knex version: 0.21.1
Database + version: sqlite3
OS: Windows 10

# Bug

## Description

I'm using [Custom Migration Source][1]

```js
class MigrationSource {
  getMigrations = () => this.migrations.map((x, i) => i)
  getMigrationName = i => i
  getMigration = i => this.migrations[i]
  migrations = [{
    async up(knex) {},
    async down(knex) {},
  }]
}
```

The migrations are specified within the source itself, i.e. no need to look for a migration directory. 

It works fine on the first run. 

But subsequently it gives the following error:

## Error message

```
Error: The migration directory is corrupt, the following files are missing: 0
    at validateMigrationList (...\node_modules\knex\lib\migrate\Migrator.js:556:11)
    at ...\node_modules\knex\lib\migrate\Migrator.js:62:11
```

It's looking for a migration directory...

## Reduced test code

Run the following code **twice**. Works the first time but gives the above error on second run:

```js
const Knex = require('knex');

const knex = Knex({
  client: 'sqlite3',
  connection: { filename: 'database.db' }
});

class MigrationSource {
  getMigrations = () => this.migrations.map((x, i) => i)
  getMigrationName = i => i
  getMigration = i => this.migrations[i]
  migrations = [{
    async up(knex) {
      if (!await knex.schema.hasTable('user'))
        await knex.schema.createTable('user', t => {
          t.string('username').unique();
        });
    },
    down: knex => knex.schema.dropTableIfExists('user')
  }]
}

knex.migrate.latest({ migrationSource: new MigrationSource() });
```

[1]: http://knexjs.org/#custom-migration-sources

**Comment by laggingreflex** [comment]
Ah, my bad. User error. 

```js
class MigrationSource {
-  getMigrations = () => this.migrations.map((x, i) => i)
+  getMigrations = () => this.migrations.map((x, i) => String(i))
```
That fixed it.
