### ISSUE TITLE
Cannot overwrite 'transaction' method since version 0.20.12

### ISSUE THREAD

**Issue by tubular400** [knex/knex#3895]
# Environment

Knex version: 0.20.12
Database + version: SQLite 3.27.2
OS: Debian Linux 10

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
I have written an automated test in which I attempt to overwrite Knex's `transaction` method.

2. Error message
When I run my test, I get the following error message:
 
        TypeError: Cannot assign to read only property 'transaction' of function 'function knex(tableName, options) {
            return createQueryBuilder(knex.context, tableName, options);
          }'                   
 
3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
database connection to MySQL or PostgreSQL, then single file example which initializes
needed data and demonstrates the problem.
Here is a little Linux Bash script which shows that the problem first appeared in Knex 0.20.12:

```shell
#!/bin/bash

temp_dir=/tmp/knex2

try_to_overwrite() {
  node -e '
    Object.assign(
      require("knex")({
        client: "sqlite3",
        useNullAsDefault: true,
        connection: {
          filename: ":memory:",
        },
      }),
      { transaction: 0 },
    );
  '
}

if mkdir "$temp_dir" && cd "$temp_dir"; then
  echo '{}' > package.json

  npm install --loglevel silent --progress false --audit false --fund false sqlite3@4.2.0

  npm install --loglevel silent --progress false --audit false --fund false knex@0.20.11
  echo Trying with Knex 0.20.11
  try_to_overwrite

  npm install --loglevel silent --progress false --audit false --fund false knex@0.20.12
  echo Trying with Knex 0.20.12
  try_to_overwrite
fi
```

When I run that script, I get the following output:

    [sqlite3] Success: "/tmp/knex2/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node" is installed via remote
    + sqlite3@4.2.0
    added 68 packages from 48 contributors in 3.923s
    + knex@0.20.11
    added 154 packages from 131 contributors in 6.255s
    Trying with Knex 0.20.11
    + knex@0.20.12
    updated 1 package in 9.672s
    Trying with Knex 0.20.12
    [eval]:2
        Object.assign(
               ^
    
    TypeError: Cannot assign to read only property 'transaction' of function 'function knex(tableName, options) {
        return createQueryBuilder(knex.context, tableName, options);
      }'
        at Function.assign (<anonymous>)
        at [eval]:2:12
        at Script.runInThisContext (vm.js:120:20)
        at Object.runInThisContext (vm.js:311:38)
        at Object.<anonymous> ([eval]-wrapper:10:26)
        at Module._compile (internal/modules/cjs/loader.js:1158:30)
        at evalScript (internal/process/execution.js:94:25)
        at internal/main/eval_string.js:23:3

Note that after "Trying with Knex 0.20.11", there is no output from the `node` command (the next line you see is from `npm install`), but after "Trying with Knex 0.20.12", the `node` command outputs the error message that I quoted above.

**Comment by mercmobily** [comment]
The bisect you did was spot on. I very much doubt you even care 5 years later, but... here it is.

This is expected after 0.20.12. We refactored the exported `knex` function to define core methods (including `transaction`) via property descriptors so they forward to an internal context. Those descriptors aren’t writable, so `Object.assign(knex, { transaction: ... })` throws. See lib/knex-builder/make-knex.js:9–58 (KNEX_PROPERTY_DEFINITIONS) and 262–310 (Object.defineProperties(knex, ...)).

If your goal is to customise transaction behaviour, recommended approaches are:
- Wrap `knex.transaction` in your own helper without mutating the instance, or
- Use `knex.withUserParams(...)` to pass flags you can inspect inside your wrapper, or
- Call the lower‑level `knex.client.transaction(container, config)` if you need access to the raw transactor.

Directly overwriting core methods on the function export is no longer supported; keeping those stable is important for type safety and cloning.
