### ISSUE TITLE
 ESM module interop fails if  calling module/package is of type 'module'   

### ISSUE THREAD

**Issue by D10221** [knex/knex#3937]
# Environment

Knex version: 0.21.2

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

    ESM module interop fails if  calling module/package is of type 'module'   

2. Error message
    Error [ERR_REQUIRE_ESM]: Must use import to load ES Module
3. Reduced test code, 
```json
{
  "name": "knex14",
  "version": "1.0.0",
  "main": "index.js", 
  "type": "module",
  "dependencies": {
    "knex": "^0.21.2",
    "sqlite3": "^5.0.0"
  }
}
```sh
./node_modules/.bin/knex --esm migrate:up
```

This is more of an [esm](https://github.com/standard-things/esm) bug, see [#868](https://github.com/standard-things/esm/issues/868).  
That in turns is because a change in Node v13.8+ default behavior.

Solution.
As explained on [#868](https://github.com/standard-things/esm/issues/868). 
Provide a require extension to avoid Node's resolution 'error' .
```
//  knex/bin/cli.js line:46
require.extensions['.js'] = (m, fileName)=> 
      m._compile(require("fs").readFileSync(fileName, "utf8"), fileName);
```

**Comment by D10221** [comment]
Here is a pr [#3938](https://github.com/knex/knex/pull/3938) with the proposed solution

**Comment by kibertoad** [comment]
Released in 0.21.3

**Comment by rajsinghUSA** [comment]
Thank you greatly for your work on this! I have been waiting for this feature for a long time, and I really appreciate your PR.

Unfortunately, I am getting this error:
```js
raj@r-sb2:~/repos/testserver$ npx knex@latest migrate:latest
npx: installed 159 in 7.501s
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/raj/repos/testserver/knexfile.js
require() of ES modules is not supported.
require() of /home/raj/repos/testserver/knexfile.js from /home/raj/.npm/_npx/9669/lib/node_modules/knex/lib/util/import-file.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename knexfile.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/raj/repos/testserver/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1273:13)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at importFile (/home/raj/.npm/_npx/9669/lib/node_modules/knex/lib/util/import-file.js:10:7)
    at openKnexfile (/home/raj/.npm/_npx/9669/lib/node_modules/knex/bin/cli.js:27:22)
    at initKnex (/home/raj/.npm/_npx/9669/lib/node_modules/knex/bin/cli.js:48:13)
    at Command.<anonymous> (/home/raj/.npm/_npx/9669/lib/node_modules/knex/bin/cli.js:167:32)
    at Command.listener [as _actionHandler] (/home/raj/.npm/_npx/9669/lib/node_modules/knex/node_modules/commander/index.js:413:31)
```
even though my `knexfile.js` only has `import`s:
```js
import { fileURLToPath } from 'url';
import { dirname } from 'path';
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
```
and my versions appear to be the latest:
```js
raj@r-sb2:~/repos/testserver$ npx knex --version
Knex CLI version: 0.21.5
Knex Local version: 0.21.5
```
with `node --version` 14.7.0

Any ideas?

**Comment by rajsinghUSA** [comment]
Nevermind, I ran `npx knex@latest migrate:latest` without `--esm`. I'll leave it all here, just in case anyone else runs into the issue.
