### ISSUE TITLE
MySQL 8.0.13 CURRENT_DATE as default knex throws ER_INVALID_DEFAULT at migrate:down

### ISSUE THREAD

**Issue by nogurenn** [knex/knex#3958]
# Environment

Knex version: 0.21.2
Database + version: MySQL 8.0.19
OS: Mac OS 10.14.6

# Bug

1. Expected behaviour

`down()` would work as expected after running in the CLI. MySQL supports `CURRENT_DATE` as default value for DATE columns as of 8.0.13. See https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html#data-types-defaults-explicit

2. Error message

```
Error: ER_INVALID_DEFAULT: Invalid default value for 'search_date'
    at Function.get (/Users/glenn/Developer/apollo/yelp-core/node_modules/knex/lib/util/make-knex.js:42:26)
    at Object.exports.down (/Users/glenn/Developer/apollo/yelp-core/db/knex_migrations/20200801195748_create_search_terms.js:37:15)
    at /Users/glenn/Developer/apollo/yelp-core/node_modules/knex/lib/migrate/Migrator.js:543:36
    at /Users/glenn/Developer/apollo/yelp-core/node_modules/knex/lib/transaction.js:184:22
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

3. Reduced test code

```js
exports.up = function(knex) {
  return knex.schema.createTable('my_table', function(t) {
    t.increments().primary();

    // this is now valid as of MySQL 8.0.13, but migrate:down complains saying invalid default
    // migrate:up works perfectly fine. Inserting into table yields proper default date
    t.date('search_date').defaultTo(knex.raw('(CURRENT_DATE)')); 
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable(name);  // the error gets thrown here
};

```

**Comment by mercmobily** [comment]
MySQL 8.0.13+ does allow `CURRENT_DATE` as a default for DATE, so the `up` side looks fine. The error being raised on `down()` at `dropTable` suggests server SQL modes or the exact default expression might be in play.

Checks to make:
- Use `t.date('search_date').defaultTo(knex.raw('CURRENT_DATE'))` (no parentheses). MySQL accepts `CURRENT_DATE` and `CURRENT_DATE()` interchangeably, but we shouldn’t wrap it in extra parentheses when used as a default.
- Share your `sql_mode` (e.g. `SELECT @@sql_mode;`) and whether `NO_ZERO_DATE`/`STRICT_TRANS_TABLES` are enabled; these influence default validation.
- Confirm there are no dependent FKs or triggers on the table that could be tripping `dropTable`.

If you can provide the exact DDL from `SHOW CREATE TABLE my_table` and the error stack with `DEBUG=knex:*`, I’ll dig further. 

However, being 5+ years since the report, I very much doubt that this is still an issue for you... sorry for the late response. Closing it for now.
