### ISSUE TITLE
Remote database access uses external ip address instead of defined host

### ISSUE THREAD

**Issue by Gabsii** [knex/knex#3991]
# Environment

Knex version: knex@0.21.5
Database + version: mysql 5.7 
OS: db is running on debian buster, trying to deploy from Mac OSX Catalina

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I tried to deploy a web app using Vercel. When migrating to a remote database on my own server I get an error. Saying that the access was denied but when reading through the error message I noticed that the host config parameter was set to my external IP address instead of the one I defined in the knexfile. 

2. Error message
```
➜ yarn migrate
yarn run v1.22.4
$ knex migrate:latest
Using environment: production
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'admin'@'MY_EXTERNAL_IP_ADDRESS' (using password: YES)
    at Handshake.Sequence._packetToError (/Users/lukasgabsi/Projects/sprint-slides-generator/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/lukasgabsi/Projects/sprint-slides-generator/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/lukasgabsi/Projects/sprint-slides-generator/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/lukasgabsi/Projects/sprint-slides-generator/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/lukasgabsi/Projects/sprint-slides-generator/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/lukasgabsi/Projects/sprint-slides-generator/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/lukasgabsi/Projects/sprint-slides-generator/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/lukasgabsi/Projects/sprint-slides-generator/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Protocol._enqueue (/Users/lukasgabsi/Projects/sprint-slides-generator/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/lukasgabsi/Projects/sprint-slides-generator/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/Users/lukasgabsi/Projects/sprint-slides-generator/node_modules/mysql/lib/Connection.js:116:18)
    at /Users/lukasgabsi/Projects/sprint-slides-generator/node_modules/knex/lib/dialects/mysql/index.js:69:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/Users/lukasgabsi/Projects/sprint-slides-generator/node_modules/knex/lib/dialects/mysql/index.js:64:12)
    at create (/Users/lukasgabsi/Projects/sprint-slides-generator/node_modules/knex/lib/client.js:291:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

knexfile.js

```
// when logging the env variables I get the correct address 
console.log({
  host: process.env.DATABASE_HOST,
  database: process.env.DATABASE_NAME,
  user: process.env.DATABASE_USER,
  password: process.env.DATABASE_PASSWORD,
});

module.exports = {
  development: {
    ...
  },
  production: {
    client: 'mysql',
    version: '5.7',
    connection: {
      host: process.env.DATABASE_HOST,
      database: process.env.DATABASE_NAME,
      user: process.env.DATABASE_USER,
      password: process.env.DATABASE_PASSWORD,
    },
    migrations: {
      tableName: 'knex_migrations',
    },
  },
};

```

**Comment by elhigu** [comment]
Is your database user `admin` ? Anyways doesn't look like a knex bug.

**Comment by elhigu** [comment]
Check mysql driver's documentation how to connect to the database.

**Comment by Gabsii** [comment]
For anyone stumbling upon this issue: 

My problem was that I had to enable remote database access on my MySQL server and go through all of the necessary configuration steps. This article helped me get through it https://www.digitalocean.com/community/tutorials/how-to-allow-remote-access-to-mysql
