### ISSUE TITLE
Bug: random `ambiguous column name` error

### ISSUE THREAD

**Issue by beenotung** [knex/knex#4025]
## Environment

Knex version: 0.21.5
Database + version: pg@8.3.3, mysql@2.18.1, sqlite3@5.0.0
OS: Archlinux

# Bug

**1. Explain what kind of behaviour you are getting and how you think it should do**

When I use knex sql builder to construct a join-table sql query and execute it with knex, it fails randomly.
1. I execute exactly the the same sql query for below conditions
2. It works fine for the first time per database connection
3. It fails at the second time using the same database connect
4. It works fine after restart the (express) server (back to point 2)
5. Tried pg, mysql, and sqlite3, obtain different error message but point to the same issue
6. Tried raw sql, it works for multiple times in the same connection (no problem in point 3)

I tried to rename the table name into plural form to avoid conflict on table name and column alias, but it doesn't help.

Create Tables:
```typescript
  await knex.schema.createTable('component_types', table => {
    table.increments('id').primary()
    table.string('name')
  })
  await knex.schema.createTable('users', table => {
    table.increments('id').primary()
    table.string('username')
  })
  await knex.schema.createTable('components', table => {
    table.increments('id').primary()
    table.integer('type').unsigned().references('id').inTable('component_types')
    table.string('name')
    table.integer('owner').unsigned().references('id').inTable('users')
  })
```

Query with knex sql builder (has bug):
```typescript
    let components = await tables.components
      .innerJoin<component_type>('component_types', 'components.type', 'component_types.id')
      .innerJoin<user>('users', 'components.owner', 'users.id')
      .select([
        'components.id as component_id',
        'components.name as component_name',
        'component_types.name as component_type',
        'users.username as owner_username',
      ])
```

Raw sql query with knex (no bug):
```typescript
      let components = await knex.raw(/* sql */`
select
    components.id as component_id,
    components.name as component_name,
    component_types.name as component_type,
    users.username as owner_username
from
    components
inner join component_types on components.type = component_types.id
inner join users on users.id = components.owner
`)
```

**2. Error message**

sqlite version error:
```
[Error: select `components`.`id` as `component_id`, `components`.`name` as `component_name`, `component_types`.`name` as `component_type`, `users`.`username` as `owner_username`, `components`.`id` as `component_id`, `components`.`name` as `component_name`, `component_types`.`name` as `component_type`, `users`.`username` as `owner_username` from `components` inner join `component_types` on `components`.`type` = `component_types`.`id` inner join `users` on `components`.`owner` = `users`.`id` inner join `component_types` on `components`.`type` = `component_types`.`id` inner join `users` on `components`.`owner` = `users`.`id` - SQLITE_ERROR: ambiguous column name: component_types.name] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
```

postgres version error:
```
error: select "component"."id" as "component_id", "component"."name" as "component_name", "component_type"."name" as "component_type", "user"."username" as "owner_username", "component"."id" as "component_id", "component"."name" as "component_name", "component_type"."name" as "component_type", "user"."username" as "owner_username" from "component" inner join "component_type" on "component"."type" = "component_type"."id" inner join "user" on "component"."owner" = "user"."id" inner join "component_type" on "component"."type" = "component_type"."id" inner join "user" on "component"."owner" = "user"."id" - table name "component_type" specified more than once
    at Parser.parseErrorMessage (/path/to/project/node_modules/.pnpm/pg-protocol@1.2.5/node_modules/pg-protocol/src/parser.ts:357:11)
    at Parser.handlePacket (/path/to/project/node_modules/.pnpm/pg-protocol@1.2.5/node_modules/pg-protocol/src/parser.ts:186:21)
    at Parser.parse (/path/to/project/node_modules/.pnpm/pg-protocol@1.2.5/node_modules/pg-protocol/src/parser.ts:101:30)
    at Socket.<anonymous> (/path/to/project/node_modules/.pnpm/pg-protocol@1.2.5/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 128,
  severity: 'ERROR',
  code: '42712',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '423',
  routine: 'checkNameSpaceConflicts'
}
```

mysql version error:
```
Error: ER_NONUNIQ_TABLE: Not unique table/alias: 'component_type'
    at Query.Sequence._packetToError (/path/to/project/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/path/to/project/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/path/to/project/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/path/to/project/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/path/to/project/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/path/to/project/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/path/to/project/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/path/to/project/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Protocol._enqueue (/home/beenotung/workspace/github.com/jasison27/polychain/baas-platform/baas-server/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/beenotung/workspace/github.com/jasison27/polychain/baas-platform/baas-server/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:198:25)
    at /home/beenotung/workspace/github.com/jasison27/polychain/baas-platform/baas-server/node_modules/.pnpm/knex@0.21.5_bb082626faf87689bc1860bdb8228cbd/node_modules/knex/lib/dialects/mysql/index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/home/beenotung/workspace/github.com/jasison27/polychain/baas-platform/baas-server/node_modules/.pnpm/knex@0.21.5_bb082626faf87689bc1860bdb8228cbd/node_modules/knex/lib/dialects/mysql/index.js:129:12)
    at Client_MySQL.query (/home/beenotung/workspace/github.com/jasison27/polychain/baas-platform/baas-server/node_modules/.pnpm/knex@0.21.5_bb082626faf87689bc1860bdb8228cbd/node_modules/knex/lib/client.js:169:17)
    at Runner.query (/home/beenotung/workspace/github.com/jasison27/polychain/baas-platform/baas-server/node_modules/.pnpm/knex@0.21.5_bb082626faf87689bc1860bdb8228cbd/node_modules/knex/lib/runner.js:151:36)
    at /home/beenotung/workspace/github.com/jasison27/polychain/baas-platform/baas-server/node_modules/.pnpm/knex@0.21.5_bb082626faf87689bc1860bdb8228cbd/node_modules/knex/lib/runner.js:40:23
    at /home/beenotung/workspace/github.com/jasison27/polychain/baas-platform/baas-server/node_modules/.pnpm/knex@0.21.5_bb082626faf87689bc1860bdb8228cbd/node_modules/knex/lib/runner.js:277:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ER_NONUNIQ_TABLE',
  errno: 1066,
  sqlMessage: "Not unique table/alias: 'component_type'",
  sqlState: '42000',
  index: 0,
  sql: "select `component`.`id` as `component_id`, `component`.`name` as `component_name`, `component`.`desc` as `component_desc`, `component_type`.`name` as `component_type`, `user`.`username` as `owner_username`, count(deployment.id) as num_deployment, `component`.`id` as `component_id`, `component`.`name` as `component_name`, `component_type`.`name` as `component_type`, `user`.`username` as `owner_username` from `component` inner join `component_type` on `component`.`type` = `component_type`.`id` inner join `user` on `component`.`owner` = `user`.`id` left join `deployment` on `deployment`.`component` = `component`.`id` inner join `component_type` on `component`.`type` = `component_type`.`id` inner join `user` on `component`.`owner` = `user`.`id` where `component`.`id` = '1' group by `component`.`id` limit 1"
}
```

**3. Reduced test code** on https://runkit.com/embed/k53nb9nf9k3j

(Cannot reproduce this bug in the runkit)

```javascript
require('sqlite3');
const Knex = require('knex');

const knex = Knex({
  client: 'sqlite',
  connection: ':memory:',
});

(async function run() {
  await knex.schema.createTable('component_type', (t) => {
    t.increments('id').primary();
    t.string('name');
  });
  await knex.schema.createTable('user', (t) => {
    t.increments('id').primary();
    t.string('name');
  });
  await knex.schema.createTable('component', (t) => {
    t.increments('id').primary();
    t.integer('owner').unsigned().references('id').inTable('user')
    t.integer('type').unsigned().references('id').inTable('component_type')
    t.string('name');
  });

  await knex('component_type').insert({ id: 1, name: 'app' });
  await knex('user').insert({ id: 1, name: 'admin' });
  await knex('component').insert([
    { id: 1, name: 'Alice', owner: 1, type: 1 },
    { id: 2, name: 'Bob', owner: 1, type: 1 },
  ]);

  function loadUsers () {
    return knex('component')
      .innerJoin('component_type', 'component.type', 'component_type.id')
      .innerJoin('user', 'component.owner', 'user.id')
      .select([
        'component.id as component_id',
        'component.name as component_name',
        'component_type.name as component_type',
        'user.name as component_owner',
      ])
  }

  let users = await loadUsers()
  console.log('users 1:', users);
  
  await new Promise((resolve)=>setTimeout(resolve,2000))
  
  users = await loadUsers()
  console.log('users 2:', users);
  
})();
```

**Comment by elhigu** [comment]
Props for great reproduction example! 🎉 🌮 Anyways if your code above you are creating table called `component_types` and in your reproduction `component_type` meaning that when you try to create an alias called `component_type` it overrides the joined table.

Try to fix that table name in repro and try again.

**Comment by beenotung** [comment]
I tried to name the table as `component_types` and `component_type`, but the same error occur, will share a reproduction later (probably not on runkit, but as github repo)

**Comment by elhigu** [comment]
> I tried to name the table as component_types and component_type, but the same error occur.

Please update the reproduction code how did you try out with different names and exact error messages from both cases. I don't believe that until I see it. Maybe you changed table name to one place and forgot to change it in queries. So far this doesn't seem like knex issue at all.

Also if you run that code with DEBUG=knex:* environment variable set, you will see all the queries that are ran. Then you can tell me exact generated SQL which is throwing the error you are experiencing.

**Comment by beenotung** [comment]
I think it is a bug in the knex because 
1. The error doesn't occur in the first time with knex.
The error occurs for second (and further) runs for the exact same query for each connection.
2. The error doesn't occur if running the query with knex.raw

Will attach a reproducible repo at night.
