### ISSUE TITLE
 knex: Required configuration option 'client' is missing.

### ISSUE THREAD

**Issue by slim-hmidi** [knex/knex#4032]
# Environment

Knex version:0.21.5
Database + version:
OS: windows 10

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

When I run the knex migrate:latest I got an error that the client missed.

2. Error message
```
Working directory changed to ~\Desktop\projects\done_list\build
Error: knex: Required configuration option 'client' is missing.
    at new Client (C:\Users\Slim\Desktop\projects\done_list\node_modules\knex\lib\client.js:55:11)
    at Knex (C:\Users\Slim\Desktop\projects\done_list\node_modules\knex\lib\knex.js:53:28)        
    at initKnex (C:\Users\Slim\Desktop\projects\done_list\node_modules\knex\bin\cli.js:57:10)     
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.<anonymous> (C:\Users\Slim\Desktop\projects\done_list\node_modules\knex\bin\cli.js:167:26)
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

knexfile.ts:
```
import dotenv from "dotenv";
import { Config } from "knex";
dotenv.config({ path: "../.env" });

interface KnexConfig {
  [name: string]: Config;
}

const knexConfig: KnexConfig = {
  development: {
    client: "pg",
    connection: {
      host: process.env.DB_HOST || "127.0.0.1",
      user: process.env.DB_USERNAME || "postgres",
      password: process.env.DB_PASSWRORD || "postgres",
      database: process.env.DB_DEV_NAME || "done_list",
    },
    migrations: {
      directory: "./src/migrations",
      extension: "ts",
    },
    seeds: {
      directory: "./src/seeds",
    },
  },
  test: {
    client: "pg",
    connection: {
      host: process.env.DB_HOST || "127.0.0.1",
      user: process.env.DB_USERNAME || "postgres",
      password: process.env.DB_PASSWRORD || "postgres",
      database: process.env.DB_DEV_NAME || "done_list_test",
    },
  },
};

export { knexConfig };
```

**Comment by slim-hmidi** [comment]
I fixed the issue by updating the knexfile.ts:
```ts
import dotenv from "dotenv";
dotenv.config({ path: "../.env" });

module.exports = {
  development: {
    client: "pg",
    connection: {
      host: process.env.DB_HOST || "127.0.0.1",
      user: process.env.DB_USERNAME || "postgres",
      password: process.env.DB_PASSWRORD || "postgres",
      database: process.env.DB_DEV_NAME || "done_list",
    },
    migrations: {
      directory: "./migrations",
      extension: "ts",
    },
    seeds: {
      directory: "./seeds",
    },
  },
  test: {
    client: "pg",
    connection: {
      host: process.env.DB_HOST || "127.0.0.1",
      user: process.env.DB_USERNAME || "postgres",
      password: process.env.DB_PASSWRORD || "postgres",
      database: process.env.DB_DEV_NAME || "done_list_test",
    },
  },
};
```

**Comment by x80486** [comment]
I ran into the same thing; you can use the original approach if you use the `default export` instead. Took me a couple of hours to figure it out 😓
