### ISSUE TITLE
The migration directory is corrupt, the following files are missing: 20200916144643_user.js with typescript

### ISSUE THREAD

**Issue by slim-hmidi** [knex/knex#4037]
# Environment

Knex version: 0.21.5
Database + version: postgresql
OS: windows 10
Node: 14.9.0
typescript: 4.0.2

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I have a test file described by:
```
process.env.NODE_ENV = "test";
import request from "supertest";
import { app } from "../app";
import connection from "../db";

describe("Authentication", () => {
  beforeEach(async () => {
    await connection.migrate.rollback();
    await connection.migrate.latest();
  });
  afterAll(async () => {
    await connection.migrate.rollback();
  });
  it("Should returns an error if any field is missed", async () => {
    const response = await request(app)
      .post("/auth/signup")
      .send({
        firstName: "John",
        lastName: "Smith",
        email: "john.smith@gmail.com",
        birthday: "1990-12-01",
        password: "jSmith@2020",
      });

    expect(response.status).toBe(400);
    expect(response.body.message).toEqual("Username required");
  });
```

knexfile.ts:
```
export = {
  development: {
    client: "pg",
    connection: {
      host: process.env.DB_HOST || "127.0.0.1",
      user: process.env.DB_USERNAME || "postgres",
      password: process.env.DB_PASSWRORD || "postgres",
      database: process.env.DB_DEV_NAME || "done_list",
    },
  },
  test: {
    client: "pg",
    connection: {
      host: process.env.DB_HOST || "127.0.0.1",
      user: process.env.DB_USERNAME || "postgres",
      password: process.env.DB_PASSWRORD || "postgres",
      database: process.env.DB_DEV_NAME || "done_list_test",
    },
    migrations: {
      directory: "./src/migrations",
      extension: "ts",
    },
  },
};
```
db.ts:
```
import knex from "knex";
import knexConfig from "./knexfile";

const environment = process.env.NODE_ENV || "development";
const connectionConfig = (knexConfig as any)[environment];

const connection = knex(connectionConfig);

export default connection;
```
migrations/20200916144643_user.ts:
```
import * as Knex from "knex";

export async function up(knex: Knex): Promise<void> {
  return knex.schema.hasTable("user").then((exists) => {
    if (!exists) {
      return knex.schema.createTable("user", (table) => {
        table.increments("id"),
          table.string("first_name", 255).notNullable(),
          table.string("last_name", 255).notNullable(),
          table.string("username", 50).notNullable().unique(),
          table.string("password", 255).notNullable(),
          table.string("email").notNullable().unique(),
          table.date("birthday");
      });
    }
  });
}

export async function down(knex: Knex): Promise<void> {
  return knex.schema.dropTableIfExists("user");
}
```

2. Error message
I got this error message when I run the tests:
```
 console.log
      FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations

      at Logger._log (node_modules/knex/lib/logger.js:45:13)

    console.log
      FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations

      at Logger._log (node_modules/knex/lib/logger.js:45:13)

    console.log
      FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations

      at Logger._log (node_modules/knex/lib/logger.js:45:13)

    console.log
      FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations

      at Logger._log (node_modules/knex/lib/logger.js:45:13)

  ● Authentication › Should returns an error if any field is missed

    The migration directory is corrupt, the following files are missing: 20200916144643_user.js

      at validateMigrationList (node_modules/knex/lib/migrate/Migrator.js:566:11)
      at node_modules/knex/lib/migrate/Migrator.js:176:13

A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --runInBand --detectOpenHandles to find leaks.
```

**Comment by elhigu** [comment]
Probably you have compiled .ts .js  at some point and ran migrations thus making DB to have .js file logged in migration table. Then maybe after some cleanup .js file hasn't been in migration directory anymore and migration API will think that directory doesn't match data in migration table anymore.

Looks more like an user error. Check what is contents in your knex_migrations table... Closing until there is some minimal test case to pinpoint that there actually isa bug in knex causing this.

More minimal testcase is for example single .js file that calls the migration API and the migration file.

**Comment by elhigu** [comment]
If someone is able to help with given info feel free to do so.
