### ISSUE TITLE
Incorrect `connection` throws uncatchable TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string..

### ISSUE THREAD

**Issue by cskeogh** [knex/knex#4120]
# Environment

Knex version :0.21.12
Database + version: PostgreSQL 13.1
OS: Windows

# Bug

1. I want to let the user know they have set the `connection` string incorrectly. However, Knex.js throws un-catchable TypeError. For example, the user missed one `/` and instead of `postgres://user:password@host:port/database` provided `postgres:/user:password@host:port/database`.

   Note: if the user, password, host are wrong, Knex.js **does** throw a nice catchable exception.

2. Error message:
```
internal/crypto/keys.js:322
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received null
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at new Hmac (internal/crypto/hash.js:111:9)
    at Object.createHmac (crypto.js:147:10)
    at createHMAC (c:\proj\node_modules\pg\lib\sasl.js:133:17)
    at Hi (c:\proj\node_modules\pg\lib\sasl.js:137:13)
    at Object.continueSession (c:\proj\node_modules\pg\lib\sasl.js:32:24)
    at Client._handleAuthSASLContinue (c:\proj\node_modules\pg\lib\client.js:257:10)
    at Connection.emit (events.js:315:20)
    at c:\proj\node_modules\pg\lib\connection.js:115:12
    at Parser.parse (c:\proj\node_modules\pg-protocol\dist\parser.js:40:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

3. Reduced test code:
```javascript
async function testdb() {
    try {
        let pg = require('knex')({
            client: 'pg',
            connection: 'postgres:/user:password@host:port/database'
        });

        var res = await pg.raw('select 1+1 as result');
        console.log('connected to database');
    } catch (e) {
        console.log("ERROR:");
        console.log(e);
    }
}

testdb();
```

I'd expect `ERROR:` and the exception displayed. Instead the above error is displayed.

**Comment by elhigu** [comment]
Cannot reproduce:

```
mlepisto@DESKTOP-VKJ76GO ~/G/Projects/test
λ cat test.js
async function testdb() {
    try {
        let pg = require('knex')({
            client: 'pg',
            connection: 'postgres:/user:password@192.168.99.101:15432/database'
        });

        var res = await pg.raw('select 1+1 as result');
        console.log('connected to database');
    } catch (e) {
        console.log("ERROR:");
        console.log(e);
    }
}

testdb();
mlepisto@DESKTOP-VKJ76GO ~/G/Projects/test
λ node test.js
ERROR:
{ Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432 }
mlepisto@DESKTOP-VKJ76GO ~/G/Projects/test
λ
```

Also the error seems to be coming from pg driver, so if it throws type error, then it is what you get. Knex does not validate all the arguments that are passed to internal libs by design. 

Lets reopen if there is something that `knex` should do to change this behavior.
