### ISSUE TITLE
Unable to compile TypeScript when running migrations

### ISSUE THREAD

**Issue by rbeier** [knex/knex#4123]
# Environment

Knex version: 0.21.12
Database + version: mysql 2.18.1
OS: MacOS Catalina

@lorefnon 

### 1. Explain what kind of behaviour you are getting and how you think it should do
I tried to execute a _typescript_ migration and npm throws an error. Plain JavaScript migrations are working as expected. Goal is to migrate the js codebase to typescript. The rest of the codebase is a small next.js project.

### 2. Error message
```bash
npm run migrate

> test@0.1.0 migrate /Users/rb/dev/privat/test
> knex migrate:latest

Requiring external module ts-node/register
Using environment: development
TSError: ⨯ Unable to compile TypeScript:
src/migrations/20191117165830_test.ts:1:26 - error TS2532: Object is possibly 'undefined'.

1 var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
                           ~~~~
src/migrations/20191117165830_test.ts:10:28 - error TS2532: Object is possibly 'undefined'.

10 var __generator = (this && this.__generator) || function (thisArg, body) {
                              ~~~~
src/migrations/20191117165830_test.ts:25:111 - error TS2322: Type 'number' is not assignable to type '{ label: number; sent: () => any; trys: any[]; ops: any[]; }'.

25                     if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                                                                                                                 ~

    at createTSError (/Users/rb/dev/privat/test/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/Users/rb/dev/privat/test/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/Users/rb/dev/privat/test/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/Users/rb/dev/privat/test/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/Users/rb/dev/privat/test/node_modules/ts-node/src/index.ts:1043:43)
    at Module.m._compile (/Users/rb/dev/privat/test/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at require.extensions.(anonymous function) (/Users/rb/dev/privat/test/node_modules/ts-node/src/index.ts:1046:12)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/rb/dev/privat/test/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

### 3. Reduced test code  

knexfile.ts:
```js
require('ts-node').register();

module.exports = {
  development: {
    client: 'mysql',
    connection: {
      port: 33060,
      user: 'root',
      password: 'root',
      database: 'test',
    },
    migrations: {
      tableName: 'migrations',
      directory: './src/migrations',
      loadExtensions: ['.ts']
    },
    seeds: {
      directory: './src/seeds'
    }
  }
};
```

migration.ts:
```js
import * as Knex from "knex";

export async function up(knex: Knex): Promise<void> {
  return knex.schema
    .createTable('test', table => {
      table.increments('id');
    });
}

export async function down(knex: Knex): Promise<void> {
  return knex.schema
    .dropTable('test');
}
```

**Comment by kibertoad** [comment]
Looks like the error is on your side, please read the log you posted.
```
TSError: ⨯ Unable to compile TypeScript:
src/migrations/20191117165830_test.ts:1:26 - error TS2532: Object is possibly 'undefined'.
```

**Comment by rbeier** [comment]
Hi @kibertoad,

I see it a little differently. The migration is called with `knex migrate:latest`, which apparently does not correctly pass the knex instance to the migration. This is not an error on my side. 

Unfortunately the documentation is not very detailed regarding its use with TypeScript. Is there an example repo where you can see how to use it correctly with TypeScript?
