### ISSUE TITLE
Timeout error when trying to insert into MSSQL database with approximately 100 bindings

### ISSUE THREAD

**Issue by fhoa** [knex/knex#4126]
# Environment

Knex version: ^0.14.0
Database + version: MSSQL ^4.1.0
OS: Ubuntu 18.04

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @ smorey2.
Rest of dialects don't need tags.
If issue is about TypeScript definitions, tag @ lorefnon.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

When trying to insert into a table with approximately 100 bindings, the query runs forever without terminating. When wrapping it in a try/catch block I can however force an error to be outputted (see following).

If I reduce the amount of bindings the query runs perfectly fine. Furthermore, I've tried running the query directly from SQL Server studios and here it works perfectly fine.

I've experienced similar error before with another insert statement. This one only had 3 bindings, however when one of the bindings were more than 3000 characters, the exact same error occured.

2. Error message

 RequestError: Connection closed before request completed.
     at Request.tds.Request.err [as userCallback] (/src/node_modules/mssql/lib/tedious.js:578:19)
     at Request._this.callback (/src/node_modules/tedious/lib/request.js:48:27)
     at Connection.cleanupConnection (/src/node_modules/tedious/lib/connection.js:451:24)
     at Connection.enter (/src/node_modules/tedious/lib/connection.js:1780:19)
     at Connection.transitionTo (/src/node_modules/tedious/lib/connection.js:846:33)
     at Connection.socketEnd (/src/node_modules/tedious/lib/connection.js:889:19)
     at Socket.emit (events.js:203:15)
     at Socket.EventEmitter.emit (domain.js:448:20)
     at endReadableNT (_stream_readable.js:1145:12)
     at process._tickCallback (internal/process/next_tick.js:63:19)
   code: 'ECLOSE',
   number: 'ECLOSE',
   state: undefined,
   originalError:
    { RequestError: Connection closed before request completed.
        at RequestError (/src/node_modules/tedious/lib/errors.js:34:12)
        at Connection.cleanupConnection (/src/node_modules/tedious/lib/connection.js:450:21)
        at Connection.enter (/src/node_modules/tedious/lib/connection.js:1780:19)
        at Connection.transitionTo (/src/node_modules/tedious/lib/connection.js:846:33)
        at Connection.socketEnd (/src/node_modules/tedious/lib/connection.js:889:19)
        at Socket.emit (events.js:203:15)
        at Socket.EventEmitter.emit (domain.js:448:20)
        at endReadableNT (_stream_readable.js:1145:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
      message: 'Connection closed before request completed.',
      code: 'ECLOSE' },
   name: 'RequestError',
   precedingErrors: [] }

**Comment by fhoa** [comment]
@smorey2

**Comment by elhigu** [comment]
Cannot reproduce and doesn't sound like a knex issue. Try to send the same query directly with node-mssql driver and see if it hangs too. Then come up with minimal reproduction if you still think that the problem is in knex. 

Usually bug reports with this little information are actually user errors after all...
