### ISSUE TITLE
Error: stream destroyed

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [knex/knex#4132]
# Environment

Knex version: 0.21.12
Nodejs version: 14.15.1
Database + version: MariaDB 10.3.27
OS: Centos 7

# Bug

I encountered this issue after updating knex from version 0.16.3 to version 0.21.12 and NodeJS from 6.9.0 to 14.15.1, before that I have never see this error.

1. I'm trying to retrieve a large amount of data from a SELECT statement by using the stream API:
```javascript
    return new Promise((res) => {
        let query = knex(knex.ref('table').as('l'))
            .distinct('l.*');
        query = addQueries1(query);
        query = query.where(whereFilter);
        query = addQueries2(query);
        lib.log.info('QUERYING table with: ' + query.toString());
        return query.stream(res);
    });
```
After that I simply listen on events like `stream.on('data', (chunk) => {})` or `'error'` or `'end'`. I'd like to specify that there no other call on the stream rather than the `on` listeners (neither `destroy()` or `pipe()`).
2. After some random time the stream triggers an error on the `on('error')` listener, that goes like this:
```
nov 24 10:38:55 dev2.eplate.local npm[31646]: [CHILD][PID: 32545] - [INFO] [logger] - Error: stream destroyed
nov 24 10:38:55 dev2.eplate.local npm[31646]: at Transform.destroy [as _destroy] (/opt/nodejs/eplate_nodejs/node_modules/knex/lib/runner.js:91:31)
nov 24 10:38:55 dev2.eplate.local npm[31646]: at Transform.destroy (internal/streams/destroy.js:39:8)
nov 24 10:38:55 dev2.eplate.local npm[31646]: at finish (_stream_writable.js:670:14)
nov 24 10:38:55 dev2.eplate.local npm[31646]: at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
3. Demo code:
```javascript
const promise = new Promise(res => {
        let query = knex(knex.ref('table').as('l'))
            .distinct('l.*');
        // ensure a large set of data
        query = query.where({id: {lte: 100000}});
        lib.log.info('QUERYING table with: ' + query.toString());
        return query.stream(res);
});
promise.then(s => {
s.on('error', e => {console.error(e);});
s.on('data', c => {console.log(c);});
s.on('end', () => {console.log('end!');});
});
```

# Other details
I'm not able to reproduce this issue on a different OS...

**Comment by maximerichrd** [comment]
I had the same error : 
Switching from node v14 to v12, it finally worked.

**Comment by danielgindi** [comment]
> I've run into the same problem. My guess is that instead of always passing along an error the `queryStream`, it should just pass whatever error was given to the `.destroy()` function.

Actually, that `destroy` should probably removed completely. As everything is piped automatically, and the `transform` is processing chunks in the middle.

**Comment by danielgindi** [comment]
> I was wondering whether these original problem(s) are no longer an issue, or would removing the code reintroduce them?

It's simply a matter of responsibilities. If every component does what it's supposed to do, and does not so what it's not supposed to do- then there's no need for ugly workarounds.

**Comment by mercmobily** [comment]
Hi! Thanks for the detailed CentOS 7 report and the follow‑ups from others.

This has been resolved and the fix was merged via PR #5243 (which cherry‑picked the solution from #5043). The old transform stream’s custom `destroy()` implementation that emitted an error was removed, aligning with Node streams’ normal destroy semantics. Current runner stream code no longer injects an error on destroy; see lib/execution/runner.js:25..116.

If you’re on a version prior to that merge, please upgrade Knex. If you still see a similar error with a current release, let us know with a fresh reproduction.

Related issues:
- 5043 Destroy should not trigger an error (closed)
