### ISSUE TITLE
Class constructor Client cannot be invoked without 'new' during migration rollback

### ISSUE THREAD

**Issue by cozzbie** [knex/knex#4221]
# Environment

Knex version: 0.21.15
Database + version: Pgsql 12
OS: Docker running linux

# Bug
I am trying to run a migration rollback on a column against a Postgres table.

```js
exports.down = knex => knex.schema
    .table('tablename', (table) => {
        table.dropColumns(
            table.boolean('default'),
            table.boolean('visible')
        );
    });
```
and for the love of me I am getting the following error

```
TypeError: Class constructor Client cannot be invoked without 'new'
    at Formatter.compileCallback (/app/node_modules/knex/lib/formatter.js:221:14)
    at Formatter.parseObject (/app/node_modules/knex/lib/formatter.js:253:31)
    at Formatter.wrap (/app/node_modules/knex/lib/formatter.js:181:21)
    at Formatter.parseObject (/app/node_modules/knex/lib/formatter.js:265:27)
    at Formatter.wrap (/app/node_modules/knex/lib/formatter.js:181:21)
    at Formatter.parseObject (/app/node_modules/knex/lib/formatter.js:265:27)
    at Formatter.wrap (/app/node_modules/knex/lib/formatter.js:181:21)
    at /app/node_modules/knex/lib/schema/tablecompiler.js:270:51
    at Array.map (<anonymous>)
    at TableCompiler_PG.TableCompiler.dropColumn (/app/node_modules/knex/lib/schema/tablecompiler.js:269:64)
```
And this is the complete debug error

```
Using environment: development
  knex:client acquired connection from pool: __knexUid1 +0ms
  knex:query select * from information_schema.tables where table_name = ? and table_schema = current_schema() undefined +0ms
  knex:bindings [ 'knex_migrations' ] undefined +0ms
  knex:client releasing connection to pool: __knexUid1 +35ms
  knex:client acquired connection from pool: __knexUid1 +2ms
  knex:query select * from information_schema.tables where table_name = ? and table_schema = current_schema() undefined +34ms
  knex:bindings [ 'knex_migrations_lock' ] undefined +34ms
  knex:client releasing connection to pool: __knexUid1 +6ms
  knex:client acquired connection from pool: __knexUid1 +2ms
  knex:query select * from "knex_migrations_lock" undefined +12ms
  knex:bindings [] undefined +11ms
  knex:client releasing connection to pool: __knexUid1 +10ms
  knex:client acquired connection from pool: __knexUid1 +2ms
  knex:query select "name" from "knex_migrations" order by "id" asc undefined +9ms
  knex:bindings [] undefined +9ms
  knex:client releasing connection to pool: __knexUid1 +31ms
  knex:client acquired connection from pool: __knexUid1 +4ms
  knex:query select * from "knex_migrations" where "batch" = (select max("batch") from "knex_migrations") order by "id" desc undefined +38ms
  knex:bindings [] undefined +38ms
  knex:client releasing connection to pool: __knexUid1 +8ms
  knex:tx trx2: Starting top level transaction +0ms
  knex:client acquired connection from pool: __knexUid1 +5ms
  knex:query BEGIN; trx2 +10ms
  knex:bindings undefined trx2 +12ms
  knex:query update "knex_migrations_lock" set "is_locked" = ? where "is_locked" = ? trx2 +8ms
  knex:bindings [ 1, 0 ] trx2 +7ms
  knex:query COMMIT; trx2 +4ms
  knex:bindings undefined trx2 +5ms
  knex:tx trx2: releasing connection +22ms
  knex:client releasing connection to pool: __knexUid1 +23ms
  knex:client acquired connection from pool: __knexUid1 +10ms
  knex:query select max("batch") as "max_batch" from "knex_migrations" trx2 +22ms
  knex:bindings [] trx2 +21ms
  knex:client releasing connection to pool: __knexUid1 +6ms
  knex:tx trx3: Starting top level transaction +23ms
  knex:client acquired connection from pool: __knexUid1 +6ms
  knex:query BEGIN; trx3 +11ms
  knex:bindings undefined trx3 +11ms
  knex:query ROLLBACK trx3 +13ms
  knex:bindings undefined trx3 +14ms
  knex:tx trx3: releasing connection +19ms
  knex:client releasing connection to pool: __knexUid1 +40ms
migration file "20210109184809_add_bank_default.js" failed
migration failed with error: Class constructor Client cannot be invoked without 'new'
  knex:client acquired connection from pool: __knexUid1 +3ms
  knex:query update "knex_migrations_lock" set "is_locked" = ? trx3 +29ms
  knex:bindings [ 0 ] trx3 +27ms
  knex:client releasing connection to pool: __knexUid1 +6ms
TypeError: Class constructor Client cannot be invoked without 'new'
    at Formatter.compileCallback (/app/node_modules/knex/lib/formatter.js:221:14)
    at Formatter.parseObject (/app/node_modules/knex/lib/formatter.js:253:31)
    at Formatter.wrap (/app/node_modules/knex/lib/formatter.js:181:21)
    at Formatter.parseObject (/app/node_modules/knex/lib/formatter.js:265:27)
    at Formatter.wrap (/app/node_modules/knex/lib/formatter.js:181:21)
    at Formatter.parseObject (/app/node_modules/knex/lib/formatter.js:265:27)
    at Formatter.wrap (/app/node_modules/knex/lib/formatter.js:181:21)
    at /app/node_modules/knex/lib/schema/tablecompiler.js:270:51
    at Array.map (<anonymous>)
    at TableCompiler_PG.TableCompiler.dropColumn (/app/node_modules/knex/lib/schema/tablecompiler.js:269:64)
```

Any help will be greatly appreciated.

**Comment by kibertoad** [comment]
@cozzbie What was the issue?

**Comment by cozzbie** [comment]
@kibertoad if you take a look at the syntax I was passing the wrong types into the _dropColumns_ function. I should have been passing strings instead

```js
// Wrong
exports.down = knex => knex.schema
    .table('tablename', (table) => {
        table.dropColumns(
            table.boolean('default'), //Issue was here
            table.boolean('visible') //and here
        );
    });

// Right
exports.down = knex => knex.schema
    .table('tablename', (table) => {
        table.dropColumns(
           'default',
            'visible
        );
    });
```
