### ISSUE TITLE
knex migrate:latest  --> Error: Access denied for user

### ISSUE THREAD

**Issue by gaetaneferon** [knex/knex#4309]
# Environment

Knex version:  0.21.18
Database + version: mariadb  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
OS: Linux Debian 10

# Bug

When I launch the command 
`$ knex migrate:latest`

I get the following error :

```
Using environment: development
Error: Access denied for user 'myuser'@'localhost' (using password: YES)
    at Packet.asError (/home/gaetane/projects/services/node_modules/mysql2/lib/packets/packet.js:712:17)
    at ClientHandshake.execute (/home/gaetane/projects/services/node_modules/mysql2/lib/commands/command.js:28:26)
    at Connection.handlePacket (/home/gaetane/projects/services/node_modules/mysql2/lib/connection.js:425:32)
    at PacketParser.onPacket (/home/gaetane/projects/services/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/home/gaetane/projects/services/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/gaetane/projects/services/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
```
My knexfile.js is : 

```
module.exports = {

  development: {
    client: 'mysql2',
    connection: {
      host: "localhost",
      user: "myuser",
      password: "pwd",
      database: "mybdd"
    },
    debug: true
  },
  production: {
    client: 'mysql2',
    connection: {
      host: "localhost",
      user: "myuser",
      password: "pwd",
      database: "mybdd"
    },
    debug: false
  }
};
```

Any idea to solve the issue? Many thanks in advance

**Comment by kibertoad** [comment]
This seems like an authentication issue. Does it work when you connect to database directly using exact same credentials?

**Comment by gaetaneferon** [comment]
Yes indeed
`mysql --host=localhost --user=myuser --password=pwd mybdd`
I get:
`ERROR 1045 (28000): Access denied for user 'myuser'@'localhost' (using password: YES)`

But when I check on phpadmin it seems to be correct parameters. how can I check in command line?

**Comment by gaetaneferon** [comment]
I solved my issue this way : 

I duplicated myuser with host "localhost" because in database it was created with host "%"
Now it works fine

this link help me understand the issue : https://stackoverflow.com/questions/10823854/using-for-host-when-creating-a-mysql-user
