### ISSUE TITLE
MySQL2 stream option 'Illegal invocation' error

### ISSUE THREAD

**Issue by bartversluijs** [knex/knex#4329]
# Environment

Knex version: 0.21.18
Database + version: MariaDB 10.2.37
OS: macOS 11.2.2

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
I want to connect to MySQL via an SSH tunnel. So I've set up an SSH tunnel via `ssh2` and used the `ssh2.forwardOut` to create the tunnel. This works as expected.

I've tried to create a connection with MySQL2 and query raw data. Which works as expected, I can query data via the SSH tunnel. See code below.

Now, I've created a Knex connection, with client `mysql2` and the same config as the MySQL2 connection I've used before Knex. I expected this to work properly, however, I get an "TypeError: Illegal invocation" error when querying the database. See code below

2. Error message
```
02-03 12:36:13 [index.ts, master (10932)] error: uncaughtException:Illegal invocation TypeError: Illegal invocation
    at Cipheriv.update (internal/crypto/cipher.js:161:29)
    at send_ (./node_modules/ssh2-streams/lib/ssh.js:5047:34)
    at send (./node_modules/ssh2-streams/lib/ssh.js:4961:12)
    at SSH2Stream.channelData (./node_modules/ssh2-streams/lib/ssh.js:969:10)
    at Channel._write (./node_modules/ssh2/lib/Channel.js:347:21)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Channel.Writable.write (_stream_writable.js:303:10)
    at Connection.write (./node_modules/mysql2/lib/connection.js:230:32)
    at Connection.writePacket (./node_modules/mysql2/lib/connection.js:279:12)
    at ClientHandshake.sendCredentials (./node_modules/mysql2/lib/commands/client_handshake.js:64:16)
    at ClientHandshake.handshakeInit (./node_modules/mysql2/lib/commands/client_handshake.js:137:12)
    at ClientHandshake.execute (./node_modules/mysql2/lib/commands/command.js:39:22)
    at Connection.handlePacket (./node_modules/mysql2/lib/connection.js:425:32)
    at PacketParser.onPacket (./node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (./node_modules/mysql2/lib/packet_parser.js:75:16)
    at Channel.<anonymous> (./node_modules/mysql2/lib/connection.js:82:25)
```

3. Reduced test code

```ts
import { Client, ClientChannel } from 'ssh2';
import mysql2 from 'mysql2';
import Knex from 'knex';

const init = async () => {
  // Connect to SSH
  const ssh = new Client();
  await new Promise(async (resolve, reject) => {
    try {
      ssh.connect({ ... });
    } catch (e) {
      reject(e);
    }

    ssh.on('ready', resolve);
    ssh.on('error', reject);
  });

  // Create SSH tunnel from SSH client port 3306 to local PC port 3306
  let stream: ClientChannel;
  stream = await new Promise((resolve, reject) => {
    ssh.forwardOut('127.0.0.1', 3306, '127.0.0.1', 3306, (err: Error | undefined, channel: ClientChannel) => {
      if (err) return reject(err);
      resolve(channel);
    });
  });

  // MySQL2 connection
  // Everything goes fine here
  const mysqlConnection = mysql2.createConnection({ 
    host: '127.0.0.1', 
    port: 3306, 
    stream: stream 
  });

  mysqlConnection.query('SELECT 1', (err, result) => {
    if (err) { 
      throw err;
    }

    console.log('mysql2 result', result);
  });

  // Knex connection
  const knex = Knex({ 
    client: 'mysql2',
    connection: {
      host: '127.0.0.1',
      port: 3306,
      stream: stream
    }
  });

  // This will error with 'TypeError: Illegal invocation'
  console.log('knex result', knex.raw('SELECT 1'));
};

init();
```

**Comment by israelidanny** [comment]
Getting exactly the same problem. @bartversluijs did you manage to solve it somehow?

**Comment by bartversluijs** [comment]
Hi @israelidanny, unfortunately I could not find a fix for this.

I created a workaround, which was creating a tunnel using [tunnel-ssh](https://www.npmjs.com/package/tunnel-ssh) and tunneled the port 3306 to 127.0.0.1:3306, and connected to that. So instead of using the MySQL2 engine to do that, I created a tunnel for the whole Node.js application.

**Before you do this**, after a while I got a nasty memory leak. I checked everything, and after removing the SSH tunnel and directly connecting to the database with an open firewall, the memory leak was gone. So I would not advise you to use the workaround I did.

I hoped someone of the Knex maintainers would find a solution for this. It's probably something with a wrong bind or something, but haven't had the time and resources to debug it myself.

**Comment by kibertoad** [comment]
@bartversluijs It is unlikely that maintainers will find a solution for this, because unfortunately all of them are very busy and are unlikely to dedicate any time to investigating a problem as niche as this. However, any community contributions here would be dearly appreciated.

**Comment by bartversluijs** [comment]
@kibertoad I totally get that. As said, if I find some time / resources to debug this problem, I probably will. I totally agree it's a niche problem. 

Just hoped that someone would see this and thought: "Oh, that's an easy fix" 🙂

**Comment by Miikis** [comment]
Hi. I ran into this issue earlier today. Just thought I'd share that providing a function that returns the connection config, for the `connection` property seems to work as expected. So, instead of this:

```
const knex = Knex({ 
    client: 'mysql2',
    connection: {
      host: '127.0.0.1',
      port: 3306,
      stream: stream
    }
  });
```

try this instead:

```
const knex = Knex({ 
    client: 'mysql2',
    connection: () => ({
      host: '127.0.0.1',
      port: 3306,
      stream: stream
    })
  });
```

**Comment by lgh06** [comment]
I am wondering which driver should I use when connecting to MariaDB v10...
as the https://knexjs.org/ says, 

```
If you want to use a MariaDB instance, you can use the mysql driver.
```  
So knex don't support mysql2 to connet to MariaDB ?

**Comment by lgh06** [comment]
https://github.com/knex/knex/issues/717

**Comment by mercmobily** [comment]
This is an integration edge case with mysql2’s stream option and SSH tunnels. Workarounds exist; a robust fix would likely land in the client connection initialisation for mysql2, rather than knex.

What you’re hitting is a `TypeError: Illegal invocation` thrown inside `ssh2-streams` when the `mysql2` driver writes to the provided stream during handshake. Knex passes your connection object through to `mysql2`, but it also wraps connection acquisition via the pool and may call methods in a way that triggers this error path when a pre-created stream is reused.

Two data points from the thread are useful:
- A plain `mysql2.createConnection` with the same stream works, so the driver supports it in principle.
- Using a function for connection in Knex, i.e. `connection: () => ({ host, port, stream })`, avoids the error for multiple people (see the comment citing `knex@0.95.13`). That suggests that deferring the creation of the connection object per acquisition sidesteps whatever binding/closure trips the invocation error.

Given this, immediate options are:
- Use a connection factory function in Knex config instead of an object literal when providing a custom stream.
- Alternatively, tunnel to a local port and point Knex at host/port without passing a stream, avoiding the driver stream path entirely; just be mindful of resource and memory implications.

From Knex side, we can add a small doc note under `mysql2` configuration calling out that when providing a stream, using a function returning a fresh object is advisable. If there’s a minimal fix we can implement in the `mysql2` client initialisation code path to clone the connection config before passing to the driver, we could look into that too, but given that `mysql2` accepts the stream already when used directly, the safer immediate step is documenting the working pattern.
