### ISSUE TITLE
Inserting uuid's always adds {}'s around causing postgresql to error

### ISSUE THREAD

**Issue by JasonDictos** [knex/knex#4393]
# Environment
Database + version: Postgresql (Docker) 13.2 (Debian 13.2-1.pgdg100+1) 
Knex version: 0.95.2
OS: Windows 10 x64 20H2

# Bug

I'm using uuids as a primary key:
```... table: table: Knex.CreateTableBuilder) {
		table.uuid("id")
		.primary()
		.notNullable()
		.unique()
		.defaultTo(knex.raw('uuid_generate_v4()'))
```
2. Error message
Every time I try to select the row by its id like so:

```knex.table("entity").select().where("id", id)```

It generates a query with braces around the string:
``` "{"236f7763-8d9a-4230-a1cc-d07ef9698513"}"```

This causes postgresql to error:
```
error: select * from "bobo7"."entity" where "id" = $1 - invalid input syntax for type uuid: "{"236f7763-8d9a-4230-a1cc-d07ef9698513"}"\n    at Parser.parseErrorMessage (D:\\CustodyCalendar-Server\\node_modules\\pg-protocol\\src\\parser.ts:357:11)\n    at Parser.handlePacket (D:\\CustodyCalendar-Server\\node_modules\\pg-protocol\\src\\parser.ts:186:21)\n    at Parser.parse (D:\\CustodyCalendar-Server\\node_modules\\pg-protocol\\src\\parser.ts:101:30)\n    at Socket.<anonymous> (D:\\CustodyCalendar-Server\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:378:20)\n    at addChunk (node:internal/streams/readable:313:12)\n    at readableAddChunk (node:internal/streams/readable:288:9)\n    at Socket.Readable.push (node:internal/streams/readable:227:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)\n    at TCP.callbackTrampoline (node:internal/async_hooks:132:14) {length: 135, name: 'error', severity: 'ERROR', code: '22P02', detail: undefined, …}

```

However if I instead use the whereRaw api like so:
```knex.table("entity").select().whereRaw(`id = ${id}`)```

It does not produce the braces and I'm able to select ok

I'm not sure if its a bug or not, if a repro is required if its not an obvious mistake by myself I can work on one, thanks in advance for any help or ideas, great project btw.

**Comment by JasonDictos** [comment]
Not reproducible, I think the data type was an array instead of a string
