### ISSUE TITLE
knex.raw can't excute two SQL statements

### ISSUE THREAD

**Issue by JE-lee** [knex/knex#4408]
# Environment

Knex version: 0.21.17
Database + version: mysql 8.0+
OS: any
# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

the code beflow can work
```javascript
const sql = `
CREATE TABLE \`user\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB AUTO_INCREMENT=1332233001286 DEFAULT CHARSET=utf8;
`;

knex.raw(sql)
```

but with two SQL statement, it fail

```javascript
const sql = `
DROP TABLE IF EXISTS \`user\`;
CREATE TABLE \`user\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB AUTO_INCREMENT=1332233001286 DEFAULT CHARSET=utf8;
`;

knex.raw(sql)
```
2. Error message
```bash
Requiring external module ts-node/register
Using environment: development
migration file "20210401114128_1.ts" failed
migration failed with error: 
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1332233001286 DEFAULT CHARSET=utf8;
 - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE `user` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY ' at line 2
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE `user` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY ' at line 2
    at Query.Sequence._packetToError (/Users/wuliheng/workspace/side-project/iam/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/wuliheng/workspace/side-project/iam/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/wuliheng/workspace/side-project/iam/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/wuliheng/workspace/side-project/iam/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/wuliheng/workspace/side-project/iam/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/wuliheng/workspace/side-project/iam/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/wuliheng/workspace/side-project/iam/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/wuliheng/workspace/side-project/iam/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    --------------------
    at Protocol._enqueue (/Users/wuliheng/workspace/side-project/iam/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/wuliheng/workspace/side-project/iam/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/wuliheng/workspace/side-project/iam/node_modules/knex/lib/dialects/mysql/index.js:134:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/wuliheng/workspace/side-project/iam/node_modules/knex/lib/dialects/mysql/index.js:128:12)
    at Client_MySQL.query (/Users/wuliheng/workspace/side-project/iam/node_modules/knex/lib/client.js:168:17)
    at /Users/wuliheng/workspace/side-project/iam/node_modules/knex/lib/transaction.js:325:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/Users/wuliheng/workspace/side-project/iam/node_modules/knex/lib/transaction.js:320:12)
    at Runner.query (/Users/wuliheng/workspace/side-project/iam/node_modules/knex/lib/runner.js:151:36)
```

**Comment by elhigu** [comment]
> Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE `user` (
>   `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '�' at line 2

Looks like the query where from your error message is coming from and query you have entered here are not the same... error says that your query has `COMMENT` part.

**Comment by JE-lee** [comment]
I have reduced my code for privacy。so this is the

> > Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE `user` (
> > `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '�' at line 2
> 
> Looks like the query where from your error message is coming from and query you have entered here are not the same... error says that your query has `COMMENT` part.

For privacy, I streamlined my code before. I have re-updated my question. 
You can reproduce that.

**Comment by elhigu** [comment]
You need to  enable multi-query support in mysql connection parameters. Also it may make your code vulnerable to SQL injection attacks. Check more info from mysql driver docs.
