### ISSUE TITLE
Initializing Knex doesn't work when using enviroment variable to select configuration

### ISSUE THREAD

**Issue by leo-holanda** [knex/knex#4440]
# Environment

Knex version: "^0.95.4"
Database + version: PG, "^8.5.1"
OS: Pop!_OS 20.10

# Bug

This is the first issue that I open in all my life so please if I did something wrong let me know. I tried everything I could before creating this issue.

I'm getting this error when I run my tests in Jest that connects with a Postgres DB through Knex.

```
 Test suite failed to run

    TypeError: Cannot read property 'client' of undefined

      1 | const knexfile = require('../../knexfile');
      2 | const enviroment = process.env.NODE_ENV || 'development';
    > 3 | const db = require('knex')(knexfile[enviroment]);
        |            ^
      4 |
      5 | module.exports = db;

      at resolveConfig (node_modules/knex/lib/knex-builder/internal/config-resolver.js:20:20)
      at knex (node_modules/knex/lib/knex-builder/Knex.js:10:39)
      at Object.<anonymous> (server/infra/database.js:3:12)
      at Object.<anonymous> (server/data/productsData.js:1:1)
```

This is the database.js file.

```
const knexfile = require('../../knexfile');
const enviroment = process.env.NODE_ENV || 'development';
const db = require('knex')(knexfile[enviroment]);

module.exports = db;
```
What is strange to me is when I console.log(knexfile[enviroment]) I get this:

```
{
  client: 'postgresql',
  connection: {
    host: 'localhost',
    port: '5432',
    database: 'edr_dev',
    user: 'postgres',
    password: 'postgres'
  },
  migrations: {
    tableName: 'knex_migrations',
    directory: '/home/leo/projects/Edroms/edroms-api/database/migrations'
  }
}
```
So It is not undefined. When I do this:
```
const knexfile = require('../../knexfile');
const enviroment = process.env.NODE_ENV || 'development';

const db = require('knex')({
	client: 'postgresql',
	connection: {
		host: 'localhost',
		port: '5432',
		database: 'edr_dev',
		user: 'postgres',
		password: 'postgres'
	},
	migrations: {
		tableName: 'knex_migrations',
		directory: '/home/leo/projects/Edroms/edroms-api/database/migrations'
	}
});

module.exports = db;
```
It works fine. And in Heroku this works fine too. It gets the process.env.NODE_ENV value.

I just don't know what to do. It is simply beyond my capabilities. What can I do to solve this problem? If you guys need more information please let me know and I will comment here.

**Comment by andrescellini** [comment]
can you show us the knexfile?

**Comment by leo-holanda** [comment]
Sure!
```
// Update with your config settings.
require('dotenv').config();

module.exports = {

	development: {
		client: 'postgresql',
		connection: {
			host: process.env.DEV_HOST,
			port: process.env.DEV_PORT,
			database: process.env.DEV_DATABASE,
			user: process.env.DEV_USER,
			password: process.env.DEV_PASSWORD,
		},
		migrations: {
			tableName: 'knex_migrations',
			directory: __dirname + '/database/migrations',
		},
	},

	production: {
		client: 'postgresql',
		connection: {
			connectionString: process.env.DATABASE_URL,
			ssl: {
				rejectUnauthorized: false
			}
		},
		migrations: {
			directory: __dirname + '/database/migrations',
		},
	}
};

```

**Comment by andrescellini** [comment]
if you hardcode "development" like const enviroment = 'development' what happend?

**Comment by leo-holanda** [comment]
With this
```
const knexfile = require('../../knexfile');
const enviroment = 'development';
const db = require('knex')(knexfile[enviroment]);

module.exports = db;
```
When I run yarn dev ("supervisor server/server.js") I get this in terminal
```
Running node-supervisor with
  program 'server/server.js'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node server/server.js'
Watching directory '/home/leo/projects/Edroms/edroms-api' for changes.
Press rs for restarting the process.
/home/leo/projects/Edroms/edroms-api/node_modules/knex/lib/knex-builder/internal/config-resolver.js:20
    (!parsedConfig.client && !parsedConfig.dialect)
                   ^

TypeError: Cannot read property 'client' of undefined
    at resolveConfig (/home/leo/projects/Edroms/edroms-api/node_modules/knex/lib/knex-builder/internal/config-resolver.js:20:20)
    at knex (/home/leo/projects/Edroms/edroms-api/node_modules/knex/lib/knex-builder/Knex.js:10:39)
    at Object.<anonymous> (/home/leo/projects/Edroms/edroms-api/server/infra/database.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/leo/projects/Edroms/edroms-api/server/data/ordersData.js:1:18)
Program node server/server.js exited with code 1
```
And it keeps repeating until I do Ctrl + C

**Comment by leo-holanda** [comment]
With this
```
const knexfile = require('../../knexfile');
const enviroment = 'development';
const db = require('knex')(knexfile[enviroment]);

module.exports = db;
```
It runs fine!

**Comment by andrescellini** [comment]
its a client side app that its builded before deploy? like react or vue? maybe running a dev env the NODE_ENV var its set, but after compiling and serve statics files its undefined.

**Comment by leo-holanda** [comment]
Yes, it's React! And I think you found what was causing the problem! I searched "React NODE_ENV" and found this [link](https://create-react-app.dev/docs/adding-custom-environment-variables/) that says that NODE_ENV is defined by default and I can't override it, and how its value change when using npm start, test and build. Must be something like this that is causing the problem. 

So, If I do:
```
const enviroment = process.env.DEV_ENV || process.env.NODE_ENV;
```
with DEV_ENV = development in dotenv file, everything works fine! In Heroku and in development.

Thank you so much for helping me!! I felt really stuck in that bug!

**Comment by parkerjgit** [comment]
Looks like there may be typo in run script that is resulting in NODE_ENV being set to `development'`.
changing:
```js
"dev": "cross-env 'NODE_ENV=development' 'DEBUG=speckle:*' nodemon ./bin/www --watch . --watch ./bin/www  -e js,graphql,env"
```
to 
```js
"dev": "cross-env NODE_ENV=development DEBUG=speckle:* nodemon ./bin/www --watch . --watch ./bin/www  -e js,graphql,env"
```
fixes issue for me.
