### ISSUE TITLE
Thrown undefined bindings promise does not carry the full stack in the error

### ISSUE THREAD

**Issue by jpike88** [knex/knex#4531]
# Environment

Knex version:0.95.6
Database + version:mysql 5.6
OS:macOS

This is a big issue that ends up wasting a lot of time fishing in production code for a specific query, rendering any error reporting tools next to useless.

I deliberately make this void line to force an uncaught promise:
<img width="723" alt="Screenshot 2021-06-21 at 11 53 22 AM" src="https://user-images.githubusercontent.com/9585787/122708837-48479200-d287-11eb-9d9a-dda50376a529.png">

I then have an uncaught promise handler, which should contain a full stack in the 'reason' object:
<img width="805" alt="Screenshot 2021-06-21 at 11 54 36 AM" src="https://user-images.githubusercontent.com/9585787/122708925-74fba980-d287-11eb-90f0-c8965e7b2932.png">

But it doesn't, it only goes as deep as ```builder-interface-augmenter```.
<img width="938" alt="Screenshot 2021-06-21 at 11 56 47 AM" src="https://user-images.githubusercontent.com/9585787/122709088-c310ad00-d287-11eb-8cd2-bd2f17331acf.png">

And looks like the asyncStackTraces is useless in this situation because the code doesn't even get that far.
<img width="895" alt="Screenshot 2021-06-21 at 11 55 29 AM" src="https://user-images.githubusercontent.com/9585787/122709053-aeccb000-d287-11eb-93b0-97a0e1b35813.png">

**Comment by jpike88** [comment]
@kibertoad thoughts?

**Comment by jpike88** [comment]
@kibertoad I understand you're a busy guy, but just your 5 cents on this would be appreciated.

**Comment by jpike88** [comment]
never mind I just realised why this is an issue, it's due to #2253

**Comment by jpike88** [comment]
reopening because this is still a problem, and the workaround I tried for some reason either never worked or doesn't work anymore. I've moved to postgres dialect and it's still present there. When I run into this issue it can literally wipe hours away while I hunt down the original code due to a useless stack trace. Can this please be elevated to issue number one it's such a huge pain with knex.

**Comment by naive17** [comment]
this is hugely relevant.
I have the same type of errors all the time and i need to snipe the query each time.
To me it happens every time a wrong column is referenced or a wrong type of input is given, really annoying

**Comment by mercmobily** [comment]
Hi! Thanks for reporting the stack trace problem — error clarity matters.

Short answer: I am 99% sure `asyncStackTraces: true` will solve the problem. Long story, and VERY long story, to follow.

Long story:

Knex captures an async call stack snapshot when `asyncStackTraces` is enabled and rewrites thrown errors to include a more helpful stack. The binding validation itself throws from the compiler when undefined bindings are detected. To get augmented stacks for those thrown errors, ensure `asyncStackTraces: true` is set in config. Relevant code: lib/util/save-async-stack.js:1–14 captures an error snapshot on builder/raw creation; lib/builder-interface-augmenter.js:17–43 intercepts `then()` and, on rejection, splices the async stack into the error’s stack (preserving `originalStack`). The undefined bindings errors originate in lib/query/querycompiler.js:138–154 (throws with a message that includes the compiled SQL) and lib/formatter/rawFormatter.js:21–33/67–77 for raw cases.

In the code: lib/builder-interface-augmenter.js:17–43 shows the error stack rewrite when `asyncStackTraces` is enabled. lib/query/querycompiler.js:138–154 throws `Undefined binding(s) detected when compiling …` including the SQL; lib/raw.js:104–121 throws `Undefined binding(s) detected for keys […] when compiling RAW query: …`.

Please enable `asyncStackTraces: true` in your Knex config during development to get enriched stacks for these promise rejections. If you already had it on and still see truncated stacks, we should investigate a minimal reproduction. A small improvement we can consider is including the saved async stack on synchronous validation throws as well, to unify behaviour.

VERY long story:

You can reproduce it with this:

Code used for reproduction (sandbox/4531_repro/repro.js):

```
const path = require('path');
const { setTimeout: delay } = require('timers/promises');
const knexFactory = require('../../knex');

async function runCase(asyncStacks) {
  console.log(`\n=== asyncStackTraces: ${asyncStacks} ===`);
  const knex = knexFactory({
    client: 'sqlite3',
    connection: { filename: ':memory:' },
    useNullAsDefault: true,
    asyncStackTraces: asyncStacks,
  });

  process.on('unhandledRejection', (reason) => {
    console.log('\n[unhandledRejection] reason.message =', reason && reason.message);
    console.log('[unhandledRejection] reason.stack:\n', reason && reason.stack);
  });

  // Create a thenable rejection by returning the builder from a then() chain
  // with an undefined binding to trigger compile-time validation error.
  Promise.resolve().then(() => {
    return knex('t').where({ id: undefined }).select('*');
  });

  await delay(100); // allow the unhandled rejection to surface
  await knex.destroy();
}

(async () => {
  await runCase(false);
  await runCase(true);
})();
```

Observed stack traces:

```
=== asyncStackTraces: false ===

[unhandledRejection] reason.message = Undefined binding(s) detected when compiling SELECT. Undefined column(s): [id] query: select * from `t` where `id` = ?
[unhandledRejection] reason.stack:
 Error: Undefined binding(s) detected when compiling SELECT. Undefined column(s): [id] query: select * from `t` where `id` = ?
    at QueryCompiler_SQLite3.toSQL (/home/merc/Development/forked/knex/lib/query/querycompiler.js:112:13)
    at QueryBuilder_SQLite3.toSQL (/home/merc/Development/forked/knex/lib/query/querybuilder.js:84:44)
    at ensureConnectionCallback (/home/merc/Development/forked/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
    at Runner.ensureConnection (/home/merc/Development/forked/knex/lib/execution/runner.js:318:20)
    at async Runner.run (/home/merc/Development/forked/knex/lib/execution/runner.js:30:19)

=== asyncStackTraces: true ===

[unhandledRejection] reason.message = Undefined binding(s) detected when compiling SELECT. Undefined column(s): [id] query: select * from `t` where `id` = ?
[unhandledRejection] reason.stack:
 Error: Undefined binding(s) detected when compiling SELECT. Undefined column(s): [id] query: select * from `t` where `id` = ?
    at Object.queryBuilder (/home/merc/Development/forked/knex/lib/knex-builder/make-knex.js:112:26)
    at createQueryBuilder (/home/merc/Development/forked/knex/lib/knex-builder/make-knex.js:320:26)
    at knex (/home/merc/Development/forked/knex/lib/knex-builder/make-knex.js:101:12)
    at /home/merc/Development/forked/knex/sandbox/4531_repro/repro.js:22:12

[unhandledRejection] reason.message = Undefined binding(s) detected when compiling SELECT. Undefined column(s): [id] query: select * from `t` where `id` = ?
[unhandledRejection] reason.stack:
 Error: Undefined binding(s) detected when compiling SELECT. Undefined column(s): [id] query: select * from `t` where `id` = ?
    at Object.queryBuilder (/home/merc/Development/forked/knex/lib/knex-builder/make-knex.js:112:26)
    at createQueryBuilder (/home/merc/Development/forked/knex/lib/knex-builder/make-knex.js:320:26)
    at knex (/home/merc/Development/forked/knex/lib/knex-builder/make-knex.js:101:12)
    at /home/merc/Development/forked/knex/sandbox/4531_repro/repro.js:22:12
```
