### ISSUE TITLE
Unable to CREATE USER with password using raw - syntax error at or near "$1"

### ISSUE THREAD

**Issue by cskeogh** [knex/knex#4537]
# Environment

Knex version: 0.95.6
Database + version: postgres 13.3.2
OS: Windows 10

# Bug

1. Unable to CREATE USER with password using `.raw`. Expected result is new user created.

2. Error message

```shell
C:\Users\craig\Projects\test-knex\node_modules\pg-protocol\dist\parser.js:287
        const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
                                                                                                 ^

error: CREATE USER "newuser" WITH ENCRYPTED PASSWORD $1 - syntax error at or near "$1"
    at Parser.parseErrorMessage (C:\Users\craig\Projects\test-knex\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket (C:\Users\craig\Projects\test-knex\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Users\craig\Projects\test-knex\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Users\craig\Projects\test-knex\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 91,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '47',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1180',
  routine: 'scanner_yyerror'
}
```

3. Reduced test code:

```javascript
import knex from 'knex';
const dbConfig = {
    'client': 'pg',
    'connection': process.env.PG_CONNECTION_STRING
};
const db = knex(dbConfig);

// below works OK, to demonstrate Knex and raw is working.
//   (Note: Don't use .raw to INSERT like below, instead use Knex insert
//    query, for example only)
await db.raw('INSERT INTO :tableName: (:columnName:) VALUES (:val)',
    {
        'tableName': 't11test',
        'columnName': 'data',
        'val': 'd'
    });

// named bindings fail with syntax error at or near "$1" (full error above)
await db.raw('CREATE USER :user: WITH ENCRYPTED PASSWORD :password',
     {
         'user': 'newuser',
         'password': 'secret'
     });
// positional bindings fail too with syntax error at or near "$1" (full error above)
await db.raw('CREATE USER ?? WITH ENCRYPTED PASSWORD ?', ['newuser', 'secret']);
```

Thank you for Knex.js!

**Comment by elhigu** [comment]
Looks like postgresql doesn't allow using parameter bindings for setting password of an user. So you need to validate password not being malicious and include it as part of sql string.

Closing as not being bug.
