### ISSUE TITLE
CLI fails when running typescript migrations without a knexfile

### ISSUE THREAD

**Issue by kieranmaine** [knex/knex#4538]
# Environment

Knex version: 0.95.6
Database + version: sqlite3
OS: windows

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

When running typescript migrations without a `knexfile.ts` file the migrations fail. The failing command is:
```
npx knex migrate:latest --client sqlite3 --connection ./dev.sqlite3 --migrations-directory migrations
```
2. Error message
```
Using environment: development
this.connectionSettings.filename ./dev.sqlite3
c:\Users\CODE_DIR\migrations\20210626175716_create_db.ts:1
import { Knex } from "knex";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at importFile (c:\Users\CODE_DIR\node_modules\knex\lib\migrations\util\import-file.js:12:7)
    at async c:\Users\CODE_DIR\node_modules\knex\lib\migrations\migrate\Migrator.js:86:39
    at async Promise.all (index 0)
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

Steps to reproduce:

* Run `knex migrate:make -x ts --migrations-directory migrations create_db`
* Update the generated file with the following migration:
```
import { Knex } from "knex";

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable("test_table", function (table) {
    table.increments("id").primary().notNullable();
    table.dateTime("the_date").notNullable();
  });
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTable("test_table");
}
```
* Run `knex migrate:latest --client sqlite3 --connection ./dev.sqlite3 --migrations-directory migrations`

**Comment by mercmobily** [comment]
You've discovered that TypeScript support only works when there's a knexfile.ts to trigger the TypeScript loader registration.
Without it, Knex doesn't know to load ts-node, so your TypeScript migrations fail with "Cannot use import statement".

This is an architectural limitation - Knex's loader system needs a TypeScript entry point to activate TypeScript support. We're
fixing this in #5800 by using tsx, which can be activated globally and doesn't need a specific trigger file.

Workaround without creating a knexfile:

```
  NODE_OPTIONS='--import tsx/esm' npx knex migrate:latest --client sqlite3 --connection ./dev.sqlite3 --migrations-directory
  migrations
```

Once #5800 is implemented, TypeScript migrations will work regardless of whether you have a knexfile or not.
