### ISSUE TITLE
SQLite column delete fails when column name contains special characters

### ISSUE THREAD

**Issue by rijkvanzanten** [knex/knex#4608]
# Environment

Knex version: 0.95.9
Database + version: SQLite 3.31.0
OS: macOS Big Sur

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

When dropping a column that has special characters in the name, like `*my_column:`, the operation will crash

```js
await knex.schema.alterTable('my_table', table => {
  table.dropColumn('*my_column:');
});
```

2. Error message
```
SyntaxError: Invalid regular expression: /\b* my_column:\b/: Nothing to repeat
    at new RegExp (<anonymous>)
    at /path/to/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:161:34
    at Array.map (<anonymous>)
    at SQLite3_DDL._doReplace (/path/to/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:145:17)
    at /path/to/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:300:29
    at Array.forEach (<anonymous>)
    at /path/to/node_modules/knex/lib/dialects/sqlite3/schema/ddl.js:298:21
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

https://runkit.com/rijkvanzanten/610d7c81beb083001be06b6b

---

@nickrum We should be able to easily fix this by escaping any illegal character in the regex source string using something like `_.escapeRegExp` from lodash https://lodash.com/docs/4.17.15#escapeRegExp

**Comment by OlivierCavadenti** [comment]
It seems this issue is resolved thanks to https://github.com/knex/knex/pull/4648 (the line that raise the error is refactored : https://github.com/knex/knex/pull/4648/files#diff-5f25c0fa1385a69dcdb2fdfc6a534146c0a945831dbede0e43be423c317c3a57L161)

You can try it here : https://runkit.com/embed/nofoablygsjn
