### ISSUE TITLE
Query is not executed and timeouts after ~16 minutes

### ISSUE THREAD

**Issue by amd032** [knex/knex#4630]
# Environment

Knex version: 0.95.10
Database + version: postgres, client pg@8.7.1, server PostgreSQL version 10
OS: node:12.22.3-alpine3.12

# Bug

There's a transactions started on the client side which is never executed on the server. BEGIN is visible in the knex logs on the client and is NOT visible in postgres server statement logs. Other transactions and queries are executed normally at the same time and are visible on client and servers logs. No other errors (except from the ones presented below) are visible on the client nor the server.
It happens ones per thousands of requests.
Such transaction is timedout after nearly 16 mintues, the time is always the same. 
Such timeouts appear also for queries outside a transactions, even for simple `select * from table`

The client logs:
```
2021-08-20T03:18:24.427Z knex:tx trx28575: Starting top level transaction
2021-08-20T03:18:24.427Z knex:client acquired connection from pool: __knexUid28569
2021-08-20T03:18:24.427Z knex:query BEGIN; trx28575
2021-08-20T03:18:24.427Z knex:bindings undefined trx28575
2021-08-20T03:34:03.926Z knex:tx trx28575 error running transaction query
2021-08-20T03:34:03.926Z knex:tx trx28575: releasing connection
2021-08-20T03:34:03.926Z knex:client releasing connection to pool: __knexUid28569
2021-08-20T03:34:03.927Z knex:tx trx28575: Transaction completed: select "data", "name", "_modifiedts" from "public"."table_name" where "id1" = ? and "name" = ? and "id2" = ? for update
2021-08-20T03:34:03.930Z knex:tx trx28575: Transaction completed: select "data", "name", "_modifiedts" from "public"."table_name" where "id1" = ? and "name" = ? and "id2" = ? for update
2021-08-20T03:34:03.931Z knex:tx trx28575: Transaction completed: insert into "public"."table_name" ("_modifiedts", "name", "data", "id2", "id1") values ('2021-08-20T03:18:24.426Z', 'name_value', '{"some":"json"}', 1, 2) ON CONFLICT (id1, name, id2) DO UPDATE SET data = ?, _modifiedts = ?
2021-08-20T03:34:03.932Z knex:tx trx28575: Transaction completed: ROLLBACK
2021-08-20T03:34:03.932Z knex:tx trx28575 error running transaction query
```
The error caught by our application for transaction is:
```
{	
	"name": "Error",
	"message": "Transaction query already complete, run with DEBUG=knex:tx for more info",
	"stack": "Error: Transaction query already complete, run with DEBUG=knex:tx for more info
	          at completedError (/src/node_modules/knex/lib/transaction.js:358:9)
			  at /src/node_modules/knex/lib/transaction.js:324:24
			  at new Promise (<anonymous>)
			  at Client_PG.trxClient.query (/src/node_modules/knex/lib/transaction.js:320:12)
			  at Runner.query (/src/node_modules/knex/lib/runner.js:151:36)
			  at Runner.wrappedQuery [as query] (/src/node_modules/elastic-apm-node/lib/instrumentation/modules/knex.js:54:23)
			  at /src/node_modules/knex/lib/runner.js:40:23
			  at /src/node_modules/knex/lib/runner.js:277:24
			  at elasticAPMCallbackWrapper (/src/node_modules/elastic-apm-node/lib/instrumentation/index.js:365:27)
			  at runMicrotasks (<anonymous>)
			  at processTicksAndRejections (internal/process/task_queues.js:97:5)"
}
```
The error caught by our application for a simple select is:
```
{
	"errno": "ETIMEDOUT",
	"code": "ETIMEDOUT",
	"syscall": "read",
	"name": "Error",
	"message": "select count(*) from \"schema_name\".\"table_name\" - read ETIMEDOUT",
	"stack": "Error: select count(*) from \"schema_name\".\"table_name\" - read ETIMEDOUT
			  at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)"
}
```

Is there anything else I can do to investigate it further?

**Comment by kibertoad** [comment]
@amd032 Can you share your code? Are you sure the transaction is correctly committed or rollbacked at the end?

**Comment by amd032** [comment]
I can share the code, but as I said, the long timeout may happen also outside the transaction, so I don't think it has something to do with this particular transaction handling. It just happens in this piece of the code, as it's executed most often and takes more time to finalize. I guess the probability is just higher here.

```
const trx = await db_connection.transaction()
await db_connection
    .withSchema('public')
    .from('table_name')
    .transacting(trx)
    .forUpdate()
    .select('data', 'name', '_modifiedts')
    .where({
        id1,
        name,
        id2
    })

...

const insertQuery = db_connection
    .withSchema('public')
    .from('table_name')
    .insert({
        id1,
        name,
        id2,
        _modifiedts: timestamp,
        data: dataJson
      })
      .toQuery()

await trx.raw(
        `${insertQuery} ON CONFLICT (id1, name, id2) DO UPDATE SET data = ?, _modifiedts = ?`,
        [dataJson, timestamp]
      )
```

Transaction is for sure not commited, because postgres server logs do NOT show any entry for this action. The BEGIN itself doesn't even reach the server.

**Comment by kibertoad** [comment]
Where is the `await trx.commit`? Also having catch block with `trx.rollback` is highly recommended.

**Comment by amd032** [comment]
Ah, sorry, forgot to paste it :) I updated my previous answer.
It really looks more or less like this
```
let trx
try {
  trx = await db_connection.transaction()
  ...
  trx.commit()
} catch (e) {
  if (trx) trx.rollback()
}
```
as you can see we don't use `await` for `trx.commit()` and `trx.rollback()` calls. Should we?

**Comment by kibertoad** [comment]
@amd032 Yes, definitely, both of them return promises.

**Comment by molomby** [comment]
I have something similar in the logs of an app running Knex [0.20.6](https://github.com/knex/knex/releases/tag/0.20.6), released late 2019.

I've been trying to understand an outage we had last week. Basically, the DB server dropped offline then, about 16-17 minutes later we have 80 `read ETIMEDOUT` errors as the 10 pooled connections across 8 threads all error out.

The DB itself was only offline for 2-3 minutes but this connection timeout meant the system to take closer to 20 mins to recover. I imagine we can prevent this in future by setting [query builder `.timeout()`](https://knexjs.org/#Builder-timeout) but, regardless, I'm interested to know where the current 16-17 minute timeout is coming from. (It's suspiciously close to 1000 seconds (16.66 minutes) but that line of investigation hasn't produced anything.)

Don't know the root cause of our DB outage yet but it appears to have simply dropped offline or restarted without warning. (It's RDS and we weren't logging events to CloudTrail). @amd032, I wonder if some connectivity glitch or transient networking problem may be the cause of your "once per thousands of requests" problem.

**Comment by amd032** [comment]
@molomby I was wondering about connectivity issues, but I have some incidents when our application begins two queries within the same millisecond, one of them succeeds, while the other one hangs.

I have modified my code, added missing `await` and `.timeout()` as suggested. None of that helped. The time in the log between `Transaction starting` and `Transaction started` is ~16 minutes. Postgres server log doesn't contain BEGIN at that time.
Can I somehow add a timeout to `.transaction()` call?

```
let trx
const queryTimeout = 5000

try {
	console.log('Transaction starting')
	trx = await db_connection.transaction()
	console.log('Transaction started')
	
	await db_connection
		.withSchema('public')
		.from('table_name')
		.transacting(trx)
		.forUpdate()
		.select('data', 'name', '_modifiedts')
		.where({
			id1,
			name,
			id2
		})
		.timeout(queryTimeout, { cancel: true })

	...

	const insertQuery = db_connection
		.withSchema('public')
		.from('table_name')
		.insert({
			id1,
			name,
			id2,
			_modifiedts: timestamp,
			data: dataJson
		  })
		  .toQuery()

	await trx
		.raw(
			`${insertQuery} ON CONFLICT (id1, name, id2) DO UPDATE SET data = ?, _modifiedts = ?`,
			[dataJson, timestamp]
		)
		.timeout(queryTimeout, { cancel: true })

	await trx.commit().timeout(queryTimeout, { cancel: true })
} catch (err) {
    if (trx) {
		await trx.rollback().timeout(queryTimeout, { cancel: true })
	}
}
```

**Comment by maximelkin** [comment]
Maybe you exhausted connection pool by some long txs?

**Comment by amd032** [comment]
In scenarios when pool is full I get a message `Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`
I don't think it's the case here. I have few hundreds queries per minute and one in a while one of them hangs for exactly 15-16 minutes.

**Comment by elhigu** [comment]
Please provide a reduced testcase that can reproduce the error. That code provided cannot be tested by anyone else. 

Also interpolating `${insertQuery}` the way it is done above if completely wrong and probably throws an error in DB side since the generated query will be ` "[object Object] ON CONFLICT (id1, name, id2) DO UPDATE SET data = ?, _modifiedts = ?"` https://runkit.com/embed/en80x1fx26uj

It should be done like this:

```
const insertQuery = db_connection
		.withSchema('public')
		.from('table_name')
		.insert({
			id1,
			name,
			id2,
			_modifiedts: timestamp,
			data: dataJson
		  });

await trx.raw(
			`? ON CONFLICT (id1, name, id2) DO UPDATE SET data = ?, _modifiedts = ?`,
			[insertQuery, dataJson, timestamp]
			)
```

**Comment by amd032** [comment]
@elhigu 
Thanks for the answer. I really appreciate it.
In your runkit you used `.toSQL()` call, we use `.toQuery()`. I guess it makes a difference, right?
`dataJson` is set to `JSON.stringify({ this: 'will', work: 'fine' })`

Now moving to the main point. It's rather impossible to provide a test to reproduce it. We see it only on our production environment, where the load is pretty heavy. And as I said in my original message: the issue seems to be not related to this particular piece of code. We see the same error (but with lower frequency) even for simple selects from DB, without any transaction involved.

**The main question is: where does this timeout for ~16 minutes come from and how to avoid it?**

**Comment by kibertoad** [comment]
@amd032 I've checked the code, and Knex itself only sets timeouts on rollback operations and on acquiring connections. All other timeouts are either included by users, or come from external factors.

I've looked up what PostgreSQL has to says about it, found this:
```
postgresql does not time out connections on the server side. It does
configure TCP_KEEPALIVE behavior on its sockets, so depending on kernel
configuration you might either have connections dropped at some interval
or not at all. 
```

Coming back to your earlier question. I don't think it's currently possible to set timeout on transaction initiation, but that shouldn't be too difficult to implement.
`lib/dialects/postgres/execution/pg-transaction.js` potentially could be wrapped into `timeout`, same way `lib/execution/transaction.js` does it for a rollback. Would you consider sending a PR for that? (it would have to come with tests and cover as many databases as possible)

**Comment by amd032** [comment]
@kibertoad I will consider creating a PR for `timeout` on transaction and let you know here.

However I have been digging more in this area and found out that ~16 minutes timeout comes from outside of our service. It seems that either IP stack in OS, or some external "device/service/router" is dropping the connection between PG client and PG server after this magic value of ~1000 seconds.

I have made an experiment when I set `query_timeout: 5000` in knex config options. It forces PG client to throw an error after 5 seconds of waiting for a response from PG server. When I run this code in our performance test, I have found 184 transactions in a row failing on BEGIN with the following message: `BEGIN; - Query read timeout`. 184 x 5 seconds = 920 seconds =~ 16 minutes!
This lead me to a conclusion that one particular connection from PG pool is somehow broken and not delivering requests to the PG server. However neither knex, nor pg-client know about that until this ~16 minutes timeouts. And even after `query_timeout` is reached, the same connection from the pool is being reused for subsequent requests.

The question now is: is there a way to identify and drop such particular unusable connection?

**Comment by mercmobily** [comment]
This issue is being tracked as part of #6241 (Connection and Pooling Meta-Issue). Timeout handling is closely related to connection and pool management.

**Comment by mercmobily** [comment]
Thank you for this detailed bug report with excellent logs. You've identified a serious and mysterious issue where queries (including transaction BEGIN statements) are never actually sent to the PostgreSQL server, yet appear in Knex's client-side logs, and then timeout after approximately 16 minutes.

The key observations from your logs:

1. **BEGIN is logged by Knex but never reaches PostgreSQL** - The server has no record of the BEGIN statement
2. **The timeout is consistently ~16 minutes** (939 seconds from 03:18:24 to 03:34:03)
3. **Other queries execute normally** - This happens intermittently (once per thousands of requests)
4. **The error is "Transaction query already complete"** rather than a clear timeout error
5. **Happens for both transactions and simple SELECT queries**

**Where the ~16 minute timeout comes from:**

This is likely the operating system's TCP keepalive timeout. When a connection is established but no data flows, the OS eventually kills the socket. The default TCP keepalive timeout on Linux is typically 7200 seconds (2 hours), but your system appears configured for ~940 seconds (~16 minutes). This is not a Knex, pg, or PostgreSQL timeout - it's the TCP layer giving up on the connection.

**Root cause hypothesis:**

The connection is somehow in a broken state where:
- Knex believes the connection is active and tries to send queries
- The TCP socket is actually dead/stalled, so queries never leave the client
- No error is detected until the TCP keepalive expires
- This creates the illusion that the query is "in flight" for 16 minutes

This could be caused by:
1. **Network issues** - Firewalls, load balancers, or network interruptions silently dropping the connection
2. **Connection pool corruption** - The pool returning a dead connection that it believes is alive
3. **PostgreSQL server closing the connection** without properly notifying the client
4. **Client-side socket state issues** - The pg driver's socket becoming unwritable

**Investigation steps:**

1. **Enable TCP keepalive with shorter intervals** in your connection config:
```javascript
{
  connection: {
    keepAlive: true,
    keepAliveInitialDelayMillis: 10000, // 10 seconds
  }
}
```

2. **Check your network infrastructure** - Firewalls, proxies, or load balancers might be silently dropping idle connections

3. **Monitor PostgreSQL server logs** for unexpected connection closures

4. **Check for pg driver updates** - There may be socket state bugs in pg@8.7.1

This issue has been added to our Connection and Pooling META issue #6241, where we are tracking all connection lifecycle and pool management problems. This is a classic example of the connection pool containing a dead connection that hasn't been properly detected and removed.

The connection pool should:
1. Detect when connections are dead before trying to use them
2. Remove dead connections from the pool
3. Provide clear error messages when queries fail due to connection issues
4. Not report "Transaction query already complete" when the real issue is a network timeout

This issue will remain open and tracked under META #6241.

Related issues:
- #6241 - Connection and Pooling META issue
- #5186 - Postgres connections not released when server closes them
- #3523 - Connection terminated unexpectedly
- #3447 - Connection reset after idle time

**Comment by miszczu-drako** [comment]
I have seen exactly the same sympthoms, i.e. ~16 minutes query read timeout few years back. Our solution, or rather work around, was to set the following configuration for knex:
```js
  const connection = knex({
    client: 'pg',
    connection: {
      database,
      host,
      password,
      user,
      ssl,
      statement_timeout: 4000,
      query_timeout: 4500,
      idle_in_transaction_session_timeout: 2000,
      keepAlive: true,
      keepAliveInitialDelayMillis: 30000,
      application_name: applicationName
    },
    pool: {
      acquireTimeoutMillis: 4000,
      min: 10,
      max: 10
    }
  })
```
The timeouts still happen from time to time, however they are visible quick enough to take some appropriate and immediate action
The most important and not so obvious change was to set min and max pool to the same value. We observed that connections get into a "broken" state when they are returned to the pool and then immediately taken from it. When number of connections never drops, the main issue disappeared.

**Comment by mercmobily** [comment]
Ugh. This is honestly one of the very first thing we are going to get our hands on when we finish the big triaging job (which is nearly finished!)
