### ISSUE TITLE
[BUG] Docker sqlite3

### ISSUE THREAD

**Issue by MegaNoam** [knex/knex#4634]
Knex version: `0.95.6`
Database + version: `sqlite3: "5.0.2"`
OS: `node:12.2.0-alpine`

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @smorey2.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do:

I am trying to run Docker which contains **knex in version 0.95.6** together with **sqllite3 in version 5.0.2**
As soon as I run the Docker I get a strange error, I added the error log from the Docker logs

2. Error message:
```
> my-project@1.0.0 start /app
> node app.js

Knex: run
$ npm install sqlite3 --save
Cannot find module '/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node'
Require stack:
- /app/node_modules/sqlite3/lib/sqlite3-binding.js
- /app/node_modules/sqlite3/lib/sqlite3.js
- /app/node_modules/knex/lib/dialects/sqlite3/index.js
- /app/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /app/node_modules/knex/lib/knex-builder/Knex.js
- /app/node_modules/knex/lib/index.js
- /app/node_modules/knex/knex.js
- /app/config/database.js
- /app/app.js
Error: Cannot find module '/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node'
Require stack:
- /app/node_modules/sqlite3/lib/sqlite3-binding.js
- /app/node_modules/sqlite3/lib/sqlite3.js
- /app/node_modules/knex/lib/dialects/sqlite3/index.js

/app/node_modules/knex/lib/client.js:182
      throw new Error(`${message}\n${e.message}`);
      ^

Error: Knex: run
$ npm install sqlite3 --save
Cannot find module '/app/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node'
Require stack:
- /app/node_modules/sqlite3/lib/sqlite3-binding.js
- /app/node_modules/sqlite3/lib/sqlite3.js
- /app/node_modules/knex/lib/dialects/sqlite3/index.js
- /app/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /app/node_modules/knex/lib/knex-builder/Knex.js
- /app/node_modules/knex/lib/index.js
- /app/node_modules/knex/knex.js
- /app/config/database.js
- /app/app.js
    at Client_SQLite3.initializeDriver (/app/node_modules/knex/lib/client.js:182:13)
    at new Client (/app/node_modules/knex/lib/client.js:71:12)
    at new Client_SQLite3 (/app/node_modules/knex/lib/dialects/sqlite3/index.js:20:5)
    at knex (/app/node_modules/knex/lib/knex-builder/Knex.js:12:28)
    at Object.<anonymous> (/app/config/database.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ms-node-passport@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ms-node-passport@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-22T02_47_27_119Z-debug.log

- /app/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /app/node_modules/knex/lib/knex-builder/Knex.js
- /app/node_modules/knex/lib/index.js
- /app/node_modules/knex/knex.js
- /app/config/database.js
- /app/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/app/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
```

**Comment by kibertoad** [comment]
Did you manage to resolve the problem? I think it was related to failing to install dependencies, not to knex itself.

**Comment by wajeht** [comment]
> Did you manage to resolve the problem? I think it was related to failing to install dependencies, not to knex itself.

add a `.dockerignore` to include `node_modules`
```
.tmp/
.cache/
.git/
build/
node_modules/
.env
data/
`
