### ISSUE TITLE
limit not working from MS SQL 2000

### ISSUE THREAD

**Issue by SimplyKot** [knex/knex#4704]
# Environment

Knex version: 0.95.11
Database: MS SQL 2000
OS: Windows 10

# Bug

1.  Using LIMIT in simple query causes error

2.   RequestError: select top (@p0) [firmid] from [firm] - Line 1: Incorrect syntax near '('.
      at Parser.<anonymous> (F:\_dev_\misgkh-api\node_modules\tedious\lib\connection.js:1160:27)
      at Parser.emit (events.js:400:28)
      at Readable.<anonymous> (F:\_dev_\misgkh-api\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
      at Readable.emit (events.js:400:28)
      at addChunk (internal/streams/readable.js:290:12)
      at readableAddChunk (internal/streams/readable.js:265:9)
      at Readable.push (internal/streams/readable.js:204:10)
      at next (internal/streams/from.js:88:29)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

3.  testDB('firm')
    .select('firmid')
    .offset(0)
    .limit(100)

**Comment by mercmobily** [comment]
SQL Server 2000 has very limited support for `LIMIT`/`OFFSET` patterns.

Knex’s MSSQL dialect targets modern SQL Server versions; for SQL Server 2000 specifically, `OFFSET` is unsupported and even `TOP` requires a literal rather than a parameter in some contexts, which is why `select top (@p0) ...` fails on SQL Server 2000.

If you must target SQL Server 2000, you’ll need to avoid `.offset()` and emulate pagination using keyset pagination or `ROWCOUNT`, or upgrade the database. The underlying driver (`tedious`) and Knex do not officially support SQL Server 2000.
