### ISSUE TITLE
Handling of query read timeout in PG transaction BEGIN is not consistent

### ISSUE THREAD

**Issue by miszczu-drako** [knex/knex#4709]
# Environment

Knex version: 0.95.10
Database + version: postgres, client pg@8.7.1, server PostgreSQL version 10
OS: node:12.22.3-alpine3.12

# Bug
I have been playing around with `query_timeout` recently and spotted that timeout during transaction BEGIN behaves differently for `.transaction()` and `.transaction(handlerFunc)`
To make it easily reproducible I have modified my `node_modules/pg/lib/client.js` code in method `query` adding this code before `if (readTimeout) {` condition:
```
  if (query.text.includes('BEGIN')) {
    console.log('#### Setting 1 msec timeout for BEGIN')
    readTimeout = 1
  }
```

My simple transaction code samples are:
Version 1:
```
let trx
try {
  trx = await db_connection.transaction()
  await trx.raw('SELECT col FROM tbl')
  await trx.commit()
} catch (exception) {
  if (trx) await trx.rollback()
}
```

Version 2:
```
const selectFunc = async (trx) => {
  await trx.raw('SELECT col FROM tbl')
}
await db_connection.transaction(selectFunc)
```

Version 1 returns a valid trx object, however `trx.raw` call on it throws an Error
```
{
	"name": "Error",
	"message": "Transaction query already complete, run with DEBUG=knex:tx for more info",
	"stack": "Error: Transaction query already complete, run with DEBUG=knex:tx for more info
				at completedError (/src/node_modules/knex/lib/execution/transaction.js:396:9)
				at /src/node_modules/knex/lib/execution/transaction.js:362:24
				at new Promise (<anonymous>)
				at Client_PG.trxClient.query (/src/node_modules/knex/lib/execution/transaction.js:358:12)
				at Runner.query (/src/node_modules/knex/lib/execution/runner.js:130:36)
				at ensureConnectionCallback (/src/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
				at Runner.ensureConnection (/src/node_modules/knex/lib/execution/runner.js:272:20)
				at processTicksAndRejections (internal/process/task_queues.js:97:5)
				at async Runner.run (/src/node_modules/knex/lib/execution/runner.js:30:19)
				at async Object.exports.getData (/src/models/postgreSQL/myTable.js:42:22)"
}
```
I have also checked that `trx.isCompleted()` returns `true` in this case

Version 2 throws an Error, but different:
```
{
	"name": "Error",
	"message": "BEGIN; - Query read timeout",
	"stack": "Error: BEGIN; - Query read timeout    
				at Timeout._onTimeout (/src/node_modules/pg/lib/client.js:533:21)
				at listOnTimeout (internal/timers.js:554:17)
				at processTimers (internal/timers.js:497:7)"
}
```

From my perspective the 2nd version behaves more accurate to me. The 1st one hides query timeout and instead returns a completed transaction object.

Is it a bug or feature?

**Comment by mercmobily** [comment]
This issue is being tracked as part of #6241 (Connection and Pooling Meta-Issue). Timeout handling is closely related to connection and pool management.

**Comment by mercmobily** [comment]
Thank you for this detailed bug report. You've identified an important inconsistency in how Knex handles query timeouts during transaction BEGIN between the two transaction API styles.

The issue is that when a timeout occurs during the `BEGIN` statement of a transaction, the two transaction APIs behave very differently:

**Version 1: `await knex.transaction()` (manual transaction)**
- Returns a transaction object even though BEGIN timed out
- The transaction is silently marked as completed due to the timeout
- Subsequent queries on this transaction object throw "Transaction query already complete"
- The real timeout error is hidden from the user
- This is problematic because the user doesn't know why the transaction appears completed

**Version 2: `await knex.transaction(handlerFunc)` (callback transaction)**
- Throws the actual timeout error: "BEGIN; - Query read timeout"
- The user immediately knows what went wrong
- This is the correct behaviour

The first version is clearly buggy - it should throw the timeout error just like the second version does, rather than silently marking the transaction as completed and returning a seemingly valid transaction object that will fail on any subsequent operation.

This inconsistency makes error handling unpredictable depending on which transaction API you use. Users expect both APIs to behave the same way, especially for error conditions.

This issue has been added to our Connection and Pooling META issue #6241, where we are tracking all connection lifecycle and pool management problems. Timeout handling during transaction operations is a connection management concern because:

- Transaction BEGIN failures should properly release the connection back to the pool
- Error propagation needs to be consistent across both transaction APIs
- Timeout errors during BEGIN indicate connection or database issues that users need to be aware of

The correct behaviour should be:
1. Both transaction APIs should throw the timeout error when BEGIN times out
2. The connection should be properly cleaned up and returned to the pool
3. No transaction object should be returned if BEGIN failed

This issue will remain open and tracked under META #6241.

Related issues:
- #6241 - Connection and Pooling META issue
- #5434 - Timeout not preserved in clone()
- #4630 - Query timeouts after ~16 minutes
- #4423 - Migration statement timeout errors
