### ISSUE TITLE
No error handling for tedious error "ESOCKET"on connection

### ISSUE THREAD

**Issue by jamescammarano** [knex/knex#4735]
# Environment
knex: 0.95.11
tedious: 13.1.0
MSSQL

OS:
MacOS

For MSSql tag @smorey2.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Currently on connection to an MSSQL database through tedious I get an error during connection.

I would expect knex to be able to handle the connection and fail gracefully on socket error.

2. Error message
```
 return new ConnectionError(message, code);
           ^
ConnectionError: Connection lost - unexpected end of message stream
    at ConnectionError (/path/node_modules/tedious/lib/errors.js:13:12)
    at Connection.socketError (/path/node_modules/tedious/lib/connection.js:1381:54)
    at /path/node_modules/tedious/lib/connection.js:2378:14
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on Connection instance at:
    at Connection.emit /path/node_modules/tedious/lib/connection.js:1031:18)
    at Connection.socketError (/path/node_modules/tedious/lib/connection.js:1381:12)
    at /path/node_modules/tedious/lib/connection.js:2378:14
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ESOCKET
  ```

**Comment by kibertoad** [comment]
Would you consider sending PR for this?

**Comment by rijkvanzanten** [comment]
I'm wondering if it's because we only attach the on error event handler in the callback of the "connect" method here:

https://github.com/knex/knex/blob/2b1e37ca44bbd75ced9ca7367e6c6bacebe599e7/lib/dialects/mssql/index.js#L142-L164

It could be that the connection fails for whatever reason before it gets to that callback, which is then no longer caught by Knex. Could be a bug in Tedious as well, as I would've expected that error to exist in the "err" object in that callback param in that case, but I digress.

Haven't confirmed this to be the case, but could be a good first angle to test with @jaycammarano

**Comment by serbanmarti** [comment]
Is anyone still working to fix this?

**Comment by kibertoad** [comment]
don't think so, feel free to send a PR!

**Comment by mercmobily** [comment]
Adding additional information from #6106:

This issue also affects two specific scenarios that cause the application to crash:

1. **Connecting with MSSQL client to a PostgreSQL server** (wrong client type) - This causes a "Socket hang up" error that crashes the entire Node.js process
2. **Connecting with wrong password** - Authentication errors also cannot be caught with try/catch and crash the server

Both scenarios produce errors during the connection handshake that are emitted as error events on the connection object before the error handler is attached, making them unhandled errors that crash the process.

This is particularly problematic for applications that allow users to switch between databases manually, as configuration mistakes can bring down the entire server. The errors cannot be caught even when wrapping connection attempts in try/catch blocks.

These are important test cases to include when implementing a fix for this issue.
