### ISSUE TITLE
Certain Knex + sqlite3 + jest configuration - produces "this.driver.Database is not a constructor"

### ISSUE THREAD

**Issue by flash548** [knex/knex#4746]
# Environment

Knex version: 0.95.11
Database + version: sqlite3 / 5.0.2
OS: MacOS

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

With jest option `moduleDirectories` set to search `[ "node_modules", "." ]` sqlite3 cannot get/make a connection because the dialect class does a `require('sqlite3')` which fails because the dialect file is named `sqlite3.js` and is imported instead of the `node_modules/sqlite3` library.

2. Error message: 
```
    TypeError: this.driver.Database is not a constructor

      at node_modules/knex/lib/dialects/sqlite3/index.js:80:18
      at Client_SQLite3.acquireRawConnection (node_modules/knex/lib/dialects/sqlite3/index.js:64:12)
      at create (node_modules/knex/lib/client.js:237:39)
```

3. Test code here to show/reproduce bug - https://github.com/flash548/knex-test - which can be shown with running `npm test` within this project.  The workaround is that I don't have "." in the `moduleDirectories` of the jest config anymore.

**Comment by kibertoad** [comment]
How do you suggest fixing it? I'm not sure one can require node_module in any other way.

**Comment by flash548** [comment]
1. Can you refactor the name of the sqlite3 dialect file?  To like `sqlite` or `sqlite3-dialect.js`?
-or-
2. You can specify `require('node_modules/sqlite3')` which forces it to look there first, but that's kinda hacky.
-or-
3. I guess just list it as a known issue for now for those that have this offending jest config.

**Comment by flash548** [comment]
err I mean 3 changes - 
- folder name change
- SUPPORTED_CLIENTS edit
- and the config `client` field named to `sqlite-3`

**Comment by mercmobily** [comment]
@kibertoad Do you happen to remember what the fix was? It was only 4 years and 10 days ago :D

This is likely a module resolution collision; the `sqlite3` dialect folder name shadowing the `sqlite3` package under certain resolver settings. A permanent fix requires a breaking rename in Knex; in the meantime, workarounds exist.

@kibertoad Was your solution the simple renaming?

With `moduleDirectories` including `'.'`, `require('sqlite3')` from `lib/dialects/sqlite3/index.js:22` can resolve to the local dialect folder named `sqlite3` instead of the `sqlite3` package. That leads to `this.driver.Database` being undefined and the “Database is not a constructor” error at `lib/dialects/sqlite3/index.js:64–82`.

Workarounds:
- Adjust Jest config to remove `'.'` from `moduleDirectories` for code that initialises Knex.
- Use a custom `moduleNameMapper` to force `sqlite3` to resolve to `node_modules/sqlite3`.

Path forward in Knex : I assume it's just a rename of the dialect folder to avoid shadowing (e.g. `sqlite` or `sqlite-3`) and adjust `SUPPORTED_CLIENTS` accordingly. As noted in the thread, this would be a semver‑major change.
