### ISSUE TITLE
Support filetype .cjs for knexfile

### ISSUE THREAD

**Issue by VladRabota** [knex/knex#4819]
# Environment

Knex version: ^0.95.14
Database + version: mysql2
OS: Ubuntu 20.04
Node version: 16.13.0

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Hi, i am pretty new to programming, so i apologize if this issue didn't make sense.
So, at my current project i need to use ESModules and i have `"type": "module",` in my package.json file.
When i run `npx knex init` all fine, knexfile.js is created. But when i run `npx knex migrate:make test-migration` i get this message: 
```
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/vlad/nodejs/main-project-side/prototype1/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```
So i followed message and renamed knexfile.js to knexfile.cjs. I run `npx knex migrate:make test-migration` and get this message instead: 
```
Failed to resolve config file, knex cannot determine where to generate migrations
The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.resolve (node:path:1098:7)
    at /home/vlad/nodejs/main-project-side/prototype1/node_modules/knex/lib/migrations/migrate/MigrationGenerator.js:77:19
    at Array.map (<anonymous>)
    at MigrationGenerator._absoluteConfigDirs (/home/vlad/nodejs/main-project-side/prototype1/node_modules/knex/lib/migrations/migrate/MigrationGenerator.js:71:24)
    at MigrationGenerator._ensureFolder (/home/vlad/nodejs/main-project-side/prototype1/node_modules/knex/lib/migrations/migrate/MigrationGenerator.js:28:23)
    at MigrationGenerator.make (/home/vlad/nodejs/main-project-side/prototype1/node_modules/knex/lib/migrations/migrate/MigrationGenerator.js:20:16)
    at Migrator.make (/home/vlad/nodejs/main-project-side/prototype1/node_modules/knex/lib/migrations/migrate/Migrator.js:314:27)
    at Command.<anonymous> (/home/vlad/nodejs/main-project-side/prototype1/node_modules/knex/bin/cli.js:218:10)
```
I didn't find on internet anything that helped me, so i dig down in knex source code. I find that in file [https://github.com/knex/knex/blob/master/bin/cli.js](https://github.com/knex/knex/blob/master/bin/cli.js) at line 67 filetypes didn't have 'cjs', so i added it and now migrations works fine for me. I changed line `const filetypes = ['js', 'coffee', 'ts', 'eg', 'ls'];` to this `const filetypes = ['js', 'coffee', 'ts', 'eg', 'ls', 'cjs'];`

**Comment by VladRabota** [comment]
If path to knexfile is specified, like this `npx knex migrate:latest --knexfile knexfile.cjs`, then I can run migrations without changes to knex source code.
