### ISSUE TITLE
Error running migration

### ISSUE THREAD

**Issue by GustavoContreiras-Feegow** [knex/knex#4894]
# Environment

Knex version: 0.95.11
Database + version: mysql 8.0
OS: macos

```
exports.up = function(knex) {
    return knex.schema.alterTable('email_contact', function (table) {
        table.renameColumn('verified', 'confirmed');
    });
};

exports.down = function(knex) {
    return knex.schema.alterTable('email_contact', function (table) {
        table.renameColumn('confirmed', 'verified');
    });
};

```
```
migration file "20211117134036_rename_column_verified_to_confirmed_email_contact.js" failed
migration failed with error: SELECT KCU.CONSTRAINT_NAME, KCU.TABLE_NAME, KCU.COLUMN_NAME,        KCU.REFERENCED_TABLE_NAME, KCU.REFERENCED_COLUMN_NAME,        RC.UPDATE_RULE, RC.DELETE_RULE FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS RC        USING(CONSTRAINT_NAME)WHERE KCU.REFERENCED_TABLE_NAME = 'email_contact'   AND KCU.CONSTRAINT_SCHEMA = 'messaging_homolog'   AND RC.CONSTRAINT_SCHEMA = 'messaging_homolog' - ER_QUERY_TIMEOUT: Query execution was interrupted, maximum statement execution time exceeded
SELECT KCU.CONSTRAINT_NAME, KCU.TABLE_NAME, KCU.COLUMN_NAME,        KCU.REFERENCED_TABLE_NAME, KCU.REFERENCED_COLUMN_NAME,        RC.UPDATE_RULE, RC.DELETE_RULE FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS RC        USING(CONSTRAINT_NAME)WHERE KCU.REFERENCED_TABLE_NAME = 'email_contact'   AND KCU.CONSTRAINT_SCHEMA = 'messaging_homolog'   AND RC.CONSTRAINT_SCHEMA = 'messaging_homolog' - ER_QUERY_TIMEOUT: Query execution was interrupted, maximum statement execution time exceeded
Error: ER_QUERY_TIMEOUT: Query execution was interrupted, maximum statement execution time exceeded
    at Query.Sequence._packetToError (/Users/feegow/dev/feegow-messaging-service/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/feegow/dev/feegow-messaging-service/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/feegow/dev/feegow-messaging-service/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/feegow/dev/feegow-messaging-service/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/feegow/dev/feegow-messaging-service/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/feegow/dev/feegow-messaging-service/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/feegow/dev/feegow-messaging-service/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/feegow/dev/feegow-messaging-service/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    --------------------
    at Protocol._enqueue (/Users/feegow/dev/feegow-messaging-service/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/feegow/dev/feegow-messaging-service/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/feegow/dev/feegow-messaging-service/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/feegow/dev/feegow-messaging-service/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/Users/feegow/dev/feegow-messaging-service/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/feegow/dev/feegow-messaging-service/node_modules/knex/lib/client.js:134:12)
    at /Users/feegow/dev/feegow-messaging-service/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/Users/feegow/dev/feegow-messaging-service/node_modules/knex/lib/execution/transaction.js:358:12)
```

I like Knex but it's so full of errors....

**Comment by GustavoContreiras-Feegow** [comment]
Somehow this was fixed just by trying again and again and again..

**Comment by kibertoad** [comment]
Not a knex issue. Judging by the error, it was a timeout due to a long-running operation.
