### ISSUE TITLE
Knex 0.21.1 not playing nicely with webpack

### ISSUE THREAD

**Issue by dwjohnston** [knex/knex#4921]
# Environment

Knex version: 0.21.1
Database + version: Any/All
OS: MacOS 

# Bug

Knex not playing nicely with webpack. 

I have a repro for this issue here: 

https://github.com/dwjohnston/knex-webpack-issue/tree/main/take2

For a simple application like: 

```javascript
import knex from "knex"; 

const myKnexConfig = {
    client: 'postgresql',
    connection: "someconnection",
    pool: {
        min:1, 
        max: 2
    }
  };

const knexConnecion = knex(myKnexConfig);
```

When webpacked up and ran, you will get an error like: 

```
MAC-DJOHNSTON:take2 djohnston$ node dist/main.js
webpack://my-webpack-project/./node_modules/knex/lib/dialects/_sync_^\.\/.*\/index\.js$?:4
	throw e;
	^

Error: Cannot find module './postgresql/index.js'
    at webpackEmptyContext (webpack://my-webpack-project/./node_modules/knex/lib/dialects/_sync_^\.\/.*\/index\.js$?:2:10)
    at Knex (webpack://my-webpack-project/./node_modules/knex/lib/knex.js?:44:109)
    at eval (webpack://my-webpack-project/./src/index.ts?:13:64)
    at Object../src/index.ts (/Users/djohnston/git/knex-webpack-issue/take2/dist/main.js:3301:1)
    at __webpack_require__ (/Users/djohnston/git/knex-webpack-issue/take2/dist/main.js:3559:41)
    at /Users/djohnston/git/knex-webpack-issue/take2/dist/main.js:3635:37
    at Object.<anonymous> (/Users/djohnston/git/knex-webpack-issue/take2/dist/main.js:3637:12)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32) {
  code: 'MODULE_NOT_FOUND'
}
```

This appears to be the way that webpack resolves that dynamic require: 

```
require(`./dialects/${resolvedClientName}/index.js`);
```
[Link to source code](https://github.com/knex/knex/blob/0.21.1/lib/knex.js#L44)

**Comment by dwjohnston** [comment]
This issue also occurs in knex 0.21.17

**Comment by dwjohnston** [comment]
Possibly a dupe of this issue: https://github.com/knex/knex/issues/3542

**Comment by mercmobily** [comment]
Hi! Thanks for the minimal repro. This is a duplicate of #6242 (Document bundler solutions and add clean dialect entrypoints — NG_documentation). We’ll close this in favour of that one.

Not covered in the meta: your repro shows webpack failing to include the dynamically required dialect path. I will reference that repro in #6242 so it’s captured as a concrete case.

Please track updates in #6242; that ticket will own the final guidance and any follow‑up changes.
