### ISSUE TITLE
Getting column "1" does not exist when passing bigint to knex.raw query

### ISSUE THREAD

**Issue by lancejpollard** [knex/knex#4935]
Not sure if I am doing something wrong or if this is an issue, so I thought I would post.

I have this JS:

```js
const UPDATE = `
UPDATE my_table
SET some_bigint = :someBigInt:
WHERE some_id = :someId:
  AND other_id = :otherId:;
`

await knex.raw(UPDATE, {
  someId,
  otherId,
  someBigInt: 1n
})
```

Then I am getting this error on the latest knex (0.95.15).

```
UPDATE my_table
SET some_bigint = "1"
WHERE some_int_id = 0
  AND other_int_id = 0;
 - column "1" does not exist
    at Parser.parseErrorMessage (/Users/my/test/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/my/test/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/my/test/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/my/test/node_modules/pg-protocol/dist/index.js:11:42)
```

Is this an issue with bigints in the raw query, or something I'm doing wrong?

**Comment by kibertoad** [comment]
i think you need to wrap number in knex.raw to avoid it bein interpreted as a column name there

**Comment by kibertoad** [comment]
why do you use raw there in the first place, btw?

**Comment by lancejpollard** [comment]
Yeah haha I realize I can just use `knex().update`.
