### ISSUE TITLE
better-sqlite3: migrations with consecutive changes to same table fail with “SQL logic error”

### ISSUE THREAD

**Issue by tkalliom** [knex/knex#4947]
# Environment

Knex version: 1.0.1
Database + version: sqlite3 3.34.1
OS: Linux

# Bug
Migrations with multiple consecutive changes to the same table (workaround to #4450) fail with the error message `SQL logic error` when using the new better-sqlite3 driver support. For the below code:

```js
const Knex = require('knex');

const knex = Knex({
  client: 'better-sqlite3',
  connection: 'test.db'
});

(async function run() {
  // first migration
  await knex.schema.createTable('events', t => {
    t.string('id').primary();
    t.enu('action', ['activation']);
  });

  // second migration
  await knex.schema.alterTable('events', t => {
    t.dropColumn('action');
  });
  await knex.schema.alterTable('events', t => {
    t.enu('action', ['activation', 'cancellation'])
  });
})();
```
the following  output is produced:
```
knex:query create table `events` (`id` varchar(255), `action` text check (`action` in ('activation')), primary key (`id`)) undefined +0ms
knex:query PRAGMA table_info(`events`) undefined +1ms
knex:query BEGIN; trx2 +1ms
knex:query SELECT type, sql FROM sqlite_master WHERE (type='table' OR (type='index' AND sql IS NOT NULL)) AND tbl_name='events' trx2 +0ms
knex:query COMMIT; trx2 +0ms
knex:query PRAGMA foreign_keys trx2 +4ms
knex:query PRAGMA foreign_keys = OFF trx2 +0ms
knex:query BEGIN; trx3 +0ms
knex:query CREATE TABLE `_knex_temp_alter138` (`id` varchar(255), PRIMARY KEY (`id`)) trx3 +0ms
knex:query INSERT INTO "_knex_temp_alter138" SELECT "id" FROM "events"; trx3 +0ms
knex:query DROP TABLE "events" trx3 +1ms
knex:query ALTER TABLE "_knex_temp_alter138" RENAME TO "events" trx3 +0ms
knex:query PRAGMA foreign_key_check trx3 +0ms
knex:query COMMIT; trx3 +0ms
knex:query PRAGMA foreign_keys = ON trx3 +0ms
knex:query alter table `events` add column `action` text check (`action` in ('activation', 'cancellation')) trx3 +0ms
(node:41249) UnhandledPromiseRejectionWarning: SqliteError: alter table `events` add column `action` text check (`action` in ('activation', 'cancellation')) - SQL logic error
    at Database.prepare (/tmp/abc/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at Client_BetterSQLite3._query (/tmp/abc/node_modules/knex/lib/dialects/better-sqlite3/index.js:30:34)
    at executeQuery (/tmp/abc/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/tmp/abc/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/tmp/abc/node_modules/knex/lib/execution/runner.js:130:36)
    at Runner.queryArray (/tmp/abc/node_modules/knex/lib/execution/runner.js:224:21)
    at ensureConnectionCallback (/tmp/abc/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19)
    at Runner.ensureConnection (/tmp/abc/node_modules/knex/lib/execution/runner.js:307:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

This used to work with knex 0.95 and the old `sqlite3` driver. For comparison, here is the output for a successful run of the same migration code with 0.95+sqlite3:
```
knex:query create table `events` (`id` varchar(255), `action` text check (`action` in ('activation')), primary key (`id`)) undefined +0ms
knex:query PRAGMA table_info(`events`) undefined +1ms
knex:query BEGIN; trx2 +1ms
knex:query SELECT type, sql FROM sqlite_master WHERE (type="table" OR (type="index" AND sql IS NOT NULL)) AND tbl_name="events" trx2 +1ms
knex:query CREATE TABLE `_knex_temp_alter307` (`id` varchar(255), PRIMARY KEY (`id`)) trx2 +5ms
knex:query INSERT INTO _knex_temp_alter307 SELECT "id" FROM events; trx2 +1ms
knex:query DROP TABLE "events" trx2 +0ms
knex:query ALTER TABLE "_knex_temp_alter307" RENAME TO "events" trx2 +0ms
knex:query COMMIT; trx2 +0ms
knex:query alter table `events` add column `action` text check (`action` in ('activation', 'cancellation')) trx2 +1ms
```

**Comment by j-refs** [comment]
gonna go ahead and +1 this, just started using knex, and am hesitant to try out migrations. 
I usually use Joshua's `better-sqlite3` on its own, manually i guess you can say, and usually handle migrations by hand or using custom scripts.

I went to research and see how well knex migrations are handled, but seeing this year old issue basically regarding my concern, having no dev interaction at all even though the project is actively maintained, makes me think my time is better spent handwriting migration scripts than learning knex migrations.

I REALLY hope the dev jumps in and gives some feedback, I simply don't have the time to write a bunch of tests to verify myself, and I believe testing is an authors responsibility anyways. I have a knex/better-sqlite3 requirement for this project, and this ignored issue is gonna be the reason I give my client why I wont include knex migrations

again, HOPEFULLY, the devs get to this and clear the air up, I do get quite tired of handwriting migrations, but to me, I'd rather do that and ensure functionality than deal with annoying integration bugs later on

**Comment by kibertoad** [comment]
Issue is old and slipped through the cracks as there wasn't any activity around it. We'll take a look at it, thank you for the ping.

**Comment by mercmobily** [comment]
SQLite does not support many ALTER TABLE operations directly; Knex emulates them by recreating the table, copying data, dropping the original, and renaming the temporary table. This workflow is implemented in the SQLite DDL helpers and is the same regardless of driver; see `lib/dialects/sqlite3/schema/ddl.js:14` for the DDL helper class, with recreation steps such as `getTableSql()` at `lib/dialects/sqlite3/schema/ddl.js:28`, `dropOriginal()` at `lib/dialects/sqlite3/schema/ddl.js:56`, `renameTable()` at `lib/dialects/sqlite3/schema/ddl.js:52`, and `copyData()` at `lib/dialects/sqlite3/schema/ddl.js:60`.

This issue is related to #4450, where altering an enum produces duplicate CHECK constraints on SQLite. Using two separate `alterTable()` calls (drop then recreate) avoids the duplicate-constraint bug, but with Better‑SQLite3 this sequence can fail with a generic “SQL logic error”, likely due to the driver’s transaction/statement handling under rapid table recreation. The root Knex logic is the same across sqlite3 and better‑sqlite3; the divergence is at the driver layer.

Workarounds you can apply today:

1) Perform the change in a single raw DDL operation that creates a new table with the desired schema, copies data across, and swaps tables. This mirrors Knex’s internal flow but gives you explicit control over the exact statements.

2) If feasible, use the `sqlite3` driver instead of Better‑SQLite3 for this migration sequence. Note you may still hit #4450 unless you use the drop‑and‑recreate approach.

This issue is a better‑sqlite3‑specific error that arises from the drop‑and‑recreate alterTable sequence used to work around issue 4450’s SQLite  enum DDL bug (duplicate CHECK constraints), so fixing 4450 should eliminate  that sequence and likely resolve 4947. However, we should also look at this, as this bug might well resurface in other back-to-back operations.
