### ISSUE TITLE
afterCreate in Pool with better-sqlite3

### ISSUE THREAD

**Issue by xJonahS** [knex/knex#4971]
# Environment

Knex version: 1.0.1

# Bug

1. After switching from sqlite3 to better-sqlite3 we are having issues with the following line of code:

`knexConfig.pool = {
afterCreate: (conn, cb) => conn.run("PRAGMA foreign_keys = ON", cb),
};`

2. Error: 
     `TypeError: conn.run is not a function
      at afterCreate (src/shared/database/configurations/KnexConfigFactory.ts:9:128)
      at node:internal/util:360:7
      at new Promise (<anonymous>)
      at afterCreate (node:internal/util:346:12)
      at create (node_modules/knex/lib/client.js:252:50)
`

# Question

Is this a known bug or is there another way to use foreign keys with better-sqlite3?

**Comment by kibertoad** [comment]
@benjdlambert Any chance you could take a look? I assume connection statements are executed differently in better-sqlite.

**Comment by schmetzyannick** [comment]
We also tried to execute `PRAGMA foreign_keys = ON`, after the connection is established, as a raw statement. The raw statement seems to never be resolved, nor rejected (I have waited for about 2 minutes). 

Example code can be found here (add a catch clauses): https://stackoverflow.com/questions/65423969/foreign-key-constraint-ignored-by-knex-js

**Comment by lvivier** [comment]
`better-sqlite3`'s`Database` class doesn't have a `run()` method, but it does have an `exec()` method. There's also a `pragma()` method [specifically for executing PRAGMA statements](https://github.com/JoshuaWise/better-sqlite3/blob/master/docs/api.md#pragmastring-options---results). From the docs:

> It's better to use this method instead of normal prepared statements when executing PRAGMA, because this method normalizes some odd behavior that may otherwise be experienced.

You can probably do something like (not tested):

```js
(conn, cb) => {
  conn.pragma("foreign_keys = ON")
  cb()
}
```

**Comment by schmetzyannick** [comment]
@lvivier seems to work, thank you :)

**Comment by benjdlambert** [comment]
Wondering if we can close this? Do we need to update some documentation somewhere as it looks like it works just it's not compatible with the sqlite3 api, but I think that's ok right as it's the raw connection object you get,

**Comment by schmetzyannick** [comment]
I would expect the documentation it in SchemaBuilder->foreign for better- and "normal"-sqlite. I would recommend closing the issue after the documentation is completed, so it will not be forgotten.

**Comment by mercmobily** [comment]
I created a documentation ticket, placed here: https://github.com/knex/documentation/issues/582
