### ISSUE TITLE
Any known issues with Node v17+?

### ISSUE THREAD

**Issue by Jakub41** [knex/knex#4972]
# Environment

 - Docker
 - postgres:14.1-alpine
 - Node 17.3
 - Knex 1.0.1
 - PG 8.7.1
 - Objection 3.0.1
 
 # Project
 
 [Repository](https://github.com/Jakub41/testingKnexObjectionJS)
 
 My question is if Node v17 is supported?
 
 The reason is that I'm building a project with the above technologies and I'm unable to get the first query running as
 
 `await Pokemons.query();`
 
I'm getting the issue below and cannot understand what is wrong with my code so I'm seeking some help to understand what could be the issue in my situation.
 
 # Issue
 
 ```
status: 500,
message: "Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?",
stack: "KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/home/node/code/node_modules/knex/lib/client.js:307:26)
    at async Runner.ensureConnection (/home/node/code/node_modules/knex/lib/execution/runner.js:294:28)
    at async Runner.run (/home/node/code/node_modules/knex/lib/execution/runner.js:30:19)
    at async QueryBuilder.execute (/home/node/code/node_modules/objection/lib/queryBuilder/QueryBuilder.js:446:22)
    at async getPokemons (file:///home/node/code/src/controllers/pokemons/PokemonsController.js:13:17)"
```

I hope to get some help as I'm blocked with my personal project due to these issues and I started to believe is Node version is the issue.

Thank you for your help and support :-)

**Comment by jpike88** [comment]
Check the driver too. Try testing with mysql driver instead on a mysql database and see if that has drama

**Comment by kibertoad** [comment]
Considering that our full CI suite is passing on Node 17, there mustn't be absolute showstoppers there, at least with the latest drivers.
