### ISSUE TITLE
Knex Throwing SQLITE3 error when SQLITE3 Is Installed, 

### ISSUE THREAD

**Issue by Jerrardsmith215** [knex/knex#5002]
# Environment

Knex version: 1.0.2
Database + version: sqlite3 @ latest
OS: Windows 10

# Bug

1. Hi. I am experiencing an issue where I am having an error thrown while trying to use knex. If I migrate:latest I get the error below. I have tried reinstalling sqlite3 until I recognized that it asked for a @vscode-sqlite3 package. I installed that package and still the failures. 

2. Error message

Knex: run
$ npm install sqlite3 --save
Cannot find module '@vscode/sqlite3'
Require stack:
- C:\Users\jsmith1\Desktop\PPMUniversity\api\node_modules\knex\lib\dialects\sqlite3\index.js
- C:\Users\jsmith1\Desktop\PPMUniversity\api\node_modules\knex\lib\knex-builder\internal\config-resolver.js
- C:\Users\jsmith1\Desktop\PPMUniversity\api\node_modules\knex\lib\knex-builder\Knex.js
- C:\Users\jsmith1\Desktop\PPMUniversity\api\node_modules\knex\lib\index.js
- C:\Users\jsmith1\Desktop\PPMUniversity\api\node_modules\knex\knex.js
- C:\Users\jsmith1\Desktop\PPMUniversity\api\knexfile.js
- C:\Users\jsmith1\AppData\Roaming\npm\node_modules\knex\lib\migrations\util\import-file.js
- C:\Users\jsmith1\AppData\Roaming\npm\node_modules\knex\bin\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Client_SQLite3._driver (C:\Users\jsmith1\Desktop\PPMUniversity\api\node_modules\knex\lib\dialects\sqlite3\index.js:33:12)
    at Client_SQLite3.initializeDriver (C:\Users\jsmith1\Desktop\PPMUniversity\api\node_modules\knex\lib\client.js:190:26)
    at new Client (C:\Users\jsmith1\Desktop\PPMUniversity\api\node_modules\knex\lib\client.js:75:12)
    at new Client_SQLite3 (C:\Users\jsmith1\Desktop\PPMUniversity\api\node_modules\knex\lib\dialects\sqlite3\index.js:22:5)
    at knex (C:\Users\jsmith1\Desktop\PPMUniversity\api\node_modules\knex\lib\knex-builder\Knex.js:12:28)
    at initKnex (C:\Users\jsmith1\AppData\Roaming\npm\node_modules\knex\bin\cli.js:63:10)
Knex: run
$ npm install sqlite3 --save
Cannot find module '@vscode/sqlite3'

**Comment by Jerrardsmith215** [comment]
NOTE: Resolved  by going into node_modules and RENAMING vscode-sqlite3 to @vscode/sqlite3

**Comment by RodrigoNovais** [comment]
> NOTE: Resolved by going into node_modules and RENAMING vscode-sqlite3 to @vscode/sqlite3
> 
> PLEASE NOTE THAT THE VSCODE-SQLITE3 PACKAGE DOES NOT INSTALL AS @VSCODE/SQLITE3!!!!!!

Even if it does solve the issue it should not be taken as a solution nor a recomendation
Since the library is looking for a path that does not exist and cannot be installed via npm, some change should be made in order for it to locate the correct folder for the required package

Hope someone could actually solve it since it passed a month and this trick seems to be still required

**Comment by kibertoad** [comment]
Released in 1.0.5
