### ISSUE TITLE
knex.fn.now erroring out when precision is specified in mssql

### ISSUE THREAD

**Issue by KrisLau** [knex/knex#5027]
# Environment

Knex version: ^0.95.14
Database + version: MSSQL @smorey2 
OS: Windows

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Getting an error because it is using `CURRENT_TIMESTAMP` but I'm actually hoping to get the `SYSDATETIMEOFFSET()` or `SYSDATETIME()`. I feel like `knex.fn.now()` should use `SYSDATETIME()` since the default timestamp created is `datetime2(7)`

    Also I'm not sure if my timestamps should be `datetime2` or `datetimeoffset`? `table.timestamps(true, true)` creates it as a `datetime2(7)`. 

    - Is this best practice or should it be `datetimeoffset`? 
    - If it is supposed to be `datetimeoffset`, how do I change `.timestamps` to use `datetimeoffset`?

    I'm migrating over from postgres so I'm just confused because the default for postgres `.timestamps(true, true)` is `timestampz` which takes into account the timezone.

2. Error message
```
migration file "20211111223601_init.js" failed
migration failed with error: CREATE TABLE [deleted_record] ([table_name] nvarchar(max) not null, [id] nvarchar(255) not null, [created_at] datetimeoffset CONSTRAINT [deleted_record_created_at_default] DEFAULT CURRENT_TIMESTAMP(7)) -
 Incorrect syntax near '('.
CREATE TABLE [deleted_record] ([table_name] nvarchar(max) not null, [id] nvarchar(255) not null, [created_at] datetimeoffset CONSTRAINT [deleted_record_created_at_default] DEFAULT CURRENT_TIMESTAMP(7)) - Incorrect syntax near '('.
Error: CREATE TABLE [deleted_record] ([table_name] nvarchar(max) not null, [id] nvarchar(255) not null, [created_at] datetimeoffset CONSTRAINT [deleted_record_created_at_default] DEFAULT CURRENT_TIMESTAMP(7)) - Incorrect syntax near
 '('.
    at RequestTokenHandler.onErrorMessage (C:\Users\Kristin\IdeaProjects\Prototype\backend\node_modules\tedious\lib\token\handler.js:360:21)
    at Readable.<anonymous> (C:\Users\Kristin\IdeaProjects\Prototype\backend\node_modules\tedious\lib\token\token-stream-parser.js:26:33)
    at Readable.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Readable.push (internal/streams/readable.js:223:10)
    at next (internal/streams/from.js:88:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

3. Reduced test code
Migration code snippet:
```
.createTable('deleted_record', (table) => {
    table.text('table_name').notNullable();
    table.string('id').notNullable();
    table.timestamp('created_at', {useTz: true}).defaultTo(knex.fn.now());
  })
```

**Comment by KrisLau** [comment]
Also I've been trying to figure out how to recreate this in SSMS but I have been unsuccessful so far:
```
CREATE OR REPLACE FUNCTION public.fn_update_timestamp()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE NOT LEAKPROOF
AS $BODY$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$BODY$;

DO $$
DECLARE
    t text;
BEGIN
    FOR t IN
        SELECT TABLE_NAME FROM information_schema.columns WHERE COLUMN_NAME = 'updated_at'
    LOOP
        EXECUTE format('CREATE TRIGGER tr_update_timestamp
                    ON %I AFTER UPDATE 
                    FOR EACH ROW EXECUTE PROCEDURE fn_update_timestamp()', t,t);
    END loop;
END;
$$ language 'plpgsql';
```

**Comment by KrisLau** [comment]
Ended up just using knex.raw
