### ISSUE TITLE
Escaped question marks (\\?) in whereRaw as treated as bindings

### ISSUE THREAD

**Issue by stefanorumi7** [knex/knex#5091]
# Environment

Knex version: v1.0.4
Database + version: Postgres v12
OS: MacOS, node v12

# Bug

@lorefnon

1. Explain what kind of behaviour you are getting and how you think it should do

When using `q.whereRaw('i.foo @\\? \'$.*.bar \\? (@ == "?")\'', bar)` the first 2 question marks should be treated as JSONB operators and only the last one as a binding.

2. Error message

`Error: Expected 1 bindings, saw 3`

**Comment by iyuiasd7** [comment]
I have same issue with `REGEXP_LIKE(column1, '^[+-]?\d*\.?\d+([eE][+-]?\d+)?$')` function in oracle

**Comment by OlivierCavadenti** [comment]
I test with you whereRaw expression and my unit test pass:

![image](https://user-images.githubusercontent.com/10152806/172049289-7e6d565f-c3d7-46eb-932e-65caa0decd41.png)

What is the value of "bar" ?

**Comment by OlivierCavadenti** [comment]
I will build some intégration tests to investigate

**Comment by stefanorumi7** [comment]
@OlivierCavadenti just tried it out with knex v2.1.0 and the issue persists:
Code:
![image](https://user-images.githubusercontent.com/17889654/172126563-1ede5b0d-8312-4dd4-a4cc-5e55ba863f7a.png)
Query builder internal state (this where clause):
![image](https://user-images.githubusercontent.com/17889654/172126799-94bdc87a-46e3-4a56-b1b9-1b4a57cb6a99.png)
Query builder internal state (other where clause):
![image](https://user-images.githubusercontent.com/17889654/172128085-8c9f7c97-6ee2-48a3-bbcf-9caaaf6ae1ec.png)
Error message:
![image](https://user-images.githubusercontent.com/17889654/172127672-9875f6d1-2972-4aab-bad9-0d86534988a2.png)
![image](https://user-images.githubusercontent.com/17889654/172127206-d145839c-0f6a-43ad-9cc0-040d4d7f6438.png)
It seems that what is happening is that the bindings order gets mixed up as `@\\?` gets replaced by `@'customer-id-filter'` in-query when that should be actually escaped and not bound.

**Comment by rubengmurray** [comment]
I'm taking a stab at investigating getting this. I can replicate the issue with 3.0.1 using Postgres 14.15.

As far as I can tell, the query outputted via the `toQuery()` method is actually correct; it's the execution of the query where the bug is introduced.

```
const binding = 'bar_bind';
const query = knex.select('*')
  .from('users')
  .whereRaw('users.key @\\? \'$.*.bar \\? (@ == "?")\'', binding);

console.log({ toSQL: query.toSQL(), toQuery: query.toQuery() });
await query;
```

Prints

```
{
  toSQL: {
    method: 'select',
    options: {},
    timeout: false,
    cancelOnTimeout: false,
    bindings: [ 'bar_bind' ],
    __knexQueryUid: 'x9K-PKVcRx9O1DvzmB1OL',
    sql: `select * from "users" where users.key @\\? '$.*.bar \\? (@ == "?")'`
  },
  toQuery: `select * from "users" where users.key @? '$.*.bar ? (@ == "'bar_bind'")'`
}
```

Then the error hits

```
error: select * from "users" where users.key @'bar_bind' '$.*.bar ? (@ == "$1")' - bind message supplies 1 parameters, but prepared statement "" requires 0
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:285:98)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:122:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:35:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

Dumping this here for now in case I don't get any further this evening

**Comment by rubengmurray** [comment]
OK I've got a little further. I've managed to confirm the values being passed to `pg` - latest version `8.16.3` - and I've played with escaping, and not escaping, but neither work. So I feel like we need to check out the `node-postgres` docs here.

```
{
  text: `select * from "users" where users.key @? '$.*.bar ? (@ == "$1")'`,
  values: [ 'bar_bind' ]
}

Produces: error: select * from "users" where users.key @'bar_bind' '$.*.bar ? (@ == "$1")' - bind message supplies 1 parameters, but prepared statement "" requires 0
```

```
{
  text: `select * from "users" where users.key @\\? '$.*.bar \\? (@ == "$1")'`,
  values: [ 'bar_bind' ]
}

Produces: error: select * from "users" where users.key @? '$.*.bar ? (@ == "$1")' - syntax error at or near "\"
```

I'm logging this out at https://github.com/knex/knex/blob/master/lib/dialects/postgres/index.js#L227

**Comment by rubengmurray** [comment]
I think I have a breakthrough for this case. Using `pg-format` before passing it to the driver results in this no longer throwing an error.

I'll need to confirm this doesn't break anything else though.

**Comment by mercmobily** [comment]
Thank you. Please do and let us know :D

**Comment by mercmobily** [comment]
Just a reminder that this is one piece of the puzzle in of #6236

**Comment by rubengmurray** [comment]
Could very well be that #6163 is related as that's also PG specific. Will write a test for that too.
