### ISSUE TITLE
generateDdlCommands() throws TypeError on compound foreign keys in SQLite 

### ISSUE THREAD

**Issue by ghakko** [knex/knex#5092]
Forgive me for being obtuse, but I was told to seek help here by the Mikro-ORM people. I have no idea how to reproduce this bug with the plain Knex API. I'm using Knex 1.0.4 and MikroORM 5.1.1 on Node 16.14.2.

When running the following:
```
import { MikroORM, Collection, Entity, ManyToOne, OneToMany, PrimaryKey } from "@mikro-orm/core";

@Entity() export class Foo {
  @OneToMany(() => Bar, bar => bar.foo) bars = new Collection<Bar>(this);
  @PrimaryKey() id!: number;
  @PrimaryKey() something?: number;
}

@Entity() export class Bar {
  @ManyToOne() foo!: Foo;
  @PrimaryKey() id!: number;
}

MikroORM.init({ dbName: "crashme.db", type: "sqlite", entities: [Foo, Bar] })
  .then(orm => orm.getSchemaGenerator().updateSchema().then(() => orm.close()))
```
I get the SQL:
```
CREATE TABLE `foo` (`id` integer not null, `something` integer not null, primary key (`id`, `something`));
CREATE TABLE `bar` (`id` integer not null primary key autoincrement, `foo_id` integer not null, `foo_something` integer not null, constraint `bar_foo_id_foo_something_foreign` foreign key(`foo_id`, `foo_something`) references `foo`(`id`, `something`) on update cascade);
CREATE INDEX `bar_foo_id_foo_something_index` on `bar` (`foo_id`, `foo_something`);
```
This is correct. But when I run it a second time, it throws this:
```
/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:204
  return ast.columns.map((column) => identifier(column, wrap)).join(', ');
                     ^
TypeError: ast.columns.map is not a function
    at columnNameList (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:204:22)
    at columnNameListOptional (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:200:40)
    at foreignKeyClause (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:193:43)
    at foreignTableConstraint (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:189:9)
    at tableConstraint (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:156:14)
    at /tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:142:29
    at Array.reduce (<anonymous>)
    at tableConstraintList (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:140:26)
    at createTable (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:16:7)
    at compileCreateTable (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:2:10)
```
This happens with SQLite, but not with MariaDB.

**Comment by kibertoad** [comment]
@nickrum Could you please take a look?

**Comment by nickrum** [comment]
This is actually an issue in micro-orm. They are monkey-patching the method [`TableCompiler_SQLite3.foreign()`](https://github.com/knex/knex/blob/24c32f9e58dfe51cc51ea8748467937733ceb9ce/lib/dialects/sqlite3/schema/sqlite-tablecompiler.js#L225) over [here](https://github.com/mikro-orm/mikro-orm/blob/757801e9260b4cc89577b89ddbeec7a428fdb9a0/packages/sqlite/src/SqliteConnection.ts#L101) based on an old version of that function. Since #4648, identifiers in `foreignInfo` shouldn't be wrapped when passed to `SQLite3_DDL.foreign()`.

**Comment by B4nan** [comment]
Thanks for the pointer @nickrum!

**Comment by B4nan** [comment]
FYI I would very much like to not monkey patch knex, but this particular patch I have there is to allow creating 1:1 FKs. IIRC it is the exact same problem I was reporting years ago (https://github.com/knex/knex/issues/3351) and is still not fixed. It is not possible to add a new column to existing table in sqlite, while making it a FK. Knex simply ignores the FK and creates just the column without the constraint. My workaround (that is no broken) proves its easily possible, the query is totally valid.

This is the test that gets broken when I remove my patch:

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/615580/164412986-99792b54-4a05-4833-acaf-b4b96fcc23c5.png">

**Comment by mercmobily** [comment]
@B4nan I am closing this.  For what is worth, I gave #3351 High priority
