### ISSUE TITLE
whereLike does not work with the MySQL utf8mb4 character set

### ISSUE THREAD

**Issue by affenull2345** [knex/knex#5143]
# Environment

Knex version: 1.0.7
Database + version: MariaDB 10.5.15
OS: Debian GNU/Linux 11

# Bug

1. Expected behavior: `whereLike` should work on tables using the `utf8mb4` charset

    Actual behavior: it does not work on the tables because it forces `utf8_bin` collation

3. Error message: 
```
Error: select `content` from `acb_books` where `id` = 1 and `type` = 'membership' and `content` like '1:%' COLLATE utf8_bin - COLLATION 'utf8_bin' is not valid for CHARACTER SET 'utf8mb4'
    at Packet.asError (.../node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (.../node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (.../node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (.../node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (.../node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (.../node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10) {
  code: 'ER_COLLATION_CHARSET_MISMATCH',
  errno: 1253,
  sqlState: '42000',
  sqlMessage: "COLLATION 'utf8_bin' is not valid for CHARACTER SET 'utf8mb4'",
  sql: "select `content` from `acb_books` where `id` = 1 and `type` = 'membership' and `content` like '1:%' COLLATE utf8_bin"
}
```

The table was created manually using:
```
CREATE TABLE acb_books (id INTEGER, type VARCHAR(30), content TEXT, hidden TEXT);
```

The default charset for the server is `utf8mb4`. Here is my select call:

```javascript
knex
  .select('content')
  .from('acb_books')
  .where('id', id)
  .where('type', 'membership')
  .whereLike('content', '1:%')
```

There seems to be no option to change the collation since it is hardcoded in https://github.com/knex/knex/blob/master/lib/dialects/mysql/query/mysql-querycompiler.js#L163. Using `whereILike` instead of `whereLike` fixes the problem in my case, but will cause problems in other applications where the search must be case sensitive.

**Comment by xegulon** [comment]
What about this:

```js
whereLike(statement, collation = 'utf8_bin') {
    return `${this._columnClause(statement)} ${this._not(
      statement,
      'like '
    )}${this._valueClause(statement)} COLLATE ${collation}`;
  }
```

?

**Comment by ophilan** [comment]
Why not make the default utf8mb4 as it is, I believe, the MySQL default as well?
The best would be to detect it automatically, but I guess this would not be easy.

**Comment by throrin19** [comment]
Any news ? I have already this error

**Comment by mercmobily** [comment]
Hi there!

This is a duplicate of #6158, which was already merged on January 5, 2025. The fix is in the master branch but hasn't been released yet (current version is 3.1.0 from December 2023).

Until the next release, you can work around this by using `knex.raw()`:

```javascript
knex.raw('SELECT * FROM users WHERE email <=> ?', [value])
```

Related issues:
- #6158 (CLOSED) - Added support for the `<=>` operator
