### ISSUE TITLE
`Migrator.rollback` may throw

### ISSUE THREAD

**Issue by spencerwilson** [knex/knex#5150]
# Environment

Knex version: 0.95.14, but the same thing looks possible on 1525f0f9167828125d103f8380cdf7c5c7ce2c51
Database + version: Postgres 12.8
OS: macOS 12.3

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

```ts
await knex.migrate.rollback().finally(() => console.log('hello'));
```

Expectation: "hello" is always printed. This depends on `rollback` always returning a promise. I expect `rollback` to surely return a promise because

- all of the examples on Knex docs show promise-like usage;
- no prose says otherwise; and
- the typings for `Migrator` say that all methods return a promise: https://github.com/knex/knex/blob/1525f0f9167828125d103f8380cdf7c5c7ce2c51/types/index.d.ts#L2662-L2672

Actual: `rollback` may throw.

2. Error message

An example error thrown by `Migrator.rollback`:
```
Error: Unable to acquire a connection
        at Client_PG.acquireConnection (/Users/ssw/code/api/node_modules/knex/lib/client.js:296:13)
        at Runner.ensureConnection (/Users/ssw/code/api/node_modules/knex/lib/execution/runner.js:259:46)
        at Runner.run (/Users/ssw/code/api/node_modules/knex/lib/execution/runner.js:30:30)
        at SchemaBuilder.Target.then (/Users/ssw/code/api/node_modules/knex/lib/builder-interface-augmenter.js:24:43)
        at ensureTable (/Users/ssw/code/api/node_modules/knex/lib/migrations/migrate/table-creator.js:12:6)
        at listCompleted (/Users/ssw/code/api/node_modules/knex/lib/migrations/migrate/migration-list-resolver.js:12:9)
        at Object.listAllAndCompleted (/Users/ssw/code/api/node_modules/knex/lib/migrations/migrate/migration-list-resolver.js:28:5)
        at /Users/ssw/code/api/node_modules/knex/lib/migrations/migrate/Migrator.js:177:10
        at new Promise (<anonymous>)
        at Migrator.rollback (/Users/ssw/code/api/node_modules/knex/lib/migrations/migrate/Migrator.js:166:12)
```

4. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

Don't have time right now to make this, sorry. Hopefully the above description suffices.

# Possible fixes

- Make every method on Migrator return a promise, to be consistent with the typings
- Make `rollback` return a promise, to be consistent with its current typing. A small change that would accomplish this would be to add the `async` keyword to the method definition, making it an async method.
- Update the docs + typings to reflect the implementation: that rollback and some other methods may throw. Document the conditions in which they throw.

**Comment by mercmobily** [comment]
Hi! Thanks for the precise expectation and stack trace.

 The contract should be that `migrator.rollback()` returns a promise, even in error paths, matching docs and typings. Today, there are paths that throw synchronously in `down()`/`up()` and within the internal executor (e.g. when a named migration isn’t found), which technically become promise rejections if thrown inside a `then`, but the outer `rollback()` has its own manual `new Promise` wrapper (lib/migrations/migrate/Migrator.js:205) (?!?) that calls `reject(e)` without early return and continues processing. this is a pattern that can contribute to confusing sequencing.

I am only doing mass-triaging now, but I am SURE there are good reasons why the code does what it does. We will get to it.

POSSIBLE direction:
- Refactor `rollback()` to be `async` and rely on `await`/`try` instead of a manual `new Promise`, ensuring it always returns a promise and that all error paths consistently reject it. Harmonise the validation paths so name lookup failures are handled in the same async flow.

**Comment by thecoolestcoderrushil** [comment]
a migrator.rollback that throws synchronously instead of returning a rejected promise is a painful contract bug, since finally handlers never run and the error escapes the promise chain. rehearsing the migration on a production-shaped twin first would surface the rollback problem before deploy day. antifailure.dev (https://antifailure.dev) builds disposable database twins for migration rehearsal and is open source and free to try, with demos available for teams that want one.
