### ISSUE TITLE
Syntax error when alter primary key from `increments` to `bigIncrements`

### ISSUE THREAD

**Issue by cawa-93** [knex/knex#5163]
# Environment

Knex version:  knex@1.0.5
Database + version: PostgresSQL 13.5
OS: Windows 10

# Bug

1. I trien altering primary `id`.

It was created like:
```js
table.increments('id', {primaryKey: true}).unsigned()
```

Now I want alter to `bigIncrements`:
```js
schema.alterTable('tableName', (table) => {
      table
        .bigIncrements('id', {primaryKey: true})
        .unsigned()
        .alter({alterNullable: false})
})
```
3. Syntax Error message

```node
alter table "tableName" alter column "id" type bigserial primary key using ("id"::bigserial primary key) - ошибка синтаксиса (примерное положение: "primary")
    at Parser.parseErrorMessage (C:\Users\kozac\Dev\kitlink\node_modules\pg-protocol\src\parser.ts:369:69)
    at Parser.handlePacket (C:\Users\kozac\Dev\kitlink\node_modules\pg-protocol\src\parser.ts:188:21)
    at Parser.parse (C:\Users\kozac\Dev\kitlink\node_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (C:\Users\kozac\Dev\kitlink\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by EndlessBox** [comment]
any updates on this ?

**Comment by mercmobily** [comment]
What you are hitting is a PostgreSQL limitation. Changing an `increments` column to `bigincrements` generates SQL that tries to cast the column to `bigserial`. PostgreSQL treats `serial`/`bigserial` as shorthand that is only valid in `create table` statements; they expand to three things: an `integer`/`bigint` column, a sequence, and a `default nextval('...')`. They are not real types you can cast to in `alter table ... alter column ... type ...` statements, so `... type bigserial using (id::bigserial)` will fail.

This is exactly how Knex currently compiles an alter‑type: it emits `alter table <tbl> alter column <col> type <type> using (<col>::<type>)` (see lib/dialects/postgres/schema/pg-tablecompiler.js:135). For `bigincrements`, the `<type>` comes from the dialect’s column compiler and is `bigserial` (lib/dialects/postgres/schema/pg-columncompiler.js:121). Put together, that produces invalid SQL on PostgreSQL.

There is also a subtlety around primary keys. In create‑table flows, `increments()` may append `primary key`. On alter flows, we must not attempt to change a type and a constraint in a single `type` clause. The safe route is to handle type and constraints separately.

A safe migration path on PostgreSQL is:

1) Drop the default that points to the current sequence.

2) Change the column’s underlying type to `bigint` using an explicit cast: `... alter column id type bigint using id::bigint`.

3) Ensure the column has a suitable sequence and default. You can keep using the existing sequence if appropriate, or create a new `AS bigint` sequence, set its value, and attach it to the column.

4) Re‑apply or keep the `primary key` constraint separately (if it was present before).

Concrete SQL example for a table named `tableName` with an `id` column:

alter table "tableName" alter column "id" drop default;
alter table "tableName" alter column "id" type bigint using "id"::bigint;
-- Option A: keep existing sequence and just reattach the default
alter table "tableName" alter column "id" set default nextval('"tableName_id_seq"'::regclass);

-- Option B: create a fresh bigint sequence and switch the default
-- create sequence "tableName_id_seq_big" as bigint owned by "tableName"."id";
-- select setval('"tableName_id_seq_big"', coalesce(max("id"), 0) + 1, false) from "tableName";
-- alter table "tableName" alter column "id" set default nextval('"tableName_id_seq_big"'::regclass);

From Knex’s side, we can avoid generating `bigserial` in alter‑type code paths. A robust fix would be to special‑case alter operations for `increments`/`bigincrements` on PostgreSQL:

- When altering an `increments` to `bigincrements`, emit `bigint` for the `type` change rather than `bigserial`.
- Drop and restore the column default around the type change and ensure the default points to a sequence owned by the column.
- Leave `primary key` handling to separate DDL where needed, not inside the type clause.

Concretely, this means teaching the Postgres table compiler to detect that the column builder is in an alter flow for an `increments`‑family type and to substitute `bigint` in place of `bigserial` for the `type` part, then emit the default adjustment as a separate statement (lib/dialects/postgres/schema/pg-tablecompiler.js:135, lib/dialects/postgres/schema/pg-columncompiler.js:121). That keeps the behaviour correct without surprising users.

If we decide not to add this complexity in core right now, we should document that changing `increments` to `bigincrements` on PostgreSQL is not supported via `.alter()` and provide the raw SQL sequence above as a recommended manual migration.
