### ISSUE TITLE
Postgres connection not release from Pool when server closes it

### ISSUE THREAD

**Issue by tasdflkjweio** [knex/knex#5186]
# Environment

Knex version: 2.0.0, but it was happening on one of the latest releases as well
Database + version: Postgres 9.5.22 (pg driver v8.7.3)
OS: CentOS/Linux

Select applicable template from below.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Server side, either Linux or Postgres is closing out idle TCP connections after ~2 hours. However, the client-side connection that's living in the tarn pool does not recognize that its been closed. It seems this is the out-of-the-box `validate` function that `pg` is using: 

```
(connection) => {
        if (connection.__knex__disposed) {
          this.logger.warn(`Connection Error: ${connection.__knex__disposed}`);
          return false;
        }

        return this.validateConnection(connection);
      }
```

So what's the issue? The dead connection hangs out in the pool until it tries to get used next. The connection fails to get pulled out of the pool, and the request hangs until the http request times out. The process stays in this orphaned state for about 15 minutes, before it's finally 'released'. From that point, all subsequent requests succeed, at least until there's another lengthy period of inactivity.

I have validated that the connection is closed by looking at the connections PG-side.

2. Error message

There is first a warning `Connection Error: Connection ended unexpectedly`, which I believe is generated by the validate function above.

Secondly, there is the following err:

```
{
    "stack": "Error: read ETIMEDOUT\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)",
    "message":"BEGIN; - read ETIMEDOUT",
    "type":"Error"
}
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

I don't have a means of sharing how to reproduce other than waiting for idle connections to get killed by the server, then trying to perform a query. However, it is guaranteed related to inactivity and the pool not recognizing the connection as closing. It is happening reliably and predictably.

**Comment by arath17** [comment]
@tasdflkjweio I'm facing a similar issue, did you find a solution for this? I tried setting the connection pool : `{ min: 0 }` which reduced the number of errors but the issue is still there.

**Comment by tasdflkjweio** [comment]
@arath17 i completely missed your question, apologies. i set the min to zero, but you're right...it doesn't actually solve the issue. kind of hard to believe that the bug has been around for this long and remains unaddressed.

**Comment by huntedman** [comment]
@tasdflkjweio Any updates? Also experiencing this.

**Comment by huntedman** [comment]
Ok I found out about this: https://github.com/Vincit/tarn.js/pull/74

**Comment by sshettyyara** [comment]
Is the issue still open i am getting bellow error with knex 0.21.21 and pg 8.7.1 sometimes i production with the configuration {min: 2, max: 10}

Error: Connection terminated
at Connection. (/app/node_modules/pg/lib/client.js:132:36)
at Object.onceWrapper (events.js:519:28)
at Connection.emit (events.js:412:35)
at Connection.emit (domain.js:475:12)
at Socket. (/app/node_modules/pg/lib/connection.js:57:12)
at Socket.emit (events.js:400:28)
at Socket.emit (domain.js:475:12)
at TCP. (net.js:686:12)
at TCP.callbackTrampoline (internal/async_hooks.js:130:17)

**Comment by tasdflkjweio** [comment]
Set min to 0 to get around it. There's some mention of this in the official documentation now.

**Comment by mercmobily** [comment]
Thank you for reporting this issue. You've identified a connection leak problem where Postgres connections that are closed by the server are not being properly released back to the pool.

When the Postgres server closes a connection (due to timeouts, restarts, or other reasons), the pool should detect this and remove the stale connection, but instead it appears the connection slot remains occupied. This leads to pool exhaustion over time as more connections become stale.

This issue has been added to our connection and pooling META issue #6241, where we are tracking all connection lifecycle and pool management problems. The Postgres-specific connection cleanup needs to properly detect when the server has closed a connection and release it from the pool.

This issue will remain open and tracked under META #6241.
