### ISSUE TITLE
Getting error file already exists when knex tries to run "npm install mysql2 --save"

### ISSUE THREAD

**Issue by Heebojibo** [knex/knex#5196]
# Environment

Knex version: 2.1.0
Database + version: MariaDB 10.3
OS: CentOS 7

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Installing Ghost (tryghost/ghost) using their CLI. It installs fine, however any version above ghost 4.38.0 uses new "mysql2" libraries instead of "mysql" in previous versions. When starting ghost and attempting to access the site it just continuously writes the following error to the log and never actually loads:

3. Error message

{"name":"Log","hostname":"domainremoved","pid":2352271,"level":50,"err":{"id":"8fec50b0-aa99-11ec-8044-e7767faa5190","domain":"http://localhost:2368","code":null,"name":"InternalServerError","statusCode":500,"level":"critical","message":"Knex: run\n$ npm install mysql2 --save\nEEXIST: file already exists, uv_pipe_open","stack":"Error: Knex: run\n$ npm install mysql2 --save\n$ npm install mysql2 --save\nEEXIST: file already exists, uv_pipe_open\n    at Client_MySQL2.initializeDriver (/node/16/lib/node_modules/knex/lib/client.js:235:13)\n    at Client_MySQL2.Client (/node/16/lib/node_modules/knex/lib/client.js:69:10)\n    at Client_MySQL2.Client_MySQL (/node/16/lib/node_modules/knex/lib/dialects/mysql/index.js:20:10)\n    at new Client_MySQL2 (/node/16/lib/node_modules/knex/lib/dialects/mysql2/index.js:11:16)\n    at Knex (/node/16/lib/node_modules/knex/lib/knex.js:14:28)\n    at Object.connect (/node/16/lib/node_modules/knex-migrator/lib/database.js:35:12)\n    at KnexMigrator.isDatabaseOK (/node/16/lib/node_modules/knex-migrator/lib/index.js:566:32)\n    at DatabaseStateManager.getState (/public_html//ghost/core/server/data/db/state-manager.js:40:37)\n    at DatabaseStateManager.makeReady (/public_html//ghost/core/server/data/db/state-manager.js:73:36)\n    at initDatabase (/public_html/ghost/core/boot.js:60:26)\n    at bootGhost (/public_html/ghost/core/boot.js:394:15)","hideStack":false},"msg":"Knex: run\n$ npm install mysql2 --save\nEEXIST: file already exists, uv_pipe_open","time":"2022-05-26T11:08:26.302Z","v":0}

**Comment by kibertoad** [comment]
Judging by logs, it's not the knex throwing error, ` run\n$ npm install mysql2 --save` seems to be failing.
