### ISSUE TITLE
Unhandled rejections (asynchronously handled)

### ISSUE THREAD

**Issue by MartinKolarik** [knex/knex#5199]
# Environment

Knex version: 2.1.0
Database + version: MariaDB 10.5
OS: Linux

# Bug

1. Explain what kind of behavior you are getting and how you think it should do

I upgraded from 1.0.2 to 2.1.0 yesterday without any significant app code changes and noticed the app now crashes sometimes with unhandled rejections coming from knex. Based on the logs, the rejections are actually handled but only later, so node first emits `unhandledRejection` event (and we schedule a `process.exit()` here) and then `rejectionHandled` 

The actual error seems to be #3447 and I can replicate it reliably in our staging environment which doesn't get many requests - after maybe half an hour of inactivity, the first request always fails with this error. The difference is that in `1.0.2` the error was at least properly handled.

2. Error message

```
Error: read ECONNRESET      at TCP.onStreamRead (node:internal/stream_base_commons:217:20)      at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
May 27 06:05:58 PM        --------------------
May 27 06:05:58 PM        at Protocol._enqueue (/opt/render/project/src/node_modules/mysql/lib/protocol/Protocol.js:144:48)
May 27 06:05:58 PM        at Connection.query (/opt/render/project/src/node_modules/mysql/lib/Connection.js:198:25)
May 27 06:05:58 PM        at Connection.wrappedQuery [as query] (/opt/render/project/src/node_modules/elastic-apm-node/lib/instrumentation/modules/mysql.js:106:25)
May 27 06:05:58 PM        at /opt/render/project/src/node_modules/knex/lib/dialects/mysql/index.js:132:18
May 27 06:05:58 PM        at new Promise (<anonymous>)
May 27 06:05:58 PM        at Client_MySQL._query (/opt/render/project/src/node_modules/knex/lib/dialects/mysql/index.js:126:12)
May 27 06:05:58 PM        at executeQuery (/opt/render/project/src/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
May 27 06:05:58 PM        at Client_MySQL.query (/opt/render/project/src/node_modules/knex/lib/client.js:146:12)
May 27 06:05:58 PM        at Runner.query (/opt/render/project/src/node_modules/knex/lib/execution/runner.js:130:36)
May 27 06:05:58 PM        at ensureConnectionCallback (/opt/render/project/src/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
May 27 06:05:58 PM        at Runner.ensureConnection (/opt/render/project/src/node_modules/knex/lib/execution/runner.js:307:20)
May 27 06:05:58 PM        at runMicrotasks (<anonymous>)
May 27 06:05:58 PM        at processTicksAndRejections (node:internal/process/task_queues:96:5)
May 27 06:05:58 PM        at async Runner.run (/opt/render/project/src/node_modules/knex/lib/execution/runner.js:30:19)
May 27 06:05:58 PM        [app code]
```

```
May 27 06:05:59 PM  (node:48) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
```

3. Reduced test code,

The app code in question is a simple `await knex(table).select()`

**Comment by kibertoad** [comment]
@MartinKolarik What is your pool.min value? If it's not 0, can you try setting it to 0 and check if it helps?

**Comment by MartinKolarik** [comment]
Pool settings are `2 - 40` - will try and report back.

**Comment by MartinKolarik** [comment]
Note that even if the pool config change fixes the underlying ECONNRESET, there's still the problem with how the rejections are handled - they should be handled so that no `unhandledRejection` is emitted, regardless of the config.

**Comment by MartinKolarik** [comment]
> @MartinKolarik What is your pool.min value? If it's not 0, can you try setting it to 0 and check if it helps?

Indeed that resolved the issue with broken connections.

**Comment by kibertoad** [comment]
@OlivierCavadenti any ideas where we might be shooting unhandledrejections in this case?

**Comment by mercmobily** [comment]
Hi! Thanks for the detailed logs and for testing `pool.min = 0`.

Status: This needs further work and should be tracked under the NG_ meta for connection/pooling reliability (6241). Your report ties two aspects together: (1) an underlying connection reset on idle (ECONNRESET) that mitigates with `pool.min = 0`, and (2) an “unhandledRejection handled asynchronously” warning that indicates the promise rejection surfaced before the handler attached.

Notes from code:
- Query execution errors are caught and re‑thrown in runner paths (lib/execution/runner.js:33 and :230), and stream acquisition errors are emitted on the stream if no connection was acquired (lib/execution/runner.js:83). Even so, there are still timing edge cases when a driver emits errors on a different tick, which can trip Node’s unhandledRejection bookkeeping.
- ECONNRESET on idle is a known class of issues across drivers; there are many linked reports in 6241.

Recommendations:
- Keep `pool.min = 0` for environments where servers close idle connections.
- If you can share a small, driver‑specific reproduction, we can add it to 6241 and audit the promise/error choreography in the MySQL/Maria paths specifically.
