### ISSUE TITLE
Migration error: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Object

### ISSUE THREAD

**Issue by oxodesign** [knex/knex#5275]
# Environment

Knex version: 2.2.0
Database + version: PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit (Docker)
OS: MacOS

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Im getting following error when trying to run migration on Postgres, same code works fine on Mysql!

3. Error message

```
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Object
    at new NodeError (internal/errors.js:322:7)
    at Function.byteLength (buffer.js:750:11)
    at Writer.addCString (/node_modules/pg-protocol/src/buffer-writer.ts:43:24)
    at Object.startup (/node_modules/pg-protocol/src/serializer.ts:25:28)
    at Connection.startup (/node_modules/pg/lib/connection.js:123:33)
    at Connection.<anonymous> (/node_modules/pg/lib/client.js:121:13)
    at Connection.emit (events.js:400:28)
    at Connection.emit (domain.js:475:12)
    at Socket.<anonymous> (/node_modules/pg/lib/connection.js:44:12)
    at Object.onceWrapper (events.js:519:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

5. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

Here is my migration file:
```
import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
    return knex.schema.createTable('users', table => {
        table.increments('id');
        table.string('full_name').nullable();
        table.string('company_name').nullable();
        table.string('email').unique().notNullable();
        table.string('password').notNullable();
        table.timestamp('created_at').notNullable().defaultTo(knex.fn.now());
        table.timestamp('updated_at').notNullable().defaultTo(knex.fn.now());
    });
}

export async function down(knex: Knex): Promise<void> {
    return knex.schema.dropTable('users');
}
```

What am I doing wrong?

**Comment by oxodesign** [comment]
Found out, this was not related to the KNEX but rather to the PG driver, I was sending the port under options on the connection object, probably I just copied the config from an old config.
