### ISSUE TITLE
`AggregateError` when performing a raw query that works in SQL Server

### ISSUE THREAD

**Issue by KrisLau** [knex/knex#5278]
# Environment

Knex version: ^0.95.14
Database + version: MSSQL @smorey2 
OS: Windows

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
I'm trying to do a raw SQL query using knex from my `bree` job to find events where the start date is between two dates but I keep getting an `AggregateError`.

I've tried a bunch of stuff like swapping out the backtick for a regular single quotation mark(`'`) because I thought it was a problem with the escaping of characters. I also tried using the objectionJS `raw` method, and instantiating knex inside the job, 

2. Error message
```
AggregateError: SELECT e.id AS id,
                 e.title AS title,
                 e.team_id AS teamID,
                 eo.start_date AS startDate,
                 eo.end_date AS endDate
          FROM event_occurrence eo INNER JOIN event e ON eo.event_id = e.id
          WHERE DATEADD(DAY, -1, eo.startDate) 
              BETWEEN (
                  SELECT je.last_run_at 
                  FROM job_execution je 
                  WHERE name = 'notifications'
              ) AND SYSDATETIMEOFFSET() - 
    at RequestTokenHandler.onErrorMessage (/Users/newuser/Desktop/Prototype/backend/node_modules/tedious/lib/token/handler.js:379:30)
    at Readable.<anonymous> (/Users/newuser/Desktop/Prototype/backend/node_modules/tedious/lib/token/token-stream-parser.js:26:33)
    at Readable.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at next (node:internal/streams/from:98:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.
```
//jobLastRunAt is from DB
jobLastRunAt = new Date(jobLastRunAt).toISOString();

// Send day before reminders
const eventDayReminders = await knex.raw(
  `SELECT 
    e.title AS title, 
    e.team_id AS teamID,
    eo.start_date AS startDate,
    eo.end_date AS endDate
  FROM event_occurrence eo INNER JOIN event e ON eo.event_id = e.id
  WHERE DATEADD(DAY, -1, eo.start_date) 
  BETWEEN (
    SELECT je.last_run_at
    FROM job_execution je
    WHERE name = 'notifications'
  ) AND SYSDATETIMEOFFSET()`
);
```

**Comment by KrisLau** [comment]
Nevermind got it to work using the `raw` method from objectionjs

**Comment by mercmobily** [comment]
Hi! Thanks for the error trace. I know it's late... at this stage this is here for Google posterity...

`AggregateError` here is from Tedious raising a SQL error; Knex just surfaces it. A couple of SQL issues to check in the snippet:

- Use the correct column names in `DATEADD` (your first trace shows `eo.startDate` vs your final code `eo.start_date`). Typos will bubble up from the driver.
- Ensure the subselect in `BETWEEN (...) AND SYSDATETIMEOFFSET()` returns a scalar; if there are multiple `job_execution` rows with the same `name`, you’ll get an error.

On the Knex side this flows through the MSSQL client’s `_query()` path and rejects on error (lib/dialects/mssql/index.js:431–456). If you had shared the exact compiled SQL (`.toString()` for debugging) that raises `AggregateError`, I would have been able to pinpoint the offending expression (maybe).

As a general pattern for time windows on SQL Server, consider parameterising the lower bound and comparing directly to avoid subselect surprises:

```js
await knex('event_occurrence as eo')
  .join('event as e', 'eo.event_id', 'e.id')
  .select('e.title as title', 'e.team_id as teamID', 'eo.start_date as startDate', 'eo.end_date as endDate')
  .whereRaw('DATEADD(DAY, -1, eo.start_date) BETWEEN ? AND SYSDATETIMEOFFSET()', [lastRunAt]);
```

Closing this since it's so old and I very much doubt the original poster is still waiting.
