### ISSUE TITLE
Not able to catch error if DB service is down.

### ISSUE THREAD

**Issue by RomanBurunkov** [knex/knex#5310]
# Environment

Knex version: 2.2.0
Database + version: MySQL 8.0
OS: Windows

# Bug

If database service down app crashing due unhandled exception in client.js.
It is not possible to catch this error by wrapping into try/catch fail query.
As a result app crashes.

```
async function select() {
  try {
     const res = await knex(table).select();
     return res;
  } catch(err) {
     console.log(err);
  }
}
```

Expected behavior: Query promise rejection, so it is possible to catch such errors.

2. Error message

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);

Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
    --------------------
    at Protocol._enqueue (C:\Users\User\Desktop\dev\project\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\User\Desktop\dev\project\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at Connection.connect (C:\Users\User\Desktop\dev\project\node_modules\mysql\lib\Connection.js:116:18)
    at C:\Users\User\Desktop\dev\project\node_modules\knex\lib\dialects\mysql\index.js:66:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (C:\Users\User\Desktop\dev\project\node_modules\knex\lib\dialects\mysql\index.js:61:12)
    at create (C:\Users\User\Desktop\dev\project\node_modules\knex\lib\client.js:249:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true
}

It looks the same as issue #1542, but the closed for now and I can't see any details if that was resolved.

**Comment by mercmobily** [comment]
Thank you for reporting this issue..

I've investigated this thoroughly and tested the behaviour with the current version of Knex (3.1.0). Connection errors ARE properly catchable using try/catch blocks. The code example you provided should work correctly:

```javascript
async function select() {
  try {
     const res = await knex(table).select();
     return res;
  } catch(err) {
     console.log(err); // This WILL catch ECONNREFUSED errors
  }
}
```

When I tested with MySQL pointing to a non-existent port (to simulate the database being down), the ECONNREFUSED error was successfully caught in the try/catch block without causing an unhandled rejection. The promise is properly rejected and the error propagates through the promise chain as expected.


**Understanding the error flow**

The connection acquisition happens in `lib/execution/runner.js:305` when `ensureConnection()` is called. If the database is unreachable, the `acquireRawConnection()` method in `lib/dialects/mysql/index.js:66-79` will properly reject the promise when `connection.connect()` fails at line 72-75. This rejection bubbles up through the promise chain and can be caught with try/catch or `.catch()`.

However, there's an important caveat: the `query-error` event is NOT emitted for connection acquisition failures. This is because the event is only emitted from within the actual query execution in `lib/execution/internal/query-executioner.js:46-53`, which happens AFTER the connection is successfully acquired. Connection errors occur before we reach that point, so they bypass the `query-error` event mechanism. This is documented in issue #3113.


**What might have caused your issue**

Given that you were using Knex 2.2.0 (released July 2022) and connection errors should have been catchable even in that version, there are a few possibilities:

1. **Timing issue**: The error might be occurring at a different point than expected, such as during an idle connection validation or a connection event listener

2. **Event listener without handler**: If you had registered an error event listener on the builder (`knex('table').on('error', ...)`) but it threw an error or wasn't properly set up, this could cause issues

3. **Pool minimum connections**: If you had `pool.min` set to a non-zero value, the pool tries to create minimum connections immediately, and errors from those background connection attempts might not have been properly handled in older versions (this was specifically addressed in issue #5199)

4. **Unrelated uncaught rejection**: The stack trace you showed comes from `node:internal/process/promises:279`, which suggests an unhandled promise rejection. This could be from a different part of your code that's triggered when the database is unavailable


**Recommendations**

For anyone encountering this issue:

1. Upgrade to the latest version of Knex. Many connection error handling improvements have been made since 2.2.0, particularly in version 2.5.0 which fixed uncaught errors during connection attempts (PR #5552)

2. Ensure you're using try/catch or `.catch()` on all query promises

3. Consider setting `pool.min: 0` in your configuration to avoid background connection attempts when the pool is created

4. Add a global unhandled rejection handler during development to identify where uncaught promises are coming from:
   ```javascript
   process.on('unhandledRejection', (err) => {
     console.error('Unhandled rejection:', err);
   });
   ```

5. If you need to detect connection errors separately from query errors, you'll need to examine the error code (`ECONNREFUSED`, `ETIMEDOUT`, etc.) in your catch block, as the `query-error` event won't fire for these

**Recommendation**

I am closing this issue since connection errors from a down database server are catchable using try/catch blocks. If you're still experiencing uncaught errors, please:

1. Upgrade to Knex 2.5.0 or later (current is 3.1.0)
2. Check your code for missing error handlers
3. Review your pool configuration (set `pool.min: 0`)
4. Add a global unhandled rejection handler to identify the source

If you need the `query-error` event to fire for connection errors (which is a separate feature request), please follow issue #3113 instead.

**Related issues**

- #3113 - `knex.on('query-error')` does not trigger on connection errors (OPEN) - **This is the main issue for the missing event**
- #5689 - Crash on database server down (OPEN) - Similar but wants reconnection logic
- #1712 - `acquireConnectionTimeout` errors are not emitted as error event (OPEN)
- #5199 - Unhandled rejections (asynchronously handled) (OPEN)

**Exact duplicates**
- #1542 - How to catch connection errors? (CLOSED - connection errors should be caught via try/catch on queries)
- #448 - Handling ECONNREFUSED? (CLOSED - handle errors on a per-query basis)

**Fixed in later versions**
- #5454 - Uncaught exception when using timeout (CLOSED in 2.5.0 via PR #5552)
