### ISSUE TITLE
`disableTransactions: true` still uses transaction when migrating

### ISSUE THREAD

**Issue by soonoo** [knex/knex#5359]
# Environment

Knex version:
Database + version: rqlite 7.7.2 with [knex-rqlite](https://github.com/rqlite/knex-rqlite) dialect
OS: macOS 12.2.1

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
With `disableTransactions: true` option in [migration config](https://knexjs.org/guide/migrations.html#migration-api), knex seems still using transaction.  
knex-rqlite dialect does not support transaction currently. Is there any way to completely disable transaction when using migration cli?

3. Error message
```
Requiring external module ts-node/register
Using environment: development
migration failed with error: Method not implemented.
Method not implemented.
Error: Method not implemented.
    at RqliteDialect.transaction (/Users/soonoo/dev/ddq-api/node_modules/knex-rqlite/lib/rqliteDialect.ts:84:11)
    at Object._transaction (/Users/soonoo/dev/ddq-api/node_modules/knex/lib/knex-builder/make-knex.js:146:33)
    at Object.transaction (/Users/soonoo/dev/ddq-api/node_modules/knex/lib/knex-builder/make-knex.js:139:19)
    at Function.value (/Users/soonoo/dev/ddq-api/node_modules/knex/lib/knex-builder/make-knex.js:91:29)
    at transact (/Users/soonoo/dev/ddq-api/node_modules/knex/lib/migrations/migrate/Migrator.js:338:64)
    at Migrator._getLock (/Users/soonoo/dev/ddq-api/node_modules/knex/lib/migrations/migrate/Migrator.js:339:12)
    at Migrator._runBatch (/Users/soonoo/dev/ddq-api/node_modules/knex/lib/migrations/migrate/Migrator.js:358:18)
    at Migrator.latest (/Users/soonoo/dev/ddq-api/node_modules/knex/lib/migrations/migrate/Migrator.js:97:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (/Users/soonoo/.nvm/versions/node/v16.17.0/lib/node_modules/knex/bin/cli.js:248:32)
```

**Comment by o0th** [comment]
I did run in the same issue, even if you set `disableTransactions: true` or `transaction: false` for the migrations knex still use transaction to acquire the lock on the migrations table.

**Comment by mercmobily** [comment]
Thank you for reporting this issue and for providing such clear error output. You've identified a genuine limitation in Knex's migration locking mechanism that affects custom dialects which don't support transactions.

This issue remains unresolved. The `disableTransactions: true` configuration option currently only controls whether individual migrations are wrapped in transactions during execution, but it does not affect the migration table locking mechanism. The lock acquisition in `_getLock()` at lib/migrations/migrate/Migrator.js:338-345 unconditionally uses a transaction, even when transactions are disabled.

Looking at the implementation, the `_getLock` method always calls `this.knex.transaction(fn)` to acquire the migration lock:

```javascript
_getLock(trx) {
  const transact = trx ? (fn) => fn(trx) : (fn) => this.knex.transaction(fn);
  return transact((trx) => {
    return this._lockMigrations(trx);
  }).catch((err) => {
    throw new LockError(err.message);
  });
}
```

The only exception to this behaviour is for CockroachDB, which was addressed in PR #4717. At line 356 in Migrator.js, there's a check for `canGetLockInTransaction`:

```javascript
const canGetLockInTransaction =
  this.knex.client.driverName !== 'cockroachdb';
await this._getLock(canGetLockInTransaction ? trx : undefined);
```

However, this is a hardcoded database-specific workaround rather than a configurable option that custom dialects can leverage. For your knex-rqlite dialect, which doesn't support transactions at all, this creates an insurmountable problem because the locking mechanism will always attempt to use transactions.

The root issue is that Knex's architecture assumes all database engines support transactions, at least for the locking mechanism. Even though `disableTransactions: true` exists as a configuration option, it was designed primarily for databases where DDL statements have implicit commits (like MySQL and Oracle), not for databases that lack transaction support entirely.

There are a few potential approaches to resolve this:

**Option 1: Add a configuration flag for lock transaction behaviour**
Introduce a new configuration option like `disableLockTransactions` that would allow the locking mechanism to operate without transactions. This would require modifying `_getLock()` to check this configuration and potentially using advisory locks or other mechanisms.

**Option 2: Extend the driverName check**
Modify the `canGetLockInTransaction` check to support a broader set of databases, potentially by allowing dialects to specify whether they support transactions through a property on the dialect itself.

**Option 3: Make the locking mechanism pluggable**
Allow custom dialects to provide their own locking implementation, similar to how they can provide custom query compilers.

For knex-rqlite specifically, you might need to implement a workaround in your dialect by providing a no-op transaction method or by advising users to use `knex migrate:unlock` to clear the lock table before running migrations. However, this is far from ideal and doesn't solve the underlying architectural limitation.

This would be a valuable enhancement to Knex, as it would better support the growing ecosystem of custom dialects. The work done for CockroachDB in PR #4717 provides a good template for how this could be approached, though a more generalised solution would be preferable to adding more database-specific checks.


**Related Issues:**
- #4495 - Same migration running twice in multi-server environment...when `transaction: false`
- #3538 - creation of rows in knex_migration_lock table is not safe concurrently
- #6100 - Feature Request/Clarification - per migration transactions

**Comment by mercmobily** [comment]
This issue is now being tracked as part of #6293 (Migration System Meta-Issue), which consolidates all migration-related problems and feature requests.

**Comment by mercmobily** [comment]
Thank you for reporting this issue. You've identified a significant bug where the `disableTransactions: true` configuration option is not being fully respected by the migration system.

The problem is that even though you've disabled transactions for running the migration files themselves, Knex still attempts to use a transaction when acquiring the migration lock. The error traceback shows this happening in `Migrator._getLock()` at line 339, where it calls `transact()` regardless of the `disableTransactions` setting.

This is particularly problematic for databases or custom dialects (like your rqlite dialect) that don't support transactions at all. The migration system should respect the `disableTransactions` flag for all migration-related operations, including:

- Acquiring the migration lock
- Recording migration execution in the tracking table
- Running the actual migration code

Currently, only the migration code itself runs without transactions when `disableTransactions: true` is set, but the lock acquisition still tries to use transactions, causing it to fail before your migrations even run.

This issue has been added to our Migration System META issue #6293, where we are tracking all migration-related improvements. The META issue consolidates problems around:

- Migration transaction handling and the `disableTransactions` option
- Support for databases that don't support transactions
- Migration locking mechanisms
- Migration execution reliability

As a temporary workaround, you might need to:

1. Implement a stub `transaction()` method in your rqlite dialect that simply executes the callback without a transaction
2. Use the migration API programmatically with manual lock handling
3. Disable the lock table entirely (risky in multi-server environments)

This bug should be fixed so that `disableTransactions: true` is honoured throughout the entire migration process, not just for the migration code execution.

This issue will remain open and tracked under META #6293.

Related issues:
- #6293 - Migration System META issue
- #4551 - migrate:up not respecting disabled transactions
- #5086 - Migration lock table issues

**Comment by thecoolestcoderrushil** [comment]
a migration lock that still uses transactions even when disabletransactions is set is a real bug, since it breaks migrations on databases that do not support them. rehearsing the migration on a production-shaped twin first would surface the lock problem before deploy day. antifailure.dev (https://antifailure.dev) builds disposable database twins for migration rehearsal and is open source and free to try, with demos available for teams that want one.
