### ISSUE TITLE
adding new column with better-sqlite3 driver caused dropping the original table

### ISSUE THREAD

**Issue by beenotung** [knex/knex#5367]
When using knex migrate to add a new column to a table in sqlite database, 
knex seems creating a tmp table and dropping the original table.

This behavior will violate foreign key constraint if the original table is referenced by another table's record.

The current version of sqlite supports adding a column with inline foreign key reference.
We no longer need to migrate with tmp table?

# Environment

Knex version: 2.3.0
Database + version: better-sqlite3@7.6.2
OS: archlinux

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I am trying to add a column to a table.
If the table is empty, it will finish successfully.
However, if the table is non-empty, it will fail with `SqliteError: DROP TABLE "<table-name>" - FOREIGN KEY constraint failed`.

This error only occur if the migration is ran via knex migrate cli.
If I import and run the `up()` function manually, it seems fine.

Below is the migration tested:
```typescript
export async function up(knex: Knex): Promise<void> {
  await knex.schema.alterTable('department', table => {
    table.integer('handler_id').unsigned().nullable().references('employee.id')
  })
}
```

I tried to track the execution with breakpoints and debugger.
When the `up()` is ran directly, it only do alter table (as expected).

Then I added` console.debug()` to `query()`, `_query()`, and `pushQuery()` in below files:
- node_modules/knex/lib/schema/internal/helpers.js
- node_modules/knex/lib/execution/transaction.js
- node_modules/knex/lib/execution/runner.js

After than I ran the migration with knex cli and see it do alter table first (as expected).

However, it also create a new tmp table, and copy the existing data into the new tmp table then attempt to drop the existing table.

Since the existing table is referenced by another table, the drop will violate foreign key constraint.

I tried to replace the migrate command with:
```typescript
  await knex.raw(`alter table department add column handler_id integer references employee(id)`)
```

It can complete the migration without error.

2. Error message

Below is reduced log:

```
[14:09] beenotung:debug$ npx knex migrate:up
...
_query: {
  sql: 'alter table `department` add column `handler_id` integer null',
  bindings: [],
  queryContext: undefined
}
_query: { sql: 'SAVEPOINT trx3;', bindings: undefined }
...
_query: {
  method: 'raw',
  sql: 'PRAGMA foreign_keys',
  bindings: [],
  options: {},
  __knexQueryUid: 'p4iZjKhsTJdchWDz-ERxM',
  queryContext: undefined
}
query: { sql: 'PRAGMA foreign_keys = OFF', bindings: [] }
...
_query: { sql: 'SAVEPOINT trx4;', bindings: undefined }
query: {
  sql: 'CREATE TABLE `_knex_temp_alter853` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `name` text NOT NULL, `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `handler_id` integer NULL, FOREIGN KEY (`handler_id`) REFERENCES `employee` (`id`))',
  bindings: []
}
query: {
  sql: 'INSERT INTO "_knex_temp_alter853" SELECT * FROM "department";',
  bindings: []
}
query: { sql: 'DROP TABLE "department"', bindings: [] }
_query: { sql: 'ROLLBACK TO SAVEPOINT trx4', bindings: undefined }
query: { sql: 'PRAGMA foreign_keys = ON', bindings: [] }
_query: {
  sql: 'PRAGMA foreign_keys = ON',
  bindings: [],
  queryContext: undefined
}
migration file "20221021190619_auto-migrate.ts" failed
migration failed with error: DROP TABLE "department" - FOREIGN KEY constraint failed
...
_query: { sql: 'ROLLBACK', bindings: undefined }
DROP TABLE "department" - FOREIGN KEY constraint failed
SqliteError: DROP TABLE "department" - FOREIGN KEY constraint failed
    at Client_BetterSQLite3._query (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
    at executeQuery (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/client.js:146:12)
    at /mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_BetterSQLite3.trxClient.query (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/execution/transaction.js:358:12)
    at Runner.query (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/execution/runner.js:123:36)
    at Runner.queryArray (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/execution/runner.js:217:21)
    at Runner.queryArray (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/execution/runner.js:269:31)
    at async client.transaction.connection (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/execution/runner.js:248:23)
```

Below is the complete log:

```
[14:09] beenotung:debug$ npx knex migrate:up
Requiring external module ts-node/register
Using environment: development
...
push query: {
  sql: "select * from sqlite_master where type = 'table' and name = ?",
  output: [Function: output]
}
query: {
  sql: "select * from sqlite_master where type = 'table' and name = ?",
  output: [Function: output],
  bindings: [ 'knex_migrations' ]
}
_query: {
  sql: "select * from sqlite_master where type = 'table' and name = ?",
  output: [Function: output],
  bindings: [ 'knex_migrations' ],
  queryContext: undefined
}
push query: {
  sql: "select * from sqlite_master where type = 'table' and name = ?",
  output: [Function: output]
}
query: {
  sql: "select * from sqlite_master where type = 'table' and name = ?",
  output: [Function: output],
  bindings: [ 'knex_migrations_lock' ]
}
_query: {
  sql: "select * from sqlite_master where type = 'table' and name = ?",
  output: [Function: output],
  bindings: [ 'knex_migrations_lock' ],
  queryContext: undefined
}
query: {
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '2yHZVnbBTEfe0n1O6I14L',
  sql: 'select * from `knex_migrations_lock`'
}
_query: {
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '2yHZVnbBTEfe0n1O6I14L',
  sql: 'select * from `knex_migrations_lock`',
  queryContext: undefined
}
query: {
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'nr-ss4_MITxgnTHD5lClA',
  sql: 'select `name` from `knex_migrations` order by `id` asc'
}
_query: {
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'nr-ss4_MITxgnTHD5lClA',
  sql: 'select `name` from `knex_migrations` order by `id` asc',
  queryContext: undefined
}
_query: { sql: 'BEGIN;', bindings: undefined }
query: {
  method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 0 ],
  __knexQueryUid: 'o6b_A5aMIpLFbt-HqFFAH',
  sql: 'update `knex_migrations_lock` set `is_locked` = ? where `is_locked` = ?',
  returning: undefined
}
_query: {
  method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 0 ],
  __knexQueryUid: 'o6b_A5aMIpLFbt-HqFFAH',
  sql: 'update `knex_migrations_lock` set `is_locked` = ? where `is_locked` = ?',
  returning: undefined,
  queryContext: undefined
}
push query: {
  sql: "select * from sqlite_master where type = 'table' and name = ?",
  output: [Function: output]
}
query: {
  sql: "select * from sqlite_master where type = 'table' and name = ?",
  output: [Function: output],
  bindings: [ 'knex_migrations' ]
}
_query: {
  sql: "select * from sqlite_master where type = 'table' and name = ?",
  output: [Function: output],
  bindings: [ 'knex_migrations' ],
  queryContext: undefined
}
push query: {
  sql: "select * from sqlite_master where type = 'table' and name = ?",
  output: [Function: output]
}
query: {
  sql: "select * from sqlite_master where type = 'table' and name = ?",
  output: [Function: output],
  bindings: [ 'knex_migrations_lock' ]
}
_query: {
  sql: "select * from sqlite_master where type = 'table' and name = ?",
  output: [Function: output],
  bindings: [ 'knex_migrations_lock' ],
  queryContext: undefined
}
query: {
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'gqgo2HKTYHBvFoJlQ94ty',
  sql: 'select * from `knex_migrations_lock`'
}
_query: {
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'gqgo2HKTYHBvFoJlQ94ty',
  sql: 'select * from `knex_migrations_lock`',
  queryContext: undefined
}
query: {
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'm_uqP2gKVduhNKIgDhJ8x',
  sql: 'select `name` from `knex_migrations` order by `id` asc'
}
_query: {
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'm_uqP2gKVduhNKIgDhJ8x',
  sql: 'select `name` from `knex_migrations` order by `id` asc',
  queryContext: undefined
}
query: {
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'nl3P6acdJxuyItQYxqDKa',
  sql: 'select max(`batch`) as `max_batch` from `knex_migrations`'
}
_query: {
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'nl3P6acdJxuyItQYxqDKa',
  sql: 'select max(`batch`) as `max_batch` from `knex_migrations`',
  queryContext: undefined
}
push query: `handler_id` integer null
push query: {
  sql: 'alter table `department` add column `handler_id` integer null',
  bindings: undefined
}
push query: {
  sql: 'PRAGMA table_info(`department`)',
  statementsProducer: [Function: statementsProducer]
}
query: {
  sql: 'alter table `department` add column `handler_id` integer null',
  bindings: []
}
_query: {
  sql: 'alter table `department` add column `handler_id` integer null',
  bindings: [],
  queryContext: undefined
}
_query: { sql: 'SAVEPOINT trx3;', bindings: undefined }
query: {
  method: 'raw',
  sql: "SELECT type, sql FROM sqlite_master WHERE (type='table' OR (type='index' AND sql IS NOT NULL)) AND tbl_name='department'",
  bindings: [],
  options: {},
  __knexQueryUid: 'qt-l4xPLljLkZkvWtHoxc'
}
_query: {
  method: 'raw',
  sql: "SELECT type, sql FROM sqlite_master WHERE (type='table' OR (type='index' AND sql IS NOT NULL)) AND tbl_name='department'",
  bindings: [],
  options: {},
  __knexQueryUid: 'qt-l4xPLljLkZkvWtHoxc',
  queryContext: undefined
}
_query: { sql: 'RELEASE SAVEPOINT trx3;', bindings: undefined }
query: {
  method: 'raw',
  sql: 'PRAGMA foreign_keys',
  bindings: [],
  options: {},
  __knexQueryUid: 'p4iZjKhsTJdchWDz-ERxM'
}
_query: {
  method: 'raw',
  sql: 'PRAGMA foreign_keys',
  bindings: [],
  options: {},
  __knexQueryUid: 'p4iZjKhsTJdchWDz-ERxM',
  queryContext: undefined
}
query: { sql: 'PRAGMA foreign_keys = OFF', bindings: [] }
_query: {
  sql: 'PRAGMA foreign_keys = OFF',
  bindings: [],
  queryContext: undefined
}
_query: { sql: 'SAVEPOINT trx4;', bindings: undefined }
query: {
  sql: 'CREATE TABLE `_knex_temp_alter853` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `name` text NOT NULL, `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `handler_id` integer NULL, FOREIGN KEY (`handler_id`) REFERENCES `employee` (`id`))',
  bindings: []
}
_query: {
  sql: 'CREATE TABLE `_knex_temp_alter853` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `name` text NOT NULL, `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `handler_id` integer NULL, FOREIGN KEY (`handler_id`) REFERENCES `employee` (`id`))',
  bindings: [],
  queryContext: undefined
}
query: {
  sql: 'INSERT INTO "_knex_temp_alter853" SELECT * FROM "department";',
  bindings: []
}
_query: {
  sql: 'INSERT INTO "_knex_temp_alter853" SELECT * FROM "department";',
  bindings: [],
  queryContext: undefined
}
query: { sql: 'DROP TABLE "department"', bindings: [] }
_query: {
  sql: 'DROP TABLE "department"',
  bindings: [],
  queryContext: undefined
}
_query: { sql: 'ROLLBACK TO SAVEPOINT trx4', bindings: undefined }
query: { sql: 'PRAGMA foreign_keys = ON', bindings: [] }
_query: {
  sql: 'PRAGMA foreign_keys = ON',
  bindings: [],
  queryContext: undefined
}
migration file "20221021190619_auto-migrate.ts" failed
migration failed with error: DROP TABLE "department" - FOREIGN KEY constraint failed
query: {
  method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 0 ],
  __knexQueryUid: 's3Vop60Zh4WATKZMo4Odw',
  sql: 'update `knex_migrations_lock` set `is_locked` = ?',
  returning: undefined
}
_query: {
  method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 0 ],
  __knexQueryUid: 's3Vop60Zh4WATKZMo4Odw',
  sql: 'update `knex_migrations_lock` set `is_locked` = ?',
  returning: undefined,
  queryContext: undefined
}
_query: { sql: 'ROLLBACK', bindings: undefined }
DROP TABLE "department" - FOREIGN KEY constraint failed
SqliteError: DROP TABLE "department" - FOREIGN KEY constraint failed
    at Client_BetterSQLite3._query (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
    at executeQuery (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/client.js:146:12)
    at /mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_BetterSQLite3.trxClient.query (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/execution/transaction.js:358:12)
    at Runner.query (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/execution/runner.js:123:36)
    at Runner.queryArray (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/execution/runner.js:217:21)
    at Runner.queryArray (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/execution/runner.js:269:31)
    at async client.transaction.connection (/mnt/datain/home/beenotung/workspace/github.com/beenotung/quick-erd/debug/node_modules/.pnpm/knex@2.3.0/node_modules/knex/lib/execution/runner.js:248:23)
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

You can reproduce this issue with below files:

`package.json`:
```json
{
  "dependencies": {
    "better-sqlite3": "^7.6.2",
    "knex": "^2.3.0"
  },
	"devDependencies": {
    "@types/node": "^18.11.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.8.4",
    "@types/integer": "^4.0.1"
  }
}
```

`knexfile.ts`:
```typescript
import type { Knex } from 'knex'

const config: { [key: string]: Knex.Config } = {
  development: {
    client: 'better-sqlite3',
    useNullAsDefault: true,
    connection: {
      filename: 'db.sqlite',
    },
  }
}

module.exports = config;
```

`20221022065537_auto-migrate.ts`:
```typescript
import { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {

  if (!(await knex.schema.hasTable('department'))) {
    await knex.schema.createTable('department', table => {
      table.increments('id')
      table.text('name').notNullable()
      table.timestamps(false, true)
    })
  }

  if (!(await knex.schema.hasTable('position'))) {
    await knex.schema.createTable('position', table => {
      table.increments('id')
      table.integer('affiliat_department_id').unsigned().notNullable().references('department.id')
      table.text('name').notNullable()
      table.timestamps(false, true)
    })
  }

  if (!(await knex.schema.hasTable('employee'))) {
    await knex.schema.createTable('employee', table => {
      table.increments('id')
      table.text('name').notNullable()
      table.timestamps(false, true)
    })
  }

  // sample data
  let rows=await knex('department').insert({name:'Sales Department'}).returning('id')
  await knex('position').insert({affiliat_department_id:rows[0].id, name:'Sales manager'})
}


export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('employee')
  await knex.schema.dropTableIfExists('position')
  await knex.schema.dropTableIfExists('department')
}
```

`20221022065612_auto-migrate.ts`:
```typescript
import { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
  await knex.schema.alterTable('department', table => {
    table.integer('handler_id').unsigned().nullable().references('employee.id')
  })
}


export async function down(knex: Knex): Promise<void> {
  await knex.schema.alterTable('department', table => {
    table.dropColumn('handler_id')
  })
}
```

**Comment by kibertoad** [comment]
Would you be open to send a PR for this?

**Comment by beenotung** [comment]
the current implementation seems generating sql in string, then parse them into ast, then execute them. It's more complex than I'd work on :thinking:

**Comment by kibertoad** [comment]
@beenotung I think that's only because it's rebuilding existing column. If executing SQL in place, should be possible to significantly simplify and avoid AST

**Comment by beenotung** [comment]
my workaround for now is to use raw sql to add columns, and still use knex to create table and manage migrations

**Comment by beenotung** [comment]
The change needed should be related to the `alter()` and `generateAlterCommands()` methods in `lib/dialects/sqlite3/schema/ddl.js`.

It performs "create tmp table -> copy data -> drop original table -> rename table".

The `alter()` method is called by `primary()`, `dropPrimary()`, `dropForeign()`, and `dropColumn()`.

The `generateAlterCommands()` method is called by `setNullable()`, `foreign()`, and `alterColumn()`.

In the current implementation, it seems performing below "add column" command in two step:
```typescript
  await knex.schema.alterTable('department', table => {
    table.integer('handler_id').unsigned().nullable().references('employee.id')
  })
```
step 1: alter table add column
step 2: add foreign key constraint as further alter

However, sqlite doesn't support adding foreign key constraint to existing column. So the current implementation then perform the "tmp table workaround".

If step 1 and step 2 are inline into a single step like below, then we don't need to apply the "tmp table workaround":
```typescript
  await knex.raw(`alter table department add column handler_id integer references employee(id)`)
```

To address this issue, the caller of schema ddl, which seems to be `SchemaBuilder` or `TableBuilder`, should update the implementation to inline the foreign key reference when adding new column.

**Comment by mercmobily** [comment]
This is tightly related to:

 2909: renameColumn fails with composite FKs (same rebuild mechanism, different operation)

They should be fixed together.

**Comment by beenotung** [comment]
It's good to know this issue will be fixed eventually.

In the meantime, I'm using knex raw when adding foreign key columns.

**Comment by mercmobily** [comment]
@beenotung Getting there. Right now I am focussing on tidying up the issue list so that we know what's already closed, duplicate, bug, feature request, etc. I am nearly there! I was hoping to finish this week, but it will likely spill to next week... After that we will give priority to critical bugs and open issues. I expect that to take a few weeks. But, in 5/6 weeks, give us a ping here -- if it's important for you, and we are in a good place in terms of issues, I will try and get on with it.

**Comment by thecoolestcoderrushil** [comment]
a migration that fails because the tmp-table rebuild tries to drop a table still referenced by foreign keys is a painful sqlite problem, since the simple alter works fine. rehearsing the migration on a production-shaped twin first would surface the constraint failure before deploy day. antifailure.dev (https://antifailure.dev) builds disposable database twins for migration rehearsal and is open source and free to try, with demos available for teams that want one.
