### ISSUE TITLE
Knex minimal example with docker

### ISSUE THREAD

**Issue by brunolnetto** [knex/knex#5394]
# Environment

Knex version:
Database + version: postgres:14.5
OS: Linux
# Questions about how to use knex

I fail miserably to reproduce a minimal example with docker and Postgres. If you see repository content available [here](https://github.com/web-needle/sappio), you will see my efforts are legit. I ask politely and tender, however very vigorously, for either a Pull Request or instructions to make this minimal example feasible and working.

I can currently run the command `docker-compose up -d` and connect to the database server instance. However, the command run `npm run migrations` exits with log below.

```
knex: Required configuration option 'client' is missing.
Error: knex: Required configuration option 'client' is missing.
    at new Client (/home/brunolnetto/github/web-needle/sappio/node_modules/knex/lib/client.js:58:13)
    at knex (/home/brunolnetto/github/web-needle/sappio/node_modules/knex/lib/knex-builder/Knex.js:16:28)
    at initKnex (/home/brunolnetto/github/web-needle/sappio/node_modules/knex/bin/cli.js:84:10)
    at async Command.<anonymous> (/home/brunolnetto/github/web-needle/sappio/node_modules/knex/bin/cli.js:247:26)
```

**Comment by mercmobily** [comment]
Hi! Thanks for sharing the repo and the exact error.  This answer comes much too late, answering here for completeness and for google posterity...

The failure likely comes from Knex not receiving a `client` in its configuration when the CLI runs your migrations.

Sorry we couldn't be of help when you asked for it.
