### ISSUE TITLE
Migrartion make raise an error

### ISSUE THREAD

**Issue by vsedyshev-intermedia** [knex/knex#5421]
# Environment

Knex version: 2.3.0
OS: Linux

# Bug

1. Create `knexfile.mjs` with next content
```
const config = {
    client: ...,
    connection: ...,
    migrations: {
        directory: './migrations'.
    },
    seeds: {
        directory: './seeds'.
    },
};
export default config;
export const {client, connection, migrations, seeds} = config;
```
2. Execute `knex migrate:make migration_name` raise an next error output:
```
Using environment: development
Using environment: development
Using environment: development
Failed to resolve config file, knex cannot determine where to generate migrations
The "path" argument must be of type string. Received null
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1098:7)
    at /home/vsedyshev/Work/HPBX-11369/quality-center/server/node_modules/knex/lib/migrations/migrate/MigrationGenerator.js:77:19
    at Array.map (<anonymous>)
    at MigrationGenerator._absoluteConfigDirs (/home/vsedyshev/Work/HPBX-11369/quality-center/server/node_modules/knex/lib/migrations/migrate/MigrationGenerator.js:71:24)
    at MigrationGenerator._ensureFolder (/home/vsedyshev/Work/HPBX-11369/quality-center/server/node_modules/knex/lib/migrations/migrate/MigrationGenerator.js:28:23)
    at MigrationGenerator.make (/home/vsedyshev/Work/HPBX-11369/quality-center/server/node_modules/knex/lib/migrations/migrate/MigrationGenerator.js:20:16)
    at Migrator.make (/home/vsedyshev/Work/HPBX-11369/quality-center/server/node_modules/knex/lib/migrations/migrate/Migrator.js:315:27)
    at Command.<anonymous> (/usr/lib/node_modules/knex/bin/cli.js:231:12)
```

Look like `directory` value in `MigrationGenerator.js:77` is `null`. Could you please suggest me  where is born?

**Comment by kibertoad** [comment]
Judging by the error, your config file is being ignored. Csn you explicitly specify it when running knex:migrate?

**Comment by vsedyshev-intermedia** [comment]
> Judging by the error, your config file is being ignored. Can you explicitly specify it when running knex:migrate?

Yes. I was try next command `knex --knexfile=./knexfile.mjs migrate:make migration_name` and receive next output:

```
Requiring external module /usr/lib/node_modules/knex/node_modules/interpret/mjs-stub
Created Migration: ...20221228215404_migration_name.mjs
```

Look as working. But why my config file is being ignored?

**Comment by mercmobily** [comment]
This is way too old now. Sorry...

`migrate:make` delegates to `MigrationGenerator` which resolves the stub and writes the file (lib/migrations/migrate/MigrationGenerator.js:1–40). Errors here usually come from an invalid stub path, missing extension resolution, or filesystem permissions. The CLI resolves the stub via `--stub` or falls back to the default in the dialect’s stub directory (bin/cli.js:220–255 for migrations). Without the error text, we cannot pinpoint.

In the code: lib/migrations/migrate/MigrationGenerator.js:1–40 (file write), bin/cli.js:220–255 (CLI wiring).

Since I don't have crucial information like command ran,  CLI flags, the knexfile (redact secrets), and the full error and stack, I can't really help/

Closing this issue... Sorry.
