### ISSUE TITLE
Updating a column with an object throws an error, but inserting the same object into the column does not. 

### ISSUE THREAD

**Issue by cloudytraveller** [knex/knex#5450]
# Environment
Knex version: 2.3.0
Database + version: Sqlite3
OS: Ubuntu

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Inserting a new item into a table with one column that has an object, it gets converted to a string, as expected.
When *updating* said item, with similar object structure to how it was inserted, it throws an error. Look at the comments in the test code.
2. Error message
```
(node:407) UnhandledPromiseRejectionWarning: TypeError: update `test` set `preferences` = {"channels":[1,2,3,4,5],"anotherSetting":false} where `id` = 1 - SQLite3 can only bind numbers, strings, bigints, buffers, and null
    at Client_BetterSQLite3._query (/sandbox/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
    at executeQuery (/sandbox/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/sandbox/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/sandbox/node_modules/knex/lib/execution/runner.js:123:36)
    at ensureConnectionCallback (/sandbox/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/sandbox/node_modules/knex/lib/execution/runner.js:300:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Runner.run (/sandbox/node_modules/knex/lib/execution/runner.js:30:19)
    at async run (/sandbox/src/index.js:31:3)
```
3. Reduced test code
(Couldn't use RunKit because RunKit does not support binarys, which better-sqlite3 has. Maybe reconsider the code test platform for issues?)
https://codesandbox.io/s/modest-aryabhata-u5r7dq?file=/src/index.js

**Comment by mercmobily** [comment]
This issue is being tracked as part of #6294 (Update vs Insert Behavior Inconsistencies META), which consolidates issues where update() and insert() handle values differently.

**Comment by mercmobily** [comment]
Thank you for this detailed bug report with an excellent reproduction. You've identified another significant inconsistency between how Knex handles objects in `insert()` versus `update()` operations.

The behaviour you've discovered:

**INSERT:** Objects are automatically serialised to JSON strings
```javascript
knex('test').insert({
  id: 1,
  preferences: {channels: [1,2,3], anotherSetting: false}
})
// Works! Object is converted to JSON string: '{"channels":[1,2,3],"anotherSetting":false}'
```

**UPDATE:** Objects cause a binding error
```javascript
knex('test').update({
  preferences: {channels: [1,2,3], anotherSetting: false}
}).where('id', 1)
// Error: SQLite3 can only bind numbers, strings, bigints, buffers, and null
// The object is NOT converted to JSON
```

**Why this happens:**

The error message reveals the problem - in the UPDATE query, the object literal `{"channels":[1,2,3,4,5],"anotherSetting":false}` is being placed directly in the SQL string instead of being bound as a parameter. This happens because:

1. **INSERT path:** Objects are detected and serialised to JSON before binding
2. **UPDATE path:** Objects are not serialised, and the driver rejects them as invalid bind parameters

The error "SQLite3 can only bind numbers, strings, bigints, buffers, and null" confirms that the object is reaching the driver layer without being converted to a JSON string first.

**This is clearly a bug** because:

1. The same data structure should behave identically in insert and update
2. Both operations are writing to the same column type
3. There's no documented reason why object serialisation would differ
4. It breaks the principle of least surprise

**Impact:**

This inconsistency makes it very difficult to write generic data persistence functions that work for both insert and update operations. Developers have to remember to `JSON.stringify()` objects manually for updates but not for inserts.

**Current workaround:**

Manually serialise objects for updates:
```javascript
knex('test').update({
  preferences: JSON.stringify({channels: [1,2,3], anotherSetting: false})
}).where('id', 1)
```

But this shouldn't be necessary - Knex should handle object serialisation consistently across all write operations.

**Expected behaviour:**

Objects passed to update() should be automatically serialised to JSON strings, exactly like they are in insert() operations. This would make the API consistent and predictable.

This issue has been added to META #6294 (Update vs Insert Behavior Inconsistencies), which consolidates issues where update() and insert() handle values differently. These inconsistencies need to be fixed to provide a coherent and predictable API.

This issue will remain open and tracked under META #6294.

Related issues:
- #6294 - Update vs Insert Behavior Inconsistencies META
- #5488 - Different treatment of undefined values for update vs insert
- #5320 - Can't insert data to json column when array used as top-level
