### ISSUE TITLE
Uncaught exception occasionally when using timeout

### ISSUE THREAD

**Issue by LukeNotable** [knex/knex#5454]
# Environment

Knex version: 2.4.0
Database + version: PostgreSQL 14.6 (via postgres:14-alpine docker)
OS: macOS Ventura 13.1

# Bug

Our production app is crashing once in a while with an uncaught exception. After investigating, my best guess so far is that some kind of race condition leads to mishandling connection errors when the query has `.timeout()` (we get lots of random `terminating connection due to conflict with recovery` in particular). 

Trying to get a minimal reproduction, I came up with this:

<details>

<summary>code</summary>

```js
// index.mjs

import knex from "knex";

process.on("uncaughtException", (err) => {
  console.error("*** UNCAUGHT EXCEPTION ***", err);
  process.exit(1);
});

const k = knex({
  client: "pg",
  connection: {
    user: "whatever",
    password: "whatever",
    database: "whatever",
  },
  pool: {
    min: 2,
    max: 40,
    idleTimeoutMillis: 5000,
  },
  asyncStackTraces: true,
});

async function f() {
  try {
    await k
      .raw("do $$ begin perform pg_sleep(0.001); raise exception 'boo'; end $$")
      .timeout(3, { cancel: true });
    console.log("Knex okay!");
  } catch (err) {
    console.error("Knex error!", err.message);
  }
}

await Promise.all([...Array(100000).keys()].map(() => f()));

await k.destroy();
```

</details>

If I start this running and then shut down the postgres docker container, _usually_ I get an uncaught exception:

```
*** UNCAUGHT EXCEPTION *** error: terminating connection due to administrator command
    at Parser.parseErrorMessage (/Users/luke/vivaa/backend/ppp/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/luke/vivaa/backend/ppp/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/luke/vivaa/backend/ppp/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/luke/vivaa/backend/ppp/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

I noticed a possibly-related [issue](https://github.com/brianc/node-postgres/issues/2439) in `pg-protocol`, which the stack trace suggests is involved, but _usually_ these connection errors are handled just fine, with just a rare uncaught exception like the one above.

**Comment by OlivierCavadenti** [comment]
Released in [2.5.0](https://github.com/knex/knex/releases/tag/2.5.0)
