### ISSUE TITLE
JSON array are considered "invalid input" for type json when updating (insert works though)

### ISSUE THREAD

**Issue by nobarany** [knex/knex#5465]
# Environment

Knex version: 2.4.2
Database + version: PostgreSQL 14
OS: GCP cloud sql env

# Bug

In postgres json columns we can save a json array. With knex, this works when inserting, but not when updating.
The error message is ` invalid input syntax for type json`

My current workaround is to `JSON.stringify` the array.

The following works:
```
knex('table')
    .insert({list: ['item']})
```

The following does not work:
```
knex('table')
    .where({ uuid })
    .update({list: ['item']})
```

workaround:
```
knex('table')
    .where({ uuid })
    .update({list: JSON.stringify(['item'])})
```

**Comment by yjw0628** [comment]
I have the same problem

**Comment by mouhannad-sh** [comment]
I'm facing the same issue with, it can be particularly frustrating with typescript

**Comment by mouhannad-sh** [comment]
Managed to get a workaround working for this using events

```ts
const db = require('knex')(/*...config..*/).on("query", (query) => {
  // A workaround to fix JSON array inserts/updates until this issue is resolved
  if (["update", "insert"].includes(query.method) && Array.isArray(query.bindings)) {
    for (let i = 0; i < query.bindings.length; i++) {
      if (Array.isArray(query.bindings[i])) {
        query.bindings[i] = JSON.stringify(query.bindings[i]);
      }
    }
  }
})
```

**Comment by Jiia** [comment]
I have the exact same issue with both inserts and updates on knex 3.1.0 and older versions as well. Manually stringifying before passing to knex works fine 👍 

```js
const query = knex.insert({ some_json_column: [1,2,3] }).into('knex_bug')
console.log(query.toQuery())
await query
```

```
insert into "knex_bug" ("some_json_column") values ('{1,2,3}')
{
  method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ [ 1, 2, 3 ] ],
  __knexQueryUid: 'MveF1iYVXwK0jTu382_lZ',
  sql: 'insert into "knex_bug" ("some_json_column") values (?)',
  returning: undefined
}
/app/node_modules/pg-protocol/src/parser.ts:369
      name === 'notice' ? new NoticeMessage(length, messageValue) : new DatabaseError(messageValue, length, name)
                                                                    ^
error: insert into "knex_bug" ("some_json_column") values ($1) - invalid input syntax for type json
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Socket.Readable.push (node:internal/streams/readable:286:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 195,
  severity: 'ERROR',
  code: '22P02',
  detail: 'Expected ":", but found ",".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: `JSON data, line 1: {"1",...\nunnamed portal parameter $1 = '...'`,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'jsonfuncs.c',
  line: '627',
  routine: 'json_ereport_error'
}
```

**Comment by Jiia** [comment]
Our production environment is using Postgres 14 while I'm running Postgres 15 locally. I'm wondering if that has something to do with it.

**Comment by itsMarydan** [comment]
The workaround provided by @mouhannad-sh works, but it would be nice to get a permanent fix for this soon.
Thanks! @mouhannad-sh 
+1

**Comment by jesspoemape** [comment]
Thanks for the workaround. Just a quick note: using this method will insert a string into the database instead of the expected array. This means that when you retrieve the data, you'll need to parse the stringified array before applying any array methods. A more robust workaround might be to execute a raw SQL update, which would preserve the correct data type.

**Comment by mercmobily** [comment]
OK this one was a hard one. It will be closed in favour of #6126 which now has a comment that includes ALL of this information.

This issue remains present in the current version of Knex. The root cause lies in a fundamental ambiguity in how JavaScript arrays should be serialised for PostgreSQL: they could represent either native PostgreSQL arrays (e.g., `INTEGER[]`) or JSON arrays stored in JSONB columns. Since Knex has no knowledge of column types at query time, it cannot automatically determine the correct serialisation format.

The issue manifests differently depending on which query method you use:

**Insert operations** (using `.insert()`): Currently work correctly for plain objects but arrays in JSONB columns require manual stringification. This is even though PostgreSQL supports JSON arrays nativly.

**Update operations** (using `.update()`): Objects are automatically stringified when using the two-argument form `.update('column', {object})` (see lib/query/querybuilder.js:1239-1240), but arrays are NOT stringified in either form. This creates an inconsistency where `.update('column', {object})` works but `.update('column', [array])` fails.

The specific code handling this in lib/query/querybuilder.js:1238-1243 only checks `isPlainObject(returning)`:

```javascript
if (isString(values)) {
  if (isPlainObject(returning)) {
    obj[values] = JSON.stringify(returning);
  } else {
    obj[values] = returning;  // Arrays pass through here unchanged!
  }
```

When arrays reach the PostgreSQL dialect's `_escapeBinding` method (lib/dialects/postgres/index.js:304-306), they are converted to PostgreSQL's native array format `{1,2,3}` by the `arrayString` function (lines 343-359). This is correct behaviour for native PostgreSQL array columns, but produces invalid syntax for JSONB columns.

There have been multiple attempts to address this issue:

**PR #5063** (March 2022): Added JSON stringification for objects in update operations, but did not handle arrays.

**PR #5321** (September 2022): Attempted to fix array handling by adding `|| Array.isArray(value)` to the stringification check in lib/client.js. However, this created a new problem.

**PR #5439** (January 2023): **Reverted PR #5321** because the automatic array stringification broke legitimate use cases where users were inserting arrays into native PostgreSQL array columns (like `TEXT[]` or `INTEGER[]`). The test case added in PR #5439 demonstrates this:

```javascript
await knex('redirect_array')
  .insert({
    name: 'knex',
    redirect_urls: ['https://knexjs.org/', 'https://knexjs.org/guide/'],
  })
```

For a `TEXT[]` column, this must remain as a JavaScript array so the pg driver can properly format it as `ARRAY['url1', 'url2']`, not as a JSON string `'["url1", "url2"]'`.

This revert explains why your issue persists even though there was an attempt to fix it. The fix was technically correct for JSONB columns but broke PostgreSQL native array columns.

As documented in the schema builder guide (docs/src/guide/schema-builder.md:589), the official workaround is to use `JSON.stringify()`:

```javascript
knex('table')
  .where({ uuid })
  .update({ list: JSON.stringify(['item']) })
```

This applies to both insert and update operations when working with arrays in JSONB columns.

The workaround suggested by @mouhannad-sh using query events (intercepting and modifying bindings) is clever but has significant downsides:

- It modifies ALL array bindings regardless of column type, breaking native array columns
- It creates action-at-a-distance behaviour that's difficult to debug
- It runs on every query, adding overhead
- As @jesspoemape noted, if implemented incorrectly it can cause type mismatches

The safest approach is explicit stringification at the application level where you have full context about which columns are JSONB vs native arrays.

Several possible solutions have been discussed by maintainers:

**Column-aware type hints**: @elhigu suggested wrapper helpers like `knex.lit()` or `knex.json()` that would indicate the desired serialisation format:

```javascript
// Hypothetical API
knex('table').update({
  jsonb_column: knex.json(['item']),  // Stringify as JSON
  array_column: ['item']              // Keep as native array
})
```

This was discussed in issues #791, #2229, and #3805, with @wubzz also mentioning work on casting support.

**Automatic column introspection**: Query the database schema to determine column types and automatically apply correct serialisation. However, this would:

- Add significant performance overhead
- Require caching mechanisms
- Complicate the API
- Not work for dynamic tables or raw queries

**Configuration-based approach**: Allow users to specify which columns are JSONB in the Knex configuration:

```javascript
knex({
  client: 'pg',
  jsonColumns: {
    'users': ['preferences', 'metadata'],
    'profiles': ['settings']
  }
})
```

**Breaking change**: Always require explicit stringification for all object/array values in JSON columns. This would make behaviour predictable but break existing code.

The current behaviour is documented but clearly causes confusion, as evidenced by numerous duplicate issues. Several improvements could help:

**Enhanced documentation**: Add prominent warnings and examples in the query builder documentation, not just the schema builder section. Include TypeScript examples showing how to handle this safely with types.

**Better error messages**: Detect common patterns and provide helpful error messages:
```
KnexError: Array value provided for PostgreSQL query. If inserting into a JSONB column, use JSON.stringify(value). If inserting into a native array column (e.g., TEXT[]), this error indicates a bug - please report it.
```

**TypeScript support**: Add helper types that make it explicit when stringification is needed:
```typescript
type JsonbValue<T> = string;  // Must be pre-stringified
interface Profile {
  id: number;
  name: string;
  preferences: JsonbValue<UserPreferences>;  // Type indicates string expected
}
```

**Status**: Confirmed issue, working as currently designed. Requires explicit `JSON.stringify()` for arrays in JSONB columns.

**Workaround**: Always use `JSON.stringify()` when inserting or updating arrays in PostgreSQL JSONB columns:
```javascript
// Both insert and update
knex('table').insert({ list: JSON.stringify(['item']) })
knex('table').where({ uuid }).update({ list: JSON.stringify(['item']) })
```

**Root cause**: Ambiguity between PostgreSQL native arrays and JSON arrays prevents automatic detection. Previous fix attempts (PR #5321) were reverted (PR #5439) because they broke native array column handling.

**Future solution**: Likely requires an API enhancement to explicitly indicate value types, such as wrapper functions (`knex.json()`) or configuration-based column type hints. This would be a feature request rather than a bug fix.


Related issues (all describing the same underlying problem with varying specifics):

- #6126 - Documentation improvement request for JSONB array handling
- #3805 - Incorrect handling of arrays in JSONB columns
- #4642 - Arrays being converted to PostgreSQL format in JSONB columns
- #4635 - Inserting empty arrays into JSONB columns
- #1546 - Update JSONB column with array of strings
- #1349 - PostgreSQL JSON insert problem
- #1004 - PostgreSQL JSON root array values serialised incorrectly
- #315 - JSON array becomes key of JSON object
- #569 - PostgreSQL array columns (native arrays, not JSON)
- #791 - WHERE IN with array arguments (related to type ambiguity)
- #2229 - Discussion about array type handling
- #519 - Conflict with PostgreSQL JSONB operators
