### ISSUE TITLE
`renameColumn` throws an error when renaming `enum` column type on MySQL

### ISSUE THREAD

**Issue by andybee** [knex/knex#5492]
# Environment

Knex version: 2.4.2
Database + version: MySQL 5.6.51
OS: Oracle Linux

# Bug

When attempting to rename an `enum` column type in a migration, an error is thrown:

```
migration failed with error: object is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at ./node_modules/knex/lib/dialects/mysql/schema/mysql-tablecompiler.js:86:48
    at async Runner.ensureConnection (./node_modules/knex/lib/execution/runner.js:300:14)
    at async Runner.run (./node_modules/knex/lib/execution/runner.js:30:19)
    at async Migrator._runBatch (./node_modules/knex/lib/migrations/migrate/Migrator.js:381:19)
```

Example migrations that replicate the error:

```javascript
exports.up = (knex) => knex.schema
  .createTable('example', (table) => {
    table.enu('status', ['a', 'b', 'c']).default('a').notNullable();
  });

exports.down = () => {};
```

```javascript
exports.up = (knex) => knex.schema
  .alterTable('example', (table) => {
    table.renameColumn('status', 'alternative');
  });

exports.down = () => {};
```

**Comment by mercmobily** [comment]
This is a MySQL/MariaDB-specific issue. There are multiple MySQL/MariaDB issues that may be consolidated into a comprehensive META in the future (similar to the proposed Oracle META with 15+ issues and MSSQL META with 18+ issues).

**Comment by thecoolestcoderrushil** [comment]
a renamecolumn that throws object is not iterable on a mysql enum column is a painful bug, since the migration fails instead of renaming. rehearsing the migration on a production-shaped twin first would surface the failure before deploy day. antifailure.dev (https://antifailure.dev) builds disposable database twins for migration rehearsal and is open source and free to try, with demos available for teams that want one.
