### ISSUE TITLE
knex in monorepo can't find sqlite3 installation.

### ISSUE THREAD

**Issue by codelocksdev** [knex/knex#5495]
# Environment

Knex version: 2.4.2
Database + version: sqlite3@5.1.4
OS: Windows 10 and Mac Ventura 13.1

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I have an @nrwl/nx setup and I have my knex code set up in a library file that is then being imported in my backend node app, with some simple test insertion and then printing the query to the console per the objectionjs getting started docs.

When I build the node app, everything compiles and runs, until the `knex: run` background process happens at which point I get error output that looks like it's trying to npm install sqlite3, which I already have installed at the root of my monorepo project. The error is indicating to me that the CWD is not what knex is expecting, so it's #1 not finding my node_modules and therefore not finding my sqlite3 installation, and #2 it's calling npm install in a directory that doesn't have a package.json and so that's failing too. 

2. Error message

```
> nx run backend:serve

[ watch ] build succeeded, watching for changes...
Debugger listening on ws://localhost:9229/fa3267c7-c2c9-4312-8cd3-5c675c1c0c19
Debugger listening on ws://localhost:9229/fa3267c7-c2c9-4312-8cd3-5c675c1c0c19
For help, see: https://nodejs.org/en/docs/inspector
Knex: run
$ npm install sqlite3 --save
/Users/codelocksdev/Documents/dev/repos/gedmap/dist/apps/package.jsondoes not exist
Error: /Users/codelocksdev/Documents/dev/repos/gedmap/dist/apps/package.jsondoes not exist
    at Object.exports.find (/Users/codelocksdev/Documents/dev/repos/gedmap/node_modules/@mapbox/node-pre-gyp/lib/pre-binding.js:19:11)
    at node_modules/sqlite3/lib/sqlite3-binding.js (/Users/codelocksdev/Documents/dev/repos/gedmap/node_modules/sqlite3/lib/sqlite3-binding.js:3:29)
    at __require (/Users/codelocksdev/Documents/dev/repos/gedmap/dist/apps/backend/main.js:8:50)
    at node_modules/sqlite3/lib/sqlite3.js (/Users/codelocksdev/Documents/dev/repos/gedmap/node_modules/sqlite3/lib/sqlite3.js:2:17)
    at __require (/Users/codelocksdev/Documents/dev/repos/gedmap/dist/apps/backend/main.js:8:50)
    at Client_SQLite3._driver (/Users/codelocksdev/Documents/dev/repos/gedmap/node_modules/knex/lib/dialects/sqlite3/index.js:42:12)
    at Client_SQLite3.initializeDriver (/Users/codelocksdev/Documents/dev/repos/gedmap/node_modules/knex/lib/client.js:190:26)
    at new Client (/Users/codelocksdev/Documents/dev/repos/gedmap/node_modules/knex/lib/client.js:75:12)
    at new Client_SQLite3 (/Users/codelocksdev/Documents/dev/repos/gedmap/node_modules/knex/lib/dialects/sqlite3/index.js:22:5)
    at knex2 (/Users/codelocksdev/Documents/dev/repos/gedmap/node_modules/knex/lib/knex-builder/Knex.js:16:28)

/Users/codelocksdev/Documents/dev/repos/gedmap/node_modules/knex/lib/client.js:194
      throw new Error(`${message}\n${e.message}`);
            ^
Error: Knex: run
$ npm install sqlite3 --save
/Users/codelocksdev/Documents/dev/repos/gedmap/dist/apps/package.jsondoes not exist
    at Client_SQLite3.initializeDriver (/Users/codelocksdev/Documents/dev/repos/gedmap/node_modules/knex/lib/client.js:194:13)
    at new Client (/Users/codelocksdev/Documents/dev/repos/gedmap/node_modules/knex/lib/client.js:75:12)
    at new Client_SQLite3 (/Users/codelocksdev/Documents/dev/repos/gedmap/node_modules/knex/lib/dialects/sqlite3/index.js:22:5)
    at Knex (/Users/codelocksdev/Documents/dev/repos/gedmap/node_modules/knex/lib/knex-builder/Knex.js:16:28)
    at Object.<anonymous> (/Users/codelocksdev/Documents/dev/repos/gedmap/libs/db/src/config/knex.ts:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.Module._load (/Users/codelocksdev/Documents/dev/repos/gedmap/packages/js/src/executors/node/node-with-require-overrides.ts:16:27)
```

While this bug seems to be caused by the combination of knex and an integrated monorepo project structure, I think the root of the problem seems to be happening in the knex logic. 

Is this configurable or does it need a bug fix?

**Comment by nicolasgfe** [comment]
Tambem estou com esse problema

**Comment by mercmobily** [comment]
This is a common challenge when using Knex with modern build tools and monorepo setups, particularly with NX which bundles backend code using esbuild or webpack.

The error you're encountering occurs because sqlite3 is a native Node.js module with compiled binary components, and NX's build process is attempting to bundle it as if it were a normal JavaScript module. When the bundled code executes from the `dist/` directory, Node.js cannot find the native sqlite3 binaries, triggering the "Knex: run" error message that suggests installing sqlite3.

This isn't actually a bug in Knex itself, but rather a configuration requirement for bundlers that process backend code. Knex correctly tries to load sqlite3 through a standard `require('sqlite3')` call in lib/dialects/sqlite3/index.js:42, but bundlers like webpack and esbuild need explicit configuration to handle native modules properly.

The solution depends on which bundler NX is configured to use for your backend application. NX typically uses esbuild or webpack. You'll need to configure your bundler to exclude database drivers and other native Node.js modules from the bundle, treating them as external dependencies instead.

**For esbuild (most common with modern NX setups):**

In your NX project configuration file (`project.json` or `workspace.json`), locate the build target for your backend app and add an `externalDependencies` option:

```json
{
  "targets": {
    "build": {
      "executor": "@nrwl/node:webpack",
      "options": {
        "externalDependencies": [
          "sqlite3",
          "better-sqlite3",
          "mysql",
          "mysql2",
          "pg",
          "pg-query-stream",
          "oracledb",
          "tedious",
          "mssql"
        ]
      }
    }
  }
}
```

If using the esbuild executor directly, add to your `esbuild` options:

```json
{
  "targets": {
    "build": {
      "executor": "@nrwl/esbuild:esbuild",
      "options": {
        "external": [
          "sqlite3",
          "better-sqlite3",
          "mysql",
          "mysql2",
          "pg",
          "pg-query-stream",
          "oracledb",
          "tedious",
          "mssql"
        ]
      }
    }
  }
}
```


**For webpack:**

If your NX setup uses webpack, you'll need to add a custom webpack configuration. Create a `webpack.config.js`:

```javascript
module.exports = {
  externals: {
    'sqlite3': 'commonjs sqlite3',
    'better-sqlite3': 'commonjs better-sqlite3',
    'mysql': 'commonjs mysql',
    'mysql2': 'commonjs mysql2',
    'pg': 'commonjs pg',
    'pg-query-stream': 'commonjs pg-query-stream',
    'oracledb': 'commonjs oracledb',
    'tedious': 'commonjs tedious',
    'mssql': 'commonjs mssql'
  }
};
```

**Why this happens:**

The error message shows the bundled code is trying to load sqlite3 from `/Users/codelocksdev/Documents/dev/repos/gedmap/dist/apps/backend/main.js`, which is the bundled output directory. However, sqlite3's native bindings need to be loaded from `node_modules` using Node.js's standard module resolution, not from within a bundled JavaScript file.

The sqlite3 module uses `@mapbox/node-pre-gyp` to locate its compiled binary based on the location of `package.json`. When your code is bundled, this resolution mechanism breaks because there's no `package.json` in the `dist/apps/` directory, which is exactly what the error message indicates: `/Users/codelocksdev/Documents/dev/repos/gedmap/dist/apps/package.json does not exist`.

**Additional verification steps:**

After configuring external dependencies, ensure sqlite3 is actually installed at your monorepo root (which it appears to be from your description):

```bash
# From your monorepo root
npm ls sqlite3
```

When you run your built application, Node.js should be able to resolve `require('sqlite3')` from your root `node_modules` directory, even though the code is executing from `dist/apps/backend/`.


**Alternative: Using better-sqlite3:**

If you continue experiencing issues with sqlite3, consider switching to better-sqlite3, which tends to work more reliably with bundlers whilst still requiring the same external configuration:

```javascript
// In your knex config
{
  client: 'better-sqlite3',
  connection: {
    filename: './dev.sqlite3'
  },
  useNullAsDefault: true
}
```

This configuration challenge affects all bundlers (webpack, esbuild, rollup) and all native Node.js modules, not just Knex. The Knex documentation could certainly be improved to address bundler configuration requirements more prominently, particularly for popular tools like NX, Next.js, and Electron.


**Related Issues:**

- #1128 - "Module not found" errors when using knex with webpack (extensive webpack configuration discussion)
- #4474 - Not compatible with Webpack 5 (webpack 5 polyfill requirements)
- #5234 - Problem with esbuild (esbuild external dependencies configuration)
- #5501 - Electron packaging with SQLite3 (similar native module bundling issue)
- #5102 - Knex imports sqlite in migrate:make (fixed in 1.0.7, but demonstrates how Knex loads database clients)
