### ISSUE TITLE
 Can't add new command when connection is in closed state

### ISSUE THREAD

**Issue by applemate** [knex/knex#5520]
# Environment

Knex version:
Database + version: mysql  Ver 15.1 Distrib 10.3.9-MariaDB, for osx10.13 (x86_64) using readline 5.1 
OS:  ubuntu

# Bug
```bash
error async Error: select * from `prolife_user` where `email` = 'my@gmail.com' and `password` = '1223' - 
Can't add new command when connection is in closed state
0|app  |     at Connection._addCommandClosedState (/root/prolife-server/node_modules/mysql2/lib/connection.js:148:17)
0|app  |     at Connection.query (/root/prolife-server/node_modules/mysql2/lib/connection.js:546:17)
0|app  |     at /root/prolife-server/node_modules/knex/lib/dialects/mysql/index.js:126:18
0|app  |     at new Promise (<anonymous>)
0|app  |     at Client_MySQL2._query (/root/prolife-server/node_modules/knex/lib/dialects/mysql/index.js:120:12)
0|app  |     at executeQuery (/root/prolife-server/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
0|app  |     at Client_MySQL2.query (/root/prolife-server/node_modules/knex/lib/client.js:134:12)
0|app  |     at Runner.query (/root/prolife-server/node_modules/knex/lib/execution/runner.js:130:36)
0|app  |     at ensureConnectionCallback (/root/prolife-server/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
0|app  |     at Runner.ensureConnection (/root/prolife-server/node_modules/knex/lib/execution/runner.js:272:20) {
0|app  |   fatal: true
0|app  | }
```

and this is how I use knex

```js
// knexdb.js
export const kx = knex({
	client: 'mysql2',
	connection: {
		host: host,
		user: dbusername,
		port: 3306,
		password: dbpassword,
		database: dbname,
	},
})
```

```js
// in other files
try {
	const address = const address = await kx(table.shipping_address).select()
		res.json({ message: 'success', data: address })
} catch (error) {
	res.json({ message: 'fail', error })
}
```

**Comment by mercmobily** [comment]
Thank you for reporting this issue. This is a duplicate of #5192, which was reported earlier with the exact same error message and root cause.

The problem you are experiencing ("Can't add new command when connection is in closed state") occurs when the MySQL connection pool tries to use a connection that has been closed by the server, but the pool hasn't properly detected and removed it yet. This is being tracked as part of our connection and pooling META issue #6241.

Closing this as a duplicate of #5192. Please follow #5192 and #6241 for updates on this issue.
