### ISSUE TITLE
Knex pg-query-stream fails to import when using Yarn3 Workspaces

### ISSUE THREAD

**Issue by LiamAttClarke** [knex/knex#5542]
# Environment

Knex version: 2.4.2
Database + version: postgresql (latest)
OS: Windows 11 Pro (22H2)

# Bug

When running knex inside a [Yarn3 Workspace](https://yarnpkg.com/features/workspaces), knex fails to resolve the import of `pg-query-stream`.

Error:
```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: knex tried to access pg-query-stream, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: pg-query-stream
Required by: knex@virtual:560696f833017658981ba6f8d5f48110004949ef7413e18d74c3876da0e873de7bd4ac12b20e876a43bb2113243cacd6042960e956fba8e458ecaa6347d699a1#npm:2.4.2 (via C:\Users\liama\Projects\knex-streams\.yarn\__virtual__\knex-virtual-01c6f15313\0\cache\knex-npm-2.4.2-a7caf35691-cfb6436c0e.zip\node_modules\knex\lib\dialects\postgres\)

Require stack:
- C:\Users\liama\Projects\knex-streams\.yarn\__virtual__\knex-virtual-01c6f15313\0\cache\knex-npm-2.4.2-a7caf35691-cfb6436c0e.zip\node_modules\knex\lib\dialects\postgres\index.js
- C:\Users\liama\Projects\knex-streams\.yarn\__virtual__\knex-virtual-01c6f15313\0\cache\knex-npm-2.4.2-a7caf35691-cfb6436c0e.zip\node_modules\knex\lib\dialects\index.js
- C:\Users\liama\Projects\knex-streams\.yarn\__virtual__\knex-virtual-01c6f15313\0\cache\knex-npm-2.4.2-a7caf35691-cfb6436c0e.zip\node_modules\knex\lib\knex-builder\internal\config-resolver.js
- C:\Users\liama\Projects\knex-streams\.yarn\__virtual__\knex-virtual-01c6f15313\0\cache\knex-npm-2.4.2-a7caf35691-cfb6436c0e.zip\node_modules\knex\lib\knex-builder\Knex.js
- C:\Users\liama\Projects\knex-streams\.yarn\__virtual__\knex-virtual-01c6f15313\0\cache\knex-npm-2.4.2-a7caf35691-cfb6436c0e.zip\node_modules\knex\lib\index.js
- C:\Users\liama\Projects\knex-streams\.yarn\__virtual__\knex-virtual-01c6f15313\0\cache\knex-npm-2.4.2-a7caf35691-cfb6436c0e.zip\node_modules\knex\knex.js
- C:\Users\liama\Projects\knex-streams\apps\example\index.js
    at Function.require$$0.Module._resolveFilename (C:\Users\liama\Projects\knex-streams\.pnp.cjs:9404:13)
    at Function.require$$0.Module._load (C:\Users\liama\Projects\knex-streams\.pnp.cjs:9254:42)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Client_PG._stream (C:\Users\liama\Projects\knex-streams\.yarn\__virtual__\knex-virtual-01c6f15313\0\cache\knex-npm-2.4.2-a7caf35691-cfb6436c0e.zip\node_modules\knex\lib\dialects\postgres\index.js:192:9)
    at Client_PG.stream (C:\Users\liama\Projects\knex-streams\.yarn\__virtual__\knex-virtual-01c6f15313\0\cache\knex-npm-2.4.2-a7caf35691-cfb6436c0e.zip\node_modules\knex\lib\client.js:151:17)
    at ensureConnectionStreamCallback (C:\Users\liama\Projects\knex-streams\.yarn\__virtual__\knex-virtual-01c6f15313\0\cache\knex-npm-2.4.2-a7caf35691-cfb6436c0e.zip\node_modules\knex\lib\execution\internal\ensure-connection-callback.js:26:26)
    at Runner.ensureConnection (C:\Users\liama\Projects\knex-streams\.yarn\__virtual__\knex-virtual-01c6f15313\0\cache\knex-npm-2.4.2-a7caf35691-cfb6436c0e.zip\node_modules\knex\lib\execution\runner.js:300:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I've created a minimal reproduction here: 
https://github.com/LiamAttClarke/issue-knex-pg-streams-yarn3

The same script works on this branch with the Yarn3 workspace removed:
https://github.com/LiamAttClarke/issue-knex-pg-streams-yarn3/tree/sans-yarn3-workspaces

**Comment by LiamAttClarke** [comment]
This turned out to be caused by Yarn3's default strictness with resolving dependencies not listed in a package's `package.json`.

From the Yarn3 docs:
> Because the hoisting heuristics aren't standardized and predictable, PnP operating under strict mode will prevent packages from requiring dependencies that are not explicitly listed; even if other dependencies also depend on it. This may cause issues with some packages.

To address this problem, Yarn ships with a "loose" mode which will cause the PnP linker to work in tandem with the node-modules hoister - we will first generate the list of packages that would have been hoisted to the top level in a typical node_modules install, then remember this list as what we call the "fallback pool".

So, adding the following to your `.yarnrc.yaml`:
```
pnpMode: loose
```

**Comment by LiamAttClarke** [comment]
This turned out to be caused by Yarn3's default strictness with resolving dependencies not listed in a package's package.json.

From the Yarn3 docs:

> Because the hoisting heuristics aren't standardized and predictable, PnP operating under strict mode will prevent packages from requiring dependencies that are not explicitly listed; even if other dependencies also depend on it. This may cause issues with some packages.

To address this problem, Yarn ships with a "loose" mode which will cause the PnP linker to work in tandem with the node-modules hoister - we will first generate the list of packages that would have been hoisted to the top level in a typical node_modules install, then remember this list as what we call the "fallback pool".

So, adding the following to your .yarnrc.yaml:
```
pnpMode: loose
```

**Comment by LiamAttClarke** [comment]
For some reason `pg-native` is listed as an optional peerDependency but `pg-query-stream` is not 🤷.
See: https://github.com/knex/knex/blob/master/package.json#L94

**Comment by LiamAttClarke** [comment]
For now, I found a workaround here: https://github.com/styled-components/styled-components/issues/3082

Add the following to your '.yarnrc.yml' file:
```
packageExtensions:
  knex@*:
    dependencies:
      pg-query-stream: "*"
```

**Comment by rubengmurray** [comment]
I'll take this one

**Comment by mercmobily** [comment]
Thank you for reporting this issue. This has been added to the TypeScript META issue #6248 where we are tracking all TypeScript-related improvements and fixes. Your issue will be addressed as part of our comprehensive TypeScript support improvements. We are consolidating all TypeScript issues to avoid fragmentation and to tackle the underlying problems systematically.
