### ISSUE TITLE
Error: knex: Unknown configuration option 'client' value [object KnexClient]. Note that it is case-sensitive, check documentation for supported values.        

### ISSUE THREAD

**Issue by palakrawat-bct** [knex/knex#5553]
connectionMangaer.js
const knex = require('knex');

const commonDBConnection = require('../common/commonDBConnection');

const {getNamespace} = require('continuation-local-storage');

let connectionMap;

/**
 *  Create knex instance for all the tenants defined in common database and store in a map.
**/
async function connectAllDb() {
  let tenants;

  try {
    tenants = await commonDBConnection.select('*').from('tenants');
  } catch (e) {
    console.log('error', e);

    return;
  }

  connectionMap =
    tenants
      .map(tenant => {
        return {
          [tenant.subdomain]: knex(createConnectionConfig(tenant))
        }
      })
      .reduce((prev, next) => {
        return Object.assign({}, prev, next);
      }, {});
}

/**
 *  Create configuration object for the given tenant.
**/
function createConnectionConfig(tenant) {
  return {
    client: 'mysql',
    connection: {
      host: tenant.db_host,
      port: tenant.db_port,
      user: tenant.db_username,
      database: tenant.db_name,
      password: tenant.db_password
    },
    pool: { min: 2, max: 20 }
  };
}

/**
 *  Get the connection information (knex instance) for the given tenant's slug.
**/
function getConnectionBySlug(slug) {
    if (connectionMap) {
      return connectionMap[slug];
    }
  }
  
  /**
   *  Get the connection information (knex instance) for current context.
  **/
function getConnection() {
    const nameSpace = getNamespace('unique context');
    const conn = nameSpace.get('connection');
  
    if (!conn) {
      conn = knex(commonDBConnection).clone();
      nameSpace.set('connection', conn);
    }
  
    return conn;
  }

  module.exports = {
    connectAllDb,
    getConnectionBySlug,
    getConnection
  }
commonDbConnection.js
var knex = require('knex');

const knexConfig = {
  client: "mysql",
  connection: {
    user: "root",
    host: "localhost",
    port: "3306",
    database: "devops_ninja_core",
    password: "password"
  },
  pool: { min: 2, max: 20 }
};

module.exports = knex(knexConfig);
tenantUserService.js
async function getTenantInformation(req) {
    if (req.query.token) {
      const userInfo = jwtDecode(req.query.token);
      console.log(userInfo)
      const userId = userInfo.userId;
      const userData = await tenantUserDAO.getTenantById(userId);
      const allUserData = await tenantUserDAO.getAllTenantsInformation();
      conosle.log("user specific data is ",userData);
      console.log("all users data is ",allUserData);
      return allUserData;
    } 
    else  {
      const userData = await tenantUserDAO.getAllTenantsInformation();
      return userData;
    }
  }
tenantUserDao.js
const { getConnection } = require("../middleware/connectionManager");

async function getAllTenantsInformation() {

    return  await getConnection().select("id", "user_meta_id", "first_name", "last_name", "dob", "email", "address", "mobile_number", "created_at", "updated_at").from("user")

};

async function getTenantById(id){

    return await getConnection().select("id","user_meta_id", "first_name","last_name","dob","email","address","mobile_number","created_at","updated_at" ).from("user").where("id", id);
        
};
Error:
C:\Users\palak.rawat\Desktop\devsecopsninja\devsecops-ninja-core-backend\node_modules\knex\lib\knex-builder\internal\config-resolver.js:32
      throw new Error(
            ^

Error: knex: Unknown configuration option 'client' value [object KnexClient]. Note that it is case-sensitive, check documentation for supported values.        
    at resolveConfig (C:\Users\palak.rawat\Desktop\devsecopsninja\devsecops-ninja-core-backend\node_modules\knex\lib\knex-builder\internal\config-resolver.js:32:13)
    at knex (C:\Users\palak.rawat\Desktop\devsecopsninja\devsecops-ninja-core-backend\node_modules\knex\lib\knex-builder\Knex.js:14:39)
    at getConnection (C:\Users\palak.rawat\Desktop\devsecopsninja\devsecops-ninja-core-backend\middleware\connectionManager.js:71:14)
    at Object.getAllTenantsInformation (C:\Users\palak.rawat\Desktop\devsecopsninja\devsecops-ninja-core-backend\dao\tenantUserDAO.js:6:19)
    at Object.getTenantInformation (C:\Users\palak.rawat\Desktop\devsecopsninja\devsecops-ninja-core-backend\services\tenantUserService.js:11:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getTenantInformation (C:\Users\palak.rawat\Desktop\devsecopsninja\devsecops-ninja-core-backend\controllers\tenantUserController.js:6:22)

Node.js v18.15.0
[nodemon] app crashed - waiting for file changes before starting...
Was resolved using transaction in dao layer while writing queries but what's the alternative solution

**Comment by mercmobily** [comment]
This is an old issue that unfortunately went unanswered. Here is a follow up for internet posterity...

The error triggers when `client` is not a supported string/alias or a Client constructor function. If an instance/object is passed (for example `client: knex.client` or `new Client()`), `toString()` becomes `[object KnexClient]` and config resolution throws. The check happens in lib/knex-builder/internal/config-resolver.js:27–40, which accepts either a constructor function via `typeof parsedConfig.client === 'function'` or a supported name (`'pg'/'postgres'`, `'mysql2'`, `'sqlite3'`, `'mssql'`, `'oracledb'`, `'cockroachdb'`, etc.). The supported values are enumerated in lib/constants.js:10–24 via `SUPPORTED_CLIENTS`. `Client#toString()` returning `[object KnexClient]` is defined in lib/client.js:372–386 and explains the error string you observed.

In the code: lib/knex-builder/internal/config-resolver.js:27–40 throws with message `knex: Unknown configuration option 'client' value ${clientName}...` if the supplied `client`/`dialect` string is not in SUPPORTED_CLIENTS (see lib/constants.js:10–24). Passing an object instance yields the `[object KnexClient]` you saw.

This is a configuration usage issue rather than a code defect. Please supply one of the supported client identifiers, for example:
- `client: 'pg'` or `client: 'postgres'`
- `client: 'mysql2'`
- `client: 'sqlite3'`
- `client: 'mssql'`
- `client: 'oracledb'`
- `client: 'cockroachdb'`

If you require a custom client, pass the constructor function as `client: MyCustomClient` (note: function, not an instance). If the ergonomics of this error message can be improved for object values, we could augment config‑resolver to special‑case instances and advise on correct usage.
