### ISSUE TITLE
Updating from knex 2.3.0 to knex 2.4.2 breaks working code

### ISSUE THREAD

**Issue by perry-autofi** [knex/knex#5580]
# Environment

Knex version: 2.4.2
Database + version: MySQL v8
OS: Mac OS Ventura 13.2.1

@smorey2

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
The following code which is working with knex v2.3.0 now throws the error below after updating only the knex module to 2.4.2 in my project.
```javascript
    [this.#productGroup] = await db
            .select('*')
            .from('ProductGroup')
            .where({ dealerId: this.#dealerId, groupId: this.#groupId });
```

Upgrading a minor version or patch should not break working code.

3. Error message
```
    Message:
      The values in where clause must not be object or array.

      42 | 		if (!this.#productGroup) {
      43 | 			// TODO - Merge into a single join query
    > 44 | 			[this.#productGroup] = await db
         | 			                       ^
      45 | 				.select('*')
      46 | 				.from('ProductGroup')
      47 | 				.where({ dealerId: this.#dealerId, groupId: this.#groupId });

      at QueryCompiler_MySQL.whereBasic (../../node_modules/.pnpm/knex@2.4.2_mysql2@2.3.3/node_modules/knex/lib/dialects/mysql/query/mysql-querycompiler.js:167:5)
      at QueryCompiler_MySQL.where (../../node_modules/.pnpm/knex@2.4.2_mysql2@2.3.3/node_modules/knex/lib/query/querycompiler.js:573:34)
      at ../../node_modules/.pnpm/knex@2.4.2_mysql2@2.3.3/node_modules/knex/lib/query/querycompiler.js:133:40
          at Array.forEach (<anonymous>)
      at QueryCompiler_MySQL.select (../../node_modules/.pnpm/knex@2.4.2_mysql2@2.3.3/node_modules/knex/lib/query/querycompiler.js:132:16)
      at QueryCompiler_MySQL.toSQL (../../node_modules/.pnpm/knex@2.4.2_mysql2@2.3.3/node_modules/knex/lib/query/querycompiler.js:73:29)
      at Builder.toSQL (../../node_modules/.pnpm/knex@2.4.2_mysql2@2.3.3/node_modules/knex/lib/query/querybuilder.js:83:44)
      at ensureConnectionCallback (../../node_modules/.pnpm/knex@2.4.2_mysql2@2.3.3/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
      at Runner.ensureConnection (../../node_modules/.pnpm/knex@2.4.2_mysql2@2.3.3/node_modules/knex/lib/execution/runner.js:300:20)
      at Runner.run (../../node_modules/.pnpm/knex@2.4.2_mysql2@2.3.3/node_modules/knex/lib/execution/runner.js:30:19)
      at ProductGroup.exists (src/lib/dao/ProductGroup.js:44:27)
      at ProductGroup.create (src/lib/dao/ProductGroup.js:100:7)
      at Dealer.createGroups (src/lib/dao/Dealer.js:126:4)
      at Object.<anonymous> (test/lib/dao/Dealer.test.js:323:21)
```

5. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

Based on the stack trace I don't believe this requires a live connection in order to reproduce.

**Comment by castarco** [comment]
Disclaimer: I'm not related to the Knex project.

Have you checked which is the minimum version that makes your code break? (2.4.0 vs 2.4.1 vs 2.4.2). That can help to pinpoint the cause.

**Comment by perry-autofi** [comment]
@jukkaleh-atoz That's not my issue. Also I'm using the latest mysql2 "driver". I don't think the query has even made it to the "driver" at this point, it's generating the query and blowing up. You can see from the stack trace that it's still in knex code.

**Comment by jukkaleh-atoz** [comment]
> @jukkaleh-atoz That's not my issue. Also I'm using the latest mysql2 "driver". I don't think the query has even made it to the "driver" at this point, it's blowing up while generating the query. You can see from the stack trace that it's still in knex code.

Knex added anti sql injection checks that are very strict and partially broken. Previously working code was affected regardless of mysql driver.

**Comment by perry-autofi** [comment]
My point exactly. A minor version or patch version should not break existing code. It appears that 2.4.2 breaks existing code. Not good.

**Comment by mercmobily** [comment]
This is a by‑design change in 2.4.0+ to harden against SQL injection; code now rejects object/array values in basic where clauses for MySQL‑family dialects. Migration guidance is below.

MySQL query compiler asserts that basic `where` values are not plain objects or arrays, and similarly validates `whereRaw` bindings, to address CVE concerns. See lib/dialects/mysql/query/mysql-querycompiler.js:185–197 where `whereBasic` asserts `!isPlainObjectOrArray(statement.value)`, and `whereRaw` asserts bindings don’t contain plain objects/arrays. The error you posted comes directly from that assertion. Your example `.where({ dealerId: this.#dealerId, groupId: this.#groupId })` should be fine if both values are primitives; if either is an object (e.g. a Date, Buffer, custom object, or an array) it will now error. In 2.3.0 it may have silently coerced/bound such values. The new assertions are at lib/dialects/mysql/query/mysql-querycompiler.js:185–197. The changelog for 2.4.0 notes “MySQL: Add assertion for basic where clause not to be object or array #1227” (CHANGELOG.md:100–120). The stack trace you shared shows failure at `whereBasic` inside the MySQL compiler.

Ensure values in object‑form `where` are simple scalars. For arrays use `.whereIn('col', array)`. For Dates/Buffers pass them directly (they are supported), and for complex expressions use `whereRaw('col = ?', [value])` with parameter binding, or normal `.where('col', op, value)` after converting the value to a primitive. If you can narrow down which of `dealerId` or `groupId` is non‑primitive in your case, we can suggest a precise change.

Related issues: #1227; relevant code at lib/dialects/mysql/query/mysql-querycompiler.js:185.
