### ISSUE TITLE
Getting connection.removeAllListeners is not a function

### ISSUE THREAD

**Issue by djaffer** [knex/knex#5595]
# Environment

Knex version: 2.4.2
Database + version: mariadb:10.9
OS: docker on windows

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @ smorey2.
Rest of dialects don't need tags.
If issue is about TypeScript definitions, tag @ lorefnon.

# Bug
Getting this issue randomly
```
connection.removeAllListeners is not a function
    at /node_modules/knex/lib/dialects/mysql/index.js:87:30
    at Timeout._onTimeout (/node_modules/lodash/_baseDelay.js:18:39)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node: internal/timers:512:7)

```

**Comment by kibertoad** [comment]
which node version are you using?

**Comment by djaffer** [comment]
18.16.0

**Comment by mercmobily** [comment]
Thank you for reporting this issue. The error "connection.removeAllListeners is not a function" indicates that the connection object has become undefined or invalid at the point where Knex is trying to clean it up.

This is a connection lifecycle management bug that occurs when connections are being released or destroyed, but the connection object has already been garbage collected or set to null. The error happens in the MySQL dialect's connection cleanup code.

This issue has been added to our connection and pooling META issue #6241, where we are tracking all connection lifecycle and pool management problems. The random nature of this error suggests it's a race condition in how connections are being cleaned up.

This issue will remain open and tracked under META #6241.
