### ISSUE TITLE
Intermittent error: Cannot find module 'lodash/clone

### ISSUE THREAD

**Issue by skhilliard** [knex/knex#5614]
# Environment

Azure Function Runtime version 4.21.3.20740
Knex version: 2.4.2
Database + version: Azure SQL Server v12.0
OS: Windows Server 2016

# Bug

We are seeing intermittent "bursts" of errors where the knex library fails to load lodash/clone:

Result: Failure
Exception: Worker was unable to load function process-reporting-messages: 'Cannot find module 'lodash/clone'
Require stack:
- C:\home\site\wwwroot\node_modules\knex\lib\query\querybuilder.js
- C:\home\site\wwwroot\node_modules\knex\lib\client.js
- C:\home\site\wwwroot\node_modules\knex\lib\knex-builder\Knex.js
- C:\home\site\wwwroot\node_modules\knex\lib\index.js
- C:\home\site\wwwroot\node_modules\knex\knex.js
- C:\home\site\wwwroot\process-reporting-messages\index.js
- C:\Program Files (x86)\SiteExtensions\Functions\4.21.3\workers\node\dist\src\worker-bundle.js
- C:\Program Files (x86)\SiteExtensions\Functions\4.21.3\workers\node\dist\src\nodejsWorker.js'
Stack: Error: Worker was unable to load function process-reporting-messages: 'Cannot find module 'lodash/clone'
Require stack:
- C:\home\site\wwwroot\node_modules\knex\lib\query\querybuilder.js
- C:\home\site\wwwroot\node_modules\knex\lib\client.js
- C:\home\site\wwwroot\node_modules\knex\lib\knex-builder\Knex.js
- C:\home\site\wwwroot\node_modules\knex\lib\index.js
- C:\home\site\wwwroot\node_modules\knex\knex.js
- C:\home\site\wwwroot\process-reporting-messages\index.js
- C:\Program Files (x86)\SiteExtensions\Functions\4.21.3\workers\node\dist\src\worker-bundle.js
- C:\Program Files (x86)\SiteExtensions\Functions\4.21.3\workers\node\dist\src\nodejsWorker.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Object.apply (C:\Program Files (x86)\SiteExtensions\Functions\4.21.3\workers\node\dist\src\worker-bundle.js:2:44135)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (C:\home\site\wwwroot\node_modules\knex\lib\query\querybuilder.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Object.apply (C:\Program Files (x86)\SiteExtensions\Functions\4.21.3\workers\node\dist\src\worker-bundle.js:2:44135)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (C:\home\site\wwwroot\node_modules\knex\lib\client.js:15:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Object.apply (C:\Program Files (x86)\SiteExtensions\Functions\4.21.3\workers\node\dist\src\worker-bundle.js:2:44135)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (C:\home\site\wwwroot\node_modules\knex\lib\knex-builder\Knex.js:1:16)

Any idea what would cause this?

**Comment by yovasx2** [comment]
i used version 2.4.2 and all was fine

**Comment by rubengmurray** [comment]
@skhilliard did you bump and did it fix it?

**Comment by skhilliard** [comment]
@rubengmurray We are currently on 3.1.0 and AFAIK we haven't experienced this issue anymore.

**Comment by rubengmurray** [comment]
Lines up with the @yovasx2 comment as well. Good news. 

Thanks for the quick response after the dead time.

**Comment by mercmobily** [comment]
Should I close this issue?

**Comment by rubengmurray** [comment]
Yeah let's close this one
