### ISSUE TITLE
Error: Connection terminated

### ISSUE THREAD

**Issue by sshettyyara** [knex/knex#5625]
# Environment

Knex version: "0.21.21"
Database + version: postgis/postgis:11-3.1
OS:

# Bug
Hi Getting bellow error sometimes in the production DB but not reproducible in stage and Local, can someone help me on this?? 

 Error message
 Error: Connection terminated
    at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:132:36)
    at Object.onceWrapper (events.js:519:28)
    at Connection.emit (events.js:412:35)
    at Connection.emit (domain.js:475:12)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:57:12)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at TCP.<anonymous> (net.js:686:12)
    at TCP.callbackTrampoline (internal/async_hooks.js:130:17)

<anonymous> in/app/node_modules/@instana/core/src/tracing/instrumentation/database/pg.js:40
<anonymous> in/app/node_modules/knex/lib/dialects/postgres/index.js:237
new Promise in
Client_PG._query in/app/node_modules/knex/lib/dialects/postgres/index.js:236
Client_PG.query in/app/node_modules/knex/lib/client.js:168
Runner.query in/app/node_modules/knex/lib/runner.js:151
<anonymous> in/app/node_modules/knex/lib/runner.js:40
<anonymous> in/app/node_modules/knex/lib/runner.js:277
QueryBuilder.execute in/app/node_modules/objection/lib/queryBuilder/QueryBuilder.js:667

**Comment by AdamSGit** [comment]
This issue seems to take place at `pg` package level and is likely related to your production environment rather than knex. Without more elements, nothing can be done here.

**Comment by mercmobily** [comment]
Please head over #3523 which is where this issue is being discussed. Some valuable advice there too.
