### ISSUE TITLE
Breaking change: frozen config

### ISSUE THREAD

**Issue by pinko-fowle** [knex/knex#5648]
# Environment

Knex version: 2.5.0+
Database + version: any
OS: any

# Bug

Passing a frozen `connection` object to Knex's constructor will now cause it to die. This occurs since version [`2.5.0`](https://github.com/knex/knex/releases/tag/2.5.0)/#5559, with this error:

```
TypeError: Cannot redefine property: password
    at Function.defineProperty (<anonymous>)
    at setHiddenProperty (/usr/pinko-fowle/src/my-service/node_modules/knex/lib/util/security.js:18:10)
    at new Client (/usr/pinko-fowle/src/my-service/node_modules/knex/lib/client.js:49:7)
    at new Client_PG (/usr/pinko-fowle/src/my-service/node_modules/knex/lib/dialects/postgres/index.js:21:5)
    at knex (/usr/pinko-fowle/src/my-service/node_modules/knex/lib/knex-builder/Knex.js:17:28)
```

This was a breaking change for our apps, which often "deep freeze" their config objects. Now Knex expects to be able to [make properties non-enumerable](https://github.com/knex/knex/pull/5559/files#diff-be3a7897f9ac15e3a4e7c454cd2dd0333da3c865f475a3cccf5af02d27775768R18). This prevents us from our typical security stance of deep freezing config when we can, to prevent accidental runtime modification.

# Fix Option: cloning

Currently `setHiddenProperty` expects to modify the `target`, but it could instead be made to shallow or deep clone the `target` object. The callers would need to adjust their code to expect a return value.

Cloning could either be done all the time by `setHiddenProperty`, or `setHiddenProperty` could clone only as a fallback if the `defineProperty` fails.

**Comment by GeorgeBell1982** [comment]
This is a big issue for us as well, not having a frozen object is a problem

**Comment by alqu** [comment]
Same problem here in a Koa-app using knex

**Comment by PJvanDiepen** [comment]
I did change my code from:

const Knex = require('knex');
const knex = Knex(config.get('knex'));

into:

const Knex = require('knex');
const knex = Knex(JSON.parse(JSON.stringify(config.get('knex'))));

And it was fixed!

**Comment by jvyang** [comment]
I got this issue as well. I leveraged node-config's `cloneDeep` (see [utilities](https://github.com/node-config/node-config/wiki/Using-Config-Utilities)) as my solution:

```typescript
const knexConfig = config.get('knex');
const clonedKnexConfig = config.util.cloneDeep(knexConfig);
const knex = Knex(knexConfig);
```

**Comment by mdrobny** [comment]
I currently mitigate it with [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone)

```js
const knex = require('knex');

const db = knex({
    ...structuredClone(config.get('postgres')),
    client: 'pg',
});
```

**Comment by mercmobily** [comment]
Hello! You've identified a breaking change introduced in Knex 2.5.0 that affects applications using frozen configuration objects.

Evidence from this repo: the password is made non‑enumerable via `Object.defineProperty`, which fails on frozen objects. See lib/util/security.js:18 and callers in lib/client.js:22 (initial config), 44 (cloned connectionSettings), and 214 (after acquiring a connection). A minimal verification using SQLite shows the exact error message:

```js
const knex = require('knex');
try {
  knex({ client: 'sqlite3', useNullAsDefault: true, connection: Object.freeze({ filename: ':memory:', password: 'secret' }) });
} catch (e) {
  console.error(e.message); // Cannot redefine property: password
}
```

The issue was introduced in PR #5559, which added security features to hide sensitive properties like passwords using `Object.defineProperty()`. However, this fails when the config object is frozen, as frozen objects can't have their properties redefined.

The error occurs at `lib/util/security.js:18` when Knex tries to make the password property non-enumerable on a frozen object.

**Why this is a problem:**
Many applications deep-freeze their configuration objects as a security best practice to prevent accidental runtime modifications. The change in Knex 2.5.0 made this pattern impossible, forcing a choice between:
1. Not freezing configs (less secure)
2. Not upgrading Knex (missing bug fixes and features)

**Current workarounds:**
As discussed in the comments, users have found several workarounds:

1. Clone before passing to Knex:
```javascript
const knex = Knex(JSON.parse(JSON.stringify(config.get('knex'))));
```

2. Use node-config's cloneDeep utility:
```javascript
const knexConfig = config.get('knex');
const clonedKnexConfig = config.util.cloneDeep(knexConfig);
const knex = Knex(clonedKnexConfig);
```

3. Use structuredClone (Node 17+):
```javascript
const knex = require('knex')({
    ...structuredClone(config.get('postgres')),
    client: 'pg',
});
```

Proper solution: make `setHiddenProperty` tolerant of frozen targets (e.g. check `Object.isFrozen(target)` or catch the defineProperty error), clone if necessary, and avoid redefining when an identical non‑enumerable property already exists. That would remove the need for user‑side cloning.

This is a legitimate breaking change that affects real-world applications, especially those using the popular `node-config` library which freezes configuration by default. The issue deserves proper attention and a fix in Knex rather than requiring all users to implement workarounds.

It's marked as a "bug", so we will get to it as soon as we finish the mass triaging we are about to complete. Sorry it took a while.

Related issues:
- #5648 (OPEN) – Breaking change: frozen config – this thread
- #5559 (MERGED PR) – fix(security): avoid password leaks on query logs
