### ISSUE TITLE
calling knex without a tableName is deprecated

### ISSUE THREAD

**Issue by thiago-b-coelho** [knex/knex#5746]
# Environment

Knex version: 3.0.1
Database + version: mysql 8.1.0
OS: macOS 11.7

# Bug

When I try to run `npx knex migrate:latest` I get the following error:

```json
calling knex without a tableName is deprecated. Use knex.queryBuilder() instead.
select * - No tables used
Error: select * - No tables used
    at Packet.asError (/Users/Thiago/Documents/GitHub/controle-financeiro-back/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/Users/Thiago/Documents/GitHub/controle-financeiro-back/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/Users/Thiago/Documents/GitHub/controle-financeiro-back/node_modules/mysql2/lib/connection.js:478:34)
    at PacketParser.onPacket (/Users/Thiago/Documents/GitHub/controle-financeiro-back/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Users/Thiago/Documents/GitHub/controle-financeiro-back/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/Thiago/Documents/GitHub/controle-financeiro-back/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
```
I do not use 'select' query anywhere so I don´t understand where this error might be coming from.

My folder structure is as follows:

Project

```
migrations
- create_users.js
- create_categories.js
src
- config
- - database.js
- services
- - knex.js
knexfile.js
```

These are my files:
_migrations/20231121123456_create_users_table.js_
```javascript
exports.up = function (knex) {
  return knex.schema.createTable('users', function (table) {
    table.increments('id').primary();
    table.string('name');
    table.string('username');
    table.string('email');
    table.timestamps(true, true);
  });
};

exports.down = function (knex) {
  return knex.schema.dropTableIfExists('users');
};
```
_migrations/20231121123456_create_categories_table.js_
```javascript
exports.up = function (knex) {
  return knex.schema.createTable('categories', function (table) {
    table.increments('id').primary();
    table.string('name');
    table.bigInt('user_id').unsigned().references('id').inTable('users');
  });
};

exports.down = function (knex) {
  return knex.schema.dropTableIfExists('categories');
};
```
_knexfile.js_
```javascript
const config = require("./src/config/database.js");

module.exports = config;
```
_database.js_
```javascript
const dotenv = require('dotenv');
const env = dotenv.config().parsed;

const config = {
  client: 'mysql2',
  connection: {
    host: env.DB_HOST || '127.0.0.1',
    port: 3306,
    user: env.DB_USER || 'user',
    password: env.DB_PASSWORD || 'password',
    database: env.DB_NAME || 'db'
  },
  migrations: {
    tableName: 'knex_migrations',
    directory: '../../migrations'
  }
};

module.exports = require('knex')(config);
```
_knex.js_
```javascript
const knexConfig = require('../../knexfile')

let conn;

const knexService = () => {
  if (!conn) {
    conn = knexConfig;
    return conn;
  }
  return conn;
};

module.exports = knexService;
```

**Comment by kauemurakami** [comment]
I have the same problem at the moment. :/

**Comment by mercmobily** [comment]
I realise this comes really late. I hope you can still benefit from an answer, and that others will via search engines.

Looking at your setup, the problem is in your `database.js` file. You're exporting an already-initialized Knex instance:

```javascript
// database.js - INCORRECT
module.exports = require('knex')(config);
```

Then in `knexfile.js`, you're importing this initialized instance and exporting it as the config:

```javascript
// knexfile.js - INCORRECT
const config = require("./src/config/database.js");
module.exports = config;
```

The problem is that `knexfile.js` should export a configuration object, not a Knex instance. The CLI loads the file (bin/cli.js:13–33, 118–150) and passes it to `require('knex')(config)`. If what’s exported is already a callable Knex instance, it triggers the “no tableName” deprecation and “No tables used”.

**The fix:**

1. Have `database.js` export just the configuration:
```javascript
// src/config/database.js
const dotenv = require('dotenv');
const env = dotenv.config().parsed;

const config = {
  client: 'mysql2',
  connection: {
    host: env.DB_HOST || '127.0.0.1',
    port: 3306,
    user: env.DB_USER || 'user',
    password: env.DB_PASSWORD || 'password',
    database: env.DB_NAME || 'db'
  },
  migrations: {
    tableName: 'knex_migrations',
    directory: './migrations'  // Fixed path
  }
};

module.exports = config;  // Export the config, not knex(config)
```

2. Have `knexfile.js` export this config directly:
```javascript
// knexfile.js
const config = require("./src/config/database.js");
module.exports = config;
```

3. In your application code (`knex.js`), create the Knex instance:
```javascript
// src/services/knex.js
const knexConfig = require('../config/database');
const knex = require('knex')(knexConfig);

module.exports = knex;
```

Also note that your migrations directory path was `'../../migrations'` which would be relative to where the config file is. It should probably be `'./migrations'` to be relative to your project root.

The error occurs because the Knex CLI expects a configuration object, but you're passing an initialized Knex instance, which causes the "calling knex without a tableName" deprecation warning and the subsequent "No tables used" error.
