### ISSUE TITLE
getting Uncaught TypeError: Cannot assign to read only property 'ReadStream' of object '[object Object]'

### ISSUE THREAD

**Issue by pdeva** [knex/knex#5989]
Seeing this error in console when using Knex.js in a react app with Remix.js.
<img width="1496" alt="Screenshot 2023-06-27 at 1 46 47 PM" src="https://github.com/knex/documentation/assets/3190176/af885dde-45e1-485a-9187-18d36392cf2e">

```
node-modules-polyfills-commonjs:tty:6 Uncaught TypeError: Cannot assign to read only property 'ReadStream' of object '[object Object]'
    at node-modules-polyfills-commonjs:tty (node-modules-polyfills-commonjs:tty:6:25)
    at __require (chunk-FCC3XGIV.js:11:50)
    at node_modules/knex/node_modules/colorette/index.cjs (index.cjs:5:11)
    at __require (chunk-FCC3XGIV.js:11:50)
    at node_modules/knex/lib/logger.js (logger.js:1:15)
    at __require (chunk-FCC3XGIV.js:11:50)
    at node_modules/knex/lib/client.js (client.js:29:16)
    at __require (chunk-FCC3XGIV.js:11:50)
    at node_modules/knex/lib/knex-builder/Knex.js (Knex.js:1:16)
    at __require (chunk-FCC3XGIV.js:11:50)
```

**Comment by mercmobily** [comment]
Hi there, thanks for reporting this issue.

This issue is a duplicate of #6242, which comprehensively addresses bundler compatibility problems with Knex in browser environments, including Remix, Webpack 5, Vite, and Electron applications. That issue will be the master tracking issue for all browser/bundler-related problems.

The specific error you're seeing - "Cannot assign to read only property 'ReadStream'" - occurs because Remix (which uses Vite under the hood) is attempting to bundle Knex for the browser environment. The error originates from the `colorette` package (used by Knex for terminal colour output in lib/logger.js:1) trying to access the `tty` (terminal) module, which bundlers attempt to polyfill for browser use. Unfortunately, some polyfills try to assign to read-only properties, causing this error.

The fundamental issue is that Knex is primarily designed as a Node.js library for server-side database operations. When bundlers encounter Knex code, they try to make it work in the browser by providing polyfills for Node.js-specific modules like `tty`, `fs`, `util`, `stream`, and others. This often leads to errors like the one you're experiencing.

For Remix specifically (and other modern frameworks with server/client boundaries), the solution is to ensure Knex only runs on the server side, never in the browser bundle. Knex should never be imported in client-side code or in files that get bundled for the browser.

If you're accidentally importing Knex in a component that gets bundled for the browser, you have several options. First, make sure all database operations happen in Remix loaders and actions, which run server-side only. Second, if you have a shared utility file that imports Knex, split it into server-only and client-safe files. Third, configure Vite to exclude Knex from the client bundle by adding it to `ssr.noExternal` or using proper server-only imports.

For comprehensive solutions including direct dialect imports, bundler configurations, and architectural patterns, please refer to the master issue #6242. That issue documents multiple working solutions and will track any future improvements to make Knex more bundler-friendly.

I'll be closing this issue as a duplicate. If your specific use case isn't covered by the solutions in #6242, please add a comment there and we can explore additional approaches.

Related issues: #4474, #5592, #6003, #6242
