### ISSUE TITLE
Bad connection not being released from pool

### ISSUE THREAD

**Issue by akg1** [knex/knex#6041]
# Environment

Knex version: `^3.1.0`
Database + version: AWS RDS PostgreSQL 16.2
OS: `20.11-alpine` container

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @ smorey2.
Rest of dialects don't need tags.
If issue is about TypeScript definitions, tag @ lorefnon.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

This is a bit complicated to debug, but as far as I can tell, we're see an issue where we get a `server conn crashed` from PgBouncer, and subsequently, queries on our containers start failing with: `Client has encountered a connection error and is not queryable`. My best guess is that the connection is remaining in the pool. I don't know how to debug this further though.

3. Error message

Initial error:
```
error: /* query text here */ - server conn crashed?
    at Object.queryBuilder (/app/node_modules/knex/lib/knex-builder/make-knex.js:112:26)
    at Function.value (/app/node_modules/knex/lib/knex-builder/make-knex.js:92:29)
    at Function.withSchema (/app/node_modules/knex/lib/knex-builder/make-knex.js:270:28)
    at DbEntityGateway.shardQueryBuilderHelper (/app/packages/api/src/data/DbEntityGateway.ts:1067:26)
    at ctx (/app/packages/api/src/data/DbEntityGateway.ts:1363:12)
    at /app/packages/api/src/data/implementations/GroupsImpl.ts:1907:21
    at /app/node_modules/p-limit/index.js:23:31
    at run (/app/node_modules/p-limit/index.js:23:43)
    at /app/node_modules/p-limit/index.js:45:2"
```

Subsequent errors: 

`Client has encountered a connection error and is not queryable` (no real stack)

4. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

**Comment by mercmobily** [comment]
Hello! Thanks for reporting this issue.

This is a duplicate of issue #3523, which has already been triaged and marked as `NG_bug`. The issue you're experiencing is a known problem with how Knex handles PostgreSQL connections that have been terminated by the server or intermediary (like PgBouncer) after periods of inactivity.

The core problem is that when a connection in the pool becomes stale (closed by the server-side without the client being immediately aware), the connection isn't recognised as invalid until a query is attempted. When that query is made, the following sequence of events occurs:

1. Knex acquires what it believes is a valid connection from the pool
2. Knex calls `connection.query()` with your SQL
3. The pg driver then emits an `'error'` event (this is when you see `server conn crashed?`)
4. The pg driver's query callback is invoked with the same error
5. Your query fails with "Client has encountered a connection error and is not queryable"
6. The pg driver emits an `'end'` event
7. Knex marks the connection as disposed and releases it back to the pool (where it will be destroyed)
8. Subsequent queries succeed because they acquire a fresh connection

The root cause is that pg doesn't report the connection termination until the moment a query is attempted on it. By that time, it's too late - the query has already been initiated and will fail.

Even though the validation function at lib/client.js:276-283 checks for `connection.__knex__disposed`, this flag is only set after the connection error occurs (in lib/dialects/postgres/index.js:83-89), which happens during the query execution itself, not before.

There are several workarounds you can use whilst this is being addressed:

**Workaround 1: Set pool.min to 0**

Setting `{ pool: { min: 0 } }` helps reduce the issue because idle connections will be destroyed after the `idleTimeoutMillis` period (default 30 seconds). This means fewer stale connections will remain in the pool. However, this doesn't completely solve the problem, as connections can still be terminated between the time they're acquired and when a query is made.

**Workaround 2: Set a shorter idleTimeoutMillis**

Configure `{ pool: { idleTimeoutMillis: 10000 } }` (or another suitable value) to ensure connections are recycled more frequently. Be aware that `idleTimeoutMillis` only applies to connections beyond the `min` count, which is why setting `min: 0` is often recommended alongside this.

**Workaround 3: Use afterCreate with connection validation**

You can use the `afterCreate` callback to set up error handlers or test connections, though this won't prevent errors during query execution, only during connection acquisition.

The proper fix would require Knex to implement automatic query retry when a connection error occurs, checking whether the error happened immediately after connection acquisition. If the connection was freshly acquired and errors, the query should fail. But if the connection had been in the pool and errors due to staleness, Knex should acquire a fresh connection and retry the query automatically. This is similar to how other ORMs handle stale connections.

I'll close this issue as a duplicate of #3523. Please follow that issue for updates on when this will be properly resolved. If you have any additional information that isn't already covered in #3523, please feel free to add it there.

**Related Issues:**

- #3523 - Connection terminated unexpectedly (postgres) [OPEN, NG_bug] - Master issue for this problem
- #5186 - Postgres connection not released from Pool when server closes it [OPEN] - Very similar issue
- #3636 - Connection terminated unexpectedly (Postgresql / AWS Lambda) [CLOSED] - Related but specific to Lambda
- #982 - Knex stops issuing queries once all connections in pool have gone bad [CLOSED] - Historical similar issue
