### ISSUE TITLE
insert can use Buffer, but not work with Uint8Array  (I use mysql2)

### ISSUE THREAD

**Issue by i18n-now** [knex/knex#6045]
when use Uint8Array , where error (the hash column)

```

Error: insert ignore into `v` (`css`, `hash`, `idLi`, `js`) values (151, {"0":114,"1":108,"2":86,"3":55,"4":10,"5":74,"6":187,"7":109,"8":165,"9":203,"10":90,"11":226,"12":165,"13":144,"14":143,"15":33,
"16":98,"17":122,"18":116,"19":22,"20":231,"21":192,"22":78,"23":37,"24":13,"25":131,"26":169,"27":153,"28":129,"29":125,"30":136,"31":157}, X'01010101010101010101010101010101010101010101010101010101010
1010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010
10101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101', 38) - Unknown column '0' in 'field list'
    at Packet.asError (/Volumes/d/i18n/node/s3dist/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/Volumes/d/i18n/node/s3dist/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/Volumes/d/i18n/node/s3dist/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/Volumes/d/i18n/node/s3dist/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/Volumes/d/i18n/node/s3dist/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Volumes/d/i18n/node/s3dist/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column '0' in 'field list'",
  sql: "insert ignore into `v` (`css`, `hash`, `idLi`, `js`) values (151, `0` = 114, `1` = 108, `2` = 86, `3` = 55, `4` = 10, `5` = 74, `6` = 187, `7` = 109, `8` = 165, `9` = 203, `10` = 90, `11` = 226,
 `12` = 165, `13` = 144, `14` = 143, `15` = 33, `16` = 98, `17` = 122, `18` = 116, `19` = 22, `20` = 231, `21` = 192, `22` = 78, `23` = 37, `24` = 13, `25` = 131, `26` = 169, `27` = 153, `28` = 129, `29
` = 125, `30` = 136, `31` = 157, X'01010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010
101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101', 38)"
}
```

**Comment by mercmobily** [comment]
Thank you for reporting this issue. You're absolutely right - this is a genuine bug in how Knex handles Uint8Array values during query building.


The problem is in the `makeEscape` function in `lib/util/string.js:30-51`. When escaping values for SQL queries, the code checks specifically for `Buffer.isBuffer(val)` at line 44, but Uint8Array is not a Buffer even though they're closely related. When a Uint8Array is passed, it falls through to the `escapeObject` function (line 46-47), which JSON.stringifies it, turning it into an object with numeric keys like `{"0": 114, "1": 108, ...}`.

I've verified this bug by running a test:

```javascript
const { makeEscape } = require('./lib/util/string');
const escape = makeEscape();

// Buffer works correctly
const buffer = Buffer.from([114, 108, 86, 55, 10, 74, 187, 109]);
console.log(escape(buffer)); // X'726c56370a4abb6d' ✓

// Uint8Array gets incorrectly serialised
const uint8array = new Uint8Array([114, 108, 86, 55, 10, 74, 187, 109]);
console.log(escape(uint8array)); // {"0":114,"1":108,"2":86,...} ✗
```

This explains exactly the error you're seeing - MySQL tries to interpret those numeric keys as column names, hence "Unknown column '0' in 'field list'".


**Why this matters**

Even though Node.js Buffer is a subclass of Uint8Array, the `Buffer.isBuffer()` check returns false for plain Uint8Array instances. Knex has historically focused on Buffer support (which makes sense for Node.js), but with modern JavaScript and cross-platform code (browsers, Deno, Bun), developers increasingly use standard TypedArrays like Uint8Array instead of Node-specific Buffers.

Interestingly, Knex already has some awareness of TypedArrays - there's code in `lib/util/helpers.js:19` that specifically handles TypedArrays to prevent them being considered "undefined" (this was added back in 2016 via #1601 to handle PostgreSQL bytea columns being returned as Uint8Array).


**Workaround**

Until this is fixed, you can convert your Uint8Array to a Buffer before passing it to Knex:

```javascript
const uint8Data = new Uint8Array([...]);
const bufferData = Buffer.from(uint8Data);

await knex('v').insert({
  hash: bufferData  // Use Buffer instead of Uint8Array
});
```

This conversion is very lightweight - it doesn't copy the underlying data, it just wraps it.


**The fix**

The solution is to update the escape function in `lib/util/string.js` to check for TypedArrays (including Uint8Array) in addition to Buffer. Since Buffer is already a Uint8Array subclass, we can simply check for `instanceof Uint8Array` which will match both Buffers and plain Uint8Arrays:

```javascript
// Current code (line 44):
} else if (Buffer.isBuffer(val)) {
  return finalEscapeBuffer(val, finalEscape, ctx);

// Should be:
} else if (Buffer.isBuffer(val) || val instanceof Uint8Array) {
  return finalEscapeBuffer(Buffer.from(val), finalEscape, ctx);
```

The `Buffer.from()` call handles both cases - if it's already a Buffer it returns a new Buffer wrapping the same underlying data, if it's a Uint8Array it converts it to a Buffer (also without copying the actual bytes).

We'd also need to add test coverage for Uint8Array in `test/unit/query/string.js` (currently there's only a test for Buffer at line 282-286).


**Context from other drivers**

The PostgreSQL driver (pg) returns bytea columns as Uint8Array but also has similar issues when inserting - they recommend using Buffers for inserts. MySQL2 (which you're using) primarily expects Buffers for binary data. Even though the issue exists across drivers, Knex should handle the conversion transparently since it's the abstraction layer.


This would be a good enhancement to add TypedArray support across the board. It's a relatively small change but would improve compatibility with modern JavaScript and cross-runtime code.


**Related issues:**

- #1601 - Uint8Array data erroneously considered "undefined" (CLOSED - fixed TypedArray detection in validation)
- #1301 - Binary columns returned as UInt8Array (CLOSED - discussion about Knex's role in type normalisation)
