### ISSUE TITLE
KnexTimeout connection Issue while connecting with PostgreSQL DB

### ISSUE THREAD

**Issue by sharmayash02** [knex/knex#6051]
# Environment

Knex + Postgres + Node version:
> "knex": "^3.1.0"
"pg": "^8.11.3"
"node": "20.11.0"

@lorefnon @smorey2 

# Bug

1. Issue Observed:
> On running longevity, we are getting Knex timeout issue for PostgreSQL connection.  This issue is intermittent. 
Use-case: We need to upsert (insert/Modify) a table and insert the operation into audit table with the type of operation performed. for example: if _insert_ operation performed then "_insert_" as operation string gets inserted in the audit table.
There is a transaction in query with [async-await approach](https://knexjs.org/guide/transactions.html#transactions). 

2. Error message:
> Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?","stack":"KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?\n    at Client_PG.acquireConnection (/app/node_modules/knex/lib/client.js:332:26)\n    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:305:28)\n    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)

3. Test code:
   
Database connection
```
dbconnection = knexfactory({
        client: 'pg',
        connection: connectionConfig,
        pool: {
          max: 3,
        },
        migrations: {
          directory: join(__dirname, './db/scripts'),
          tableName: 'migrations',
        }
      });
```
      
Code contain Database Query 
```
async afun(){
    try {
        const instanceData = { q_id: "qid", t_id: 1, value: JSON.stringify({ "key": "value" }) };
        const databaseConnection = this.appDatabase.getDbConnection(tenantId);
        const queryResult = await databaseConnection.transaction(async (trx) => {
            return await trx
                .with(
                    'updated',
                    trx
                        .from(DatabaseConstants.TNSI)
                        .where(DatabaseConstants.CNQID, instanceData.q_id)
                        .andWhere(DatabaseConstants.CNTID, instanceData.t_id)
                        .update(instanceData)
                        .returning(`*`)
                )
                .with(
                    'inserted',
                    trx
                        .from(DatabaseConstants.TNSI)
                        .insert(instanceData)
                        .onConflict([DatabaseConstants.CNQID, DatabaseConstants.CNTID])
                        .ignore()
                        .select(DatabaseConstants.CNQID, DatabaseConstants.CNTID, DatabaseConstants.CNV)
                        .whereNotExists(trx.select(1).from(`updated`))
                        .returning(`*`)
                )
                .with(
                    `result`,
                    trx
                        .from(`updated`)
                        .columns(
                            { [DatabaseConstants.CNW]: trx.raw(`?`, [userId]) },
                            { [DatabaseConstants.CNWH]: trx.raw(`row_to_json(updated.*)`) },
                            { [DatabaseConstants.CNOP]: trx.raw(`?`, `update`) }
                        )
                        .select()
                        .unionAll(
                            trx
                                .from(`inserted`)
                                .columns(
                                    { [DatabaseConstants.CNW]: trx.raw(`?`, [userId]) },
                                    { [DatabaseConstants.CNWH]: trx.raw(`row_to_json(inserted.*)`) },
                                    { [DatabaseConstants.CNOP]: trx.raw(`?`, `insert`) }
                                )
                                .select()
                        )
                )
                .insert(
                    trx
                        .from<IDbSettingsInstances>(`result`)
                        .select(`*`)
                )
                .into(trx.raw(`?? (??, ??, ??)`, [DatabaseConstants.TNSA, DatabaseConstants.CNW, DatabaseConstants.CNWH, DatabaseConstants.CNOP]))
                .returning(DatabaseConstants.CNWH);
        });
        return { result: queryResult };
    } catch (error) {
        if (error && error.code == `23503`)
            return { errCode: ErrorCodeConstants.TYPE_ID_NOT_PRESENT };
        throw error;
    }
}

```

# Questions 
- Does it needs to have "_[transacting](https://knexjs.org/guide/query-builder.html#transacting)_" method? 
- If not, then why KnexTimeout issue is occuring?

**Comment by mercmobily** [comment]
Hello @sharmayash02, thank you for the detailed issue report with your code and environment details!

To answer your specific questions directly: **No, you do not need to use `.transacting()` in your code**. Your transaction usage is correct - you're already passing the `trx` object to the builder when you use `trx.from()`, `trx.with()`, etc. The `.transacting()` method is only needed when you have queries that start from the main knex instance (like `knex('users')`) and you want to add them to an existing transaction.

However, the KnexTimeout error message is indeed confusing here. The error says "Are you missing a .transacting(trx) call?" but that's often a red herring - the real issue is typically **connection pool exhaustion**, which can happen for several reasons even when your transaction code is correct.


**Why you're getting timeout errors:**

Looking at your code, you have a pool size of only 3 connections (`pool: { max: 3 }`). If your application receives concurrent requests, each call to `databaseConnection.transaction()` immediately acquires a connection from the pool. With only 3 connections available:

- Request 1 takes connection 1
- Request 2 takes connection 2
- Request 3 takes connection 3
- Request 4 has to wait for a connection to become available
- If requests 1-3 are still processing their complex CTE queries, request 4 will timeout

Your queries are quite complex with multiple CTEs (`WITH updated`, `WITH inserted`, `WITH result`) which take time to execute. During longevity testing with sustained load, this limited pool size becomes a bottleneck.


**Recommended solutions:**

1. **Increase your pool size**: For a production application, `max: 3` is very low. Try increasing it to at least `max: 10` or `max: 20` depending on your database server capacity and expected concurrent load.

2. **Add pool monitoring**: Consider logging pool metrics to understand when you're hitting limits:
```javascript
const pool = dbconnection.client.pool;
console.log(`Pool: used=${pool.numUsed()} free=${pool.numFree()} pending=${pool.numPendingAcquires()}`);
```

3. **Review your transaction lifecycle**: Ensure all code paths properly commit or rollback transactions. In your code snippet, I can see you have a try-catch that handles the 23503 error code, but make sure the transaction is being properly committed/rolled back in all cases (your code looks correct, but double-check any other code paths that might use transactions).

4. **Consider optimizing the query**: Your CTE chain is quite long. Whilst it's correct, you might be able to simplify it, which would reduce the time each connection is held.


**About the error message:**

You're not alone in finding this error message confusing. This is being tracked in issue #6186, which requests better error messages that actually show pool state and distinguish between "pool is full because of configuration" versus "pool is full because of dangling transactions". The current generic message assumes a specific problem (missing `.transacting()` calls) when the actual issue is often something else entirely.


**Related broader context:**

This type of timeout issue affects many Knex users and is being addressed through several initiatives:

- Issue #6241 is a META issue tracking all connection and pooling problems
- Issue #6186 specifically addresses improving the error message to be less confusing
- Issue #6258 proposes "lazy transactions" that would defer connection acquisition until the first query, which would help prevent pool exhaustion in web applications
- Issue #6034 was a similar timeout issue that was closed in favour of the lazy transaction work

The good news is that the Knex team is actively working on improvements to connection management and error reporting that will make these issues easier to diagnose and prevent in the future.


For now, I'd recommend starting by increasing your pool size and monitoring whether that resolves the intermittent timeouts during longevity testing. If you continue to see issues even with a larger pool, that would suggest there might be a connection leak somewhere in your application (transactions not being properly closed), which would be worth investigating further.


**Related issues:**
- #6241 - META: Connection and pooling issues
- #6186 - KnexTimeoutError is confusing and full pool should be visible
- #6034 - Connection timeout: pool is probably full (closed, similar issue)
- #6258 - Add lazy transaction support - defer connection acquisition until first query
- #6257 - META: Implement Lazy Transactions and Connection Context Management
- #5696 - KnexTimeoutError Created During Aquire Connection Failure Swallows Original Error Reason
- #5628 - KnexTimeoutError swallow connection close error after destroy
- #5755 - [Feature] Add Queue management for queries to prevent KnexTimeoutError
