### ISSUE TITLE
Error without actual reason in CLI due to TypeScript error

### ISSUE THREAD

**Issue by chiro-hiro** [knex/knex#6082]
# Environment

Knex version: 3.1.0
Database + version: Postgres 16
OS: Debian 12

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I ran `knex seed:run` got error without actual reason, It should give me the detail of `Error`.

2. Error message

```tx
/home/chiro/Git/oracle/node_modules/colorette/index.cjs:70
          ("" + string).indexOf(close, at),
              ^
TypeError: Cannot convert object to primitive value
    at Object.red (/home/chiro/Git/oracle/node_modules/colorette/index.cjs:70:15)
    at exit (/home/chiro/Git/oracle/node_modules/knex/bin/utils/cli-config-utils.js:82:25)
error Command failed with exit code 1.
```

3. Suggest fix

I figured out that, `text` in `console.error(color.red(text));` is an TypeScript error but It isn't `instance of Error`.

```js
function exit(text) {
  if (text instanceof Error) {
    if (text.message) {
      console.error(color.red(text.message));
    }
    console.error(
      color.red(`${text.detail ? `${text.detail}\n` : ''}${text.stack}`)
    );
  } else {
    console.error(color.red(text));
  }
  process.exit(1);
}
```

So I prefer to change this line:

https://github.com/knex/knex/blob/176151d8048b2a7feeb89a3d649a5580786d4f4e/bin/utils/cli-config-utils.js#L82

To:

`console.error(color.red(typeof text === 'string' ? text : inspect(text))); `

**Comment by chiro-hiro** [comment]
@dweinand Can you check this?

**Comment by RyanMartin-Carewell** [comment]
Ran into this today; still not patched?

**Comment by mercmobily** [comment]
Thanks for the detailed bug report and the suggested fix! You've identified a real issue with our CLI error handling.

**The Problem**

When the CLI encounters certain types of errors (particularly TypeScript errors or other objects that aren't proper Error instances), the error handling code fails when trying to colorize the output. This happens because `colorette` can't convert these objects to strings, resulting in the unhelpful "Cannot convert object to primitive value" error instead of showing the actual underlying error.

This is particularly frustrating because it completely obscures the real problem you're trying to debug.

**Your Diagnosis is Correct**

You're absolutely right that the issue is on line 82 of `cli-config-utils.js`:

```javascript
console.error(color.red(text));
```

When `text` is an object that doesn't have a proper `toString()` method, this fails.

**The Fix**

Your suggested fix is good! We should indeed check if the value is a string before passing it to `color.red()`. Here's the approach we'll take:

```javascript
const { inspect } = require('util');

function exit(text) {
  if (text instanceof Error) {
    if (text.message) {
      console.error(color.red(text.message));
    }
    console.error(
      color.red(`${text.detail ? `${text.detail}\n` : ''}${text.stack}`)
    );
  } else {
    console.error(color.red(typeof text === 'string' ? text : inspect(text)));
  }
  process.exit(1);
}
```

This ensures that non-string error objects are properly inspected and displayed, giving you the actual error details you need for debugging.

**Immediate Workaround**

Until this is fixed, if you encounter this error, you can temporarily patch your local `node_modules/knex/bin/utils/cli-config-utils.js` file with the fix above. This will at least let you see what the actual error is.

**Next Steps**

This is a straightforward fix that will improve the developer experience significantly. We'll get this patched soon. The fix is simple, well-contained, and won't break any existing functionality - it just makes error messages more visible when they're not standard Error objects.

Thanks again for the clear bug report and the suggested solution - this kind of contribution makes maintaining the project much easier!

**Comment by myndzi** [comment]
The error "cannot convert object to primitive value" occurs when attempting to coerce a value to a string that doesn't have a `toString()` method. Almost everything does, but one possible cause is objects created via e.g. `Object.create(null)`. This is almost certainly caused by the blanket `catch(exit)` here:
https://github.com/knex/knex/blob/3.1.0/bin/cli.js#L434

The stack trace is just saying that `colorette` can't turn the supplied value into red text (because it can't be coerced to a string)

However, `seed:run` wraps any error thrown in the `seed` function:
https://github.com/knex/knex/blob/3.1.0/lib/migrations/seed/Seeder.js#L114-L127

...so I'm having difficulty figuring out just _how_ `catch` received an unstringable object. 

I realize this issue is fairly old, but @chiro-hiro @RyanMartin-Carewell are either of you able to provide more detail or a reproduction case? What is the value that's being passed to `exit()` that is not a string, and where does it come from?

It is indeed fairly straightforward to fix the reported behavior, but I'd like to understand the root cause; otherwise this changes from throwing a TypeError to logging something that isn't useful anyway. If I can run down what's being thrown here and why, it can help make a more complete fix.

I've tried with:
- No seed files
- Invalid seed files (no seed function)
- Seed files that throw unexpected errors
- Seed files that produce SQL errors
- Literally editing the Seeder.js file to throw various things at the onset of the `run` method. I was able to get this error only via `throw Object.create(null)` by editing knex's source code. If I do the same in the `seed` method it catches and rethrows as expected.
- Causing the [second part of the promise chain](https://github.com/knex/knex/blob/3.1.0/bin/cli.js#L425) to fail by returning `null` or `[null]` -- these still produce Error instances which are correctly handled by `exit`

**Comment by myndzi** [comment]
... I was able to reproduce via knexfile.js :)

```js
module.exports = function () {
  throw Object.create(null);
};
```

In practice, there's a chance that some library used for creating and managing errors might have its own prototype chain derived from a null-prototype object. In any case, it'd be good to wrap errors in knexfile loading for clear context.

**Comment by mercmobily** [comment]
Thanks for the detailed bug report and the suggested fix!

So, here is where we are: when the CLI encounters certain types of errors (particularly TypeScript errors or other objects that aren't proper Error instances), the error handling code fails when trying to colourise the output. This happens because `colorette` can't convert these objects to strings, resulting in the unhelpful "Cannot convert object to primitive value" error instead of showing the actual underlying error.
This is particularly frustrating because it completely obscures the real problem you're trying to debug.

You're absolutely right that the issue is on line 82 of `cli-config-utils.js`:

```javascript
console.error(color.red(text));
```

When `text` is an object that doesn't have a proper `toString()` method, this fails.

I assume this could be a variety of reasons why these errors are thrown:

1. **Security-focused libraries** deliberately use `Object.create(null)` to prevent prototype pollution attacks:
   - Config loaders (dotenv variants, secure YAML/TOML parsers)
   - GraphQL implementations (Apollo, GraphQL.js)
   - Security-focused validation libraries

2. **Developer mistakes** where the wrong object is thrown:
   - Throwing a config object instead of wrapping it in an Error
   - Throwing validation results directly instead of creating proper Error instances
   - Throwing API responses without proper error wrapping

3. **Build tool errors** from transpilation/bundling:
   - TypeScript compilation errors that create non-standard error objects
   - Webpack/bundler error objects
   - Babel transformation errors

4. **Cross-environment issues**:
   - WASM modules returning non-standard errors
   - Native Node.js addons creating objects without prototypes
   - Cross-realm objects (iframes, workers) losing their prototype chain

The specific issue occurs because `Object.create(null)` creates objects without `Object.prototype`, so they lack the `toString()` method. When `colorette.red()` tries to convert them to strings, it fails with "Cannot convert object to primitive value".

As you discovered, this can be easily reproduced with a knexfile that throws a null-prototype object:

```javascript
// knexfile.js
module.exports = function () {
  throw Object.create(null);
};
```

Or more realistically, when using security-focused config loaders:

```javascript
// knexfile.js
const secureConfig = require('some-secure-config-lib');

module.exports = async function() {
  const config = await secureConfig.load('.env'); // Returns null-prototype object
  
  if (!config.DATABASE_URL) {
    throw config; // Oops! Should be: throw new Error('Missing DATABASE_URL')
  }
  
  return {
    client: 'pg',
    connection: config.DATABASE_URL
  };
};
```

**I believe your suggested fix is good!** We should indeed check if the value is a string before passing it to `color.red()`. Here's the approach we'll take:

```javascript
const { inspect } = require('util');

function exit(text) {
  if (text instanceof Error) {
    if (text.message) {
      console.error(color.red(text.message));
    }
    console.error(
      color.red(`${text.detail ? `${text.detail}\n` : ''}${text.stack}`)
    );
  } else {
    console.error(color.red(typeof text === 'string' ? text : inspect(text)));
  }
  process.exit(1);
}
```

This ensures that non-string error objects are properly inspected and displayed, giving you the actual error details you need for debugging. The `util.inspect()` function handles null-prototype objects gracefully and provides a readable representation of any object.

Until this is fixed, if you encounter this error, you can temporarily patch your local `node_modules/knex/bin/utils/cli-config-utils.js` file with the fix above. This will at least let you see what the actual error is.

Thanks again for the clear bug report and the suggested solution - this kind of contribution makes maintaining the project much easier!

Now... I will be triaging all of the 1080 issues (actually now down to 891!) for the next 3 weeks. So... realistically, this will get done after that. Please bear with me..

**Comment by mercmobily** [comment]
I only had time for the quickest look, but #6265 will close this right?

**Comment by myndzi** [comment]
> I only had time for the quickest look, but [#6265](https://github.com/knex/knex/pull/6265) will close this right?

Correct. That PR was created to address this issue.
