### ISSUE TITLE
Unknown pending operation error

### ISSUE THREAD

**Issue by adamsuskin** [knex/knex#6083]
# Environment

Knex version: 3.1.0
Database + version: Postgres 16.2
OS: Bookworm

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I am seeing a thrown error from tarn.js for an aborted pending operation that Knex re-raises. I am unable to diagnose what operation is pending or why there is an operation pending (since from my code, I don't see what "remains" to be done, everything has completed).

I am not sure how to introspect the aborted pending operation to see what is causing this. If it's some internal-to-knex query, then I would expect it should be safe for me to call `knex.destroy` without anticipating it. If it's something on my end, I can't tell at all.

2. Error message

```

2024-06-02T04:00:05.387Z | /app/node_modules/.pnpm/tarn@3.0.2/node_modules/tarn/dist/PendingOperation.js:25
-- | --
  | 2024-06-02T04:00:05.387Z | this.reject(new Error('aborted'));
  | 2024-06-02T04:00:05.387Z | ^
  | 2024-06-02T04:00:05.387Z | Error: aborted
  | 2024-06-02T04:00:05.387Z | at PendingOperation.abort (/app/node_modules/.pnpm/tarn@3.0.2/node_modules/tarn/dist/PendingOperation.js:25:21)
  | 2024-06-02T04:00:05.387Z | at /app/node_modules/.pnpm/tarn@3.0.2/node_modules/tarn/dist/Pool.js:208:25
  | 2024-06-02T04:00:05.387Z | at Array.map (<anonymous>)
  | 2024-06-02T04:00:05.387Z | at /app/node_modules/.pnpm/tarn@3.0.2/node_modules/tarn/dist/Pool.js:207:53
  | 2024-06-02T04:00:05.387Z | at processTicksAndRejections (node:internal/process/task_queues:95:5)
  | 2024-06-02T04:00:05.387Z    at Client_PG.destroy (/app/node_modules/.pnpm/knex@3.1.0_pg@8.11.3/node_modules/knex/lib/client.js:358:9)

```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

```
// just a snippet to give the gist
class DbImpl {
    constructor(knex) {
        this.knex = knex;
    }
    
    async destroy() {
        await this.knex.destroy();
    }
}

const config = ...;
const k = knex(config);
const db = new DbImpl(k);

// do stuff - everything is awaited

await db.destroy(); // error occurs
```

# Missing / erroneus documentation

All I can find on the `knex.destroy` method in the docs are this comment:
> If you ever need to explicitly teardown the connection pool, you may use knex.destroy([callback]). You may use knex.destroy by passing a callback, or by chaining as a promise, just not both. To manually initialize a destroyed connection pool, you may use knex.initialize([config]), if no config is passed, it will use the first knex configuration used.

So I could be wrong on how to use it, but the intent of me calling `destroy` is that I am done with the connection and want it to be GC-ed since my DB wrapper object is going to be GC-ed.

**Comment by adamsuskin** [comment]
Finally figured this out by enabling `asyncStackTraces` and seeing the operation that was being cancelled emit a log asynchronously.

There was a bug in that code that was easily rectified. Will make a PR to the docs repo to make it a bit easier to find.
