### ISSUE TITLE
`timestamps` method signature in schema is misleading

### ISSUE THREAD

**Issue by ketan** [knex/knex#6086]
# Environment

Knex version: 3.1.0
Database + version: postgresql 16.3
OS: macos sonoma

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Using the following snippet and the [typescript definition](https://github.com/knex/knex/blob/176151d8048b2a7feeb89a3d649a5580786d4f4e/types/index.d.ts#L2471-L2480) `t.timestamps()` should be chainable.

```typescript
require('sqlite3')
const Knex = require('knex')

const knexSqlite = Knex({ client: 'sqlite', connection: ':memory:' })

;(async function run() {
  await knexSqlite.schema.createTable('test', (t) => {
    t.increments('id').primary()
    t.string('data')

    t.timestamps().nonNullable() // <-- t.timestamps() returns null
  })
})()
```

2. Error message

```
> Uncaught TypeError: Cannot read properties of undefined (reading 'nonNullable')
    at TableBuilder._fn (REPL27:5:19)
    at TableBuilder.toSQL (/Users/ketanpadegaonkar/code/meshtastic/paragliding-meshmap/node_modules/knex/lib/schema/tablebuilder.js:48:16)
    at SchemaCompiler_SQLite3.build (/Users/ketanpadegaonkar/code/meshtastic/paragliding-meshmap/node_modules/knex/lib/schema/compiler.js:144:23)
```

**Comment by mercmobily** [comment]
Thank you for reporting this issue. You've identified an important inconsistency between the TypeScript definitions and the actual implementation of the `timestamps()` method.

After examining the codebase and testing the behaviour, I can confirm this is indeed a bug. The TypeScript definition in `types/index.d.ts:2476-2480` declares that `timestamps()` should return a `ColumnBuilder`, making it chainable:

```typescript
timestamps(
  useTimestamps?: boolean,
  defaultToNow?: boolean,
  useCamelCase?: boolean
): ColumnBuilder;
```

However, the actual implementation in `lib/schema/tablebuilder.js:55-68` doesn't return anything (implicitly returns `undefined`):

```javascript
timestamps(useTimestamps, defaultToNow, useCamelCase) {
  if (isObject(useTimestamps)) {
    ({ useTimestamps, defaultToNow, useCamelCase } = useTimestamps);
  }
  const method = useTimestamps === true ? 'timestamp' : 'datetime';
  const createdAt = this[method](useCamelCase ? 'createdAt' : 'created_at');
  const updatedAt = this[method](useCamelCase ? 'updatedAt' : 'updated_at');

  if (defaultToNow === true) {
    const now = this.client.raw('CURRENT_TIMESTAMP');
    createdAt.notNullable().defaultTo(now);
    updatedAt.notNullable().defaultTo(now);
  }
  // No return statement!
}
```

This means when you try to chain methods like `.notNullable()` on the result of `timestamps()`, you get the error you're seeing because you're calling `notNullable()` on `undefined`.

The TypeScript definition is misleading in another way too - it actually has TWO conflicting overloads:
1. Line 2476-2480: Returns `ColumnBuilder` (with individual parameters)
2. Line 2481-2487: Returns `void` (with options object parameter)

This inconsistency needs to be resolved. However, there's a deeper design question here: what SHOULD `timestamps()` return?

The challenge is that `timestamps()` creates TWO columns (`created_at` and `updated_at`), not one. Each of these columns has its own `ColumnBuilder` instance. It's not clear which one should be returned, or whether chaining should apply to both columns. This is fundamentally different from methods like `string('name')` which create a single column and naturally return its builder for chaining.

The maintainers have historically expressed that `timestamps()` is a convenience method of limited utility. As @elhigu noted in issue #2338, adding the two timestamp columns manually is both trivial and more powerful, allowing full control over each column individually. The recommended approach is:

```javascript
await knex.schema.createTable('test', (t) => {
  t.increments('id').primary()
  t.string('data')
  t.timestamp('created_at').notNullable().defaultTo(knex.fn.now())
  t.timestamp('updated_at').notNullable().defaultTo(knex.fn.now())
})
```

This gives you complete control over each column's configuration and works exactly as expected with method chaining.

The current proper usage of `timestamps()` is `t.timestamps(true, true)` which creates timestamp columns with `CURRENT_TIMESTAMP` defaults, but without the ability to chain additional modifiers afterwards.

The fix here should be to correct the TypeScript definitions to accurately reflect that `timestamps()` returns `void`, removing the misleading `ColumnBuilder` return type. The implementation is working as designed - it's the type definition that's wrong.

This issue will be tracked as part of the TypeScript meta issue #6248, which is consolidating all TypeScript definition problems. Even though this issue will be closed, it will be addressed through the meta issue's coordinated effort to improve Knex's TypeScript support.

Related Issues:
- #6248 - META: Improve Overly Broad/Permissive TypeScript Types (open, NG_meta)
- #2338 - Schema .timestamps() suggested changes (closed, discussion about deprecating timestamps())
- #2387 - Bug: .timestamps() is not setting default values (closed, resolved by using `.timestamps(true, true)`)
- #1928 - table.timestamps() should set ON UPDATE CURRENT_TIMESTAMP for updated_ts (open, NG_feature_request)
