### ISSUE TITLE
jsonb column update not accepting arrays

### ISSUE THREAD

**Issue by yovasx2** [knex/knex#6126]
# Environment

Knex version:
Database + version: postgres 12.17
OS: alpine

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
I defined a jsonb column and when I try to update it using a payload like [{"key": "val"}] it throws an error, if I remove the array syntax and pass a json object it runs correctly, but postgres accepts both definitions: object and array

2. Error message
```
"stack":"error: update \"ai_profiles\" set \"name\" = $1, \"sections\" = $2, \"payload\" = $3 where \"id\" = $4 - invalid input syntax for type json\n    at Parser.parseErrorMessage (/app/web/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/app/web/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/app/web/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/app/web/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:537:15)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)","length":185,"name":"error","severity":"ERROR","code":"22P02","detail":"Expected \":\", but found \"}\".","where":"JSON data, line 1: {\"{\\\"key\\\":\\\"val\\\"}\"}","file":"json.c","line":"1228","routine":"report_parse_error","level":"error"}
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.
```
export const update = async ({ profile, tx }) => {
  const client = tx || pgClient;
  return client(AI_PROFILES_TABLE)
    .where('id', profile.id)
    .update({
      name: profile.name,
      sections: profile.sections,
      payload: profile.payload
    });
};
```

where **profile.payload** is `[{"key": "val"}]`

**Comment by mercmobily** [comment]
Thank you for reporting this PostgreSQL JSONB array handling issue, @yovasx2. This is indeed a known limitation in Knex's PostgreSQL dialect that affects how JavaScript arrays are handled when inserting/updating JSONB columns. The issue stems from PostgreSQL's type system and how Knex distinguishes between PostgreSQL native arrays and JSON arrays.

The problem occurs because PostgreSQL has **two distinct array types**:

1. **Native PostgreSQL Arrays**: `ARRAY[1,2,3]` or `{1,2,3}` format
2. **JSON/JSONB Arrays**: `[1,2,3]` stored as JSON

When Knex encounters a JavaScript array `[{"key": "val"}]`, it assumes you want to insert it as a **native PostgreSQL array**, not a JSON array. This causes the type conversion error because:

- PostgreSQL tries to interpret `[{"key": "val"}]` as a native array
- But the column is defined as JSONB, expecting JSON format
- The conversion fails with "invalid input syntax for type json"

From your error message:
```
Expected ":", but found "}"
JSON data, line 1: {"{\"key\":\"val\"}"}
```

This shows PostgreSQL received the array as a malformed JSON object instead of a proper JSON array.

As @bajax mentioned, the current solution is to explicitly stringify arrays:

```javascript
export const update = async ({ profile, tx }) => {
  const client = tx || pgClient;
  return client(AI_PROFILES_TABLE)
    .where('id', profile.id)
    .update({
      name: profile.name,
      sections: profile.sections,
      payload: JSON.stringify(profile.payload) // Explicitly stringify the array
    });
};
```

Create a helper function that handles JSON serialization smartly:

```javascript
function jsonValue(value) {
  if (value === null || value === undefined) {
    return value;
  }
  
  if (Array.isArray(value) || (typeof value === 'object' && value.constructor === Object)) {
    return JSON.stringify(value);
  }
  
  return value;
}

// Usage
export const update = async ({ profile, tx }) => {
  const client = tx || pgClient;
  return client(AI_PROFILES_TABLE)
    .where('id', profile.id)
    .update({
      name: profile.name,
      sections: profile.sections,
      payload: jsonValue(profile.payload) // Handles arrays and objects
    });
};
```

Define which columns are JSON and process them automatically:

```javascript
const JSON_COLUMNS = ['payload', 'metadata', 'config']; // Define your JSON columns

function processJsonColumns(data, jsonColumns = JSON_COLUMNS) {
  const processed = { ...data };
  
  for (const column of jsonColumns) {
    if (column in processed && processed[column] !== null && processed[column] !== undefined) {
      if (Array.isArray(processed[column]) || 
          (typeof processed[column] === 'object' && processed[column].constructor === Object)) {
        processed[column] = JSON.stringify(processed[column]);
      }
    }
  }
  
  return processed;
}

// Usage
export const update = async ({ profile, tx }) => {
  const client = tx || pgClient;
  return client(AI_PROFILES_TABLE)
    .where('id', profile.id)
    .update(processJsonColumns({
      name: profile.name,
      sections: profile.sections,
      payload: profile.payload // Automatically processed
    }));
};
```


If using an ORM-like pattern, integrate JSON handling at the model level:

```javascript
class ProfileModel {
  static JSON_FIELDS = ['payload', 'sections'];

  static prepare(data) {
    const prepared = { ...data };
    
    for (const field of this.JSON_FIELDS) {
      if (field in prepared && prepared[field] != null) {
        if (typeof prepared[field] === 'object') {
          prepared[field] = JSON.stringify(prepared[field]);
        }
      }
    }
    
    return prepared;
  }

  static async update(id, data, tx = null) {
    const client = tx || pgClient;
    return client(AI_PROFILES_TABLE)
      .where('id', id)
      .update(this.prepare(data));
  }
}

// Usage
await ProfileModel.update(profile.id, {
  name: profile.name,
  sections: profile.sections,
  payload: profile.payload // Automatically handled
});
```


Here's a comprehensive example handling both storage and retrieval:

```javascript
class JsonHelper {
  static serialize(value) {
    if (value === null || value === undefined) return value;
    if (typeof value === 'object') return JSON.stringify(value);
    return value;
  }

  static deserialize(value) {
    if (typeof value === 'string') {
      try {
        return JSON.parse(value);
      } catch (e) {
        return value; // Return as-is if not valid JSON
      }
    }
    return value;
  }

  static processForStorage(data, jsonFields) {
    const processed = { ...data };
    jsonFields.forEach(field => {
      if (field in processed) {
        processed[field] = this.serialize(processed[field]);
      }
    });
    return processed;
  }

  static processFromDatabase(data, jsonFields) {
    const processed = { ...data };
    jsonFields.forEach(field => {
      if (field in processed) {
        processed[field] = this.deserialize(processed[field]);
      }
    });
    return processed;
  }
}

// Usage
const JSON_FIELDS = ['payload', 'sections'];

export const update = async ({ profile, tx }) => {
  const client = tx || pgClient;
  
  const processedProfile = JsonHelper.processForStorage(profile, JSON_FIELDS);
  
  return client(AI_PROFILES_TABLE)
    .where('id', profile.id)
    .update(processedProfile);
};

export const getById = async (id, tx) => {
  const client = tx || pgClient;
  
  const result = await client(AI_PROFILES_TABLE)
    .where('id', id)
    .first();
    
  return result ? JsonHelper.processFromDatabase(result, JSON_FIELDS) : null;
};
```


1. **Type Ambiguity**: JavaScript arrays could map to either PostgreSQL native arrays or JSON arrays
2. **Driver Limitations**: The `pg` driver needs explicit instructions for type conversion
3. **Performance**: Automatic detection would require runtime type inspection
4. **Predictability**: Explicit conversion prevents unexpected behavior

```sql
-- These are different types in PostgreSQL:
CREATE TABLE example (
  native_array INTEGER[],        -- PostgreSQL native array
  json_array JSONB              -- JSON array stored as JSONB
);

-- Different insertion syntax:
INSERT INTO example VALUES 
  (ARRAY[1,2,3], '[1,2,3]'),     -- Native array vs JSON array
  ('{1,2,3}', '[1,2,3]');       -- Alternative native syntax vs JSON
```


A possible enhancement would be column-aware JSON serialization:

```javascript
// Hypothetical future Knex enhancement
knex({
  client: 'pg',
  jsonColumns: {
    'ai_profiles': ['payload', 'sections'],
    'user_preferences': ['settings', 'metadata']
  }
});

// Would automatically stringify objects/arrays for specified columns
await knex('ai_profiles').update({
  payload: [{key: "val"}] // Automatically stringified
});
```


Always stringify JSON data explicitly for clarity:
```javascript
payload: JSON.stringify(profile.payload)
```

```javascript
function validateAndStringify(data) {
  try {
    return JSON.stringify(data);
  } catch (error) {
    throw new Error(`Invalid JSON data: ${error.message}`);
  }
}
```

```javascript
function safeJsonStringify(value) {
  if (value === null || value === undefined) return value;
  if (typeof value === 'string') return value; // Already a string
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value); // Convert primitives to string
}
```

```typescript
interface Profile {
  id: number;
  name: string;
  sections: object[];
  payload: object[];
}

function prepareProfile(profile: Profile): Record<string, any> {
  return {
    ...profile,
    sections: JSON.stringify(profile.sections),
    payload: JSON.stringify(profile.payload)
  };
}
```


- PostgreSQL native array vs JSON array handling
- Cross-database JSON column compatibility
- Type conversion in database drivers
- ORM-style automatic serialization patterns
- Performance implications of JSON stringification

---

**Status**: Working as designed - requires explicit JSON stringification for arrays
**Workaround**: Use `JSON.stringify()` for array values in JSONB columns
**Priority**: Documentation improvement - clearer examples needed for JSON array handling

**Comment by mercmobily** [comment]
After deeper investigation (and some research done after reading #5465), I've discovered the full history of why this limitation persists despite multiple attempts to address it.

There was actually an attempt to fix this automatically in **PR #5321** (September 2022), which modified lib/client.js to add `|| Array.isArray(value)` so arrays would be automatically stringified just like objects:

```javascript
// PR #5321 attempted fix:
if (isPlainObject(value) || Array.isArray(value)) {
  value = JSON.stringify(value);
}
```

However, this fix was **completely reverted in PR #5439** (January 2023) because it broke legitimate use cases where users insert arrays into **native PostgreSQL array columns** (like `TEXT[]`, `INTEGER[]`, etc.).

The test case added in PR #5439 demonstrates the conflict perfectly:

```javascript
await knex('redirect_array').insert({
  name: 'knex',
  redirect_urls: ['https://knexjs.org/', 'https://knexjs.org/guide/']
});
```

For a table with `redirect_urls TEXT[]` (native PostgreSQL array column), the JavaScript array `['url1', 'url2']` must remain as-is so the pg driver can format it as `ARRAY['url1', 'url2']`. If automatically stringified to `'["url1", "url2"]'`, it would incorrectly insert a JSON string into an array column, causing a type mismatch.

This is why the "obvious fix" of always stringifying arrays doesn't work - **JavaScript arrays are fundamentally ambiguous** in PostgreSQL context.

The issue manifests differently and inconsistently across the codebase:

**Insert operations**: Arrays pass through without stringification and eventually reach lib/dialects/postgres/index.js:304-306 where they're converted to PostgreSQL's native array format `{1,2,3}` via the `arrayString` function (lines 343-359). This works for native array columns but fails for JSONB.

**Update operations**: The handling is **inconsistent even within updates**:

**Case 1**: `.update('column', objectValue)` - lib/query/querybuilder.js:1239-1240
```javascript
if (isPlainObject(returning)) {
  obj[values] = JSON.stringify(returning);  // Objects ARE stringified
}
```

**Case 2**: `.update('column', arrayValue)` - lib/query/querybuilder.js:1242
```javascript
else {
  obj[values] = returning;  // Arrays pass through unchanged!
}
```

**Case 3**: `.update({column: value})` - lib/query/querybuilder.js:1254
```javascript
obj[keys[i]] = values[keys[i]];  // Direct assignment, no stringification
```

So objects get special treatment in the two-argument form (Case 1) thanks to **PR #5063** (March 2022), but arrays do not. This inconsistency suggests this wasn't intentionally designed this way - it's the result of partial fixes that couldn't be completed due to the native array conflict.

**Why can't Knex just detect the column type?**

Several reasons make automatic detection impractical:

1. **Performance overhead**: Would require schema queries for every insert/update
2. **Caching complexity**: Schema can change, cache invalidation is hard
3. **Dynamic queries**: Doesn't work with `knex.raw()` or computed table names
4. **Cross-database consistency**: Other databases have different type systems
5. **Connection pool timing**: Schema query might need different connection

**Why can't the pg driver handle this?**

The pg driver sees only the final bindings and SQL template - it has no context about column types either. It uses JavaScript type information to guess PostgreSQL types, which is why arrays become native PostgreSQL arrays by default.

Maintainers have discussed several approaches:

**1. Type wrapper functions** (suggested by @elhigu in #791, #2229, #3805):
```javascript
knex('table').update({
  jsonb_column: knex.json(['item']),    // Explicitly JSONB
  array_column: knex.array(['item']),   // Explicitly native array
  simple_value: 'string'                // No wrapper needed
})
```

**2. Configuration-based column hints**:
```javascript
knex({
  client: 'pg',
  jsonColumns: {
    'users': ['preferences', 'metadata'],
    'profiles': ['settings', 'data']
  }
})
```

**3. Casting support** (mentioned by @wubzz):
```javascript
knex('table').update({
  jsonb_column: knex.cast(['item'], 'jsonb')
})
```

**4. Per-query hints**:
```javascript
knex('table')
  .withColumnTypes({ jsonb_column: 'jsonb' })
  .update({ jsonb_column: ['item'] })
```


**Status**: Confirmed limitation requiring feature enhancement, not a simple bug fix

**Root cause**: JavaScript arrays are ambiguous - could represent PostgreSQL native arrays (`TEXT[]`) or JSON arrays (JSONB). Previous fix attempt (PR #5321) was reverted (PR #5439) because automatic stringification broke native array columns.

**Current workaround**: Explicit `JSON.stringify()` for all arrays in JSONB columns:
```javascript
knex('table').update({
  jsonb_col: JSON.stringify(['item'])
})
```

**Proper solution**: Requires API enhancement such as:
- Wrapper functions (`knex.json()`)
- Configuration-based column type hints
- Explicit casting support

**Documentation improvements needed**:
- Move JSONB array warning to query builder docs, not just schema builder
- Add prominent examples in `.insert()` and `.update()` documentation
- Include TypeScript examples showing type-safe approaches
- Better error messages when common patterns are detected


This issue affects a significant number of users and has persisted since at least 2014. A proper solution would require thoughtful API design to avoid breaking existing code whilst providing explicit control over array serialization.
