### ISSUE TITLE
raw() is broken if bindings name has $ (dollar sign) in it

### ISSUE THREAD

**Issue by damianobarbati** [knex/knex#6134]
# Environment

Knex version: 3.1.0
Database + version: Postgresql 16

# Bug

Knex looks broken when using raw query and a placeholder with $ sign in it:
```ts
await database.raw('select * from shipments where status in (:status$in)', { status$in: ['active'] });
```

Throws:
```ts
/Users/damians/Desktop/atlas/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/src/parser.ts:368
      name === 'notice' ? new NoticeMessage(length, messageValue) : new DatabaseError(messageValue, length, name)
                                                                    ^


error: select * from table where status in (:status$in) - syntax error at or near "table"
    at Parser.parseErrorMessage (/Users/damians/Desktop/atlas/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/src/parser.ts:368:69)
    at Parser.handlePacket (/Users/damians/Desktop/atlas/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/src/parser.ts:187:21)
    at Parser.parse (/Users/damians/Desktop/atlas/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/src/parser.ts:102:30)
    at Socket.<anonymous> (/Users/damians/Desktop/atlas/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
  length: 94,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '15',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1242',
  routine: 'scanner_yyerror'
}
```

**Comment by rubengmurray** [comment]
@mercmobily another postgres binding issue here

**Comment by mercmobily** [comment]
@rubengmurray I added it to the meta issue https://github.com/knex/knex/issues/6236 Ideally, we work through ALL of the issues in the meta one, and in the end close the meta issue!
