### ISSUE TITLE
transaction commit does not throw errors when constraints are deferred

### ISSUE THREAD

**Issue by srinesha** [knex/knex#6141]
# Environment

Knex version: `knex@^3.1.0`
Database + version: `PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit`
OS: postgres: `16.2-bookworm (docker image)`

# Bug

### Details

We have sort of foreign key deadlock where `user` need to have an `organization_id` and `organization` needs to have `created_by` id. So I have made those columns `DEFERRABLE INITIALLY DEFERRED` to make constraints checks at the end of the transaction.

```sql
ALTER TABLE "users"
ALTER CONSTRAINT users_organizations_id_foreign
  DEFERRABLE INITIALLY DEFERRED;


ALTER TABLE "organizations"
ADD CONSTRAINT "organizations_created_by_foreign"
  FOREIGN KEY ("created_by")
  REFERENCES users(id)
  DEFERRABLE INITIALLY DEFERRED;
```

### Issue

We have a seed  file to add master organization which is a dummy organization to satisfy the master `user`'s `organizations_id` and the master users. Following is the seed file.

```typescript
import { Knex } from 'knex'

export async function seed(knex: Knex): Promise<void> {
  const trx = await knex.transaction()

  try {
    const [{ id: orgId }] = await trx('organizations')
      .insert([
        {
          name: 'name',
          email: 'CONTACT@EMAIL.COM',
          created_by: -1,
        },
      ])
      .returning('id')

    const [{ id: userId }] = await trx('users')
      .insert([
        {
          email: 'MASTER@EMAIL.COM',
          organizations_id: orgId,
        },
      ])
      .onConflict('email')
      .merge()
      .returning('id')

    // await trx('organizations')
    //   .update({
    //     created_by: userId,
    //   })
    //   .where('id', orliTechOrgId)

    console.log('>>>>>>>>>>>>> commit')
    await trx.commit()
  } catch (err) {
    console.log('>>>>>>>>>>>>> rollback', err)
    await trx.rollback()
  }
}
```

In above, I have commented out the section where `userId` added to the `organization.created_by`. So transaction should fail when committing. However it does not fail but in the db, **organization nor the user was created**. 

Following is the console output:

```shell
❯ NODE_ENV=development npx knex seed:run
Requiring external module ts-node/register
>>>>>>>>>>>>> commit
Ran 13 seed files
```

If I uncomment the lines above, I get exactly the same output but in the DB, a new organization is created. **However,** any other foreign key constraint (for all the other foreign keys I have not set any `deferrable` upon table creation so I assume they are by default `DEFERRABLE INITIALLY IMMEDIATE`) are throwing errors for instance when I pass `-1` to `users.countries_id` which is another foreign key in `users` table throws an error and goes to the catch block.

### Following however, works!

I passed the callback function to `transaction` and this way, it throws the error correctly

```typescript
import { Knex } from 'knex'

export async function seed(knex: Knex): Promise<void> {
  await knex.transaction(async (trx) => {
    const [{ id: orgId }] = await trx('organizations')
      .insert([
        {
          name: 'name',
          email: 'CONTACT@EMAIL.COM',
          created_by: -1,
        },
      ])
      .returning('id')

    const [{ id: mikesId }] = await trx('users')
      .insert([
        {
          email: 'MASTER@EMAIL.COM',
          organizations_id: orgId,
        },
      ])
      .onConflict('email')
      .merge()
      .returning('id')

    // await trx('organizations')
    //   .update({
    //     created_by: mikesId,
    //   })
    //   .where('id', orliTechOrgId)
  })
}
```

```shell
❯ NODE_ENV=development npx knex seed:run
Requiring external module ts-node/register
Error while executing "/home/s1n7ax/Workspace/orlitech-be/db/seeds/05_seed_add_master_users_and_org.ts" seed: COMMIT; - insert or update on table "organizations" violates foreign key constraint "organizations_created_by_foreign"
Error: Error while executing "/home/s1n7ax/Workspace/orlitech-be/db/seeds/05_seed_add_master_users_and_org.ts" seed: COMMIT; - insert or update on table "organizations" violates foreign key constraint "organizations_created_by_foreign"
    at Seeder._waterfallBatch (/home/s1n7ax/Workspace/orlitech-be/node_modules/knex/lib/migrations/seed/Seeder.js:118:23)
error: COMMIT; - insert or update on table "organizations" violates foreign key constraint "organizations_created_by_foreign"
    at Parser.parseErrorMessage (/home/s1n7ax/Workspace/orlitech-be/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/s1n7ax/Workspace/orlitech-be/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/s1n7ax/Workspace/orlitech-be/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/s1n7ax/Workspace/orlitech-be/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
```

- I believe `trx.commit()` should throw errors when transaction commit fails

**Comment by mercmobily** [comment]
You've discovered a flaw in how Knex handles errors from manual transaction commits. When you call `trx.commit()` explicitly (rather than using the callback pattern), errors that occur during the COMMIT statement are silently swallowed instead of being thrown. This is particularly problematic with PostgreSQL's `DEFERRABLE INITIALLY DEFERRED` constraints, where constraint violations are only checked at commit time.

In your case, the organisation has `created_by = -1` which violates the foreign key constraint, but this violation is deferred until commit. When commit fails, Knex should throw an error, but instead it silently succeeds and the transaction is actually rolled back by PostgreSQL without your code knowing.

The bug is in the `query()` method in lib/execution/transaction.js:165-195. When you manually call `await trx.commit()`, here's what happens:

```javascript
commit(conn, value) {
  return this.query(conn, 'COMMIT;', 1, value);
}

query(conn, sql, status, value) {
  const q = this.trxClient
    .query(conn, sql)
    .catch((err) => {
      status = 2;
      value = err;
      this._completed = true;
      debug('%s error running transaction query', this.txid);
    })
    .then((res) => {
      if (status === 1) {
        this._resolver(value);
      }
      if (status === 2) {
        if (value === undefined) {
          if (this.doNotRejectOnRollback && /^ROLLBACK\b/i.test(sql)) {
            this._resolver();
            return;
          }
          value = new Error(`Transaction rejected with non-error: ${value}`);
        }
        this._rejecter(value);
      }
      return res;
    });
  if (status === 1 || status === 2) {
    this._completed = true;
  }
  return q;
}
```

The problem is that `this._rejecter()` rejects the internal `executionPromise` (used by the callback pattern), but the promise `q` that's returned from `query()` - and thus from your `await trx.commit()` - doesn't reject. The `.catch()` handler modifies local variables and logs the error, but the `.then()` handler doesn't re-throw the error for the returned promise chain.

When you use the callback pattern like this:

```javascript
await knex.transaction(async (trx) => {
  // queries...
  // commit happens automatically
})
```

Knex automatically commits when your callback resolves (lib/execution/transaction.js:238-244). The commit happens inside the internal promise chain, and when it fails, `this._rejecter()` is called, which properly rejects the transaction promise that you're awaiting. The error propagates correctly through the `executionPromise`.

This is actually a **regression** of issue #50 from 2013! That issue reported the exact same problem with deferred constraints, and it was closed with a fix that added error handling to the commit. However, the transaction system has been refactored since then (particularly in the 1.0 refactor #1659), and this bug was reintroduced.

Issue #3370 reports a similar problem with serialisation errors during commit not being thrown. The underlying cause is the same - errors during COMMIT are not properly propagated when using manual commit.

As you've discovered, the callback pattern works correctly:

```javascript
await knex.transaction(async (trx) => {
  const [{ id: orgId }] = await trx('organizations')
    .insert([{
      name: 'name',
      email: 'CONTACT@EMAIL.COM',
      created_by: -1,
    }])
    .returning('id')

  const [{ id: userId }] = await trx('users')
    .insert([{
      email: 'MASTER@EMAIL.COM',
      organizations_id: orgId,
    }])
    .onConflict('email')
    .merge()
    .returning('id')

  // Now update the organisation with the correct user ID
  await trx('organizations')
    .update({ created_by: userId })
    .where('id', orgId)

  // Commit happens automatically when function returns
})
```


## The Fix Required

The `query()` method in lib/execution/transaction.js needs to be fixed so that when an error occurs during a query (including COMMIT), the returned promise `q` is properly rejected. The current implementation only rejects the internal `executionPromise` but not the promise returned to the caller.

A proper fix would ensure that the `.catch()` handler re-throws the error so it propagates to the returned promise:

```javascript
query(conn, sql, status, value) {
  const q = this.trxClient
    .query(conn, sql)
    .catch((err) => {
      status = 2;
      value = err;
      this._completed = true;
      debug('%s error running transaction query', this.txid);
      throw err; // Must re-throw for the returned promise
    })
    .then((res) => {
      if (status === 1) {
        this._resolver(value);
      }
      if (status === 2) {
        // ... error handling
        this._rejecter(value);
        throw value; // Must throw for the returned promise
      }
      return res;
    });
  // ...
  return q;
}
```

However, this would require careful testing to ensure it doesn't break the callback pattern or introduce other issues with the complex transaction promise handling.

For now, I strongly recommend using the callback pattern for all transactions, as it's the only pattern that correctly handles commit errors. The manual `trx.commit()` pattern should be considered broken for any database operations where errors can occur during commit (deferred constraints, serialisation errors, etc.).

This issue needs to be fixed in Knex core. We will need to carefully redesign how the `query()` method handles promise rejection to ensure both the internal `executionPromise` and the returned promise are properly rejected when errors occur.

## Related Issues

- #50 - Constraint violations during commit are lost (CLOSED - but regression)
- #3370 - Serialisation error on transaction commit is not thrown (OPEN)
- #1943 - Unusual behaviour of promises when commit/rollback transaction errors are encountered (CLOSED)
- #5710 - How to commit or rollback inside transaction handler? (OPEN)
- #3874 - Manual transaction commit + throwing error (CLOSED)
