### ISSUE TITLE
How to handle server disconnect/reconnect ?

### ISSUE THREAD

**Issue by antoinegomez** [knex/knex#63]
Hello, after reading the doc and perform some search here I cannot find how to handle server disconnect and reconnect.

With raw MySQL lib it can be done with events listeners: on('error'), on('end') ...

The only way I know to get the connection is : Knex.client.getConnection().ten();

Any clue ?

**Comment by reduardo7** [comment]
Not working...
```
app_1  | /app/db.js:35
app_1  |     knex.client.getConnection().then(function (conn) {
app_1  |                 ^
app_1  |
app_1  | TypeError: knex.client.getConnection is not a function
app_1  |     at Object.db.onConnect (/app/db.js:35:17)
app_1  |     at Object.<anonymous> (/app/app.js:25:4)
app_1  |     at Module._compile (module.js:409:26)
app_1  |     at Object.Module._extensions..js (module.js:416:10)
app_1  |     at Module.load (module.js:343:32)
app_1  |     at Function.Module._load (module.js:300:12)
app_1  |     at Function.Module.runMain (module.js:441:10)
app_1  |     at startup (node.js:139:18)
app_1  |     at node.js:974:3
```
